# Example configuration file for running the CABLE benchmarking.
# 
# Note, optional keys are available in this config file. See
# https://benchcab.readthedocs.io/en/stable/user_guide/config_options/
# for documentation on all the available keys.
# 
# This file is in YAML format. You can get information on the syntax here:
# https://yaml.org/spec/1.2.2/#chapter-2-language-overview
# Quick tips:
# You need a space after the ":"
#
# It uses the same syntax as Python for:
#     - lists (aka sequences)
#     - dictionaries (aka mappings with key/value pairs)
#
# Strings can be given with or without double or single quotes.

realisations:
  - repo:
      git:
        branch: main
  - repo:
      local:
        path: /home/581/bjs581/work/CABLE
  
modules: [
  intel-compiler/2021.1.1,
  netcdf/4.7.4,
  openmpi/4.1.0
]

fluxsite:
  experiment: AU-Tum
  pbs:
    storage:
      - scratch/rp23