fudge_out – GW
fudge_out Interface
3 statements
Source File
public interface fudge_out
Calls
Contents
Module Procedures
fudge_out_r2D fudge_out_r1D fudge_out_r3D fudge_out_i2D
Module Procedures
public subroutine fudge_out_r2D(i, j, var, varname, vzero, vval)
Arguments
Type Intent Optional Attributes Name
integer :: i
integer :: j
real, DIMENSION(:,:) :: var
character(len=*) :: varname
logical :: vzero
real :: vval
public subroutine fudge_out_r1D(i, var, varname, vzero, vval)
Arguments
Type Intent Optional Attributes Name
integer :: i
real, DIMENSION(:) :: var
character(len=*) :: varname
logical :: vzero
real :: vval
public subroutine fudge_out_r3D(i, j, k, var, varname, vzero, vval)
Arguments
Type Intent Optional Attributes Name
integer :: i
integer :: j
integer :: k
real, DIMENSION(:,:,:) :: var
character(len=*) :: varname
logical :: vzero
real :: vval
public subroutine fudge_out_i2D(i, j, var, varname, vzero, vval)
Arguments
Type Intent Optional Attributes Name
integer :: i
integer :: j
integer, DIMENSION(:,:) :: var
character(len=*) :: varname
logical :: vzero
integer :: vval
Call graph
fudge_out calls fudge_out_r2d, fudge_out_r1d, fudge_out_i2d, fudge_out_r3d