get_gw_data – GW
get_gw_data Interface
8 statements
Source File
private interface get_gw_data
Calls
Called by
Contents
Module Procedures
get_gw_2d_var_constdef get_gw_3d_var_constdef get_gw_4d_var_constdef get_gw_2d_var get_gw_3d_var get_gw_4d_var
Module Procedures
private function get_gw_2d_var_constdef(ncfile_id, try_it, varname, default_const, nlon, nlat) result(data_vec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncfile_id
integer, intent(in) :: try_it
character(len=*), intent(in) :: varname
real, intent(in) :: default_const
integer, intent(in) :: nlon
integer, intent(in) :: nlat
Return Value real(kind=r_2),dimension(mp)
private function get_gw_3d_var_constdef(ncfile_id, try_it, varname, default_const, nlon, nlat, ms) result(data_vec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncfile_id
integer, intent(in) :: try_it
character(len=*), intent(in) :: varname
real, intent(in) :: default_const
integer, intent(in) :: nlon
integer, intent(in) :: nlat
integer, intent(in) :: ms
Return Value real(kind=r_2),dimension(mp,ms)
private function get_gw_4d_var_constdef(ncfile_id, try_it, varname, default_const, nlon, nlat, ms, npatch) result(data_vec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncfile_id
integer, intent(in) :: try_it
character(len=*), intent(in) :: varname
real, intent(in) :: default_const
integer, intent(in) :: nlon
integer, intent(in) :: nlat
integer, intent(in) :: ms
integer, intent(in) :: npatch
Return Value real(kind=r_2),dimension(mp,ms,mpatch)
private function get_gw_2d_var(ncfile_id, try_it, varname, default_data, nlon, nlat) result(data_vec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncfile_id
integer, intent(in) :: try_it
character(len=*), intent(in) :: varname
real, intent(in), dimension(:,:) :: default_data
integer, intent(in) :: nlon
integer, intent(in) :: nlat
Return Value real(kind=r_2),dimension(mp)
private function get_gw_3d_var(ncfile_id, try_it, varname, default_data, nlon, nlat, ms) result(data_vec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncfile_id
integer, intent(in) :: try_it
character(len=*), intent(in) :: varname
real, intent(in), dimension(:,:) :: default_data
integer, intent(in) :: nlon
integer, intent(in) :: nlat
integer, intent(in) :: ms
Return Value real(kind=r_2),dimension(mp,ms)
private function get_gw_4d_var(ncfile_id, try_it, varname, default_data, nlon, nlat, ms, npatch) result(data_vec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncfile_id
integer, intent(in) :: try_it
character(len=*), intent(in) :: varname
real, intent(in), dimension(:,:) :: default_data
integer, intent(in) :: nlon
integer, intent(in) :: nlat
integer, intent(in) :: ms
integer, intent(in) :: npatch
Return Value real(kind=r_2),dimension(mp,ms,mpatch)
Call graph
get_gw_data calls get_gw_2d_var_constdef, get_gw_4d_var_constdef, get_gw_3d_var_constdef, get_gw_2d_var, get_gw_3d_var, get_gw_4d_var
get_gw_2d_var_constdef calls nf90_inq_varid, nf90_get_var
get_gw_4d_var_constdef calls nf90_inq_varid, nf90_get_var
get_gw_3d_var_constdef calls nf90_inq_varid, nf90_get_var
get_gw_2d_var calls nf90_inq_varid, nf90_get_var
get_gw_3d_var calls nf90_inq_varid, nf90_get_var
get_gw_4d_var calls nf90_inq_varid, nf90_get_var
gwspatialparameters calls get_gw_data
load_parameters calls gwspatialparameters
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master