setroots – GW
setroots Interface
4 statements
Source File
public interface setroots
Calls
Called by
Contents
Module Procedures
setroots_1d setroots_2d
Module Procedures
private subroutine setroots_1d(x, F10, Zr, Fs)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(:) :: x
real(kind=r_2), intent(in) :: F10
real(kind=r_2), intent(in) :: Zr
real(kind=r_2), intent(out), DIMENSION(:) :: Fs
private subroutine setroots_2d(x, F10, Zr, Fs)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(:,:) :: x
real(kind=r_2), intent(in), DIMENSION(:) :: F10
real(kind=r_2), intent(in), DIMENSION(:) :: Zr
real(kind=r_2), intent(out), DIMENSION(:,:) :: Fs
Call graph
setroots calls setroots_1d, setroots_2d
setroots_2d calls setroots_1d
sli_main calls setroots
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker