cable_offline_driver – POP
cable_offline_driver Program
769 statements
Source File
Uses
cable_diag_module
casavariable
blaze_drv
cable_adjust_JV_gm_module
cable_pop_io
CABLE_PLUME_MIP
CABLE_LUC_EXPT
cable_def_types_mod
cable_climate_mod
casadimension
mo_isotope
cable_cbm_module
phenvariable
BLAZE_MOD
cable_c13o2
cable_bios_met_obs_params
cable_input_module
casa_inout
cable_data_module
cable_common_module
cable_IO_vars_module
POPLUC_Types
CABLE_site
POP_Types
mo_c13o2_photosynthesis
cable_cru
casa_cable
cable_casaonly_luc
POPLUC_Module
cable_c13o2_def
mo_utils
POP_Constants
cable_spincasacnp
SIMFIRE_MOD
cable_output_module
cable_write_module
vh_js !!
vh_js !! vh_js !! vh_js !! suggest LALLOC should ulitmately be a switch in the .nml file CLN WRT BLAZE_OUT here CLN BLAZE WRITE RST
Calls
Contents
Variables
cable_namelist kstart mloop LALLOC ktau ktau_tot kend koffset koffset_met ktauday idoy nyear casa_it YYYY RYEAR RRRR NRRRR LOY count_sum_casa ctime dels GSWP_MID dum str1 met air canopy rad rough bal ssnow climate soil veg C sum_flux bgc casabiome casapool casaflux sum_casapool sum_casaflux casamet casabal phen POP POPLUC PLUME CRU site LUC_EXPT cyear ncfile BLAZE SIMFIRE c13o2flux c13o2pools sum_c13o2pools c13o2luc casasave lucsave c13o2_outfile_id c13o2_vars c13o2_var_ids ileaf gpp Ra iunit ios iyear c13o2_atm_syear c13o2_atm_eyear header vegparmnew spinup spinConv spincasainput spincasa l_casacnp l_laiFeedbk l_vcmaxFeedbk CASAONLY CALL1 SPINon CASA_TIME first_casa_write liseod liseoy delsoilM delsoilT Metyear Y LOYtmp soilMtemp soilTtemp etime iDiagZero kk Ftrunk_sumbal Fnew_sumbal trunk_sumbal new_sumbal new_sumfpn new_sumfe nkend ioerror count_bal narg len1 len2 arg1 arg2
Variables
Type Attributes Name Initial
character(len=200), parameter :: cable_namelist = 'cable.nml'
integer, parameter :: kstart = 1
integer, parameter :: mloop = 30
integer :: LALLOC
integer :: ktau
integer :: ktau_tot
integer :: kend
integer :: koffset = 0
integer :: koffset_met = 0
integer :: ktauday
integer :: idoy
integer :: nyear
integer :: casa_it
integer :: YYYY
integer :: RYEAR
integer :: RRRR
integer :: NRRRR
integer :: LOY
integer :: count_sum_casa
integer :: ctime
real :: dels
integer, dimension(:,:), allocatable :: GSWP_MID
character(len=9) :: dum
character(len=4) :: str1
type(met_type) :: met
type(air_type) :: air
type(canopy_type) :: canopy
type(radiation_type) :: rad
type(roughness_type) :: rough
type(balances_type) :: bal
type(soil_snow_type) :: ssnow
type(climate_type) :: climate
type(soil_parameter_type) :: soil
type(veg_parameter_type) :: veg
type(driver_type) :: C
type(sum_flux_type) :: sum_flux
type(bgc_pool_type) :: bgc
type(casa_biome) :: casabiome
type(casa_pool) :: casapool
type(casa_flux) :: casaflux
type(casa_pool) :: sum_casapool
type(casa_flux) :: sum_casaflux
type(casa_met) :: casamet
type(casa_balance) :: casabal
type(phen_variable) :: phen
vh_js !!
type(POP_TYPE) :: POP
type(POPLUC_TYPE) :: POPLUC
type(PLUME_MIP_TYPE) :: PLUME
type(cru_type) :: CRU
type(site_TYPE) :: site
type(luc_expt_type) :: LUC_EXPT
character :: cyear*4
character :: ncfile*99
type(TYPE_BLAZE) :: BLAZE
type(TYPE_SIMFIRE) :: SIMFIRE
type(c13o2_flux) :: c13o2flux
type(c13o2_pool) :: c13o2pools
type(c13o2_pool) :: sum_c13o2pools
type(c13o2_luc) :: c13o2luc
real(kind=r_2), dimension(:,:), allocatable :: casasave
real(kind=r_2), dimension(:,:), allocatable :: lucsave
integer :: c13o2_outfile_id
character(len=40), dimension(c13o2_nvars_output) :: c13o2_vars
integer, dimension(c13o2_nvars_output) :: c13o2_var_ids
integer :: ileaf
real(kind=r_2), dimension(:,:), allocatable :: gpp
real(kind=r_2), dimension(:), allocatable :: Ra
integer :: iunit
integer :: ios
real :: iyear
integer :: c13o2_atm_syear
integer :: c13o2_atm_eyear
character(len=100) :: header
logical :: vegparmnew = .false.
logical :: spinup = .false.
logical :: spinConv = .false.
logical :: spincasainput = .false.
logical :: spincasa = .false.
logical :: l_casacnp = .false.
logical :: l_laiFeedbk = .false.
logical :: l_vcmaxFeedbk = .false.
logical :: CASAONLY = .false.
logical :: CALL1 = .true.
logical :: SPINon = .true.
logical :: CASA_TIME
logical :: first_casa_write
logical :: liseod
logical :: liseoy
real :: delsoilM
real :: delsoilT
integer :: Metyear
integer :: Y
integer :: LOYtmp
real, allocatable, dimension(:,:) :: soilMtemp
real, allocatable, dimension(:,:) :: soilTtemp
real :: etime
integer :: iDiagZero = 0
integer :: kk
character(len=30), parameter :: Ftrunk_sumbal = ".trunk_sumbal"
character(len=30), parameter :: Fnew_sumbal = "new_sumbal"
real(kind=r_2) :: trunk_sumbal = 0.0_r_2
real(kind=r_2) :: new_sumbal = 0.0_r_2
real(kind=r_2) :: new_sumfpn = 0.0_r_2
real(kind=r_2) :: new_sumfe = 0.0_r_2
integer :: nkend = 0
integer :: ioerror
integer :: count_bal = 0
integer :: narg
integer :: len1
integer :: len2
character(len=500) :: arg1
character(len=200) :: arg2
Call graph
cable_offline_driver calls c13o2_write_output, spincasacnp, c13o2_sanity_pools, get_unit, point2constants, luc_expt_init, cable_bios_init, c13o2_zero_sum_pools, cable_bios_read_met, is_casa_time, c13o2_write_restart_pools, update_sum_casa, site_init, alloc_cbm_var, cru_init, preparefiles, cable_diag, c13o2_print_delta_luc, cbm, popluc_set_patchfrac, write_casa_output_nc, c13o2_print_delta_flux, close_met_file, eq, sumcflux, close_output_file, lucdriver, casa_fluxout, open_met_file, pop_io, ini_blaze, isoratio, zero_cbm_var, read_climate_restart_nc, cable_bios_load_climate_params, c13o2_save_luc, c13o2_print_delta_pools, read_gm_lut, casaonly_luc, c13o2_sanity_luc, casa_feedback, ini_simfire, write_luc_output_nc, cru_close, plume_mip_init, cable_climate, climate_init, get_met_data, site_get_co2_ndep, close_luh2, blaze_accounting, write_climate_restart_nc, bgcdriver, report_version_no, load_parameters, nullify_write, is_leapyear, c13o2_close_output, create_restart, write_casa_dump, pop_luc_casa_transfer, c13o2_create_output, c13o2_update_sum_pools, cru_get_subdiurnal_met, write_blaze_output_nc, cable_bios_load_params, open_output_file, popdriver, write_luc_restart_nc, blaze_driver, zero_sum_casa, plume_mip_get_met, write_output, write_casa_restart_nc, ne, casa_cnpflux, c13o2_write_restart_flux, c13o2_update_luc, c13o2_write_restart_luc, read_casa_dump
c13o2_write_output calls nf90_put_var, c13o2_err_handler
spincasacnp calls c13o2_write_output, c13o2_sanity_pools, write_casa_output_nc, casa_fluxout, isoratio, blaze_accounting, c13o2_close_output, c13o2_create_output, write_blaze_output_nc, popdriver, blaze_driver, read_casa_dump, c13o2_update_pools, analyticpool, biogeochem, c13o2_save_casapool
c13o2_sanity_pools calls isosanity
point2constants calls carbon_type_ptr, rough_type_ptr, albedo_type_ptr, driver_type_ptr, cbm_type_ptr, canopy_type_ptr, ssnow_type_ptr, air_type_ptr, rad_type_ptr
luc_expt_init calls get_unit, nf90_get_att, nf90_open, nf90_get_var, nf90_inquire_dimension, luc_expt_zero, nf90_inq_varid, handle_err, cable_bios_load_biome, read_climatefile, nf90_close, nf90_inq_dimid
cable_bios_init calls get_unit, wgen_init, readarcfltheader, daydifference
cable_bios_read_met calls eq, wgen_daily_constants, wgen_subdiurnal_met, daydifference
is_casa_time calls is_leapyear
c13o2_write_restart_pools calls nf90_create, nf90_put_var, nf90_put_att, nf90_def_dim, c13o2_err_handler, nf90_enddef, nf90_close, nf90_def_var
site_init calls get_unit
alloc_cbm_var calls alloc_roughness_type, alloc_soil_snow_type, alloc_balances_type, alloc_air_type, alloc_soil_parameter_type, alloc_met_type, alloc_sum_flux_type, alloc_radiation_type, alloc_bgc_pool_type, alloc_canopy_type, alloc_climate_type, alloc_veg_parameter_type
cru_init calls get_unit, nf90_open, nf90_get_var, nf90_inquire_dimension, nf90_inq_varid, handle_err, nf90_close, nf90_inq_dimid
preparefiles calls renamefiles
cable_diag calls cable_diag1
c13o2_print_delta_luc calls ne, delta1000
cbm calls point2constants, ruff_resist, soil_snow, plantcarb, init_radiation, define_canopy, define_air, soilcarb, carbon_pl, sli_main, surface_albedo
write_casa_output_nc calls nf90_create, nf90_put_var, nf90_put_att, nf90_def_dim, handle_err, nf90_enddef, nf90_close, nf90_def_var
c13o2_print_delta_flux calls ne, delta1000
close_met_file calls nc_abort, nf90_close
eq calls equal_sp, equal_dp
close_output_file calls nc_abort, nf90_close
lucdriver calls eq, pop_init_single, popluc_weights_transfer, poplucstep, read_luh2
open_met_file calls eq, is_leapyear, nf90_get_att, cable_abort, nf90_open, nf90_get_var, nc_abort, nf90_inquire_dimension, nf90_inq_varid, handle_err, ymdhms2doysod, doysod2ymdhms, nf90_inq_dimid, nf90_inquire_variable
pop_io calls ne, nf90_open, nf90_create, nf90_put_var, nf90_get_var, nf90_put_att, nf90_inquire_dimension, nf90_def_dim, nf90_inq_varid, handle_err, nf90_enddef, nf90_close, nf90_def_var, nf90_inq_dimid
ini_blaze calls get_unit, zero_blaze
zero_cbm_var calls zero_sum_flux_type, zero_veg_parameter_type, zero_roughness_type, zero_climate_type, zero_soil_parameter_type, zero_bgc_pool_type, zero_canopy_type, zero_met_type, zero_soil_snow_type, zero_radiation_type, zero_balances_type, zero_air_type
read_climate_restart_nc calls read_netcdf_cbm_var
cable_bios_load_climate_params calls get_unit
c13o2_save_luc calls c13o2_save_casapool
c13o2_print_delta_pools calls ne, delta1000
read_gm_lut calls nf90_open, nf90_get_var, nc_abort, nf90_inquire_dimension, nf90_inq_varid, nf90_close, nf90_inq_dimid
casaonly_luc calls c13o2_zero_sum_pools, is_casa_time, update_sum_casa, popluc_set_patchfrac, eq, c13o2_save_luc, pop_luc_casa_transfer, c13o2_update_sum_pools, popdriver, write_luc_restart_nc, zero_sum_casa, c13o2_update_luc, read_casa_dump, c13o2_update_pools, pop_init_single, biogeochem, c13o2_save_casapool, popluc_weights_transfer, poplucstep, read_luh2
c13o2_sanity_luc calls isosanity
casa_feedback calls point2constants, adjust_k_collatz, adjust_jv_gm, vcmax_np, optimise_jv, find_vcmax_jmax_lut
ini_simfire calls get_unit, nf90_open, nf90_get_var, nf90_inq_varid, handle_err, nf90_close, zero_simfire
write_luc_output_nc calls nf90_create, nf90_put_var, nf90_put_att, nf90_def_dim, handle_err, nf90_enddef, nf90_close, nf90_def_var
cru_close calls handle_err, nf90_close
plume_mip_init calls get_unit, nf90_open, nf90_get_var, nf90_inquire_dimension, nf90_inq_varid, handle_err, nf90_close, nf90_inq_dimid
cable_climate calls epsif, biome1_pft
get_met_data calls eq, is_leapyear, cable_abort, nf90_get_var, nc_abort, rh_sh, sinbet
site_get_co2_ndep calls get_unit
close_luh2 calls handle_err, nf90_close
write_climate_restart_nc calls write_netcdf_cbm_var
bgcdriver calls c13o2_update_pools, biogeochem, c13o2_save_casapool, cable_phenology_clim
load_parameters calls pop_io, zero_sum_casa, write_cnp_params, c13o2_init_flux, cable_abort, nf90_open, alloc_sum_casa, casa_init, casa_readbiome, popluc_init, write_default_params, derived_parameters, nc_abort, c13o2_zero_flux, get_restart_data, c13o2_init_luc, nf90_inquire_dimension, check_parameter_values, handle_err, alloc_phenvariable, c13o2_zero_pools, c13o2_read_restart_pools, c13o2_init_pools, c13o2_alloc_pools, allocate_cable_vars, c13o2_read_restart_flux, pop_init, casa_readphen, get_parameters_met, nf90_close, nf90_inq_dimid, zero_phenvariable, c13o2_alloc_flux, alloc_casa_var, get_default_params, report_parameters, zero_casa_var
c13o2_close_output calls c13o2_err_handler, nf90_close
create_restart calls nf90_create, nf90_put_var, nf90_put_att, nc_abort, nf90_def_dim, toreal4, define_ovar, nf90_enddef, nf90_close, nf90_def_var, write_ovar
write_casa_dump calls nf90_create, def_vars, put_var_nc, def_dims, nf90_enddef, nf90_close, stderr_nc
pop_luc_casa_transfer calls eq
c13o2_create_output calls nf90_create, nf90_put_var, nf90_put_att, nf90_def_dim, c13o2_err_handler, nf90_enddef, nf90_def_var
cru_get_subdiurnal_met calls eq, open_cru_met, wgen_init, get_cru_ndep, wgen_daily_constants, get_cru_co2, cru_get_daily_met, handle_err, wgen_subdiurnal_met, doysod2ymdhms, nf90_close
write_blaze_output_nc calls nf90_create, nf90_put_var, nf90_put_att, nf90_def_dim, handle_err, nf90_enddef, nf90_close, nf90_def_var
cable_bios_load_params calls get_unit
open_output_file calls cable_abort, nf90_create, nf90_put_var, nf90_put_att, nc_abort, nf90_def_dim, toreal4, define_ovar, nf90_enddef, nf90_def_var, write_ovar
popdriver calls popstep
write_luc_restart_nc calls nf90_redef, nf90_create, nf90_put_var, nf90_put_att, nf90_def_dim, handle_err, nf90_enddef, nf90_close, nf90_def_var
blaze_driver calls is_leapyear, adjust_pop_for_fire, run_blaze, blaze_turnover, doysod2ymdhms
zero_sum_casa calls zero_casaflux, zero_casapool
plume_mip_get_met calls eq, plume_get_daily_met, file_switch, wgen_init, get_plume_co2, wgen_daily_constants, handle_err, wgen_subdiurnal_met, doysod2ymdhms, rh_sh, open_plume_met, get_plume_ndep, nf90_close
write_output calls is_leapyear, cable_abort, nf90_put_var, energy_balance, nc_abort, nf90_sync, toreal4, mass_balance, write_ovar
write_casa_restart_nc calls write_netcdf_casa_var, write_netcdf_phen_var
ne calls notequal_dp, notequal_sp
c13o2_write_restart_flux calls nf90_create, nf90_put_var, nf90_put_att, nf90_def_dim, c13o2_err_handler, nf90_enddef, nf90_close, nf90_def_var
c13o2_update_luc calls isotope_pool_model, isotope_luc_model, c13o2_save_c13o2pools
c13o2_write_restart_luc calls nf90_create, nf90_put_var, nf90_put_att, nf90_def_dim, c13o2_err_handler, nf90_enddef, nf90_close, nf90_def_var
read_casa_dump calls get_var_nc, nf90_open, nf90_close, stderr_nc
c13o2_init_flux calls init_starch_pool, init_sugar_pools
ruff_resist calls point2constants
c13o2_update_pools calls isotope_pool_model, c13o2_save_c13o2pools, c13o2_fluxmatrix_pools, c13o2_sinks_pools, c13o2_c13o2pools_back, c13o2_sources_pools
adjust_k_collatz calls light_inhibition
open_cru_met calls nf90_open, nf90_inq_varid, handle_err, cru_get_filename, cru_get_metyear
adjust_pop_for_fire calls topkill_collins, interpolate_firemortality
plume_get_daily_met calls nf90_open, nf90_get_var, nf90_inquire_dimension, nf90_inq_varid, handle_err, nf90_close, nf90_inq_dimid, plume_get_filename
get_var_nc calls get_var_ncr3, get_var_ncr2
pop_init_single calls zeropop, initpop2d_poisson, layer_recruitment_single_patch
biogeochem calls casa_cnpflux, casa_delplant, casa_xnp, casa_puptake, avgsoil, casa_ndummy, casa_xratesoil, casa_allocation, casa_xkn, casa_nuptake, casa_rplant, casa_coeffplant, casa_xrateplant, phenology, casa_cnpbal, casa_coeffsoil, casa_pdummy, casa_delsoil, casa_cnpcycle
wgen_init calls wgen_zero
adjust_jv_gm calls point2constants, light_inhibition, lmdif1, photosyn25
alloc_sum_casa calls alloc_casapool, alloc_casaflux
get_cru_ndep calls nf90_open, nf90_get_var, nf90_inq_varid, handle_err
casa_init calls read_casa_restart_nc, zero_casa_dump
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
run_blaze calls is_leapyear, blaze_turnover, doysod2ymdhms, combust, avail_fuel, simfire
def_vars calls nf90_def_var, stderr_nc
popluc_init calls pop_init_single, alloc_popluc, read_luc_restart_nc, popluc_set_params, zero_popluc
get_plume_co2 calls get_unit
write_default_params calls cable_abort, init_veg_from_vegin
nc_abort calls nf90_strerror
soil_snow calls point2constants, stempv, snow_melting, snow_accum, hydraulic_redistribution, soilfreeze_serial, surfbv, snowl_adjust, snowcheck, snowdensity, remove_trans
poplucstep calls increment_age, execute_luc_event
get_restart_data calls cable_abort, nf90_get_var, nc_abort, nf90_inquire_dimension, nf90_inq_varid, nf90_close, nf90_inq_dimid, extrarestart, readpar
write_netcdf_casa_var calls write_netcdf_casabiome, write_netcdf_casamet, write_netcdf_casaflux, write_netcdf_casabal, write_netcdf_casapool
put_var_nc calls put_var_ncr2, put_var_ncr3, put_var_ncr1
c13o2_init_luc calls c13o2_zero_luc, c13o2_alloc_luc, c13o2_read_restart_luc
plantcarb calls point2constants
def_dims calls nf90_def_dim, stderr_nc
get_cru_co2 calls get_unit
isotope_luc_model calls isotope_luc_model_1d
cru_get_daily_met calls nf90_open, nf90_inquire_dimension, nf90_inq_varid, handle_err, nf90_close, nf90_inq_dimid, cru_get_filename, cru_get_metyear, cru_read_metvals
check_parameter_values calls cable_abort
write_netcdf_cbm_var calls write_netcdf_climate_type
handle_err calls nf90_strerror
cable_bios_load_biome calls get_unit
init_radiation calls point2constants, calc_rhoch, spitter
define_canopy calls point2constants, eq, ruff_resist, define_air, sli_main, surf_wetness_fact, radiation, dryleaf
c13o2_read_restart_pools calls nf90_open, nf90_get_var, c13o2_err_handler, nf90_inq_varid, nf90_close
toreal4 calls i2sp, dp2sp, sp2sp
read_netcdf_cbm_var calls read_netcdf_climate_type
popstep calls patchannualdynamics, patch_disturb, getpatchfrequencies, getuniqueagefrequencies, patch_partial_disturb, getdiagnostics, patch_partial_disturb2
define_ovar calls define_output_parameter_r1, define_output_parameter_r2, define_output_variable_r2, define_output_variable_r1
mass_balance calls eq
ymdhms2doysod calls is_leapyear
read_luh2 calls nf90_get_var, handle_err
define_air calls point2constants
allocate_cable_vars calls alloc_cbm_var, zero_cbm_var
c13o2_read_restart_flux calls nf90_open, nf90_get_var, c13o2_err_handler, nf90_inq_varid, nf90_close
pop_init calls zeropop, initpop2d_poisson, layer_recruitment_single_patch, alloc_pop
write_netcdf_phen_var calls nf90_create, nf90_put_var, nf90_def_dim, nf90_enddef, nf90_close, nf90_def_var, nc_err
doysod2ymdhms calls is_leapyear
rh_sh calls svp
open_plume_met calls nf90_get_att, nf90_open, nf90_inq_varid, handle_err, plume_get_filename, leap_day
get_parameters_met calls nf90_inq_varid, readpar
get_plume_ndep calls nf90_open, nf90_get_var, nf90_inq_varid, handle_err
read_climatefile calls alloc_cbm_var, nf90_open, nf90_inquire_dimension, read_netcdf_cbm_var, nf90_close, nf90_inq_dimid, nc_err
daydifference calls julianday
optimise_jv calls point2constants, diff_ac_aj, golden, rtbis, total_photosynthesis_cost
cable_phenology_clim calls eq, ge
stderr_nc calls nf90_strerror
alloc_casa_var calls alloc_casapool, alloc_casabiome, alloc_casabal, alloc_casaflux, alloc_casamet
get_default_params calls spatialsoil, get_land_index, countpatch, luc_expt_set_tiles, read_gridinfo, get_type_parameters, luc_expt_set_tiles_bios, read_soilcolor
sli_main calls esat_ice, getrex, setpar_loetsch, setx, zerovars_snow, seb, setlitterpar, hyofs, zerovars_met, zerovars, solve, thetalmax, setpar, slope_esat_ice, setroots, esat, tfrz
cable_diag1 calls cable_diag_data1, cable_diag_desc1
surface_albedo calls point2constants, surface_albedosn, calc_rhoch
find_vcmax_jmax_lut calls light_inhibition
zero_casa_var calls zero_casaflux, zero_casapool, zero_casabiome, zero_casamet, zero_casabal
write_ovar calls write_output_variable_r1, write_output_parameter_r1, write_output_parameter_r2, write_output_parameter_r2d, write_output_variable_r2, write_output_parameter_r1d
write_netcdf_climate_type calls nf90_create, nf90_put_var, nf90_def_dim, nf90_enddef, nf90_close, nf90_def_var, nc_err
write_netcdf_casabiome calls nf90_create, nf90_put_var, nf90_def_dim, nf90_enddef, nf90_close, nf90_def_var, nc_err
read_casa_restart_nc calls read_netcdf_casa_var, read_netcdf_phen_var
stempv calls trimb
casa_xnp calls casa_nrequire, casa_prequire
casa_puptake calls casa_prequire
write_netcdf_casamet calls nf90_create, nf90_put_var, nf90_def_dim, nf90_enddef, nf90_close, nf90_def_var, nc_err
patchannualdynamics calls get_allometry, layer_recruitment
patch_disturb calls layer_recruitment_single_patch
spatialsoil calls nf90_open, nf90_get_var, nc_abort, nf90_inq_varid, nf90_close
diff_ac_aj calls point2constants, light_inhibition, fabc, ej3x, xgmest, fan_c3, xvcmxt3, fabcd, xvcmxt3_acclim, fam_c3, xejmxt3, xejmxt3_acclim, xrdt, fpq
get_var_ncr3 calls nf90_get_var, nf90_inq_varid, stderr_nc
define_output_parameter_r1 calls cable_abort, nf90_put_att, nc_abort, nf90_def_var
getrex calls getrex_1d, getrex_2d
isotope_pool_model_1d calls eq, ne, diag, mpi_abort
interpolate_firemortality calls realexponential
casa_allocation calls casa_wolf
write_output_variable_r1 calls cable_abort, nf90_put_var, nc_abort, range_abort
read_netcdf_climate_type calls nf90_open, nf90_get_var, nf90_inq_varid, nf90_close, nc_err
seb calls potential_evap, slope_csat, hyofh
hyofs calls tfrz, dthetalmaxdt, slope_esat, igamma
write_output_parameter_r1 calls cable_abort, nf90_put_var, nc_abort
casa_nuptake calls casa_nrequire
casa_rplant calls vcmax_np
read_luc_restart_nc calls nf90_open, nf90_get_var, nf90_inquire_dimension, nf90_inq_varid, handle_err, nf90_close, nf90_inq_dimid
write_netcdf_casaflux calls nf90_create, nf90_put_var, nf90_def_dim, nf90_enddef, nf90_close, nf90_def_var, nc_err
extrarestart calls nf90_get_var, nc_abort, nf90_inq_varid, readpar, redistr_r2, redistr_i, redistr_r, redistr_r2d, redistr_rd
nc_err calls nf90_strerror
solve calls hyofs, zerovars, sofh, litter_props, hyofh, setsol, timestep_loop
define_output_parameter_r2 calls cable_abort, nf90_put_att, nc_abort, nf90_def_var
thetalmax calls tfrz
write_output_parameter_r2 calls cable_abort, nf90_put_var, nc_abort
write_netcdf_casabal calls nf90_create, nf90_put_var, nf90_def_dim, nf90_enddef, nf90_close, nf90_def_var, nc_err
combust calls avail_fuel
surfbv calls smoisturev
put_var_ncr2 calls nf90_put_var, nf90_inq_varid, stderr_nc
write_netcdf_casapool calls nf90_create, nf90_put_var, nf90_def_dim, nf90_enddef, nf90_close, nf90_def_var, nc_err
cru_read_metvals calls nf90_get_var, handle_err
define_output_variable_r2 calls cable_abort, nf90_put_att, nc_abort, nf90_def_var
leap_day calls is_leapyear
write_output_parameter_r2d calls cable_abort, nf90_put_var, nc_abort
isotope_luc_model_1d calls eq, mpi_abort
surface_albedosn calls soilcol_albedo
getuniqueagefrequencies calls realexponential, cumexponential
simfire calls is_leapyear, annual_ba, get_popdens
casa_xrateplant calls ge, le
rtbis calls eq, ge, le
put_var_ncr3 calls nf90_put_var, nf90_inq_varid, stderr_nc
read_gridinfo calls cable_abort, nf90_open, nf90_get_var, nc_abort, nf90_inquire_dimension, nf90_inq_varid, nf90_close, nf90_inq_dimid
isotope_pool_model_2d calls eq, ne, diag, mpi_abort
ge calls greaterequal_sp, greaterequal_dp
initpop2d_poisson calls exponential, cumexponential
get_var_ncr2 calls nf90_get_var, nf90_inq_varid, stderr_nc
readpar calls readpar_rd, readpar_i, readpar_r2d, readpar_r2, readpar_r
lmdif1 calls lmdif
c13o2_read_restart_luc calls nf90_open, nf90_get_var, c13o2_err_handler, nf90_inq_varid, nf90_close
dryleaf calls light_inhibition, xvcmxt4_acclim, ej3x, xgmest, getrex_1d, fwsoil_calc_non_linear, fwsoil_calc_std, xvcmxt3, photosynthesis_gm, fwsoil_calc_lai_katul, xvcmxt3_acclim, xejmxt3, xvcmxt4, xejmxt3_acclim, xrdt
luc_expt_set_tiles_bios calls cable_bios_load_fracc4
setroots calls setroots_1d, setroots_2d
write_output_variable_r2 calls cable_abort, nf90_put_var, nc_abort, range_abort
total_photosynthesis_cost calls point2constants, light_inhibition, fabc, ej3x, xgmest, fan_c3, xvcmxt3, fabcd, xvcmxt3_acclim, fam_c3, xejmxt3, xejmxt3_acclim, xrdt, fpq
write_output_parameter_r1d calls cable_abort, nf90_put_var, nc_abort
getdiagnostics calls get_allometry, smooth_flux, interpolate_biomass_1d, interpolate_biomass_2d
put_var_ncr1 calls nf90_put_var, nf90_inq_varid, stderr_nc
layer_recruitment_single_patch calls get_allometry
casa_cnpcycle calls casa_poolzero
read_soilcolor calls ne, nf90_open, nf90_get_var, nc_abort, nf90_inquire_dimension, nf90_inq_varid, nf90_close, nf90_inq_dimid
define_output_variable_r1 calls cable_abort, nf90_put_att, nc_abort, nf90_def_var
cable_bios_load_fracc4 calls get_unit
le calls lesserequal_dp, lesserequal_sp
readpar_rd calls cable_abort, nf90_get_var, nc_abort, nf90_inq_varid, nf90_inquire_variable
xvcmxt4_acclim calls point2constants
get_allometry calls getheight, allometry, williams_allometry
xgmest calls point2constants
getrex_2d calls getrex_1d
diag calls diag_2d, diag_3d
redistr_r2 calls float
potential_evap calls slope_esat_ice, slope_esat
readpar_i calls cable_abort, nf90_get_var, nc_abort, nf90_inq_varid, nf90_inquire_variable
readpar_r2d calls cable_abort, nf90_get_var, nc_abort, nf90_inq_varid, nf90_inquire_variable
lmdif calls eq, ne, ge, le, enorm, fdjac2, lmpar, qrfac
dthetalmaxdt calls tfrz
smoisturev calls trimb
litter_props calls slope_esat
setroots_2d calls setroots_1d
xvcmxt3 calls point2constants
readpar_r2 calls cable_abort, nf90_get_var, nc_abort, nf90_inq_varid, nf90_inquire_variable
photosynthesis_gm calls fandan_c3, famdam_c3, fandan_c4, famdam_c4
get_popdens calls get_unit
xvcmxt3_acclim calls point2constants
xejmxt3 calls point2constants
read_netcdf_casa_var calls read_netcdf_casaflux, read_netcdf_casapool, read_netcdf_casamet, read_netcdf_casabal, read_netcdf_casabiome
read_netcdf_phen_var calls nf90_open, nf90_get_var, nf90_inq_varid, nf90_close, nc_err
layer_recruitment calls get_allometry
redistr_r calls float
timestep_loop calls litter_props, isotope_vap, iflux_loop
xvcmxt4 calls point2constants
smooth_flux calls regress
redistr_r2d calls float
redistr_rd calls float
interpolate_biomass_1d calls realexponential
interpolate_biomass_2d calls eq, realexponential, area_triangle
igamma calls gammln, gser, gcf
readpar_r calls cable_abort, nf90_get_var, nc_abort, nf90_inq_varid, nf90_inquire_variable
xejmxt3_acclim calls point2constants
fandan_c3 calls fdan_c3, fabc, fan_c3, fdabc
diag_2d calls mpi_abort
fdjac2 calls eq
famdam_c3 calls fabcd, fdabcd, fam_c3, fpq, fdpq, fdam_c3
lmpar calls eq, le, enorm, qrsolv
read_netcdf_casaflux calls nf90_open, nf90_get_var, nf90_inq_varid, nf90_close, nc_err
gser calls eq, gammln
read_netcdf_casapool calls nf90_open, nf90_get_var, nf90_inq_varid, nf90_close, nc_err
isotope_vap calls ne, tri
qrfac calls ne, le, enorm
fandan_c4 calls fan_c4, fabc_c4, fdan_c4, fdabc_c4
read_netcdf_casamet calls nf90_open, nf90_get_var, nf90_inq_varid, nf90_close, nc_err
diag_3d calls mpi_abort
famdam_c4 calls fam_c4, fabcm, fdabcm, fdam_c4
read_netcdf_casabal calls nf90_open, nf90_get_var, nf90_inq_varid, nf90_close, nc_err
gcf calls eq, gammln
read_netcdf_casabiome calls nf90_open, nf90_get_var, nf90_inq_varid, nf90_close, nc_err
iflux_loop calls hyofs, litter_props, get_fluxes_and_derivs, update_unknowns, update_s_t, snow_adjust, get_and_solve_eqn, estimate_timestep
get_fluxes_and_derivs calls seb, zerovars, flux, getheatfluxes, getfluxes_vp
qrsolv calls eq, ne
tri calls tri_1d, tri_2d
update_unknowns calls jsoillayer
update_s_t calls thetalmax, tfrz, jsoillayer, gtfrozen, dthetalmaxdth, rtbis_tfrozen
snow_adjust calls esat_ice, thetalmax, slope_esat_ice, tfrz, jsoillayer, gtfrozen, rtbis_tfrozen
get_and_solve_eqn calls tfrz, massman_sparse
flux calls weight
getheatfluxes calls getheatfluxes_2d, getheatfluxes_1d
getfluxes_vp calls getfluxes_vp_2d, getfluxes_vp_1d
jsoillayer calls tfrz
gtfrozen calls tfrz
dthetalmaxdth calls tfrz
rtbis_tfrozen calls gtfrozen
massman_sparse calls massman_sparse_1d, massman_sparse_2d
weight calls hyofh
getfluxes_vp_2d calls eq, zerovars, hyofh, flux
getfluxes_vp_1d calls eq, zerovars, hyofh, flux
massman_sparse_1d calls generic_thomas
massman_sparse_2d calls generic_thomas
generic_thomas calls generic_thomas_1d, generic_thomas_2d