mpi_driver – POP
mpi_driver Program
25 statements
Source File
Uses
cable_mpicommon
cable_mpiworker
mpi
cable_mpimaster
Calls
Contents
Variables
comm np rank ierr etime
Variables
Type Attributes Name Initial
integer :: comm
integer :: np
integer :: rank
integer :: ierr
real :: etime
Call graph
mpi_driver calls mpi_init, mpi_comm_size, mpi_comm_dup, mpi_abort, mpi_comm_rank, mpidrv_master, mpidrv_worker, mpi_finalize
mpidrv_master calls mpi_comm_dup, mpi_abort, c13o2_close_output, c13o2_sanity_pools, close_output_file, master_casaonly_luc, luc_expt_init, get_unit, cable_bios_load_params, load_parameters, master_casa_luc_types, master_spincasacnp, write_casa_restart_nc, c13o2_print_delta_pools, master_end, zero_cbm_var, master_outtypes, write_luc_output_grid_nc, write_output, find_extents, master_climate_types, mpi_send, open_output_file, open_met_file, pop_luc_casa_transfer, ne, mpi_bcast, climate_init, master_c13o2_luc_params, ini_simfire, write_casa_output_nc, cable_bios_load_climate_params, c13o2_update_luc, is_leapyear, master_c13o2_flux_params, nullify_write, report_version_no, plume_mip_get_met, c13o2_print_delta_luc, master_receive_pop, point2constants, create_restart, c13o2_zero_sum_pools, master_casa_params, zero_sum_casa, lucdriver, close_luh2, pop_io, master_c13o2_luc_types, master_casa_dump_types, cru_init, c13o2_create_output, master_intypes, master_casa_types, write_blaze_output_nc, c13o2_write_restart_luc, master_blaze_types, get_met_data, preparefiles, alloc_cbm_var, casa_fluxout, popluc_set_patchfrac, master_c13o2_pool_types, c13o2_write_output, casa_cnpflux, write_casa_dump, c13o2_write_restart_flux, c13o2_print_delta_flux, c13o2_sanity_luc, ini_blaze, c13o2_save_luc, write_luc_output_nc, read_gm_lut, cable_bios_init, master_pop_types, write_luc_restart_nc, c13o2_update_sum_pools, master_send_input, master_c13o2_flux_types, master_c13o2_pool_params, cable_bios_read_met, c13o2_write_restart_pools, read_climate_restart_nc, master_decomp, master_receive, plume_mip_init, master_restart_types, update_sum_casa, master_cable_params, write_climate_restart_nc, close_met_file, is_casa_time, cru_get_subdiurnal_met
mpidrv_worker calls mpi_comm_dup, mpi_abort, mpi_comm_rank, c13o2_sanity_pools, worker_restart_type, worker_intype, worker_climate_types, mpi_recv, worker_c13o2_flux_params, worker_casa_luc_types, cbm, find_extents, mpi_send, worker_end, worker_blaze_types, worker_c13o2_flux_type, worker_c13o2_pool_type, mpi_bcast, ini_simfire, is_leapyear, worker_cable_params, blaze_driver, point2constants, sumcflux, popdriver, worker_spincasacnp, blaze_accounting, cable_climate, worker_c13o2_luc_type, isoratio, worker_decomp, worker_casa_params, worker_casa_dump_types, worker_c13o2_luc_params, casa_cnpflux, worker_casa_type, ini_blaze, read_gm_lut, worker_outtype, worker_pop_types, bgcdriver, worker_c13o2_pool_params, casa_feedback, worker_send_pop, worker_casaonly_luc, is_casa_time
c13o2_close_output calls nf90_close, c13o2_err_handler
c13o2_sanity_pools calls isosanity
close_output_file calls nc_abort, nf90_close
master_casaonly_luc calls c13o2_sanity_pools, write_casa_restart_nc, write_luc_output_grid_nc, mpi_send, pop_luc_casa_transfer, c13o2_update_luc, master_receive_pop, pop_io, c13o2_write_restart_luc, popluc_set_patchfrac, c13o2_sanity_luc, c13o2_save_luc, write_luc_output_nc, write_luc_restart_nc, master_send_input, c13o2_write_restart_pools, master_receive, pop_init_single, alloc_phenvariable, eq, read_luh2, zero_casa_var, copy_save_variables, alloc_casa_var, read_casa_dump, zero_phenvariable, popluc_weights_transfer, poplucstep
luc_expt_init calls get_unit, nf90_inquire_dimension, cable_bios_load_biome, luc_expt_zero, handle_err, read_climatefile, nf90_get_att, nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nf90_inq_dimid
cable_bios_load_params calls get_unit
load_parameters calls zero_sum_casa, pop_io, c13o2_init_flux, c13o2_zero_flux, get_parameters_met, alloc_phenvariable, get_default_params, popluc_init, nf90_inquire_dimension, nc_abort, casa_readbiome, report_parameters, allocate_cable_vars, get_restart_data, c13o2_init_luc, c13o2_read_restart_flux, handle_err, check_parameter_values, alloc_sum_casa, cable_abort, zero_casa_var, write_cnp_params, c13o2_read_restart_pools, c13o2_alloc_flux, c13o2_zero_pools, alloc_casa_var, nf90_open, pop_init, derived_parameters, nf90_close, zero_phenvariable, nf90_inq_dimid, write_default_params, casa_readphen, c13o2_init_pools, casa_init, c13o2_alloc_pools
master_casa_luc_types calls mpi_abort, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_type_free, mpi_type_commit
master_spincasacnp calls c13o2_sanity_pools, write_casa_restart_nc, master_receive_pop, pop_io, casa_fluxout, master_send_input, c13o2_write_restart_pools, master_receive, alloc_phenvariable, zero_casa_var, copy_save_variables, alloc_casa_var, read_casa_dump, zero_phenvariable
write_casa_restart_nc calls write_netcdf_phen_var, write_netcdf_casa_var
worker_restart_type calls mpi_abort, mpi_comm_rank, mpi_reduce, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, add_address_1block, mpi_type_commit
worker_intype calls mpi_abort, mpi_comm_rank, mpi_reduce, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, add_address_1block, mpi_type_commit
worker_climate_types calls mpi_abort, mpi_recv, zero_cbm_var, alloc_cbm_var, mpi_reduce, mpi_type_create_struct, mpi_type_size, mpi_get_count, mpi_get_address, mpi_type_get_extent, add_address_1block, mpi_unpack, mpi_type_commit
worker_c13o2_flux_params calls mpi_abort, mpi_comm_rank, mpi_recv, mpi_reduce, c13o2_zero_flux, mpi_type_create_struct, mpi_type_size, c13o2_alloc_flux, mpi_get_count, mpi_type_get_extent, add_address_1block, mpi_unpack, mpi_type_free, mpi_type_commit, mpi_barrier
worker_casa_luc_types calls mpi_abort, mpi_comm_rank, mpi_reduce, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, add_address_1block, mpi_type_commit
cbm calls point2constants, ruff_resist, surface_albedo, init_radiation, soilcarb, sli_main, define_air, plantcarb, soil_snow, define_canopy, carbon_pl
c13o2_print_delta_pools calls ne, delta1000
master_end calls mpi_type_free
zero_cbm_var calls zero_radiation_type, zero_balances_type, zero_met_type, zero_sum_flux_type, zero_roughness_type, zero_climate_type, zero_bgc_pool_type, zero_soil_snow_type, zero_veg_parameter_type, zero_air_type, zero_canopy_type, zero_soil_parameter_type
master_outtypes calls mpi_abort, mpi_reduce, mpi_type_create_hvector, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_type_create_hindexed, mpi_get_address, mpi_type_get_extent, mpi_type_commit
write_luc_output_grid_nc calls nf90_put_var, nf90_create, nf90_enddef, nf90_redef, nf90_def_dim, handle_err, nf90_put_att, nf90_def_var, nf90_close
write_output calls is_leapyear, nf90_put_var, write_ovar, mass_balance, nc_abort, toreal4, energy_balance, cable_abort, nf90_sync
find_extents calls mpi_get_address
master_climate_types calls mpi_abort, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_isend, mpi_get_address, mpi_type_get_extent, mpi_type_commit, mpi_waitall
open_output_file calls nf90_put_var, nf90_create, nf90_enddef, write_ovar, nc_abort, toreal4, nf90_def_dim, nf90_put_att, cable_abort, nf90_def_var, define_ovar
open_met_file calls is_leapyear, nf90_inquire_variable, nf90_inquire_dimension, nc_abort, eq, ymdhms2doysod, handle_err, cable_abort, doysod2ymdhms, nf90_get_att, nf90_get_var, nf90_open, nf90_inq_varid, nf90_inq_dimid
pop_luc_casa_transfer calls eq
worker_end calls mpi_type_free
worker_blaze_types calls mpi_abort, mpi_comm_rank, mpi_reduce, mpi_type_create_struct, mpi_type_size, mpi_get_address, mpi_type_get_extent, mpi_type_commit
worker_c13o2_flux_type calls mpi_abort, mpi_reduce, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, add_address_1block, mpi_type_commit
worker_c13o2_pool_type calls mpi_abort, mpi_reduce, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, add_address_1block, mpi_type_commit
ne calls notequal_dp, notequal_sp
master_c13o2_luc_params calls mpi_abort, master_send_input, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_type_free, mpi_type_commit, mpi_barrier
ini_simfire calls get_unit, zero_simfire, handle_err, nf90_get_var, nf90_open, nf90_inq_varid, nf90_close
write_casa_output_nc calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, handle_err, nf90_put_att, nf90_def_var, nf90_close
cable_bios_load_climate_params calls get_unit
c13o2_update_luc calls c13o2_save_c13o2pools, isotope_pool_model, isotope_luc_model
worker_cable_params calls mpi_abort, mpi_comm_rank, mpi_recv, mpi_reduce, allocate_cable_vars, mpi_type_create_struct, mpi_type_size, decomp_types, mpi_get_count, mpi_type_get_extent, add_address_1block, mpi_unpack, mpi_type_free, mpi_type_commit
blaze_driver calls is_leapyear, blaze_turnover, adjust_pop_for_fire, doysod2ymdhms, run_blaze
master_c13o2_flux_params calls mpi_abort, master_send_input, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_type_free, mpi_type_commit, mpi_barrier
plume_mip_get_met calls file_switch, get_plume_ndep, open_plume_met, wgen_subdiurnal_met, eq, wgen_init, plume_get_daily_met, handle_err, wgen_daily_constants, doysod2ymdhms, rh_sh, get_plume_co2, nf90_close
c13o2_print_delta_luc calls ne, delta1000
master_receive_pop calls mpi_recv
point2constants calls driver_type_ptr, cbm_type_ptr, albedo_type_ptr, canopy_type_ptr, ssnow_type_ptr, rad_type_ptr, rough_type_ptr, air_type_ptr, carbon_type_ptr
create_restart calls nf90_put_var, nf90_create, nf90_enddef, write_ovar, nc_abort, toreal4, nf90_def_dim, nf90_put_att, nf90_def_var, define_ovar, nf90_close
popdriver calls popstep
master_casa_params calls mpi_abort, master_send_input, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, add_address_1block, mpi_type_free, mpi_type_commit, mpi_barrier
zero_sum_casa calls zero_casaflux, zero_casapool
worker_spincasacnp calls c13o2_sanity_pools, mpi_recv, mpi_send, blaze_driver, popdriver, isoratio, worker_send_pop, biogeochem, analyticpool, c13o2_update_pools, c13o2_save_casapool
lucdriver calls pop_init_single, eq, read_luh2, popluc_weights_transfer, poplucstep
close_luh2 calls handle_err, nf90_close
pop_io calls ne, nf90_put_var, nf90_create, nf90_enddef, nf90_inquire_dimension, nf90_def_dim, handle_err, nf90_put_att, nf90_get_var, nf90_open, nf90_inq_varid, nf90_def_var, nf90_close, nf90_inq_dimid
master_c13o2_luc_types calls mpi_abort, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_type_free, mpi_type_commit
master_casa_dump_types calls mpi_abort, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_type_commit
cru_init calls get_unit, nf90_inquire_dimension, handle_err, nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nf90_inq_dimid
c13o2_create_output calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, nf90_put_att, nf90_def_var, c13o2_err_handler
master_intypes calls mpi_abort, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_type_commit
master_casa_types calls mpi_abort, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_type_free, mpi_type_commit
write_blaze_output_nc calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, handle_err, nf90_put_att, nf90_def_var, nf90_close
c13o2_write_restart_luc calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, nf90_put_att, nf90_def_var, nf90_close, c13o2_err_handler
cable_climate calls epsif, biome1_pft
worker_c13o2_luc_type calls mpi_abort, mpi_reduce, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, add_address_1block, mpi_type_commit
worker_decomp calls mpi_recv
worker_casa_params calls mpi_abort, mpi_comm_rank, mpi_recv, mpi_reduce, alloc_phenvariable, mpi_type_create_struct, mpi_type_size, zero_casa_var, alloc_casa_var, zero_phenvariable, mpi_get_count, mpi_type_get_extent, add_address_1block, mpi_unpack, mpi_type_free, mpi_type_commit, mpi_barrier
worker_casa_dump_types calls mpi_abort, mpi_comm_rank, mpi_reduce, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, add_address_1block, mpi_type_commit
worker_c13o2_luc_params calls mpi_abort, mpi_comm_rank, mpi_recv, mpi_reduce, c13o2_alloc_luc, mpi_type_create_struct, mpi_type_size, c13o2_zero_luc, mpi_get_count, mpi_type_get_extent, add_address_1block, mpi_unpack, mpi_type_free, mpi_type_commit, mpi_barrier
master_blaze_types calls mpi_abort, mpi_reduce, mpi_type_create_hvector, mpi_type_create_struct, mpi_type_size, mpi_get_address, mpi_type_get_extent, mpi_type_free, mpi_type_commit
get_met_data calls is_leapyear, nc_abort, eq, cable_abort, nf90_get_var, rh_sh, sinbet
preparefiles calls renamefiles
alloc_cbm_var calls alloc_climate_type, alloc_met_type, alloc_soil_parameter_type, alloc_veg_parameter_type, alloc_air_type, alloc_soil_snow_type, alloc_bgc_pool_type, alloc_balances_type, alloc_roughness_type, alloc_radiation_type, alloc_canopy_type, alloc_sum_flux_type
master_c13o2_pool_types calls mpi_abort, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_type_free, mpi_type_commit
c13o2_write_output calls nf90_put_var, c13o2_err_handler
write_casa_dump calls nf90_create, nf90_enddef, put_var_nc, stderr_nc, def_dims, def_vars, nf90_close
c13o2_write_restart_flux calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, nf90_put_att, nf90_def_var, nf90_close, c13o2_err_handler
c13o2_print_delta_flux calls ne, delta1000
worker_casa_type calls mpi_abort, mpi_reduce, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, add_address_1block, mpi_type_commit
c13o2_sanity_luc calls isosanity
ini_blaze calls get_unit, zero_blaze
c13o2_save_luc calls c13o2_save_casapool
write_luc_output_nc calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, handle_err, nf90_put_att, nf90_def_var, nf90_close
read_gm_lut calls nf90_inquire_dimension, nc_abort, nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nf90_inq_dimid
cable_bios_init calls get_unit, wgen_init, readarcfltheader, daydifference
master_pop_types calls mpi_send, create_pop_gridcell_type
write_luc_restart_nc calls nf90_put_var, nf90_create, nf90_enddef, nf90_redef, nf90_def_dim, handle_err, nf90_put_att, nf90_def_var, nf90_close
master_send_input calls mpi_isend, mpi_waitall
master_c13o2_flux_types calls mpi_abort, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_type_free, mpi_type_commit
worker_outtype calls mpi_abort, mpi_comm_rank, find_extents, mpi_reduce, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, add_address_1block, mpi_type_commit
master_c13o2_pool_params calls mpi_abort, master_send_input, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_type_free, mpi_type_commit, mpi_barrier
cable_bios_read_met calls wgen_subdiurnal_met, eq, wgen_daily_constants, daydifference
c13o2_write_restart_pools calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, nf90_put_att, nf90_def_var, nf90_close, c13o2_err_handler
worker_pop_types calls mpi_comm_rank, mpi_recv, create_pop_gridcell_type, pop_init
read_climate_restart_nc calls read_netcdf_cbm_var
master_decomp calls mpi_comm_size, mpi_abort, mpi_send
master_receive calls mpi_irecv, mpi_waitall
plume_mip_init calls get_unit, nf90_inquire_dimension, handle_err, nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nf90_inq_dimid
master_restart_types calls mpi_abort, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_type_free, mpi_type_commit
master_cable_params calls mpi_abort, mpi_send, master_send_input, mpi_reduce, add_address_hvector, mpi_type_create_struct, mpi_type_size, decomp_types, mpi_type_get_extent, mpi_type_free, mpi_type_commit
write_climate_restart_nc calls write_netcdf_cbm_var
bgcdriver calls biogeochem, c13o2_update_pools, cable_phenology_clim, c13o2_save_casapool
worker_c13o2_pool_params calls mpi_abort, mpi_comm_rank, mpi_recv, mpi_reduce, mpi_type_create_struct, mpi_type_size, c13o2_zero_pools, mpi_get_count, mpi_type_get_extent, add_address_1block, mpi_unpack, mpi_type_free, mpi_type_commit, mpi_barrier, c13o2_alloc_pools
casa_feedback calls point2constants, adjust_jv_gm, vcmax_np, optimise_jv, find_vcmax_jmax_lut, adjust_k_collatz
worker_send_pop calls mpi_send
close_met_file calls nc_abort, nf90_close
worker_casaonly_luc calls mpi_comm_rank, c13o2_sanity_pools, mpi_recv, mpi_send, popdriver, worker_send_pop, biogeochem, c13o2_update_pools, c13o2_save_casapool
is_casa_time calls is_leapyear
cru_get_subdiurnal_met calls wgen_subdiurnal_met, eq, wgen_init, cru_get_daily_met, open_cru_met, handle_err, wgen_daily_constants, get_cru_ndep, doysod2ymdhms, get_cru_co2, nf90_close
pop_init_single calls initpop2d_poisson, zeropop, layer_recruitment_single_patch
c13o2_init_flux calls init_sugar_pools, init_starch_pool
ruff_resist calls point2constants
write_netcdf_phen_var calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, nf90_def_var, nf90_close, nc_err
surface_albedo calls point2constants, calc_rhoch, surface_albedosn
get_plume_ndep calls handle_err, nf90_get_var, nf90_open, nf90_inq_varid
open_plume_met calls handle_err, nf90_get_att, nf90_open, nf90_inq_varid, plume_get_filename, leap_day
biogeochem calls casa_cnpflux, casa_xrateplant, casa_rplant, casa_coeffplant, avgsoil, casa_ndummy, casa_cnpcycle, casa_nuptake, casa_xkn, casa_allocation, casa_puptake, casa_cnpbal, casa_delplant, casa_coeffsoil, casa_xratesoil, casa_xnp, phenology, casa_pdummy, casa_delsoil
create_pop_gridcell_type calls mpi_abort, mpi_type_create_struct, mpi_get_address, mpi_type_commit, create_patch, mpi_type_create_resized
read_netcdf_cbm_var calls read_netcdf_climate_type
write_netcdf_cbm_var calls write_netcdf_climate_type
write_ovar calls write_output_parameter_r1d, write_output_variable_r1, write_output_parameter_r1, write_output_variable_r2, write_output_parameter_r2, write_output_parameter_r2d
init_radiation calls point2constants, spitter, calc_rhoch
write_netcdf_casa_var calls write_netcdf_casapool, write_netcdf_casabal, write_netcdf_casabiome, write_netcdf_casamet, write_netcdf_casaflux
get_parameters_met calls nf90_inq_varid, readpar
get_default_params calls luc_expt_set_tiles, get_type_parameters, get_land_index, spatialsoil, read_gridinfo, countpatch, luc_expt_set_tiles_bios, read_soilcolor
put_var_nc calls put_var_ncr3, put_var_ncr2, put_var_ncr1
popluc_init calls pop_init_single, read_luc_restart_nc, popluc_set_params, zero_popluc, alloc_popluc
sli_main calls slope_esat_ice, hyofs, setpar_loetsch, zerovars_met, getrex, esat, esat_ice, setpar, seb, thetalmax, zerovars, setx, tfrz, setlitterpar, solve, setroots, zerovars_snow
mass_balance calls eq
nc_abort calls nf90_strerror
eq calls equal_sp, equal_dp
add_address_hvector calls add_address_hvector_1d_r2, add_address_hvector_2d_r1, add_address_hvector_1d_i1, add_address_hvector_3d_r1, add_address_hvector_3d_r2, add_address_hvector_2d_l, add_address_hvector_1d_r1, add_address_hvector_2d_i1, add_address_hvector_3d_i1, add_address_hvector_3d_l, add_address_hvector_2d_r2, add_address_hvector_1d_l
allocate_cable_vars calls zero_cbm_var, alloc_cbm_var
get_restart_data calls nf90_inquire_dimension, nc_abort, cable_abort, nf90_get_var, nf90_inq_varid, nf90_close, nf90_inq_dimid, extrarestart, readpar
cable_bios_load_biome calls get_unit
c13o2_init_luc calls c13o2_alloc_luc, c13o2_zero_luc, c13o2_read_restart_luc
wgen_init calls wgen_zero
stderr_nc calls nf90_strerror
cru_get_daily_met calls nf90_inquire_dimension, handle_err, nf90_open, nf90_inq_varid, nf90_close, nf90_inq_dimid, cru_get_metyear, cru_read_metvals, cru_get_filename
plume_get_daily_met calls nf90_inquire_dimension, handle_err, nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nf90_inq_dimid, plume_get_filename
toreal4 calls i2sp, dp2sp, sp2sp
open_cru_met calls handle_err, nf90_open, nf90_inq_varid, cru_get_metyear, cru_get_filename
adjust_jv_gm calls point2constants, lmdif1, light_inhibition, photosyn25
ymdhms2doysod calls is_leapyear
c13o2_read_restart_flux calls nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, c13o2_err_handler
define_air calls point2constants
read_luh2 calls handle_err, nf90_get_var
handle_err calls nf90_strerror
check_parameter_values calls cable_abort
alloc_sum_casa calls alloc_casaflux, alloc_casapool
plantcarb calls point2constants
decomp_types calls mpi_type_create_struct, mpi_get_address, mpi_type_commit, mpi_type_create_resized
adjust_pop_for_fire calls interpolate_firemortality, topkill_collins
optimise_jv calls point2constants, rtbis, golden, total_photosynthesis_cost, diff_ac_aj
get_cru_ndep calls handle_err, nf90_get_var, nf90_open, nf90_inq_varid
doysod2ymdhms calls is_leapyear
read_climatefile calls alloc_cbm_var, read_netcdf_cbm_var, nf90_inquire_dimension, nf90_open, nf90_close, nf90_inq_dimid, nc_err
zero_casa_var calls zero_casaflux, zero_casapool, zero_casabiome, zero_casamet, zero_casabal
c13o2_read_restart_pools calls nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, c13o2_err_handler
c13o2_update_pools calls c13o2_save_c13o2pools, isotope_pool_model, c13o2_sinks_pools, c13o2_sources_pools, c13o2_c13o2pools_back, c13o2_fluxmatrix_pools
find_vcmax_jmax_lut calls light_inhibition
run_blaze calls is_leapyear, blaze_turnover, doysod2ymdhms, simfire, combust, avail_fuel
adjust_k_collatz calls light_inhibition
def_dims calls stderr_nc, nf90_def_dim
soil_snow calls point2constants, surfbv, snow_melting, snowcheck, snowl_adjust, stempv, remove_trans, snow_accum, snowdensity, soilfreeze_serial, hydraulic_redistribution
alloc_casa_var calls alloc_casaflux, alloc_casabiome, alloc_casamet, alloc_casapool, alloc_casabal
read_casa_dump calls stderr_nc, nf90_open, nf90_close, get_var_nc
pop_init calls initpop2d_poisson, alloc_pop, zeropop, layer_recruitment_single_patch
rh_sh calls svp
popstep calls patchannualdynamics, getdiagnostics, patch_partial_disturb2, patch_partial_disturb, getpatchfrequencies, getuniqueagefrequencies, patch_disturb
get_plume_co2 calls get_unit
def_vars calls stderr_nc, nf90_def_var
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
get_cru_co2 calls get_unit
define_ovar calls define_output_parameter_r1, define_output_variable_r1, define_output_variable_r2, define_output_parameter_r2
define_canopy calls point2constants, ruff_resist, sli_main, eq, define_air, surf_wetness_fact, radiation, dryleaf
write_default_params calls cable_abort, init_veg_from_vegin
add_address_1block calls add_address_1block_2d_r2, add_address_1block_1d_l, add_address_1block_3d_i1, add_address_1block_1d_r1, add_address_1block_2d_l, add_address_1block_3d_l, add_address_1block_3d_r1, add_address_1block_1d_r2, add_address_1block_2d_r1, add_address_1block_2d_i1, add_address_1block_3d_r2, add_address_1block_1d_i1
isotope_luc_model calls isotope_luc_model_1d
cable_phenology_clim calls eq, ge
daydifference calls julianday
poplucstep calls increment_age, execute_luc_event
casa_init calls read_casa_restart_nc, zero_casa_dump
casa_xrateplant calls ge, le
casa_rplant calls vcmax_np
hyofs calls tfrz, dthetalmaxdt, igamma, slope_esat
write_output_parameter_r1d calls nf90_put_var, nc_abort, cable_abort
read_casa_restart_nc calls read_netcdf_casa_var, read_netcdf_phen_var
define_output_parameter_r1 calls nc_abort, nf90_put_att, cable_abort, nf90_def_var
patchannualdynamics calls get_allometry, layer_recruitment
add_address_hvector_1d_r2 calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
getdiagnostics calls get_allometry, smooth_flux, interpolate_biomass_1d, interpolate_biomass_2d
add_address_1block_1d_l calls mpi_get_address
read_luc_restart_nc calls nf90_inquire_dimension, handle_err, nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nf90_inq_dimid
write_netcdf_casapool calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, nf90_def_var, nf90_close, nc_err
write_netcdf_casabal calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, nf90_def_var, nf90_close, nc_err
casa_cnpcycle calls casa_poolzero
initpop2d_poisson calls exponential, cumexponential
casa_nuptake calls casa_nrequire
lmdif1 calls lmdif
nc_err calls nf90_strerror
write_netcdf_climate_type calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, nf90_def_var, nf90_close, nc_err
add_address_1block_3d_i1 calls mpi_get_address
surfbv calls smoisturev
add_address_1block_1d_r1 calls mpi_get_address
add_address_hvector_2d_r1 calls mpi_type_create_hvector, mpi_get_address
define_output_variable_r1 calls nc_abort, nf90_put_att, cable_abort, nf90_def_var
write_output_variable_r1 calls nf90_put_var, nc_abort, cable_abort, range_abort
spatialsoil calls nc_abort, nf90_get_var, nf90_open, nf90_inq_varid, nf90_close
put_var_ncr3 calls nf90_put_var, stderr_nc, nf90_inq_varid
write_output_parameter_r1 calls nf90_put_var, nc_abort, cable_abort
add_address_hvector_1d_i1 calls mpi_get_address
add_address_hvector_3d_r1 calls mpi_type_create_hvector, mpi_get_address
rtbis calls eq, ge, le
add_address_1block_2d_l calls mpi_get_address
add_address_1block_3d_l calls mpi_get_address
isotope_luc_model_1d calls mpi_abort, eq
simfire calls is_leapyear, annual_ba, get_popdens
casa_allocation calls casa_wolf
getrex calls getrex_1d, getrex_2d
casa_puptake calls casa_prequire
write_netcdf_casabiome calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, nf90_def_var, nf90_close, nc_err
add_address_hvector_3d_r2 calls mpi_type_create_hvector, mpi_get_address
cru_read_metvals calls handle_err, nf90_get_var
ge calls greaterequal_dp, greaterequal_sp
interpolate_firemortality calls realexponential
stempv calls trimb
add_address_hvector_2d_l calls mpi_type_create_hvector, mpi_get_address
read_gridinfo calls nf90_inquire_dimension, nc_abort, cable_abort, nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nf90_inq_dimid
read_netcdf_climate_type calls nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nc_err
write_netcdf_casamet calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, nf90_def_var, nf90_close, nc_err
create_patch calls mpi_abort, mpi_type_create_struct, mpi_get_address, mpi_type_commit, mpi_type_create_resized, create_layer
seb calls potential_evap, hyofh, slope_csat
add_address_hvector_1d_r1 calls mpi_get_address
add_address_1block_3d_r1 calls mpi_get_address
thetalmax calls tfrz
isotope_pool_model_1d calls mpi_abort, ne, eq, diag
define_output_variable_r2 calls nc_abort, nf90_put_att, cable_abort, nf90_def_var
add_address_1block_1d_r2 calls mpi_get_address
put_var_ncr2 calls nf90_put_var, stderr_nc, nf90_inq_varid
casa_xnp calls casa_prequire, casa_nrequire
add_address_hvector_2d_i1 calls mpi_type_create_hvector, mpi_get_address
c13o2_read_restart_luc calls nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, c13o2_err_handler
add_address_hvector_3d_i1 calls mpi_type_create_hvector, mpi_get_address
getuniqueagefrequencies calls realexponential, cumexponential
add_address_1block_2d_r1 calls mpi_get_address
patch_disturb calls layer_recruitment_single_patch
total_photosynthesis_cost calls point2constants, xrdt, xejmxt3, ej3x, xgmest, xejmxt3_acclim, xvcmxt3_acclim, light_inhibition, fabcd, fabc, fam_c3, xvcmxt3, fpq, fan_c3
combust calls avail_fuel
dryleaf calls light_inhibition, xrdt, xvcmxt4, photosynthesis_gm, xejmxt3, ej3x, fwsoil_calc_std, xgmest, xejmxt3_acclim, fwsoil_calc_non_linear, xvcmxt3_acclim, getrex_1d, xvcmxt3, xvcmxt4_acclim, fwsoil_calc_lai_katul
write_output_variable_r2 calls nf90_put_var, nc_abort, cable_abort, range_abort
write_netcdf_casaflux calls nf90_put_var, nf90_create, nf90_enddef, nf90_def_dim, nf90_def_var, nf90_close, nc_err
leap_day calls is_leapyear
put_var_ncr1 calls nf90_put_var, stderr_nc, nf90_inq_varid
solve calls hyofs, zerovars, hyofh, timestep_loop, sofh, setsol, litter_props
setroots calls setroots_1d, setroots_2d
add_address_hvector_3d_l calls mpi_type_create_hvector, mpi_get_address
get_var_nc calls get_var_ncr3, get_var_ncr2
isotope_pool_model_2d calls mpi_abort, ne, eq, diag
define_output_parameter_r2 calls nc_abort, nf90_put_att, cable_abort, nf90_def_var
add_address_1block_2d_i1 calls mpi_get_address
extrarestart calls nc_abort, nf90_get_var, nf90_inq_varid, readpar, redistr_r2d, redistr_r2, redistr_i, redistr_r, redistr_rd
write_output_parameter_r2 calls nf90_put_var, nc_abort, cable_abort
luc_expt_set_tiles_bios calls cable_bios_load_fracc4
layer_recruitment_single_patch calls get_allometry
surface_albedosn calls soilcol_albedo
write_output_parameter_r2d calls nf90_put_var, nc_abort, cable_abort
add_address_1block_3d_r2 calls mpi_get_address
add_address_hvector_2d_r2 calls mpi_type_create_hvector, mpi_get_address
diff_ac_aj calls point2constants, xrdt, xejmxt3, ej3x, xgmest, xejmxt3_acclim, xvcmxt3_acclim, light_inhibition, fabcd, fabc, fam_c3, xvcmxt3, fpq, fan_c3
add_address_1block_1d_i1 calls mpi_get_address
readpar calls readpar_i, readpar_rd, readpar_r2, readpar_r, readpar_r2d
read_soilcolor calls ne, nf90_inquire_dimension, nc_abort, nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nf90_inq_dimid
add_address_hvector_1d_l calls mpi_get_address
readpar_i calls nf90_inquire_variable, nc_abort, cable_abort, nf90_get_var, nf90_inq_varid
create_layer calls mpi_abort, mpi_type_create_struct, mpi_get_address, mpi_type_commit, mpi_type_create_resized, create_cohort
potential_evap calls slope_esat_ice, slope_esat
xvcmxt4 calls point2constants
photosynthesis_gm calls fandan_c3, famdam_c4, famdam_c3, fandan_c4
redistr_r2d calls float
xejmxt3 calls point2constants
dthetalmaxdt calls tfrz
get_allometry calls williams_allometry, getheight, allometry
smooth_flux calls regress
lmdif calls ne, eq, ge, le, qrfac, fdjac2, enorm, lmpar
interpolate_biomass_1d calls realexponential
readpar_rd calls nf90_inquire_variable, nc_abort, cable_abort, nf90_get_var, nf90_inq_varid
redistr_r2 calls float
get_var_ncr3 calls stderr_nc, nf90_get_var, nf90_inq_varid
readpar_r2 calls nf90_inquire_variable, nc_abort, cable_abort, nf90_get_var, nf90_inq_varid
readpar_r calls nf90_inquire_variable, nc_abort, cable_abort, nf90_get_var, nf90_inq_varid
xgmest calls point2constants
xejmxt3_acclim calls point2constants
xvcmxt3_acclim calls point2constants
timestep_loop calls litter_props, iflux_loop, isotope_vap
smoisturev calls trimb
le calls lesserequal_dp, lesserequal_sp
igamma calls gammln, gser, gcf
read_netcdf_casa_var calls read_netcdf_casamet, read_netcdf_casabiome, read_netcdf_casaflux, read_netcdf_casapool, read_netcdf_casabal
read_netcdf_phen_var calls nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nc_err
layer_recruitment calls get_allometry
interpolate_biomass_2d calls eq, realexponential, area_triangle
get_popdens calls get_unit
get_var_ncr2 calls stderr_nc, nf90_get_var, nf90_inq_varid
redistr_r calls float
cable_bios_load_fracc4 calls get_unit
xvcmxt3 calls point2constants
xvcmxt4_acclim calls point2constants
redistr_rd calls float
readpar_r2d calls nf90_inquire_variable, nc_abort, cable_abort, nf90_get_var, nf90_inq_varid
litter_props calls slope_esat
diag calls diag_3d, diag_2d
setroots_2d calls setroots_1d
getrex_2d calls getrex_1d
diag_3d calls mpi_abort
iflux_loop calls hyofs, litter_props, estimate_timestep, update_s_t, get_fluxes_and_derivs, get_and_solve_eqn, update_unknowns, snow_adjust
qrfac calls ne, le, enorm
fandan_c3 calls fabc, fan_c3, fdan_c3, fdabc
famdam_c4 calls fdam_c4, fam_c4, fdabcm, fabcm
fdjac2 calls eq
gser calls eq, gammln
read_netcdf_casamet calls nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nc_err
gcf calls eq, gammln
diag_2d calls mpi_abort
read_netcdf_casabiome calls nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nc_err
isotope_vap calls ne, tri
create_cohort calls mpi_abort, mpi_type_create_struct, mpi_get_address, mpi_type_commit, mpi_type_create_resized
famdam_c3 calls fdpq, fpq, fdam_c3, fabcd, fam_c3, fdabcd
fandan_c4 calls fdabc_c4, fabc_c4, fan_c4, fdan_c4
lmpar calls eq, le, enorm, qrsolv
read_netcdf_casaflux calls nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nc_err
read_netcdf_casapool calls nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nc_err
read_netcdf_casabal calls nf90_get_var, nf90_open, nf90_inq_varid, nf90_close, nc_err
tri calls tri_1d, tri_2d
update_s_t calls thetalmax, tfrz, dthetalmaxdth, jsoillayer, gtfrozen, rtbis_tfrozen
qrsolv calls ne, eq
get_fluxes_and_derivs calls seb, zerovars, flux, getheatfluxes, getfluxes_vp
get_and_solve_eqn calls tfrz, massman_sparse
update_unknowns calls jsoillayer
snow_adjust calls slope_esat_ice, esat_ice, thetalmax, tfrz, jsoillayer, gtfrozen, rtbis_tfrozen
dthetalmaxdth calls tfrz
jsoillayer calls tfrz
gtfrozen calls tfrz
rtbis_tfrozen calls gtfrozen
flux calls weight
getheatfluxes calls getheatfluxes_2d, getheatfluxes_1d
getfluxes_vp calls getfluxes_vp_2d, getfluxes_vp_1d
massman_sparse calls massman_sparse_1d, massman_sparse_2d
weight calls hyofh
getfluxes_vp_2d calls eq, zerovars, hyofh, flux
getfluxes_vp_1d calls eq, zerovars, hyofh, flux
massman_sparse_1d calls generic_thomas
massman_sparse_2d calls generic_thomas
generic_thomas calls generic_thomas_1d, generic_thomas_2d