cable_fprintf – CABLE
cable_fprintf Interface
3 statements
Source File
public interface cable_fprintf
Calls
Contents
Module Procedures
cable_fprintf1 cable_fprintf2 cable_fprintf3 cable_iprintf1 cable_iprintf2 cable_Lprintf2
Module Procedures
public subroutine cable_fprintf1(iDiag, basename, var1, dimx, L_fprint)
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: basename
real, dimension(dimx) :: var1
integer :: dimx
logical :: L_fprint
public subroutine cable_fprintf2(iDiag, basename, dimx, dimy, timestep, node, dir, var1)
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: basename
integer :: dimx
integer :: dimy
integer :: timestep
integer :: node
character(len=*) :: dir
real, dimension(dimx,dimy) :: var1
public subroutine cable_fprintf3(iDiag, basename, dimx, dimy, dimz, timestep, node, dir, var1)
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: basename
integer :: dimx
integer :: dimy
integer :: dimz
integer :: timestep
integer :: node
character(len=*) :: dir
real, dimension(dimx,dimy,dimz) :: var1
public subroutine cable_iprintf1(iDiag, basename, dimx, timestep, node, dir, var1)
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: basename
integer :: dimx
integer :: timestep
integer :: node
character(len=*) :: dir
integer, dimension(dimx) :: var1
public subroutine cable_iprintf2(iDiag, basename, dimx, dimy, timestep, node, dir, var1)
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: basename
integer :: dimx
integer :: dimy
integer :: timestep
integer :: node
character(len=*) :: dir
integer, dimension(dimx,dimy) :: var1
public subroutine cable_Lprintf2(iDiag, basename, dimx, dimy, timestep, node, dir, var1)
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: basename
integer :: dimx
integer :: dimy
integer :: timestep
integer :: node
character(len=*) :: dir
logical, dimension(dimx,dimy) :: var1
Call graph
cable_fprintf calls cable_fprintf1, cable_iprintf2, cable_iprintf1, cable_fprintf2, cable_fprintf3, cable_lprintf2
cable_fprintf1 calls open_file_per_node, cable_fextremes1
cable_iprintf2 calls open_file_per_node, check_timestep
cable_iprintf1 calls open_file_per_node, check_timestep
cable_fprintf2 calls open_file_per_node, check_timestep
cable_fprintf3 calls open_file_per_node, check_timestep
cable_lprintf2 calls open_file_per_node, check_timestep
open_file_per_node calls open_idiag