put_var_nc – CABLE
put_var_nc Interface
3 statements
Source File
public interface put_var_nc
Calls
Contents
Module Procedures
put_var_ncr1 put_var_ncr2 put_var_ncr3
Module Procedures
public subroutine put_var_ncr1(ncid, var_name, var)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: var_name
real, intent(in), dimension(:) :: var
public subroutine put_var_ncr2(ncid, var_name, var, n_call)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: var_name
real(kind=r_2), intent(in), dimension(:) :: var
integer, intent(in) :: n_call
public subroutine put_var_ncr3(ncid, var_name, var, n_call, nl)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: var_name
real(kind=r_2), intent(in), dimension(:,:) :: var
integer, intent(in) :: n_call
integer, intent(in) :: nl
Call graph
put_var_nc calls put_var_ncr1, put_var_ncr3, put_var_ncr2
put_var_ncr1 calls nf90_inq_varid, nf90_put_var, stderr_nc
put_var_ncr3 calls nf90_inq_varid, nf90_put_var, stderr_nc
put_var_ncr2 calls nf90_inq_varid, nf90_put_var, stderr_nc
stderr_nc calls nf90_strerror