#!/bin/bash

# Name the arguments to increase readability
FC=$1
CFLAGS=$2
LDFLAGS=$3
LD=$4
NCMOD=$5

export CINC="-I$NCMOD"
export supr=' -warn nostderrors -diag-disable 10145 '
mkdir -p tmpo
rm -f cable-mpi
rm -f cable_mpi*.o
rm -f pop_mpi.o

cp *.o tmpo/
export FOBJS=`ls tmpo/`

# this is the executable we are building
PROG=cable-mpi

$FC $supr $CFLAGS $LDFLAGS -c cable_mpicommon.F90 $FOBJS $CINC 
$FC $supr $CFLAGS $LDFLAGS -c pop_mpi.F90 cable_mpicommon.o $FOBJS $CINC 
$FC $supr $CFLAGS $LDFLAGS -c cable_mpiworker.F90 cable_mpicommon.o pop_mpi.o $FOBJS $CINC 
$FC $supr $CFLAGS $LDFLAGS -c cable_mpimaster.F90 cable_mpicommon.o cable_mpiworker.o pop_mpi.o $FOBJS $CINC 
$FC $supr $CFLAGS $LDFLAGS -o $PROG cable_mpidrv.F90 cable_mpicommon.o cable_mpimaster.o cable_mpiworker.o pop_mpi.o $FOBJS $CINC $LD

rm -fr tmpo/
