alloc_casavariable – CABLE
alloc_casavariable Subroutine
24 statements
Source File
public subroutine alloc_casavariable(casabiome, casapool, casaflux, casamet, casabal, arraysize)
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
integer, intent(in) :: arraysize
Called by
Contents
None
Call graph
init_casacnp calls alloc_casavariable
load_parameters calls alloc_casavariable
interface_um_data calls init_casacnp
cable_offline_driver calls load_parameters
mpidrv_master calls load_parameters
cable_explicit_driver calls interface_um_data
mpi_driver calls mpidrv_master