cable_Pyfprintf1 – CABLE
cable_Pyfprintf1 Subroutine
14 statements
Source File
public subroutine cable_Pyfprintf1(iDiag, basename, var1, dimx, L_fprint)
Uses
cable_common_module
cable_fFile_module
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: basename
real, dimension(dimx) :: var1
integer :: dimx
logical :: L_fprint
Calls
Called by
Contents
None
Call graph
cable_pyfprintf1 calls open_file_per_node, cable_pyprint1
open_file_per_node calls open_idiag
cable_pyfprintf calls cable_pyfprintf1