casa_fluxout – CABLE
casa_fluxout Subroutine
53 statements
Source File
public subroutine casa_fluxout(myear, veg, soil, casabal, casamet)
Uses
casaparm
casadimension
phenvariable
casavariable
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: myear
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_balance), intent(inout) :: casabal
type(casa_met), intent(inout) :: casamet
Calls
Contents
None
Call graph
casa_fluxout calls float, 5, 100