casa_ndep_pk – CABLE
casa_ndep_pk Subroutine
11 statements
Source File
public subroutine casa_ndep_pk(nidep)
Uses
casa_types_mod
cable_um_init_subrs_mod
cable_um_tech_mod
casavariable
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real, DIMENSION(um1%land_pts) :: nidep
Calls
Called by
Contents
None
Call graph
casa_ndep_pk calls um2cable_lp
interface_um_data calls casa_ndep_pk
cable_explicit_driver calls interface_um_data