casa_init – CABLE
casa_init Subroutine
166 statements
Source File
public subroutine casa_init(casabiome, casamet, casaflux, casapool, casabal, veg, phen)
Uses
casaparm
casadimension
phenvariable
cable_IO_vars_module
cable_common_module
casavariable
cable_def_types_mod
for first time reading file *_1220.csv (BP may2010)
SUBROUTINE casa_init(mst,casapool,casabal) end addition (BP may2010)
$IF (initcasa==1) THEN $ INQUIRE(FILE=TRIM(casafile%cnpipool), EXIST=EXRST) $!! vh_js!! $ IF (EXRST) THEN $ $ PRINT, ' Reading cnppoolOutfile as input: ,',casafile%cnpipool $ $ OPEN(99,file=casafile%cnpipool) $ $ DO npt =1, mp $ SELECT CASE(icycle) $ CASE(1) $ !! vh_js !! $ IF (cable_user%CALL_POP) THEN $ $ READ(99,) nyearz,npz,ivtz,istz,isoz,latz,lonz,areacellz, & $ casamet%glai(npt),slaz,phen%phase(npt) , & $ phen%doyphase(npt,3), phen%phen(npt), phen%aphen(npt), & $ casapool%clabile(npt) ,casapool%cplant(npt,:) , & $ casapool%clitter(npt,:),casapool%csoil(npt,:), & $ casaflux%frac_sapwood(npt), casaflux%sapwood_area(npt) $ $ $ ELSE $ READ(99,) nyearz,npz,ivtz,istz,isoz,latz,lonz,areacellz, & $ casamet%glai(npt),slaz,phen%phase(npt) , & $ phen%doyphase(npt,3), phen%phen(npt), phen%aphen(npt), & $ casapool%clabile(npt) ,casapool%cplant(npt,:) , & $ casapool%clitter(npt,:),casapool%csoil(npt,:) $ casaflux%frac_sapwood(:) = 1.0 $ casaflux%sapwood_area(:) = 0.0 $ ENDIF $ $ $ CASE(2) $!! vh_js !! $ IF (cable_user%CALL_POP) THEN $ READ(99,) nyearz,npz,ivtz,istz,isoz,latz,lonz,areacellz, & $ casamet%glai(npt),slaz,phen%phase(npt), & $ phen%doyphase(npt,3), phen%phen(npt), phen%aphen(npt), & $ casapool%clabile(npt),casapool%cplant(npt,:), & $ casapool%clitter(npt,:),casapool%csoil(npt,:), & $ casaflux%frac_sapwood(npt), casaflux%sapwood_area(npt), & $ casapool%nplant(npt,:),casapool%nlitter(npt,:), & $ casapool%nsoil(npt,:),casapool%nsoilmin(npt) $ $ ELSE $ READ(99,) nyearz,npz,ivtz,istz,isoz,latz,lonz,areacellz, & $ casamet%glai(npt),slaz,phen%phase(npt), & $ phen%doyphase(npt,3), phen%phen(npt), phen%aphen(npt), & $ casapool%clabile(npt),casapool%cplant(npt,:), & $ casapool%clitter(npt,:),casapool%csoil(npt,:), & $ casapool%nplant(npt,:),casapool%nlitter(npt,:), & $ casapool%nsoil(npt,:),casapool%nsoilmin(npt) $ casaflux%frac_sapwood(:) = 1.0 $ casaflux%sapwood_area(:) = 0.0 $ $ ENDIF $ CASE(3) $!! vh_js !! $ IF (cable_user%CALL_POP) THEN $ READ(99,) nyearz,npz,ivtz,istz,isoz,latz,lonz,areacellz, & $ casamet%glai(npt),slaz,phen%phase(npt), & $ phen%doyphase(npt,3), phen%phen(npt), phen%aphen(npt), & $ casapool%clabile(npt),casapool%cplant(npt,:), & $ casapool%clitter(npt,:),casapool%csoil(npt,:), & $ casaflux%frac_sapwood(npt), casaflux%sapwood_area(npt), & $ casapool%nplant(npt,:),casapool%nlitter(npt,:), & $ casapool%nsoil(npt,:),casapool%nsoilmin(npt), & $ casapool%pplant(npt,:),casapool%plitter(npt,:), & $ casapool%psoil(npt,:),casapool%psoillab(npt), & $ casapool%psoilsorb(npt),casapool%psoilocc(npt) $ ELSE $ READ(99,) nyearz,npz,ivtz,istz,isoz,latz,lonz,areacellz, & $ casamet%glai(npt),slaz,phen%phase(npt), & $ phen%doyphase(npt,3), phen%phen(npt), phen%aphen(npt), & $ casapool%clabile(npt),casapool%cplant(npt,:), & $ casapool%clitter(npt,:),casapool%csoil(npt,:), & $ casapool%nplant(npt,:),casapool%nlitter(npt,:), & $ casapool%nsoil(npt,:),casapool%nsoilmin(npt), & $ casapool%pplant(npt,:),casapool%plitter(npt,:), & $ casapool%psoil(npt,:),casapool%psoillab(npt), & $ casapool%psoilsorb(npt),casapool%psoilocc(npt) $ casaflux%frac_sapwood(:) = 1.0 $ casaflux%sapwood_area(:) = 0.0 $ $ $ ENDIF $ END SELECT $ IF (ABS(patch(npt)%longitude - lonz) > 0.9 .OR. & $ ABS(patch(npt)%latitude - latz) > 0.9) THEN $ PRINT , 'patch(npt)%longitude, lonz:', patch(npt)%longitude, lonz $ PRINT , 'patch(npt)%latitude, latz:', patch(npt)%latitude, latz $ PRINT , 'npt = ', npt $ STOP $ ENDIF $ ENDDO $ CLOSE(99) $ $ $ ELSE $ !! vh_js !! $ WRITE(,)'No valid restart file for casa_init found.' $ WRITE(,)'Using input from readbiome.!!!' $ WRITE(,) 'initialising frac_sapwood=1 and sapwood_area = 0)' $ casaflux%frac_sapwood(:) = 1.0 $ casaflux%sapwood_area(:) = 0.0 $ $ $ ENDIF ! IF (EXRST)
$ENDIF
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(in) :: casabiome
type(casa_met), intent(inout) :: casamet
type(casa_flux), intent(inout) :: casaflux
type(casa_pool), intent(inout) :: casapool
type(casa_balance), intent(inout) :: casabal
type(veg_parameter_type), intent(in) :: veg
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
None
Call graph
casa_init calls read_casa_restart_nc, 5, 2, 100
read_casa_restart_nc calls handle_err, nf90_get_var, nf90_close, nf90_inquire_dimension, nf90_open, nf90_get_att, nf90_inq_dimid, nf90_inq_varid
handle_err calls nf90_strerror
load_parameters calls casa_init
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master