create_restart – CABLE
create_restart Subroutine
205 statements
Source File
public subroutine create_restart(logn, dels, ktau, soil, veg, ssnow, canopy, rough, rad, bgc, bal, met)
$ CALL define_ovar(ncid_restart, rpid%clay, 'clay', '-', & $ 'Fraction of soil which is clay', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%sand, 'sand', '-', & $ 'Fraction of soil which is sand', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%silt, 'silt', '-', & $ 'Fraction of soil which is silt', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%ssat, 'ssat', '-', & $ 'Fraction of soil volume which is water @ saturation', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%sfc, 'sfc', '-', & $ 'Fraction of soil volume which is water @ field capacity', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%swilt, 'swilt', '-', & $ 'Fraction of soil volume which is water @ wilting point', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.)
$ CALL define_ovar(ncid_restart, rpid%froot, 'froot', '-', & $ 'Fraction of roots in each soil layer', & $ .TRUE., soilID, 'soil', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%bch, 'bch', '-', & $ 'Parameter b, Campbell eqn 1985', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%hyds, 'hyds', 'm/s', & $ 'Hydraulic conductivity @ saturation', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%sucs, 'sucs', 'm', & $ 'Suction @ saturation', .TRUE., & $ 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%css, 'css', 'J/kg/C', & $ 'Heat capacity of soil minerals', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%rhosoil, 'rhosoil', 'kg/m^3', & $ 'Density of soil minerals', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%rs20, 'rs20', '-', & $ 'Soil respiration coefficient at 20C', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%hc, 'hc', 'm', & $ 'Height of canopy', .TRUE., & $ 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%canst1, 'canst1', 'mm/LAI', & $ 'Max water intercepted by canopy', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%dleaf, 'dleaf', 'm', & $ 'Chararacteristic length of leaf', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%frac4, 'frac4', '-', & $ 'Fraction of plants which are C4', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%ejmax, 'ejmax', 'mol/m^2/s', & $ 'Max potential electron transport rate top leaf', .TRUE., & $ 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%vcmax, 'vcmax', 'mol/m^2/s', & $ 'Maximum RuBP carboxylation rate top leaf', .TRUE., & $ 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%rp20, 'rp20', '-', & $ 'Plant respiration coefficient at 20C', .TRUE., 'real', & $ 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%g0, 'g0', '-', & $ 'g0 term in Medlyn Stomatal Cond. Param', .TRUE.,'real',& $ 0, 0, 0, mpID, dummy, .TRUE.) ! Ticket #56 $ CALL define_ovar(ncid_restart, rpid%g1, 'g1', '-', & $ 'g1 term in Medlyn Stomatal Cond. Param', .TRUE.,'real',& $ 0, 0, 0, mpID, dummy, .TRUE.) ! Ticket #56 $ CALL define_ovar(ncid_restart, rpid%rpcoef, 'rpcoef', '1/C', & $ 'Temperature coef nonleaf plant respiration', .TRUE., & $ 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%shelrb, 'shelrb', '-', & $ 'Sheltering factor', .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%xfang, 'xfang', '-', & $ 'Leaf angle parameter', .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%wai, 'wai', '-', & $ 'Wood area index', .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%vegcf, 'vegcf', '-', & $ 'vegcf', .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%extkn, 'extkn', '-', & $ 'Extinction coef for vertical nitrogen profile', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%tminvj, 'tminvj', 'C', & $ 'Min temperature for the start of photosynthesis', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%tmaxvj, 'tmaxvj', 'C', & $ 'Max temperature for the start of photosynthesis', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%vbeta, 'vbeta', '-', & $ 'Stomatal sensitivity to soil water', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%xalbnir, 'xalbnir', '-', & $ 'modifier for albedo in near ir band', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ ! ratecp (Plant carbon rate constant): $ ok = NF90_DEF_VAR(ncid_restart, 'ratecp', NF90_FLOAT, (/plantcarbID/), & $ rpid%ratecp) $ IF (ok /= NF90_NOERR) CALL nc_abort & $ (ok, 'Error defining ratecp variable in restart file. '// & $ '(SUBROUTINE create_restart)') $ ok = NF90_PUT_ATT(ncid_restart, rpid%ratecp, "long_name", & $ "Plant carbon rate constant") $ ok = NF90_PUT_ATT(ncid_restart, rpid%ratecp, "units", "1/year") $ ! ratecs (Soil carbon rate constant): $ ok = NF90_DEF_VAR(ncid_restart, 'ratecs', NF90_FLOAT, (/soilcarbID/), & $ rpid%ratecs) $ IF (ok /= NF90_NOERR) CALL nc_abort & $ (ok, 'Error defining ratecs variable in restart file. '// & $ '(SUBROUTINE create_restart)') $ ok = NF90_PUT_ATT(ncid_restart, rpid%ratecs, "long_name", & $ "Soil carbon rate constant") $ ok = NF90_PUT_ATT(ncid_restart, rpid%ratecs, "units", "1/year") $ CALL define_ovar(ncid_restart, rpid%meth, 'meth', '-', & $ 'Canopy turbulence parameterisation switch', & $ .TRUE., 'integer', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%za_uv, 'za_uv', 'm', & $ 'Reference height (lowest atm. model layer) for momentum', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart, rpid%za_tq, 'za_tq', 'm', & $ 'Reference height (lowest atm. model layer) for scalars', & $ .TRUE., 'real', 0, 0, 0, mpID, dummy, .TRUE.) $ IF(cable_user%SOIL_STRUC=='sli'.OR.cable_user%FWSOIL_SWITCH=='Haverd2013') THEN $ CALL define_ovar(ncid_restart,rpid%gamma,'gamma','-', & $ 'Parameter in root efficiency function (Lai and Katul 2000)', & $ .TRUE.,'real',0,0,0,mpID,dummy,.TRUE.) $ ENDIF
$ CALL define_ovar(ncid_restart,rpid%nhorizons,'nhorizons','-', & $ 'Number of soil horizons',.TRUE.,'integer',0,0,0,mpID,dummy,.TRUE.) $ CALL define_ovar(ncid_restart,rpid%zeta,'zeta','[ ]', & $ 'exponent factor in Topmodel eq',.TRUE.,'real',0,0,0,mpID,dummy,.TRUE.) $ CALL define_ovar(ncid_restart,rpid%fsatmax,'fsatmax','[ ]', & $ 'param in Topmodel eq',.TRUE.,'real',0,0,0,mpID,dummy,.TRUE.) $ CALL define_ovar(ncid_restart,rpid%ishorizon,'ishorizon','-', & $ 'Horizon number',.TRUE., soilID, 'soil', 0, 0, 0, mpID, dummy, .TRUE.) $ CALL define_ovar(ncid_restart,rpid%clitt,'clitt','tC/ha', & $ 'Litter layer carbon content',.TRUE.,'real',0,0,0,mpID,dummy,.TRUE.) $ CALL define_ovar(ncid_restart,rpid%ZR,'ZR','cm', & $ 'Maximum rooting depth',.TRUE.,'real',0,0,0,mpID,dummy,.TRUE.) $ CALL define_ovar(ncid_restart,rpid%F10,'F10','-', & $ 'Fraction of roots in top 10 cm', & $ .TRUE.,'real',0,0,0,mpID,dummy,.TRUE.)
$ CALL write_ovar (ncid_restart, rpid%bch, 'bch', REAL(soil%bch, 4), & $ ranges%bch, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%bch, 'bch', REAL(soil%bch, 4), & $ ranges%bch, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%clay, 'clay', REAL(soil%clay, 4), & $ ranges%clay, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%sand, 'sand', REAL(soil%sand, 4), & $ ranges%sand, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%silt, 'silt', REAL(soil%silt, 4), & $ ranges%silt, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%css, 'css', REAL(soil%css, 4), & $ ranges%css, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%rhosoil, 'rhosoil', & $ REAL(soil%rhosoil,4), ranges%rhosoil, .TRUE., 'real', & $ .TRUE.) $ CALL write_ovar (ncid_restart, rpid%hyds, 'hyds', REAL(soil%hyds, 4), & $ ranges%hyds, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%sucs, 'sucs', REAL(soil%sucs, 4), & $ ranges%sucs, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%rs20, 'rs20', REAL(veg%rs20, 4), & $ ranges%rs20, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%ssat, 'ssat', REAL(soil%ssat, 4), & $ ranges%ssat, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%sfc, 'sfc', REAL(soil%sfc, 4), & $ ranges%sfc, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%swilt, 'swilt', REAL(soil%swilt, 4), & $ ranges%swilt, .TRUE., 'real', .TRUE.)
$ CALL write_ovar (ncid_restart, rpid%froot, 'froot', REAL(veg%froot, 4), & $ ranges%froot, .TRUE., 'soil', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%canst1, 'canst1', REAL(veg%canst1, 4), & $ ranges%canst1, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%dleaf, 'dleaf', REAL(veg%dleaf, 4), & $ ranges%dleaf, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%ejmax, 'ejmax', REAL(veg%ejmax, 4), & $ ranges%ejmax, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%vcmax, 'vcmax', REAL(veg%vcmax, 4), & $ ranges%vcmax, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%frac4, 'frac4', REAL(veg%frac4, 4), & $ ranges%frac4, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%hc, 'hc', REAL(veg%hc, 4), & $ ranges%hc, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%rp20, 'rp20', REAL(veg%rp20, 4), & $ ranges%rp20, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%g0, 'g0', REAL(veg%g0, 4), & $ ranges%g0, .TRUE., 'real', .TRUE.) ! Ticket #56 $ CALL write_ovar (ncid_restart, rpid%g1, 'g1', REAL(veg%g1, 4), & $ ranges%g1, .TRUE., 'real', .TRUE.) ! Ticket #56 $ CALL write_ovar (ncid_restart, rpid%rpcoef, 'rpcoef', REAL(veg%rpcoef, 4), & $ ranges%rpcoef, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%shelrb, 'shelrb', REAL(veg%shelrb, 4), & $ ranges%shelrb, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%xfang, 'xfang', REAL(veg%xfang, 4), & $ ranges%xfang, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%wai, 'wai', REAL(veg%wai, 4), & $ ranges%wai, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%vegcf, 'vegcf', REAL(veg%vegcf, 4), & $ ranges%vegcf, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%extkn, 'extkn', REAL(veg%extkn, 4), & $ ranges%extkn, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%tminvj, 'tminvj', REAL(veg%tminvj, 4), & $ ranges%tminvj, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%tmaxvj, 'tmaxvj', REAL(veg%tmaxvj, 4), & $ ranges%tmaxvj, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%vbeta, 'vbeta', REAL(veg%vbeta, 4), & $ ranges%vbeta, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%xalbnir, 'xalbnir', & $ REAL(veg%xalbnir, 4), ranges%xalbnir, .TRUE., & $ 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%tmaxvj, 'tmaxvj', REAL(veg%tmaxvj, 4), & $ ranges%tmaxvj, .TRUE., 'real', .TRUE.) $ ok = NF90_PUT_VAR(ncid_restart, rpid%ratecp, REAL(bgc%ratecp, 4)) $ IF(ok /= NF90_NOERR) CALL nc_abort(ok, & $ 'Error writing ratecp parameter to ' & $ //TRIM(frst_out)// '(SUBROUTINE create_restart)') $ ok = NF90_PUT_VAR(ncid_restart, rpid%ratecs, REAL(bgc%ratecs, 4)) $ IF(ok /= NF90_NOERR) CALL nc_abort(ok, & $ 'Error writing ratecs parameter to ' & $ //TRIM(frst_out)// '(SUBROUTINE create_restart)') $ CALL write_ovar (ncid_restart, rpid%meth, 'meth', REAL(veg%meth, 4), & $ ranges%meth, .TRUE., 'integer', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%za_uv, 'za_uv', REAL(rough%za_uv, 4), & $ ranges%za, .TRUE., 'real', .TRUE.) $ CALL write_ovar (ncid_restart, rpid%za_tq, 'za_tq', REAL(rough%za_tq, 4), & $ ranges%za, .TRUE., 'real', .TRUE.) $ IF(cable_user%SOIL_STRUC=='sli'.OR.cable_user%FWSOIL_SWITCH=='Haverd2013') THEN $ CALL write_ovar (ncid_restart,rpid%gamma,'gamma', & $ REAL(veg%gamma,4),(/-99999.0,99999.0/),.TRUE.,'real',.TRUE.) $ ENDIF $
$ CALL write_ovar (ncid_restart,rpid%nhorizons,'nhorizons', & $ REAL(soil%nhorizons,4),(/-99999.0,99999.0/),.TRUE.,'integer',.TRUE.) $ CALL write_ovar (ncid_restart,rpid%ishorizon,'ishorizon', & $ REAL(soil%ishorizon,4),(/-99999.0,99999.0/),.TRUE.,'soil',.TRUE.) $ CALL write_ovar (ncid_restart,rpid%clitt,'clitt', & $ REAL(veg%clitt,4),(/-99999.0,99999.0/),.TRUE.,'real',.TRUE.) $ CALL write_ovar (ncid_restart,rpid%ZR,'ZR', & $ REAL(veg%ZR,4),(/-99999.0,99999.0/),.TRUE.,'real',.TRUE.) $ CALL write_ovar (ncid_restart,rpid%F10,'F10', & $ REAL(veg%F10,4),(/-99999.0,99999.0/),.TRUE.,'real',.TRUE.)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: logn
real, intent(in) :: dels
integer, intent(in) :: ktau
type(soil_parameter_type), intent(in) :: soil
type(veg_parameter_type), intent(in) :: veg
type(soil_snow_type), intent(in) :: ssnow
type(canopy_type), intent(in) :: canopy
type(roughness_type), intent(in) :: rough
type(radiation_type), intent(in) :: rad
type(bgc_pool_type), intent(in) :: bgc
type(balances_type), intent(in) :: bal
type(met_type), intent(in) :: met
Calls
Called by
Contents
None
Call graph
create_restart calls nf90_def_dim, nc_abort, define_ovar, nf90_def_var, nf90_redef, nf90_enddef, nf90_put_var, nf90_close, nf90_create, nf90_put_att, write_ovar
nc_abort calls nf90_strerror
mpidrv_master calls create_restart
cable_offline_driver calls create_restart
mpi_driver calls mpidrv_master