CRU_GET_DAILY_MET – CABLE
CRU_GET_DAILY_MET Subroutine
258 statements
Source File
public subroutine CRU_GET_DAILY_MET(CRU, LastDayOfYear, LastYearOfMet)
$ IF (TRIM(CRU%Run) .EQ. 'S0_TRENDY' .OR. (TRIM(CRU%Run) .EQ. 'S1_TRENDY')) THEN $ MetYear = 1901 + MOD(CRU%CYEAR-RunStartYear,30) $ ELSE IF (TRIM(CRU%Run) .EQ. 'S2_TRENDY') THEN $ MetYear = CRU%CYEAR $ ELSE $ STOP 'Error in cable_cru.F90: CRU%Run not S0_TRENDY, S1_TRENDY, or 1901-2015' $ ENDIF
$ IF (TRIM(CRU%Run) .EQ. 'S0_TRENDY' .OR. (TRIM(CRU%Run) .EQ. 'S1_TRENDY')) THEN $ NextMetYear = 1901 + MOD(CRU%CYEAR + 1 - RunStartYear,30) $ ELSE IF (TRIM(CRU%Run) .EQ. 'S2_TRENDY') THEN $ NextMetYear = CRU%CYEAR + 1 $ ENDIF
Arguments
Type Intent Optional Attributes Name
type(CRU_TYPE) :: CRU
logical, intent(in) :: LastDayOfYear
logical, intent(in) :: LastYearOfMet
Calls
Called by
Contents
None
Call graph
cru_get_daily_met calls nf90_get_var, handle_err, nf90_close, nf90_inquire_dimension, cru_get_filename, nf90_inq_varid, nf90_open, nf90_inq_dimid
handle_err calls nf90_strerror
cru_get_subdiurnal_met calls cru_get_daily_met
mpidrv_master calls cru_get_subdiurnal_met
cable_offline_driver calls cru_get_subdiurnal_met
mpi_driver calls mpidrv_master