HgtAboveSnow – CABLE
HgtAboveSnow Subroutine
19 statements
Source File
public subroutine HgtAboveSnow(HeightAboveSnow, mp, z0surf_min, HGT_pft, SnowDepth, SnowDensity)
Arguments
Type Intent Optional Attributes Name
real :: HeightAboveSnow(mp)
integer :: mp
real :: z0surf_min
real :: HGT_pft(mp)
real :: SnowDepth(mp)
real :: SnowDensity(mp)
Called by
Contents
None
Call graph
ruff_resist calls hgtabovesnow
cbm calls ruff_resist
cable_explicit_driver calls cbm
mpidrv_worker calls cbm
cable_implicit_driver calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker