init_cable_progs – CABLE
init_cable_progs Subroutine
13 statements
Source File
public subroutine init_cable_progs(land_pts, nsurft, sm_levels, lsm_id, cable, progs_cbl_vars, progs_cbl_vars_data)
Uses
progs_cbl_vars_mod
read_cable_progs_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: land_pts
integer, intent(in) :: nsurft
integer, intent(in) :: sm_levels
integer, intent(in) :: lsm_id
integer, intent(in) :: cable
type(progs_cbl_vars_type), intent(inout) :: progs_cbl_vars
type(progs_cbl_vars_data_type), intent(inout) :: progs_cbl_vars_data
Calls
Contents
None
Call graph
init_cable_progs calls progs_cbl_vars_alloc, read_cable_progs, progs_cbl_vars_assoc
progs_cbl_vars_alloc calls ereport, dr_hook
read_cable_progs calls log_info, populate_var, log_fatal, tpl_has_var_name, fill_variables_from_file, to_string, get_var_id, log_warn, tpl_substitute_var
progs_cbl_vars_assoc calls dr_hook