landuse_transitx – CABLE
landuse_transitx Subroutine
307 statements
Source File
subroutine landuse_transitx(luc, casabiome)
Uses
landuse_constant
casaparm
casadimension
landuse_variable
casavariable
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(landuse_mland) :: luc
type(casa_biome) :: casabiome
Calls
Called by
Contents
None
Call graph
landuse_transitx calls landuse_redistribution
landuse_driver calls landuse_transitx
mpidrv_master calls landuse_driver
cable_offline_driver calls landuse_driver
mpi_driver calls mpidrv_master