limit_HGT_LAI – CABLE
limit_HGT_LAI Subroutine
35 statements
Source File
public subroutine limit_HGT_LAI(HGT_pft_temp, LAI_pft_cbl, HGT_pft_cbl, mp, land_pts, ntiles, tile_pts, tile_index, tile_frac, L_tile_pts, LAI_pft, HGT_pft, Clai_thresh)
Arguments
Type Intent Optional Attributes Name
real :: HGT_pft_temp(land_pts,ntiles)
real :: LAI_pft_cbl(mp)
real :: HGT_pft_cbl(mp)
integer :: mp
integer :: land_pts
integer :: ntiles
integer :: tile_pts(ntiles)
integer :: tile_index(land_pts,ntiles)
real :: tile_frac(land_pts,ntiles)
logical :: L_tile_pts(land_pts,ntiles)
real :: LAI_pft(land_pts,ntiles)
real :: HGT_pft(land_pts,ntiles)
real :: Clai_thresh
Called by
Contents
None
Call graph
initialize_veg calls limit_hgt_lai
interface_um_data calls initialize_veg
cable_explicit_driver calls interface_um_data