newplant – CABLE
newplant Subroutine
28 statements
Source File
public subroutine newplant(cplant_x, frac_x, ifpre_x, cplant_y, frac_y, ifpre_y, logc)
Uses
cable_def_types_mod
casaparm
casadimension
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(inout), DIMENSION(mvtype,mplant) :: cplant_x
real, intent(in), DIMENSION(mvtype) :: frac_x
logical, intent(in), DIMENSION(mvtype) :: ifpre_x
real(kind=r_2), intent(inout), DIMENSION(mvtype,mplant) :: cplant_y
real, intent(in), DIMENSION(mvtype) :: frac_y
logical, intent(in), DIMENSION(mvtype) :: ifpre_y
real(kind=r_2), intent(inout), DIMENSION(mvtype) :: logc
Called by
Contents
None
Call graph
casa_reinit_pk calls newplant
casa_init_pk calls casa_reinit_pk
init_casacnp calls casa_init_pk
interface_um_data calls init_casacnp
cable_explicit_driver calls interface_um_data