OPEN_PLUME_MET – CABLE
OPEN_PLUME_MET Subroutine
35 statements
Source File
public subroutine OPEN_PLUME_MET(PLUME)
Uses
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
type(PLUME_MIP_TYPE) :: PLUME
Calls
Called by
Contents
None
Call graph
open_plume_met calls plume_get_filename, handle_err, nf90_open, leap_day, nf90_inq_varid, nf90_get_att
handle_err calls nf90_strerror
leap_day calls is_leapyear
plume_mip_get_met calls open_plume_met
mpidrv_master calls plume_mip_get_met
cable_offline_driver calls plume_mip_get_met
mpi_driver calls mpidrv_master