pack_cnppool – CABLE
pack_cnppool Subroutine
100 statements
Source File
public subroutine pack_cnppool(casamet, casapool, casabal, phen, cpool_tile, npool_tile, ppool_tile, GLAI, PHENPHASE)
Uses
phenvariable
cable_um_tech_mod
casadimension
casavariable
test initialization of LAI
test end
test initilization of plant pool
test end
Arguments
Type Intent Optional Attributes Name
type(casa_met), intent(inout) :: casamet
type(casa_pool), intent(inout) :: casapool
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
real, intent(inout) :: cpool_tile(um1%land_pts,um1%ntiles,10)
real, intent(inout) :: npool_tile(um1%land_pts,um1%ntiles,10)
real, intent(inout) :: ppool_tile(um1%land_pts,um1%ntiles,12)
real, intent(inout) :: GLAI(um1%land_pts,um1%ntiles)
real, intent(inout) :: PHENPHASE(um1%land_pts,um1%ntiles)
Called by
Contents
None
Call graph
casa_reinit_pk calls pack_cnppool
casa_init_pk calls pack_cnppool, casa_reinit_pk
init_casacnp calls casa_init_pk
interface_um_data calls init_casacnp
cable_explicit_driver calls interface_um_data