POP_IO – CABLE
POP_IO Subroutine
1125 statements
Source File
subroutine POP_IO(POP, casamet, YEAR, ACTION, CF)
Uses
POP_constants
cable_common_module
netcdf
casa_ncdf_module
casavariable
POP_types
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
$ MPS:DO m = 1, mp $ $ $ PAT:DO p = 1, npatch2d $ $ $ STATUS = NF90_PUT_VAR(FILE_ID, VIDR7(1), POP%pop_grid(m)%freq_ranked_age_unique(p,:),& $ start=(/ m, p, 1, CNT /), count=(/ 1, 1, NDISTURB, 1 /)) $ IF(STATUS /= NF90_NoErr) CALL handle_err(STATUS)
$ STATUS = NF90_PUT_VAR(FILE_ID, VIDI8(1), POP%pop_grid(m)%patch(p)%layer(:)%ncohort,& $ start=(/ m, p, 1, CNT /), count=(/ 1, 1, nlayer, 1 /)) $ IF(STATUS /= NF90_NoErr) CALL handle_err(STATUS)
$ $ $ $ LAY:DO l = 1, nlayer $ ! COHORT STRUCTURE $ ! PUT 5D VARS (mp,npatch2d, nlayer,ncohort_max,t) $ STATUS = NF90_PUT_VAR(FILE_ID, VIDI9(1), POP%pop_grid(m)%patch(p)%layer(l)%cohort(:)%age,& $ start=(/ m, p, l, 1, CNT /), count=(/ 1, 1, 1, ncohort_max, 1 /)) $ IF(STATUS /= NF90_NoErr) CALL handle_err(STATUS) $ STATUS = NF90_PUT_VAR(FILE_ID, VIDI9(2), POP%pop_grid(m)%patch(p)%layer(l)%cohort(:)%id,& $ start=(/ m, p, l, 1, CNT /), count=(/ 1, 1, 1, ncohort_max, 1 /)) $ IF(STATUS /= NF90_NoErr) CALL handle_err(STATUS) $ $ $ END DO LAY $ END DO PAT $ END DO MPS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
type(casa_met), intent(in) :: casamet
integer, intent(in) :: YEAR
character(len=9), intent(in) :: ACTION
logical, intent(in) :: CF
Calls
Called by
Contents
None
Call graph
pop_io calls handle_err, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_redef, nf90_put_var, nf90_inquire_dimension, nf90_get_var, nf90_close, nf90_open, nf90_inq_dimid, nf90_create, nf90_inq_varid, nf90_put_att
handle_err calls nf90_strerror
casaonly_luc calls pop_io
cable_offline_driver calls pop_io, casaonly_luc, load_parameters
mpidrv_master calls pop_io, load_parameters
load_parameters calls pop_io
mpi_driver calls mpidrv_master