progs_cbl_vars_alloc – CABLE
progs_cbl_vars_alloc Subroutine
79 statements
Source File
public subroutine progs_cbl_vars_alloc(land_pts, nsurft, sm_levels, lsm_id, cable, progs_cbl_vars_data)
Uses
ereport_mod
grid_constants_mod_cbl
yomhook
jules_print_mgr
parkind1
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: land_pts
integer, intent(in) :: nsurft
integer, intent(in) :: sm_levels
integer, intent(in) :: lsm_id
integer, intent(in) :: cable
type(progs_cbl_vars_data_type), intent(inout) :: progs_cbl_vars_data
Calls
Called by
Contents
None
Call graph
progs_cbl_vars_alloc calls dr_hook, ereport
init_cable_progs calls progs_cbl_vars_alloc