READ_LUC_RESTART_NC – CABLE
READ_LUC_RESTART_NC Subroutine
86 statements
Source File
public subroutine READ_LUC_RESTART_NC(POPLUC)
Uses
netcdf
casa_ncdf_module
cable_common_module
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(inout) :: POPLUC
Calls
Called by
Contents
None
Call graph
read_luc_restart_nc calls handle_err, nf90_get_var, nf90_close, 1000, nf90_inquire_dimension, nf90_open, nf90_inq_dimid, nf90_inq_varid
handle_err calls nf90_strerror
popluc_init calls read_luc_restart_nc
load_parameters calls popluc_init
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master