WGEN_DAILY_CONSTANTS – CABLE
WGEN_DAILY_CONSTANTS Subroutine
49 statements
Source File
public subroutine WGEN_DAILY_CONSTANTS(WG, np, YearDay)
$write(71, "(1000e16.6)") WG%DecRad $ write(72, "(1000e16.6)") TAN(WG%DecRad) $ write(73, "(1000e16.6)") TAN(WG%LatRad) $ write(74, "(1000e16.6)") WG%DayLength
Arguments
Type Intent Optional Attributes Name
type(WEATHER_GENERATOR_TYPE) :: WG
integer, intent(in) :: np
integer, intent(in) :: YearDay
Called by
Contents
None
Call graph
cru_get_subdiurnal_met calls wgen_daily_constants
plume_mip_get_met calls wgen_daily_constants
mpidrv_master calls cru_get_subdiurnal_met, plume_mip_get_met
cable_offline_driver calls cru_get_subdiurnal_met, plume_mip_get_met
mpi_driver calls mpidrv_master