WRITE_LUC_OUTPUT_NC – CABLE
WRITE_LUC_OUTPUT_NC Subroutine
215 statements
Source File
public subroutine WRITE_LUC_OUTPUT_NC(POPLUC, ctime, FINAL)
Uses
netcdf
casa_ncdf_module
cable_common_module
$ $ DO i = 1, SIZE(A3) $ STATUS = NF90_def_var(FILE_ID,TRIM(A3(i)) ,NF90_FLOAT,(/land_ID,hist_ID,t_ID/),VID3(i)) $ IF (STATUS /= NF90_noerr) CALL handle_err(STATUS) $ END DO $ $ DO i = 1, SIZE(A3) $ STATUS = NF90_def_var(FILE_ID,TRIM(AI3(i)) ,NF90_INT,(/land_ID,hist_ID,t_ID/),VIDI3(i)) $ IF (STATUS /= NF90_noerr) CALL handle_err(STATUS) $ END DO
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(in) :: POPLUC
integer, intent(in) :: ctime
logical, intent(in) :: FINAL
Calls
Called by
Contents
None
Call graph
write_luc_output_nc calls handle_err, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_redef, nf90_put_var, nf90_close, nf90_create, nf90_put_att
handle_err calls nf90_strerror
mpidrv_master calls write_luc_output_nc
cable_offline_driver calls write_luc_output_nc
mpi_driver calls mpidrv_master