add_address_1block_1d_l – POP
add_address_1block_1d_l Subroutine
16 statements
Source File
private subroutine add_address_1block_1d_l(var, off, cnt, addr, blen, typ, idx)
Uses
mpi
Arguments
Type Intent Optional Attributes Name
logical, intent(in), dimension(:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
Calls
Called by
Contents
None
Call graph
add_address_1block_1d_l calls mpi_get_address
add_address_1block calls add_address_1block_1d_l
worker_c13o2_luc_params calls add_address_1block
worker_casa_dump_types calls add_address_1block
worker_outtype calls add_address_1block
worker_c13o2_luc_type calls add_address_1block
worker_restart_type calls add_address_1block
master_casa_params calls add_address_1block
worker_casa_luc_types calls add_address_1block
worker_c13o2_pool_type calls add_address_1block
worker_climate_types calls add_address_1block
worker_casa_params calls add_address_1block
worker_c13o2_flux_params calls add_address_1block
worker_cable_params calls add_address_1block
worker_c13o2_pool_params calls add_address_1block
worker_casa_type calls add_address_1block
worker_intype calls add_address_1block
worker_c13o2_flux_type calls add_address_1block
mpidrv_worker calls worker_c13o2_luc_params, worker_casa_dump_types, worker_outtype, worker_c13o2_luc_type, worker_restart_type, worker_casa_luc_types, worker_c13o2_pool_type, worker_climate_types, worker_casa_params, worker_c13o2_flux_params, worker_cable_params, worker_c13o2_pool_params, worker_casa_type, worker_intype, worker_c13o2_flux_type
mpidrv_master calls master_casa_params
mpi_driver calls mpidrv_worker, mpidrv_master