ADJUST_POP_FOR_FIRE – POP
ADJUST_POP_FOR_FIRE Subroutine
36 statements
Source File
public subroutine ADJUST_POP_FOR_FIRE(pop, disturbance_interval, burned_area, FLI)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: pop
integer(kind=i4b), intent(in) :: disturbance_interval(:,:)
real(kind=dp), intent(in) :: burned_area(:)
real(kind=dp), intent(in) :: FLI(:)
Calls
Called by
Contents
Call graph
adjust_pop_for_fire calls topkill_collins, interpolate_firemortality
interpolate_firemortality calls realexponential
blaze_driver calls adjust_pop_for_fire
spincasacnp calls blaze_driver
worker_spincasacnp calls blaze_driver
mpidrv_worker calls blaze_driver, worker_spincasacnp
cable_offline_driver calls blaze_driver, spincasacnp
mpi_driver calls mpidrv_worker