adjust_JV_gm – POP
adjust_JV_gm Subroutine
91 statements
Source File
public subroutine adjust_JV_gm(veg, p)
1) Calculate An-Ci curve 2) Exclude negative parts of the An-Ci curve Avoid unrealistic Vcmax and Jmax values
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
integer, intent(in) :: p
Calls
Called by
Contents
None
Call graph
adjust_jv_gm calls point2constants, light_inhibition, lmdif1, photosyn25
point2constants calls driver_type_ptr, cbm_type_ptr, air_type_ptr, albedo_type_ptr, canopy_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr
lmdif1 calls lmdif
lmdif calls le, enorm, fdjac2, qrfac, eq, ne, lmpar, ge
le calls lesserequal_sp, lesserequal_dp
fdjac2 calls eq
qrfac calls le, enorm, ne
eq calls equal_dp, equal_sp
ne calls notequal_sp, notequal_dp
lmpar calls le, enorm, eq, qrsolv
ge calls greaterequal_sp, greaterequal_dp
qrsolv calls eq, ne
casa_feedback calls adjust_jv_gm
mpidrv_worker calls casa_feedback
cable_offline_driver calls casa_feedback
mpi_driver calls mpidrv_worker