air_type_ptr – POP
air_type_ptr Subroutine
12 statements
Source File
public subroutine air_type_ptr(C)
Arguments
Type Intent Optional Attributes Name
type(iair_type) :: C
Called by
Contents
None
Call graph
point2constants calls air_type_ptr
cbm calls point2constants, surface_albedo, define_canopy, init_radiation, define_air, ruff_resist, soil_snow, plantcarb
surface_albedo calls point2constants
define_canopy calls point2constants, define_air, ruff_resist, dryleaf
casa_feedback calls point2constants, optimise_jv, adjust_jv_gm
xvcmxt3_acclim calls point2constants
diff_ac_aj calls point2constants, xvcmxt3_acclim, xejmxt3, xejmxt3_acclim, xvcmxt3, xgmest
xejmxt3 calls point2constants
total_photosynthesis_cost calls point2constants, xvcmxt3_acclim, xejmxt3, xejmxt3_acclim, xvcmxt3, xgmest
xvcmxt4 calls point2constants
mpidrv_master calls point2constants
mpidrv_worker calls point2constants, cbm, casa_feedback
xejmxt3_acclim calls point2constants
init_radiation calls point2constants
cable_offline_driver calls point2constants, cbm, casa_feedback
define_air calls point2constants
ruff_resist calls point2constants
optimise_jv calls point2constants, diff_ac_aj, total_photosynthesis_cost
xvcmxt4_acclim calls point2constants
soil_snow calls point2constants
adjust_jv_gm calls point2constants
plantcarb calls point2constants
xvcmxt3 calls point2constants
xgmest calls point2constants
total_an_ac_aj calls point2constants, xvcmxt3_acclim, xejmxt3, xejmxt3_acclim, xvcmxt3, xgmest
total_photosynthesis calls point2constants, xvcmxt3_acclim, xejmxt3, xejmxt3_acclim, xvcmxt3, xgmest
dryleaf calls xvcmxt3_acclim, xejmxt3, xvcmxt4, xejmxt3_acclim, xvcmxt4_acclim, xvcmxt3, xgmest
mpi_driver calls mpidrv_master, mpidrv_worker