albedo_type_ptr – POP
albedo_type_ptr Subroutine
6 statements
Source File
public subroutine albedo_type_ptr(C)
Arguments
Type Intent Optional Attributes Name
type(ialbedo_type) :: C
Called by
Contents
None
Call graph
point2constants calls albedo_type_ptr
ruff_resist calls point2constants
surface_albedo calls point2constants
xvcmxt3 calls point2constants
optimise_jv calls point2constants, diff_ac_aj, total_photosynthesis_cost
total_an_ac_aj calls point2constants, xvcmxt3, xgmest, xejmxt3_acclim, xvcmxt3_acclim, xejmxt3
define_canopy calls point2constants, ruff_resist, define_air, dryleaf
plantcarb calls point2constants
xgmest calls point2constants
xejmxt3_acclim calls point2constants
xvcmxt3_acclim calls point2constants
cable_offline_driver calls point2constants, cbm, casa_feedback
init_radiation calls point2constants
xvcmxt4 calls point2constants
diff_ac_aj calls point2constants, xvcmxt3, xgmest, xejmxt3_acclim, xvcmxt3_acclim, xejmxt3
define_air calls point2constants
cbm calls point2constants, ruff_resist, surface_albedo, define_canopy, plantcarb, init_radiation, define_air, soil_snow
adjust_jv_gm calls point2constants
xejmxt3 calls point2constants
soil_snow calls point2constants
mpidrv_worker calls point2constants, cbm, casa_feedback
mpidrv_master calls point2constants
casa_feedback calls point2constants, optimise_jv, adjust_jv_gm
xvcmxt4_acclim calls point2constants
total_photosynthesis_cost calls point2constants, xvcmxt3, xgmest, xejmxt3_acclim, xvcmxt3_acclim, xejmxt3
total_photosynthesis calls point2constants, xvcmxt3, xgmest, xejmxt3_acclim, xvcmxt3_acclim, xejmxt3
dryleaf calls xvcmxt3, xgmest, xejmxt3_acclim, xvcmxt3_acclim, xvcmxt4, xejmxt3, xvcmxt4_acclim
mpi_driver calls mpidrv_worker, mpidrv_master