alloc_casabal – POP
alloc_casabal Subroutine
7 statements
Source File
private subroutine alloc_casabal(casabal, arraysize)
Uses
casadimension
Arguments
Type Intent Optional Attributes Name
type(casa_balance), intent(inout) :: casabal
integer, intent(in) :: arraysize
Called by
Contents
None
Call graph
alloc_casa_var calls alloc_casabal
load_parameters calls alloc_casa_var
master_spincasacnp calls alloc_casa_var
master_casaonly_luc calls alloc_casa_var
worker_casa_params calls alloc_casa_var
mpidrv_master calls load_parameters, master_spincasacnp, master_casaonly_luc
cable_offline_driver calls load_parameters
mpidrv_worker calls worker_casa_params
mpi_driver calls mpidrv_master, mpidrv_worker