alloc_bgc_pool_type – POP
alloc_bgc_pool_type Subroutine
6 statements
Source File
private subroutine alloc_bgc_pool_type(bgc, mp)
Arguments
Type Intent Optional Attributes Name
type(bgc_pool_type), intent(inout) :: bgc
integer, intent(in) :: mp
Called by
Contents
None
Call graph
alloc_cbm_var calls alloc_bgc_pool_type
read_climatefile calls alloc_cbm_var
worker_climate_types calls alloc_cbm_var
allocate_cable_vars calls alloc_cbm_var
mpidrv_master calls alloc_cbm_var, luc_expt_init, load_parameters
cable_offline_driver calls alloc_cbm_var, luc_expt_init, load_parameters
luc_expt_init calls read_climatefile
worker_cable_params calls allocate_cable_vars
mpidrv_worker calls worker_climate_types, worker_cable_params
load_parameters calls allocate_cable_vars
mpi_driver calls mpidrv_master, mpidrv_worker