alloc_phenvariable – POP
alloc_phenvariable Subroutine
9 statements
Source File
public subroutine alloc_phenvariable(phen, arraysize)
Uses
casadimension
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(phen_variable), intent(inout) :: phen
integer, intent(in) :: arraysize
Called by
Contents
None
Call graph
load_parameters calls alloc_phenvariable
worker_casa_params calls alloc_phenvariable
master_spincasacnp calls alloc_phenvariable
master_casaonly_luc calls alloc_phenvariable
mpidrv_master calls load_parameters, master_spincasacnp, master_casaonly_luc
cable_offline_driver calls load_parameters
mpidrv_worker calls worker_casa_params
mpi_driver calls mpidrv_master, mpidrv_worker