allocate_cable_vars – POP
allocate_cable_vars Subroutine
37 statements
Source File
public subroutine allocate_cable_vars(air, bgc, canopy, met, bal, rad, rough, soil, ssnow, sum_flux, veg, arraysize)
Arguments
Type Intent Optional Attributes Name
type(air_type), intent(inout) :: air
type(bgc_pool_type), intent(inout) :: bgc
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(balances_type), intent(inout) :: bal
type(radiation_type), intent(inout) :: rad
type(roughness_type), intent(inout) :: rough
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(sum_flux_type), intent(inout) :: sum_flux
type(veg_parameter_type), intent(inout) :: veg
integer, intent(in) :: arraysize
Calls
Called by
Contents
None
Call graph
allocate_cable_vars calls alloc_cbm_var, zero_cbm_var
alloc_cbm_var calls alloc_met_type, alloc_climate_type, alloc_bgc_pool_type, alloc_air_type, alloc_sum_flux_type, alloc_balances_type, alloc_soil_snow_type, alloc_veg_parameter_type, alloc_canopy_type, alloc_soil_parameter_type, alloc_radiation_type, alloc_roughness_type
zero_cbm_var calls zero_bgc_pool_type, zero_climate_type, zero_soil_snow_type, zero_veg_parameter_type, zero_soil_parameter_type, zero_radiation_type, zero_sum_flux_type, zero_air_type, zero_met_type, zero_canopy_type, zero_balances_type, zero_roughness_type
load_parameters calls allocate_cable_vars
worker_cable_params calls allocate_cable_vars
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpidrv_worker calls worker_cable_params
mpi_driver calls mpidrv_master, mpidrv_worker