alloc_sum_flux_type – POP
alloc_sum_flux_type Subroutine
16 statements
Source File
private subroutine alloc_sum_flux_type(sum_flux, mp)
Arguments
Type Intent Optional Attributes Name
type(sum_flux_type), intent(inout) :: sum_flux
integer, intent(in) :: mp
Called by
Contents
None
Call graph
alloc_cbm_var calls alloc_sum_flux_type
read_climatefile calls alloc_cbm_var
mpidrv_master calls alloc_cbm_var, luc_expt_init, load_parameters
cable_offline_driver calls alloc_cbm_var, luc_expt_init, load_parameters
worker_climate_types calls alloc_cbm_var
allocate_cable_vars calls alloc_cbm_var
luc_expt_init calls read_climatefile
worker_cable_params calls allocate_cable_vars
mpi_driver calls mpidrv_master, mpidrv_worker
mpidrv_worker calls worker_climate_types, worker_cable_params
load_parameters calls allocate_cable_vars