ANNUAL_BA – POP
ANNUAL_BA Function
31 statements
Source File
public function ANNUAL_BA(FAPAR, FIRE_IDX, POPDENS, BIOME, REGIO_FLAG)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: FAPAR
real, intent(in) :: FIRE_IDX
real, intent(in) :: POPDENS
integer, intent(in) :: BIOME
integer, intent(in) :: REGIO_FLAG
Return Value real
Called by
Contents
Call graph
simfire calls annual_ba
run_blaze calls simfire
blaze_driver calls run_blaze
spincasacnp calls blaze_driver
worker_spincasacnp calls blaze_driver
mpidrv_worker calls blaze_driver, worker_spincasacnp
cable_offline_driver calls blaze_driver, spincasacnp
mpi_driver calls mpidrv_worker