AVAIL_FUEL – POP
AVAIL_FUEL Function
7 statements
Source File
public function AVAIL_FUEL(FLIx, CPLANT_w, CPLANT_g, AGL_w, AGL_g)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: FLIx
real, intent(in), DIMENSION(3) :: CPLANT_w
real, intent(in), DIMENSION(3) :: CPLANT_g
real, intent(in), DIMENSION(3) :: AGL_w
real, intent(in), DIMENSION(3) :: AGL_g
Return Value real
Called by
Contents
Call graph
run_blaze calls avail_fuel, combust
combust calls avail_fuel
blaze_driver calls run_blaze
worker_spincasacnp calls blaze_driver
cable_offline_driver calls blaze_driver, spincasacnp
mpidrv_worker calls blaze_driver, worker_spincasacnp
spincasacnp calls blaze_driver
mpi_driver calls mpidrv_worker