bgcdriver – POP
bgcdriver Subroutine
126 statements
Source File
public subroutine bgcdriver(ktau, kstart, dels, met, ssnow, canopy, veg, soil, climate, casabiome, casapool, casaflux, casamet, casabal, phen, POP, ktauday, idoy, LOY, dump_read, LALLOC, c13o2flux, c13o2pools)
Uses
casaparm
phenvariable
cable_c13o2_def
cable_c13o2
TypeDef
casavariable
cable_common_module
cable_def_types_mod
POP_TYPES
cable_phenology_module
casa_inout
casadimension
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
integer, intent(in) :: kstart
real, intent(in) :: dels
type(met_type), intent(inout) :: met
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(climate_type), intent(in) :: climate
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: POP
integer, intent(in) :: ktauday
integer, intent(in) :: idoy
integer, intent(in) :: LOY
logical, intent(in) :: dump_read
integer, intent(in) :: LALLOC
type(c13o2_flux), intent(inout) :: c13o2flux
type(c13o2_pool), intent(inout) :: c13o2pools
Calls
Called by
Contents
None
Call graph
bgcdriver calls cable_phenology_clim, c13o2_save_casapool, biogeochem, c13o2_update_pools
cable_phenology_clim calls ge, eq
biogeochem calls casa_coeffsoil, casa_cnpcycle, casa_pdummy, casa_cnpbal, casa_cnpflux, phenology, casa_rplant, casa_coeffplant, casa_xratesoil, casa_ndummy, casa_delplant, casa_nuptake, casa_delsoil, avgsoil, casa_xrateplant, casa_xnp, casa_allocation, casa_xkn, casa_puptake
c13o2_update_pools calls c13o2_fluxmatrix_pools, c13o2_sinks_pools, c13o2_sources_pools, c13o2_save_c13o2pools, c13o2_sources_pools_nofrac, c13o2_c13o2pools_back, isotope_pool_model
casa_cnpcycle calls casa_poolzero
casa_rplant calls vcmax_np
casa_nuptake calls casa_nrequire
ge calls greaterequal_sp, greaterequal_dp
eq calls equal_sp, equal_dp
casa_xrateplant calls ge, le
casa_xnp calls casa_nrequire, casa_prequire
casa_allocation calls casa_wolf
casa_puptake calls casa_prequire
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
isotope_pool_model_1d calls eq, mpi_abort, diag, ne
le calls lesserequal_sp, lesserequal_dp
isotope_pool_model_2d calls eq, mpi_abort, diag, ne
diag calls diag_2d, diag_3d
ne calls notequal_dp, notequal_sp
diag_2d calls mpi_abort
diag_3d calls mpi_abort
mpidrv_worker calls bgcdriver
cable_offline_driver calls bgcdriver
mpi_driver calls mpidrv_worker