BLAZE_TURNOVER – POP
BLAZE_TURNOVER Subroutine
36 statements
Source File
public subroutine BLAZE_TURNOVER(AB, CPLANT_g, CPLANT_w, AGL_g, AGL_w, BGL_g, BGL_w, shootfrac, TO, BT, BURNMODE, POP_TO)
$ ! Grass fuels burned by area $ CPLANT_g (LEAF) = CPLANT_g (LEAF) * (1. - AB) $ AGL_g(METB) = AGL_g(METB) * (1. - AB) $ AGL_g(STR) = AGL_g(STR) * (1. - AB) $ $ ! Leaves $ CPLANT_w (LEAF) = & $ CPLANT_w (LEAF) - (MTO(LEAF)%TO_ATM + MTO(LEAF)%TO_STR) $ ! Wood $ CPLANT_w (WOOD) = & $ CPLANT_w (WOOD) - (MTO(WOOD)%TO_ATM + MTO(WOOD)%TO_STR + MTO(WOOD)%TO_CWD) $ ! Fine roots $ CPLANT_w (FROOT) = & $ CPLANT_w (FROOT)- (MTO(FROOT)%TO_ATM+ MTO(FROOT)%TO_STR) $ $ ! Litter above ground $ AGL_w(METB) = AGL_w(METB) - MTO(MLIT)%TO_ATM $ AGL_w(STR) = AGL_w(STR) - MTO(SLIT)%TO_ATM + MTO(WOOD)%TO_STR + & $ MTO(LEAF)%TO_STR $ AGL_w(CWD) = AGL_w(CWD) - MTO(CLIT)%TO_ATM + MTO(WOOD)%TO_CWD * shootfrac $ $ ! Litter below ground $ BGL_w(STR) = BGL_w(STR) + MTO(FROOT)%TO_STR $ BGL_w(CWD) = BGL_w(CWD) + MTO(WOOD)%TO_CWD * (1. - shootfrac) $ $ IF (ANY (AGL_w .LT. 0.)) THEN $ WRITE(,)"CLIITE_W < 0 ", AGL_w $ STOP 1 $ ENDIF
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: AB
real, intent(inout) :: CPLANT_g(3)
real, intent(inout) :: CPLANT_w(3)
real, intent(inout), DIMENSION(3) :: AGL_g
real, intent(inout), DIMENSION(3) :: AGL_w
real, intent(inout), DIMENSION(3) :: BGL_g
real, intent(inout), DIMENSION(3) :: BGL_w
real, intent(in) :: shootfrac
type(TYPE_TURNOVER), intent(inout) :: TO(7)
real, intent(out) :: BT(13)
integer, intent(in) :: BURNMODE
real, intent(in), optional :: POP_TO
Called by
Contents
None
Call graph
run_blaze calls blaze_turnover
blaze_driver calls blaze_turnover, run_blaze
spincasacnp calls blaze_driver
mpidrv_worker calls blaze_driver, worker_spincasacnp
cable_offline_driver calls blaze_driver, spincasacnp
worker_spincasacnp calls blaze_driver
mpi_driver calls mpidrv_worker