BLAZE_DRIVER – POP
BLAZE_DRIVER Subroutine
136 statements
Source File
public subroutine BLAZE_DRIVER(ncells, BLAZE, SF, casapool, casaflux, casamet, climate, shootfrac, idoy, CurYear, CTLFLAG, POP, veg)
Uses
BLAZE_MOD
cable_common_module
POPMODULE
SIMFIRE_MOD
cable_IO_vars_module
cable_def_types_mod
POP_TYPES
casavariable
$ IF (CALL1) THEN $ StartYear = CurYear $ CALL1 = .FALSE. $ ENDIF
$ ! set heights at which tree mortality is calculated $ nbins = mheights $ DO i=1,nbins $ casaflux%fire_mortality_vs_height(:,i,1) = real(BIN_POWER**i, r_2) $ ENDDO
$ IF (casamet%lnonwood(patch_index) == 0) THEN ! Here woody patches $ DO nh = 1,mheights $ hgt = real(casaflux%fire_mortality_vs_height(patch_index,nh,1)) $ casaflux%fire_mortality_vs_height(patch_index,nh,2) = & $ (1._r_2 - real(p_surv_OzSavanna(hgt,BLAZE%FLI(i)),r_2)) * BLAZE%AB(i) !* $ $ $ ! (1._r_2 - casaflux%fire_mortality_vs_height(patch_index,nh,2)) & $ $ ENDDO $ ENDIF $ CALL ADJUST_POP_FOR_FIRE(pop,int(veg%disturbance_interval(Iw,:), i4b), & $ casaflux%fire_mortality_vs_height(Iw,:,:))
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncells
type(TYPE_BLAZE), intent(inout) :: BLAZE
type(TYPE_SIMFIRE) :: SF
type(casa_pool), intent(in) :: casapool
type(casa_flux), intent(in) :: casaflux
type(casa_met), intent(in) :: casamet
type(climate_type), intent(in) :: climate
real, intent(in) :: shootfrac
integer, intent(in) :: idoy
integer, intent(in) :: CurYear
integer, intent(in) :: CTLFLAG
type(POP_TYPE), intent(inout) :: POP
type(veg_parameter_type), intent(in) :: veg
Calls
Called by
Contents
None
Call graph
blaze_driver calls doysod2ymdhms, blaze_turnover, run_blaze, is_leapyear, adjust_pop_for_fire
doysod2ymdhms calls is_leapyear, mpi_abort
run_blaze calls doysod2ymdhms, blaze_turnover, is_leapyear, simfire, combust, avail_fuel
simfire calls is_leapyear, get_popdens, annual_ba
combust calls avail_fuel
get_popdens calls get_unit
spincasacnp calls blaze_driver
worker_spincasacnp calls blaze_driver
mpidrv_worker calls blaze_driver, worker_spincasacnp
cable_offline_driver calls blaze_driver, spincasacnp
mpi_driver calls mpidrv_worker