BLAZE_ACCOUNTING – POP
BLAZE_ACCOUNTING Subroutine
35 statements
Source File
public subroutine BLAZE_ACCOUNTING(BLAZE, climate, ktau, dels, year, doy)
Uses
cable_IO_vars_module
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(TYPE_BLAZE) :: BLAZE
type(climate_type), intent(in) :: climate
integer, intent(in) :: ktau
real, intent(in) :: dels
integer, intent(in) :: year
integer, intent(in) :: doy
Called by
Contents
None
Call graph
spincasacnp calls blaze_accounting
mpidrv_worker calls blaze_accounting
cable_offline_driver calls blaze_accounting, spincasacnp
mpi_driver calls mpidrv_worker