c13o2_zero_luc – POP
c13o2_zero_luc Subroutine
8 statements
Source File
public subroutine c13o2_zero_luc(c13o2luc)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(c13o2_luc), intent(inout) :: c13o2luc
Called by
Contents
None
Call graph
c13o2_init_luc calls c13o2_zero_luc
worker_c13o2_luc_params calls c13o2_zero_luc
load_parameters calls c13o2_init_luc
mpidrv_worker calls worker_c13o2_luc_params
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_worker, mpidrv_master