c13o2_close_output – POP
c13o2_close_output Subroutine
10 statements
Source File
public subroutine c13o2_close_output(file_id)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: file_id
Calls
Called by
Contents
None
Call graph
c13o2_close_output calls nf90_close, c13o2_err_handler
spincasacnp calls c13o2_close_output
cable_offline_driver calls c13o2_close_output, spincasacnp
mpidrv_master calls c13o2_close_output
mpi_driver calls mpidrv_master