c13o2_save_c13o2pools – POP
c13o2_save_c13o2pools Subroutine
23 statements
Source File
private subroutine c13o2_save_c13o2pools(c13o2pools, c13o2save)
Uses
cable_c13o2_def
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(c13o2_pool), intent(in) :: c13o2pools
real(kind=dp), intent(out), dimension(:,:) :: c13o2save
Called by
Contents
None
Call graph
c13o2_update_pools calls c13o2_save_c13o2pools
c13o2_update_luc calls c13o2_save_c13o2pools
bgcdriver calls c13o2_update_pools
casaonly_luc calls c13o2_update_pools, c13o2_update_luc
worker_casaonly_luc calls c13o2_update_pools
spincasacnp calls c13o2_update_pools
worker_spincasacnp calls c13o2_update_pools
mpidrv_master calls c13o2_update_luc, master_casaonly_luc
cable_offline_driver calls c13o2_update_luc, bgcdriver, casaonly_luc, spincasacnp
master_casaonly_luc calls c13o2_update_luc
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
mpi_driver calls mpidrv_master, mpidrv_worker