c13o2_sanity_luc – POP
c13o2_sanity_luc Subroutine
12 statements
Source File
public subroutine c13o2_sanity_luc(popluc, c13o2luc)
Uses
mo_isotope
cable_c13o2_def
POPLUC_Types
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(inout) :: popluc
type(c13o2_luc), intent(inout) :: c13o2luc
Calls
Called by
Contents
None
Call graph
c13o2_sanity_luc calls isosanity
master_casaonly_luc calls c13o2_sanity_luc
cable_offline_driver calls c13o2_sanity_luc
mpidrv_master calls c13o2_sanity_luc, master_casaonly_luc
mpi_driver calls mpidrv_master