c13o2_write_output – POP
c13o2_write_output Subroutine
55 statements
Source File
public subroutine c13o2_write_output(file_id, vars, var_ids, days, c13o2pools)
Uses
netcdf
cable_common_module
cable_def_types_mod
cable_c13o2_def
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: file_id
character(len=40), intent(in), dimension(:) :: vars
integer, intent(in), dimension(:) :: var_ids
integer, intent(in) :: days
type(c13o2_pool), intent(in) :: c13o2pools
Calls
Called by
Contents
None
Call graph
c13o2_write_output calls nf90_put_var, c13o2_err_handler
c13o2_err_handler calls mpi_abort
spincasacnp calls c13o2_write_output
cable_offline_driver calls c13o2_write_output, spincasacnp
mpidrv_master calls c13o2_write_output
mpi_driver calls mpidrv_master