c13o2_init_luc – POP
c13o2_init_luc Subroutine
22 statements
Source File
public subroutine c13o2_init_luc(c13o2luc, c13o2pools, veg, np)
Uses
casaparm
cable_common_module
cable_def_types_mod
cable_c13o2_def
Arguments
Type Intent Optional Attributes Name
type(c13o2_luc), intent(inout) :: c13o2luc
type(c13o2_pool), intent(inout) :: c13o2pools
type(veg_parameter_type), intent(in) :: veg
integer(kind=i4), intent(in) :: np
Calls
Called by
Contents
None
Call graph
c13o2_init_luc calls c13o2_alloc_luc, c13o2_zero_luc, c13o2_read_restart_luc
c13o2_read_restart_luc calls c13o2_err_handler, nf90_inq_varid, nf90_close, nf90_get_var, nf90_open
c13o2_err_handler calls mpi_abort
load_parameters calls c13o2_init_luc
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master