c13o2_create_output – POP
c13o2_create_output Subroutine
156 statements
Source File
public subroutine c13o2_create_output(casamet, c13o2pools, file_id, vars, var_ids)
Uses
netcdf
cable_common_module
cable_c13o2_def
casavariable
Arguments
Type Intent Optional Attributes Name
type(casa_met), intent(in) :: casamet
type(c13o2_pool), intent(in) :: c13o2pools
integer, intent(out) :: file_id
character(len=40), intent(out), dimension(c13o2_nvars_output) :: vars
integer, intent(out), dimension(c13o2_nvars_output) :: var_ids
Calls
Called by
Contents
None
Call graph
c13o2_create_output calls nf90_create, nf90_put_att, c13o2_err_handler, nf90_def_var, nf90_def_dim, nf90_enddef, nf90_put_var
c13o2_err_handler calls mpi_abort
spincasacnp calls c13o2_create_output
cable_offline_driver calls c13o2_create_output, spincasacnp
mpidrv_master calls c13o2_create_output
mpi_driver calls mpidrv_master