c13o2_c13o2pools_back – POP
c13o2_c13o2pools_back Subroutine
23 statements
Source File
private subroutine c13o2_c13o2pools_back(c13o2pools, c13o2save)
Uses
cable_c13o2_def
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(c13o2_pool), intent(inout) :: c13o2pools
real(kind=dp), intent(in), dimension(:,:) :: c13o2save
Called by
Contents
None
Call graph
c13o2_update_pools calls c13o2_c13o2pools_back
bgcdriver calls c13o2_update_pools
casaonly_luc calls c13o2_update_pools
worker_casaonly_luc calls c13o2_update_pools
spincasacnp calls c13o2_update_pools
worker_spincasacnp calls c13o2_update_pools
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker