c13o2_print_delta_pools – POP
c13o2_print_delta_pools Subroutine
165 statements
Source File
public subroutine c13o2_print_delta_pools(casapool, casaflux, c13o2pools)
Uses
cable_def_types_mod
cable_IO_vars_module
casavariable
mo_utils
cable_c13o2_def
mo_isotope
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(in) :: casapool
type(casa_flux), intent(in) :: casaflux
type(c13o2_pool), intent(in) :: c13o2pools
Calls
Called by
Contents
None
Call graph
c13o2_print_delta_pools calls delta1000, ne
ne calls notequal_sp, notequal_dp
mpidrv_master calls c13o2_print_delta_pools
cable_offline_driver calls c13o2_print_delta_pools
mpi_driver calls mpidrv_master