c13o2_sinks_pools – POP
c13o2_sinks_pools Subroutine
26 statements
Source File
private subroutine c13o2_sinks_pools(casaflux, casasinks)
Uses
casaparm
casavariable
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(casa_flux), intent(in) :: casaflux
real(kind=dp), intent(out), dimension(:,:) :: casasinks
Called by
Contents
Call graph
c13o2_update_pools calls c13o2_sinks_pools
bgcdriver calls c13o2_update_pools
worker_casaonly_luc calls c13o2_update_pools
casaonly_luc calls c13o2_update_pools
worker_spincasacnp calls c13o2_update_pools
spincasacnp calls c13o2_update_pools
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker