c13o2_discrimination – POP
c13o2_discrimination Subroutine
154 statements
Source File
public subroutine c13o2_discrimination(dt, isc3, Vcmax, GPP, Rd, Gammastar, ca, ci, gac, gbc, gsc, Tl, Rair, Vstarch, Rstarch, Rsucrose, Rphoto, Disc, Ass13)
Uses
mo_constants
mo_utils
\brief 13C leaf discrimination \details 13C leaf discrimination D after Farquhar et al. (Aust J Plant Physiol, 1982), Farquhar (Aust J Plant Physiol, 1983), Evans et al. (Aust J Plant Physiol, 1986), and Lloyd & Farquhar (Oecologia, 1994), with the extension of Wingate et al. (Plant Cell Environ, 2007) for leaf respiration and an analog extension for photorespiration. This is for C3 during daytime: \n D = kca/(k(ca-G)-Rd) * (a + (b-a)cc/ca + G/ca(df-da-f) + Rd/(kCa)(de-da-e)) \n where \n k = (An+Rd)/(ci-G) so that the carboxylation rate is Vc = kci and the oxygenation rate is Vo = 2.k*G, \n G is the CO2 compensation point in absence of dark respiration (Gamma star), \n Rd is mitochondrial respiration, \n ca is the ambient mixing ratio outside the leaf boundary layer, \n cc is the mixing ratio at the site of carboxylation (in chloroplast), \n a is the effective diffusion fractionation from the ambient air outside the leaf boundary layer into the site of carboxylation (interior of chloroplasts for C3, mesophyll for C4), \n b is the effective fractionation of (RuBisCO and PEP-C) carboxylation, \n e is the effective fractionation during mitochondrial respiration (-6. permil), \n f is the effective fractionation during photorespiration (+10. permil), \n da is the isotopic composition of ambient air outside the leaf boundary layer, \n de is the isotopic composition of the substrate for mitochondrial respiration, and \n df is the isotopic composition of the substrate for photorespiration. \n A sugar pool (sucrose) with the size of 300 mol(C6)/gDW is taken as the substrate for mitochondrial respiration. The isotopic composition of the sugar pool is renewed by assimilation. \n The photorespiration pool is a mixture of sugars and enzymes. 90% of sugars in leaves are sucrose so that the substrate pool is taken as 10% of the sugar pool. The pool is also turned over isotopically by assimilation. \n A starch pool is built up during day by 1/3 of assimilation, with an equilibrium fractionation of -4.4 permil. Mitochondrial respiration respires this starch pool at night, with the average isotopic composition of the pool at the beginning of the night, without fractionation. \n This is an elemental subroutine and can be called with scalars and arrays. <- ToDo \param[in] "real(dp) :: dt" Time step [s] \param[in] "logical :: isc3" C3 mask with .true. for C3 and .false. for C4 plants \param[in] "real(dp) :: Vcmax" Maximal carboxylation rate at leaf temperature Vcmax(Tl) [mol(CO2)/m^2/s] \param[in] "real(dp) :: GPP" Gross assimilation [mol(CO2)/m^2/s] \param[in] "real(dp) :: Rd" Leaf respiration [mol(CO2)/m^2/s] \param[in] "real(dp) :: Gammstar" CO2 compensation point in absence of dark respiration [mol(CO2)/mol(air)] \param[in] "real(dp) :: ca" Ambient CO2 mixing ratio [mol(CO2)/mol(air)] \param[in] "real(dp) :: ci" Stomatal CO2 mixing ratio [mol(CO2)/mol(air)] \param[in] "real(dp) :: gsc" Stomatal conductance for CO2 [mol(CO2)/m^2/s] \param[in] "real(dp) :: gac" Aerodynamic conductance for CO2 [mol(CO2)/m^2/s] \param[in] "real(dp) :: gbc" Boundary layer conductance for CO2 [mol(CO2)/m^2/s] \param[in] "real(dp) :: Tl" Leaf temperature [K] \param[in] "real(dp) :: Rair" Isotope ratio of ambient CO2 ([13C]/[12C]) \param[inout] "real(dp) :: Vstarch" Transitory starch pool [mol(C)/m2] \param[inout] "real(dp) :: Rstarch" Isotope ratio of transitory starch ([13C]/[12C]) \param[inout] "real(dp) :: Rsucrose" Isotope ratio of sucrose pool ([13C]/[12C]) \param[inout] "real(dp) :: Rphoto" Isotope ratio of pool for photorespiration ([13C]/[12C]) \param[out] "real(dp) :: Disc" Leaf discrimination \param[out] "real(dp) :: Ass13" 13C net assimilation [mol(13CO2)/m^2/s] \author Written Matthias Cuntz \date Apr-Nov 2019
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: dt
logical, intent(in), dimension(:) :: isc3
real(kind=dp), intent(in), dimension(:) :: Vcmax
real(kind=dp), intent(in), dimension(:) :: GPP
real(kind=dp), intent(in), dimension(:) :: Rd
real(kind=dp), intent(in), dimension(:) :: Gammastar
real(kind=dp), intent(in), dimension(:) :: ca
real(kind=dp), intent(in), dimension(:) :: ci
real(kind=dp), intent(in), dimension(:) :: gac
real(kind=dp), intent(in), dimension(:) :: gbc
real(kind=dp), intent(in), dimension(:) :: gsc
real(kind=dp), intent(in), dimension(:) :: Tl
real(kind=dp), intent(in), dimension(:) :: Rair
real(kind=dp), intent(inout), dimension(:) :: Vstarch
real(kind=dp), intent(inout), dimension(:) :: Rstarch
real(kind=dp), intent(inout), dimension(:) :: Rsucrose
real(kind=dp), intent(inout), dimension(:) :: Rphoto
real(kind=dp), intent(out), dimension(:) :: Disc
real(kind=dp), intent(out), dimension(:) :: Ass13
Calls
Contents
None
Call graph
c13o2_discrimination calls ne
ne calls notequal_sp, notequal_dp