c13o2_read_restart_pools – POP
c13o2_read_restart_pools Subroutine
37 statements
Source File
public subroutine c13o2_read_restart_pools(c13o2_restart_in_pools, c13o2pools)
Uses
cable_c13o2_def
netcdf
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: c13o2_restart_in_pools
type(c13o2_pool), intent(inout) :: c13o2pools
Calls
Called by
Contents
Call graph
c13o2_read_restart_pools calls c13o2_err_handler, nf90_open, nf90_inq_varid, nf90_close, nf90_get_var
load_parameters calls c13o2_read_restart_pools
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master