c13o2_update_pools – POP
c13o2_update_pools Subroutine
55 statements
Source File
public subroutine c13o2_update_pools(casasave, casaflux, c13o2flux, c13o2pools, casapool)
Uses
cable_c13o2_def
cable_def_types_mod
casavariable
casadimension
casaparm
mo_isotope_pool_model
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), dimension(:,:) :: casasave
type(casa_flux), intent(in) :: casaflux
type(c13o2_flux), intent(inout) :: c13o2flux
type(c13o2_pool), intent(inout) :: c13o2pools
type(casa_pool), intent(in), optional :: casapool
Calls
Called by
Contents
None
Call graph
c13o2_update_pools calls c13o2_save_c13o2pools, c13o2_sources_pools_nofrac, c13o2_sinks_pools, c13o2_fluxmatrix_pools, c13o2_sources_pools, isotope_pool_model, c13o2_c13o2pools_back
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
isotope_pool_model_1d calls mpi_abort, eq, diag, ne
isotope_pool_model_2d calls mpi_abort, eq, diag, ne
eq calls equal_sp, equal_dp
diag calls diag_2d, diag_3d
ne calls notequal_sp, notequal_dp
diag_2d calls mpi_abort
diag_3d calls mpi_abort
bgcdriver calls c13o2_update_pools
casaonly_luc calls c13o2_update_pools
worker_casaonly_luc calls c13o2_update_pools
spincasacnp calls c13o2_update_pools
worker_spincasacnp calls c13o2_update_pools
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker