c13o2_err_handler – POP
c13o2_err_handler Subroutine
6 statements
Source File
private subroutine c13o2_err_handler(message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: message
Called by
Contents
None
Call graph
c13o2_create_output calls c13o2_err_handler
c13o2_close_output calls c13o2_err_handler
c13o2_write_output calls c13o2_err_handler
c13o2_read_restart_luc calls c13o2_err_handler
c13o2_read_restart_flux calls c13o2_err_handler
c13o2_write_restart_flux calls c13o2_err_handler
c13o2_read_restart_pools calls c13o2_err_handler
c13o2_write_restart_pools calls c13o2_err_handler
c13o2_write_restart_luc calls c13o2_err_handler
spincasacnp calls c13o2_create_output, c13o2_close_output, c13o2_write_output
load_parameters calls c13o2_read_restart_flux, c13o2_read_restart_pools, c13o2_init_luc
mpidrv_master calls c13o2_create_output, c13o2_close_output, c13o2_write_output, c13o2_write_restart_flux, c13o2_write_restart_pools, c13o2_write_restart_luc, load_parameters, master_spincasacnp, master_casaonly_luc
cable_offline_driver calls c13o2_create_output, c13o2_close_output, c13o2_write_output, c13o2_write_restart_flux, c13o2_write_restart_pools, c13o2_write_restart_luc, spincasacnp, load_parameters
c13o2_init_luc calls c13o2_read_restart_luc
master_spincasacnp calls c13o2_write_restart_pools
master_casaonly_luc calls c13o2_write_restart_pools, c13o2_write_restart_luc
mpi_driver calls mpidrv_master