c13o2_print_delta_luc – POP
c13o2_print_delta_luc Subroutine
61 statements
Source File
public subroutine c13o2_print_delta_luc(popluc, c13o2luc)
Uses
POPLUC_Types
mo_isotope
mo_utils
cable_c13o2_def
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(in) :: popluc
type(c13o2_luc), intent(in) :: c13o2luc
Calls
Called by
Contents
None
Call graph
c13o2_print_delta_luc calls delta1000, ne
ne calls notequal_sp, notequal_dp
mpidrv_master calls c13o2_print_delta_luc
cable_offline_driver calls c13o2_print_delta_luc
mpi_driver calls mpidrv_master