c13o2_update_luc – POP
c13o2_update_luc Subroutine
159 statements
Source File
public subroutine c13o2_update_luc(casasave, lucsave, popluc, prim_only, c13o2pools, c13o2luc, casapool)
Uses
POPLUC_Module
POPLUC_Types
mo_isotope_luc_model
mo_isotope
cable_c13o2_def
mo_isotope_pool_model
POPLUC_CONSTANTS
cable_IO_vars_module
mpi
cable_def_types_mod
casavariable
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), dimension(:,:) :: casasave
real(kind=dp), intent(in), dimension(:,:) :: lucsave
type(POPLUC_TYPE), intent(in) :: popluc
logical, intent(in), dimension(:) :: prim_only
type(c13o2_pool), intent(inout) :: c13o2pools
type(c13o2_luc), intent(inout) :: c13o2luc
type(casa_pool), intent(in), optional :: casapool
Calls
Called by
Contents
None
Call graph
c13o2_update_luc calls c13o2_save_c13o2pools, mpi_abort, delta1000, isotope_pool_model, isotope_luc_model
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
isotope_luc_model calls isotope_luc_model_1d
isotope_pool_model_1d calls mpi_abort, ne, diag, eq
isotope_luc_model_1d calls mpi_abort, eq
isotope_pool_model_2d calls mpi_abort, ne, diag, eq
ne calls notequal_sp, notequal_dp
diag calls diag_3d, diag_2d
eq calls equal_sp, equal_dp
diag_3d calls mpi_abort
diag_2d calls mpi_abort
casaonly_luc calls c13o2_update_luc
cable_offline_driver calls c13o2_update_luc, casaonly_luc
master_casaonly_luc calls c13o2_update_luc
mpidrv_master calls c13o2_update_luc, master_casaonly_luc
mpi_driver calls mpidrv_master