c13o2_init_pools – POP
c13o2_init_pools Subroutine
13 statements
Source File
public subroutine c13o2_init_pools(casapool, casaflux, c13o2pools)
Uses
casavariable
cable_c13o2_def
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(in) :: casapool
type(casa_flux), intent(in) :: casaflux
type(c13o2_pool), intent(inout) :: c13o2pools
Called by
Contents
Call graph
load_parameters calls c13o2_init_pools
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master