c13o2_sources_pools – POP
c13o2_sources_pools Subroutine
18 statements
Source File
private subroutine c13o2_sources_pools(c13o2flux, casaflux, casasources)
Uses
cable_def_types_mod
cable_c13o2_def
casavariable
Arguments
Type Intent Optional Attributes Name
type(c13o2_flux), intent(inout) :: c13o2flux
type(casa_flux), intent(in) :: casaflux
real(kind=dp), intent(out), dimension(:,:) :: casasources
Called by
Contents
None
Call graph
c13o2_update_pools calls c13o2_sources_pools
bgcdriver calls c13o2_update_pools
spincasacnp calls c13o2_update_pools
worker_casaonly_luc calls c13o2_update_pools
casaonly_luc calls c13o2_update_pools
worker_spincasacnp calls c13o2_update_pools
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, spincasacnp, casaonly_luc
mpi_driver calls mpidrv_worker