c13o2_read_restart_flux – POP
c13o2_read_restart_flux Subroutine
33 statements
Source File
public subroutine c13o2_read_restart_flux(c13o2_restart_in_flux, c13o2flux)
Uses
netcdf
cable_c13o2_def
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: c13o2_restart_in_flux
type(c13o2_flux), intent(inout) :: c13o2flux
Calls
Called by
Contents
None
Call graph
c13o2_read_restart_flux calls c13o2_err_handler, nf90_inq_varid, nf90_close, nf90_get_var, nf90_open
c13o2_err_handler calls mpi_abort
load_parameters calls c13o2_read_restart_flux
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master