c13o2_write_restart_luc – POP
c13o2_write_restart_luc Subroutine
70 statements
Source File
public subroutine c13o2_write_restart_luc(popluc, c13o2luc)
Uses
cable_common_module
cable_c13o2_def
POPLUC_Types
netcdf
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(in) :: popluc
type(c13o2_luc), intent(in) :: c13o2luc
Calls
Called by
Contents
Call graph
c13o2_write_restart_luc calls nf90_create, nf90_put_att, c13o2_err_handler, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_var, nf90_close
master_casaonly_luc calls c13o2_write_restart_luc
cable_offline_driver calls c13o2_write_restart_luc
mpidrv_master calls c13o2_write_restart_luc, master_casaonly_luc
mpi_driver calls mpidrv_master