c13o2_zero_pools – POP
c13o2_zero_pools Subroutine
10 statements
Source File
public subroutine c13o2_zero_pools(c13o2pools)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(c13o2_pool), intent(inout) :: c13o2pools
Called by
Contents
Call graph
worker_c13o2_pool_params calls c13o2_zero_pools
load_parameters calls c13o2_zero_pools
mpidrv_worker calls worker_c13o2_pool_params
cable_offline_driver calls load_parameters
mpidrv_master calls load_parameters
mpi_driver calls mpidrv_worker, mpidrv_master