c13o2_save_luc – POP
c13o2_save_luc Subroutine
24 statements
Source File
public subroutine c13o2_save_luc(casapool, popluc, casasave, lucsave)
Uses
POPLUC_Types
cable_def_types_mod
casavariable
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(in) :: casapool
type(POPLUC_TYPE), intent(in) :: popluc
real(kind=dp), intent(out), dimension(:,:) :: casasave
real(kind=dp), intent(out), dimension(:,:) :: lucsave
Calls
Called by
Contents
None
Call graph
c13o2_save_luc calls c13o2_save_casapool
casaonly_luc calls c13o2_save_luc
cable_offline_driver calls c13o2_save_luc, casaonly_luc
master_casaonly_luc calls c13o2_save_luc
mpidrv_master calls c13o2_save_luc, master_casaonly_luc
mpi_driver calls mpidrv_master