c13o2_alloc_luc – POP
c13o2_alloc_luc Subroutine
13 statements
Source File
public subroutine c13o2_alloc_luc(c13o2luc, nland)
Uses
POPLUC_Module
Arguments
Type Intent Optional Attributes Name
type(c13o2_luc), intent(inout) :: c13o2luc
integer, intent(in) :: nland
Called by
Contents
None
Call graph
c13o2_init_luc calls c13o2_alloc_luc
worker_c13o2_luc_params calls c13o2_alloc_luc
load_parameters calls c13o2_init_luc
mpidrv_worker calls worker_c13o2_luc_params
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_worker, mpidrv_master