c13o2_sanity_pools – POP
c13o2_sanity_pools Subroutine
15 statements
Source File
public subroutine c13o2_sanity_pools(casapool, casaflux, c13o2pools)
Uses
casavariable
mo_isotope
cable_c13o2_def
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(c13o2_pool), intent(inout) :: c13o2pools
Calls
Called by
Contents
None
Call graph
c13o2_sanity_pools calls isosanity
spincasacnp calls c13o2_sanity_pools
master_casaonly_luc calls c13o2_sanity_pools
mpidrv_master calls c13o2_sanity_pools, master_casaonly_luc, master_spincasacnp
worker_spincasacnp calls c13o2_sanity_pools
master_spincasacnp calls c13o2_sanity_pools
mpidrv_worker calls c13o2_sanity_pools, worker_spincasacnp, worker_casaonly_luc
worker_casaonly_luc calls c13o2_sanity_pools
cable_offline_driver calls c13o2_sanity_pools, spincasacnp
mpi_driver calls mpidrv_master, mpidrv_worker