c13o2_init_flux – POP
c13o2_init_flux Subroutine
26 statements
Source File
public subroutine c13o2_init_flux(met, canopy, c13o2flux)
Uses
mo_c13o2_photosynthesis
cable_c13o2_def
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: met
type(canopy_type), intent(inout) :: canopy
type(c13o2_flux), intent(inout) :: c13o2flux
Calls
Called by
Contents
None
Call graph
c13o2_init_flux calls init_starch_pool, init_sugar_pools
load_parameters calls c13o2_init_flux
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master