c13o2_save_casapool – POP
c13o2_save_casapool Subroutine
24 statements
Source File
public subroutine c13o2_save_casapool(casapool, casasave)
Uses
cable_def_types_mod
casavariable
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(in) :: casapool
real(kind=dp), intent(out), dimension(:,:) :: casasave
Called by
Contents
Call graph
worker_spincasacnp calls c13o2_save_casapool
bgcdriver calls c13o2_save_casapool
casaonly_luc calls c13o2_save_casapool, c13o2_save_luc
c13o2_save_luc calls c13o2_save_casapool
worker_casaonly_luc calls c13o2_save_casapool
spincasacnp calls c13o2_save_casapool
mpidrv_worker calls worker_spincasacnp, bgcdriver, worker_casaonly_luc
mpidrv_master calls c13o2_save_luc, master_casaonly_luc
cable_offline_driver calls bgcdriver, casaonly_luc, c13o2_save_luc, spincasacnp
master_casaonly_luc calls c13o2_save_luc
mpi_driver calls mpidrv_worker, mpidrv_master