c13o2_write_restart_flux – POP
c13o2_write_restart_flux Subroutine
64 statements
Source File
public subroutine c13o2_write_restart_flux(casamet, c13o2flux)
Uses
casavariable
netcdf
cable_c13o2_def
cable_common_module
Arguments
Type Intent Optional Attributes Name
type(casa_met), intent(in) :: casamet
type(c13o2_flux), intent(in) :: c13o2flux
Calls
Called by
Contents
Call graph
c13o2_write_restart_flux calls nf90_create, nf90_put_att, c13o2_err_handler, nf90_def_var, nf90_def_dim, nf90_enddef, nf90_put_var, nf90_close
mpidrv_master calls c13o2_write_restart_flux
cable_offline_driver calls c13o2_write_restart_flux
mpi_driver calls mpidrv_master