c13o2_write_restart_pools – POP
c13o2_write_restart_pools Subroutine
85 statements
Source File
public subroutine c13o2_write_restart_pools(casamet, c13o2pools)
Uses
casavariable
cable_common_module
netcdf
cable_c13o2_def
Arguments
Type Intent Optional Attributes Name
type(casa_met), intent(in) :: casamet
type(c13o2_pool), intent(in) :: c13o2pools
Calls
Called by
Contents
Call graph
c13o2_write_restart_pools calls nf90_create, nf90_def_dim, nf90_put_att, nf90_def_var, c13o2_err_handler, nf90_enddef, nf90_put_var, nf90_close
master_spincasacnp calls c13o2_write_restart_pools
master_casaonly_luc calls c13o2_write_restart_pools
mpidrv_master calls c13o2_write_restart_pools, master_spincasacnp, master_casaonly_luc
cable_offline_driver calls c13o2_write_restart_pools
mpi_driver calls mpidrv_master