cable_bios_read_met – POP
cable_bios_read_met Subroutine
160 statements
Source File
public subroutine cable_bios_read_met(MET, CurYear, ktau, dels)
Uses
mo_utils
NB !! Peter to fix as in Cabledyn !!
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: MET
integer, intent(in) :: CurYear
integer, intent(in) :: ktau
real, intent(in) :: dels
Calls
Called by
Contents
None
Call graph
cable_bios_read_met calls eq, wgen_subdiurnal_met, wgen_daily_constants, daydifference
eq calls equal_sp, equal_dp
daydifference calls julianday
mpidrv_master calls cable_bios_read_met
cable_offline_driver calls cable_bios_read_met
mpi_driver calls mpidrv_master