cable_phenology_clim – POP
cable_phenology_clim Subroutine
77 statements
Source File
public subroutine cable_phenology_clim(veg, climate, phen)
Uses
mo_utils
phenvariable
casaparm
casavariable
casadimension
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(in) :: veg
type(climate_type), intent(in) :: climate
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
None
Call graph
cable_phenology_clim calls ge, eq
ge calls greaterequal_sp, greaterequal_dp
eq calls equal_dp, equal_sp
bgcdriver calls cable_phenology_clim
mpidrv_worker calls bgcdriver
cable_offline_driver calls bgcdriver
mpi_driver calls mpidrv_worker