canopy_type_ptr – POP
canopy_type_ptr Subroutine
62 statements
Source File
public subroutine canopy_type_ptr(C)
Arguments
Type Intent Optional Attributes Name
type(icanopy_type) :: C
Called by
Contents
None
Call graph
point2constants calls canopy_type_ptr
total_photosynthesis_cost calls point2constants, xvcmxt3_acclim, xgmest, xejmxt3_acclim, xvcmxt3, xejmxt3
plantcarb calls point2constants
total_an_ac_aj calls point2constants, xvcmxt3_acclim, xgmest, xejmxt3_acclim, xvcmxt3, xejmxt3
cable_offline_driver calls point2constants, cbm, casa_feedback
xvcmxt4 calls point2constants
cbm calls point2constants, plantcarb, ruff_resist, surface_albedo, init_radiation, soil_snow, define_canopy, define_air
ruff_resist calls point2constants
xvcmxt3_acclim calls point2constants
xgmest calls point2constants
xejmxt3_acclim calls point2constants
total_photosynthesis calls point2constants, xvcmxt3_acclim, xgmest, xejmxt3_acclim, xvcmxt3, xejmxt3
surface_albedo calls point2constants
init_radiation calls point2constants
diff_ac_aj calls point2constants, xvcmxt3_acclim, xgmest, xejmxt3_acclim, xvcmxt3, xejmxt3
soil_snow calls point2constants
mpidrv_master calls point2constants
casa_feedback calls point2constants, optimise_jv, adjust_jv_gm
define_canopy calls point2constants, ruff_resist, define_air, dryleaf
mpidrv_worker calls point2constants, cbm, casa_feedback
optimise_jv calls point2constants, total_photosynthesis_cost, diff_ac_aj
adjust_jv_gm calls point2constants
xvcmxt3 calls point2constants
xvcmxt4_acclim calls point2constants
define_air calls point2constants
xejmxt3 calls point2constants
dryleaf calls xvcmxt4, xvcmxt3_acclim, xgmest, xejmxt3_acclim, xvcmxt3, xvcmxt4_acclim, xejmxt3
mpi_driver calls mpidrv_master, mpidrv_worker