CASAONLY_LUC – POP
CASAONLY_LUC Subroutine
217 statements
Source File
public subroutine CASAONLY_LUC(dels, kstart, kend, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen, POP, climate, LALLOC, LUC_EXPT, POPLUC, sum_casapool, sum_casaflux, c13o2flux, c13o2pools, sum_c13o2pools, c13o2luc)
Uses
cable_carbon_module
POPLUC_Types
cable_IO_vars_module
POPModule
mo_utils
cable_common_module
cable_c13o2
casaparm
POPLUC_Module
CABLE_LUC_EXPT
casadimension
cable_c13o2_def
casa_cable
casa_inout
POP_Types
cable_def_types_mod
phenvariable
casavariable
TypeDef
CLN CHARACTER(LEN=99), INTENT(IN) :: fcnpspin vh_js !! CLN901 format(A99)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: kstart
integer, intent(in) :: kend
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: POP
type(climate_type), intent(inout) :: climate
integer, intent(in) :: LALLOC
type(luc_expt_type), intent(inout) :: LUC_EXPT
type(POPLUC_TYPE), intent(inout) :: POPLUC
type(casa_pool), intent(inout) :: sum_casapool
type(casa_flux), intent(inout) :: sum_casaflux
type(c13o2_flux), intent(inout) :: c13o2flux
type(c13o2_pool), intent(inout) :: c13o2pools
type(c13o2_pool), intent(inout) :: sum_c13o2pools
type(c13o2_luc), intent(inout) :: c13o2luc
Calls
Called by
Contents
None
Call graph
casaonly_luc calls c13o2_save_luc, is_casa_time, c13o2_zero_sum_pools, pop_luc_casa_transfer, read_casa_dump, c13o2_update_pools, update_sum_casa, c13o2_update_sum_pools, popdriver, write_luc_restart_nc, pop_init_single, poplucstep, c13o2_update_luc, popluc_set_patchfrac, eq, c13o2_save_casapool, biogeochem, read_luh2, zero_sum_casa, popluc_weights_transfer
c13o2_save_luc calls c13o2_save_casapool
is_casa_time calls is_leapyear
pop_luc_casa_transfer calls eq
read_casa_dump calls nf90_close, stderr_nc, nf90_open, get_var_nc
c13o2_update_pools calls c13o2_c13o2pools_back, c13o2_save_c13o2pools, c13o2_fluxmatrix_pools, c13o2_sinks_pools, isotope_pool_model, c13o2_sources_pools
popdriver calls popstep
write_luc_restart_nc calls nf90_redef, nf90_enddef, handle_err, nf90_close, nf90_put_var, nf90_def_dim, nf90_create, nf90_put_att, nf90_def_var
pop_init_single calls layer_recruitment_single_patch, initpop2d_poisson, zeropop
poplucstep calls increment_age, execute_luc_event
c13o2_update_luc calls c13o2_save_c13o2pools, isotope_luc_model, isotope_pool_model
eq calls equal_sp, equal_dp
biogeochem calls casa_coeffsoil, casa_delsoil, casa_cnpflux, casa_cnpcycle, casa_cnpbal, casa_nuptake, casa_puptake, casa_coeffplant, casa_pdummy, avgsoil, casa_xkn, casa_xrateplant, casa_ndummy, phenology, casa_delplant, casa_xratesoil, casa_allocation, casa_xnp, casa_rplant
read_luh2 calls nf90_get_var, handle_err
zero_sum_casa calls zero_casapool, zero_casaflux
casa_cnpcycle calls casa_poolzero
popstep calls patchannualdynamics, patch_partial_disturb2, getuniqueagefrequencies, patch_partial_disturb, patch_disturb, getpatchfrequencies, getdiagnostics
handle_err calls nf90_strerror
stderr_nc calls nf90_strerror
casa_nuptake calls casa_nrequire
casa_puptake calls casa_prequire
casa_xrateplant calls ge, le
casa_allocation calls casa_wolf
get_var_nc calls get_var_ncr2, get_var_ncr3
layer_recruitment_single_patch calls get_allometry
isotope_luc_model calls isotope_luc_model_1d
casa_xnp calls casa_nrequire, casa_prequire
casa_rplant calls vcmax_np
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
initpop2d_poisson calls cumexponential, exponential
get_var_ncr2 calls nf90_get_var, stderr_nc, nf90_inq_varid
get_var_ncr3 calls nf90_get_var, stderr_nc, nf90_inq_varid
patchannualdynamics calls get_allometry, layer_recruitment
getuniqueagefrequencies calls cumexponential, realexponential
ge calls greaterequal_sp, greaterequal_dp
isotope_luc_model_1d calls eq, mpi_abort
get_allometry calls getheight, allometry, williams_allometry
le calls lesserequal_dp, lesserequal_sp
patch_disturb calls layer_recruitment_single_patch
getdiagnostics calls get_allometry, interpolate_biomass_2d, interpolate_biomass_1d, smooth_flux
isotope_pool_model_1d calls eq, ne, diag, mpi_abort
isotope_pool_model_2d calls eq, ne, diag, mpi_abort
interpolate_biomass_2d calls eq, realexponential, area_triangle
ne calls notequal_dp, notequal_sp
diag calls diag_2d, diag_3d
interpolate_biomass_1d calls realexponential
layer_recruitment calls get_allometry
smooth_flux calls regress
diag_2d calls mpi_abort
diag_3d calls mpi_abort
cable_offline_driver calls casaonly_luc