casa_poolzero – POP
casa_poolzero Subroutine
29 statements
Source File
public subroutine casa_poolzero(n, ipool, casapool)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: ipool
type(casa_pool), intent(inout) :: casapool
Called by
Contents
None
Call graph
casa_cnpcycle calls casa_poolzero
biogeochem calls casa_cnpcycle
bgcdriver calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
spincasacnp calls biogeochem
casaonly_luc calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls bgcdriver, spincasacnp, casaonly_luc
mpi_driver calls mpidrv_worker