casa_init – POP
casa_init Subroutine
44 statements
Source File
public subroutine casa_init(casabiome, casamet, casaflux, casapool, casabal, phen)
Uses
casadimension
casaparm
phenvariable
cable_common_module
cable_IO_vars_module
cable_def_types_mod
casavariable
for first time reading file *_1220.csv (BP may2010)
SUBROUTINE casa_init(mst,casapool,casabal) end addition (BP may2010)
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(inout) :: casabiome
type(casa_met), intent(inout) :: casamet
type(casa_flux), intent(inout) :: casaflux
type(casa_pool), intent(inout) :: casapool
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
None
Call graph
casa_init calls read_casa_restart_nc, zero_casa_dump
read_casa_restart_nc calls read_netcdf_casa_var, read_netcdf_phen_var
read_netcdf_casa_var calls read_netcdf_casabiome, read_netcdf_casamet, read_netcdf_casapool, read_netcdf_casabal, read_netcdf_casaflux
read_netcdf_phen_var calls mpi_abort, nf90_inq_varid, nc_err, nf90_open, nf90_get_var, nf90_close
read_netcdf_casabiome calls mpi_abort, nf90_inq_varid, nc_err, nf90_open, nf90_get_var, nf90_close
read_netcdf_casamet calls mpi_abort, nf90_inq_varid, nc_err, nf90_open, nf90_get_var, nf90_close
read_netcdf_casapool calls mpi_abort, nf90_inq_varid, nc_err, nf90_open, nf90_get_var, nf90_close
read_netcdf_casabal calls mpi_abort, nf90_inq_varid, nc_err, nf90_open, nf90_get_var, nf90_close
read_netcdf_casaflux calls mpi_abort, nf90_inq_varid, nc_err, nf90_open, nf90_get_var, nf90_close
nc_err calls mpi_abort, nf90_strerror
load_parameters calls casa_init
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master