casa_fluxout – POP
casa_fluxout Subroutine
56 statements
Source File
public subroutine casa_fluxout(myear, veg, soil, casabal, casamet)
Uses
casaparm
casavariable
casadimension
phenvariable
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: myear
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_balance), intent(inout) :: casabal
type(casa_met), intent(inout) :: casamet
Called by
Contents
None
Call graph
spincasacnp calls casa_fluxout
master_spincasacnp calls casa_fluxout
mpidrv_master calls casa_fluxout, master_spincasacnp
cable_offline_driver calls casa_fluxout, spincasacnp
mpi_driver calls mpidrv_master