casa_cnpflux – POP
casa_cnpflux Subroutine
69 statements
Source File
public subroutine casa_cnpflux(casaflux, casapool, casabal, zeroflux)
Uses
casadimension
casavariable
cable_def_types_mod
casaparm
Arguments
Type Intent Optional Attributes Name
type(casa_flux), intent(inout) :: casaflux
type(casa_pool), intent(in) :: casapool
type(casa_balance), intent(inout) :: casabal
logical, intent(in) :: zeroflux
Called by
Contents
None
Call graph
biogeochem calls casa_cnpflux
mpidrv_worker calls casa_cnpflux, bgcdriver, worker_spincasacnp, worker_casaonly_luc
cable_offline_driver calls casa_cnpflux, bgcdriver, casaonly_luc, spincasacnp
mpidrv_master calls casa_cnpflux
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
mpi_driver calls mpidrv_worker, mpidrv_master