casa_feedback – POP
casa_feedback Subroutine
139 statements
Source File
public subroutine casa_feedback(ktau, veg, casabiome, casapool, casamet, climate, ktauday)
Uses
casaparm
cable_common_module
cable_optimise_JV_module
cable_def_types_mod
casa_cnp_module
cable_adjust_JV_gm_module
cable_data_module
casadimension
casavariable
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(in) :: casapool
type(casa_met), intent(in) :: casamet
type(climate_type), intent(in) :: climate
integer, intent(in) :: ktauday
Calls
Called by
Contents
None
Call graph
casa_feedback calls point2constants, find_vcmax_jmax_lut, adjust_k_collatz, vcmax_np, adjust_jv_gm, optimise_jv
point2constants calls driver_type_ptr, cbm_type_ptr, air_type_ptr, albedo_type_ptr, canopy_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr
find_vcmax_jmax_lut calls light_inhibition
adjust_k_collatz calls light_inhibition
adjust_jv_gm calls point2constants, lmdif1, photosyn25, light_inhibition
optimise_jv calls point2constants, diff_ac_aj, golden, total_photosynthesis_cost, rtbis
lmdif1 calls lmdif
diff_ac_aj calls point2constants, xvcmxt3_acclim, xvcmxt3, xrdt, ej3x, xgmest, light_inhibition, fabcd, fpq, fam_c3, fabc, xejmxt3, fan_c3, xejmxt3_acclim
total_photosynthesis_cost calls point2constants, xvcmxt3_acclim, xvcmxt3, xrdt, ej3x, xgmest, light_inhibition, fabcd, fpq, fam_c3, fabc, xejmxt3, fan_c3, xejmxt3_acclim
rtbis calls ge, eq, le
ge calls greaterequal_sp, greaterequal_dp
eq calls equal_dp, equal_sp
le calls lesserequal_sp, lesserequal_dp
lmdif calls ge, eq, le, fdjac2, enorm, qrfac, ne, lmpar
xvcmxt3_acclim calls point2constants
xvcmxt3 calls point2constants
xgmest calls point2constants
xejmxt3 calls point2constants
xejmxt3_acclim calls point2constants
fdjac2 calls eq
qrfac calls le, enorm, ne
ne calls notequal_sp, notequal_dp
lmpar calls eq, le, enorm, qrsolv
qrsolv calls eq, ne
mpidrv_worker calls casa_feedback
cable_offline_driver calls casa_feedback
mpi_driver calls mpidrv_worker