cbm_type_ptr – POP
cbm_type_ptr Subroutine
5 statements
Source File
public subroutine cbm_type_ptr(C)
Arguments
Type Intent Optional Attributes Name
type(icbm_type) :: C
Called by
Contents
Call graph
point2constants calls cbm_type_ptr
soil_snow calls point2constants
mpidrv_master calls point2constants
define_air calls point2constants
adjust_jv_gm calls point2constants
ruff_resist calls point2constants
xvcmxt4_acclim calls point2constants
optimise_jv calls point2constants, total_photosynthesis_cost, diff_ac_aj
casa_feedback calls point2constants, adjust_jv_gm, optimise_jv
xvcmxt3 calls point2constants
xgmest calls point2constants
xejmxt3 calls point2constants
surface_albedo calls point2constants
total_photosynthesis_cost calls point2constants, xvcmxt3, xgmest, xejmxt3, xvcmxt3_acclim, xejmxt3_acclim
init_radiation calls point2constants
cbm calls point2constants, soil_snow, define_air, ruff_resist, surface_albedo, init_radiation, define_canopy, plantcarb
xvcmxt3_acclim calls point2constants
define_canopy calls point2constants, define_air, ruff_resist, dryleaf
total_an_ac_aj calls point2constants, xvcmxt3, xgmest, xejmxt3, xvcmxt3_acclim, xejmxt3_acclim
mpidrv_worker calls point2constants, casa_feedback, cbm
diff_ac_aj calls point2constants, xvcmxt3, xgmest, xejmxt3, xvcmxt3_acclim, xejmxt3_acclim
xejmxt3_acclim calls point2constants
xvcmxt4 calls point2constants
cable_offline_driver calls point2constants, casa_feedback, cbm
total_photosynthesis calls point2constants, xvcmxt3, xgmest, xejmxt3, xvcmxt3_acclim, xejmxt3_acclim
plantcarb calls point2constants
mpi_driver calls mpidrv_master, mpidrv_worker
dryleaf calls xvcmxt4_acclim, xvcmxt3, xgmest, xejmxt3, xvcmxt3_acclim, xejmxt3_acclim, xvcmxt4