chkder – POP
chkder Subroutine
56 statements
Source File
public subroutine chkder(m, n, x, fvec, fjac, ldfjac, xp, fvecp, mode, err)
************80
CHKDER checks the gradients of M functions of N variables.
Arguments
Type Intent Optional Attributes Name
integer :: m
integer :: n
real(kind=r_2) :: x(n)
real(kind=r_2) :: fvec(m)
real(kind=r_2) :: fjac(ldfjac,n)
integer :: ldfjac
real(kind=r_2) :: xp(n)
real(kind=r_2) :: fvecp(m)
integer :: mode
real(kind=r_2) :: err(m)
Calls
Contents
Call graph
chkder calls eq, ne, ge, le
eq calls equal_sp, equal_dp
ne calls notequal_sp, notequal_dp
ge calls greaterequal_sp, greaterequal_dp
le calls lesserequal_sp, lesserequal_dp