close_luh2 – POP
close_luh2 Subroutine
14 statements
Source File
public subroutine close_luh2(LUC_EXPT)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
type(luc_expt_type), intent(inout) :: LUC_EXPT
Calls
Called by
Contents
None
Call graph
close_luh2 calls nf90_close, handle_err
handle_err calls nf90_strerror, mpi_abort
mpidrv_master calls close_luh2
cable_offline_driver calls close_luh2
mpi_driver calls mpidrv_master