COMBUST – POP
COMBUST Subroutine
65 statements
Source File
public subroutine COMBUST(BLAZE, NP, CPLANT_g, CPLANT_w, TO, BURN)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Arguments
Type Intent Optional Attributes Name
type(TYPE_BLAZE), intent(inout) :: BLAZE
integer, intent(in) :: NP
real, intent(in) :: CPLANT_g(3)
real, intent(in) :: CPLANT_w(3)
type(TYPE_TURNOVER), intent(inout) :: TO(NTO)
logical, intent(in) :: BURN
Calls
Called by
Contents
None
Call graph
combust calls avail_fuel
run_blaze calls combust
blaze_driver calls run_blaze
spincasacnp calls blaze_driver
cable_offline_driver calls blaze_driver, spincasacnp
mpidrv_worker calls blaze_driver, worker_spincasacnp
worker_spincasacnp calls blaze_driver
mpi_driver calls mpidrv_worker