copy_save_variables – POP
copy_save_variables Subroutine
51 statements
Source File
private subroutine copy_save_variables(metin, phenin, metout, phenout)
Uses
phenvariable
casavariable
cable_common_module
Arguments
Type Intent Optional Attributes Name
type(casa_met), intent(in) :: metin
type(phen_variable), intent(in) :: phenin
type(casa_met), intent(inout) :: metout
type(phen_variable), intent(inout) :: phenout
Called by
Contents
None
Call graph
master_spincasacnp calls copy_save_variables
master_casaonly_luc calls copy_save_variables
mpidrv_master calls master_spincasacnp, master_casaonly_luc
mpi_driver calls mpidrv_master