create_cohort – POP
create_cohort Subroutine
139 statements
Source File
public subroutine create_cohort(cohort_t, comm)
Uses
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: cohort_t
integer, intent(in) :: comm
Calls
Called by
Contents
Call graph
create_cohort calls mpi_get_address, mpi_type_create_resized, mpi_abort, mpi_type_create_struct, mpi_type_commit
create_layer calls create_cohort
create_patch calls create_layer
create_pop_gridcell_type calls create_patch