cru_read_metvals – POP
cru_read_metvals Subroutine
31 statements
Source File
public subroutine cru_read_metvals(cru, fid, vid, ii, t, land_x, land_y, filename)
Arguments
Type Intent Optional Attributes Name
type(cru_type), intent(inout) :: cru
integer, intent(in) :: fid
integer, intent(in) :: vid
integer, intent(in) :: ii
integer, intent(in) :: t
integer, intent(in), dimension(:) :: land_x
integer, intent(in), dimension(:) :: land_y
character(len=*), intent(in) :: filename
Calls
Called by
Contents
Call graph
cru_read_metvals calls nf90_get_var, handle_err
handle_err calls nf90_strerror
cru_get_daily_met calls cru_read_metvals
cru_get_subdiurnal_met calls cru_get_daily_met
mpidrv_master calls cru_get_subdiurnal_met
cable_offline_driver calls cru_get_subdiurnal_met
mpi_driver calls mpidrv_master