cru_close – POP
cru_close Subroutine
16 statements
Source File
public subroutine cru_close(CRU)
Arguments
Type Intent Optional Attributes Name
type(cru_type), intent(inout) :: CRU
Calls
Called by
Contents
Call graph
cru_close calls nf90_close, handle_err
handle_err calls nf90_strerror
cable_offline_driver calls cru_close