CRU_INIT – POP
CRU_INIT Subroutine
295 statements
Source File
public subroutine CRU_INIT(CRU)
Uses
mpi
cable_def_types_mod
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
type(cru_type), intent(inout) :: CRU
Calls
Called by
Contents
None
Call graph
cru_init calls get_unit, mpi_abort, handle_err, nf90_inq_dimid, nf90_open, nf90_inquire_dimension, nf90_inq_varid, nf90_get_var, nf90_close
handle_err calls mpi_abort, nf90_strerror
mpidrv_master calls cru_init
cable_offline_driver calls cru_init
mpi_driver calls mpidrv_master