define_canopy – POP
define_canopy Subroutine
554 statements
Source File
public subroutine define_canopy(bal, rad, rough, air, met, dels, ssnow, soil, veg, canopy, climate)
Uses
cable_radiation_module
cable_air_module
cable_sli_main
cable_common_module
cable_def_types_mod
cable_roughness_module
mo_utils
vh_js !! vh_js !! vh_js !! account for additional litter resistance to sensible heat transfer vh_js !! account for additional litter resistance to sensible heat transfer Ticket #90 ssnow%cls factor should be retained: required for energy balance vh_js!!
Arguments
Type Intent Optional Attributes Name
type(balances_type), intent(inout) :: bal
type(radiation_type), intent(inout) :: rad
type(roughness_type), intent(inout) :: rough
type(air_type), intent(inout) :: air
type(met_type), intent(inout) :: met
real, intent(in) :: dels
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
type(canopy_type), intent(inout) :: canopy
type(climate_type), intent(in) :: climate
Calls
Called by
Contents
None
Call graph
define_canopy calls point2constants, define_air, surf_wetness_fact, ruff_resist, radiation, dryleaf, sli_main, eq
point2constants calls air_type_ptr, rough_type_ptr, ssnow_type_ptr, driver_type_ptr, albedo_type_ptr, cbm_type_ptr, canopy_type_ptr, carbon_type_ptr, rad_type_ptr
define_air calls point2constants
ruff_resist calls point2constants
dryleaf calls xvcmxt4, photosynthesis_gm, fwsoil_calc_non_linear, ej3x, xgmest, xejmxt3, fwsoil_calc_lai_katul, xvcmxt4_acclim, fwsoil_calc_std, xrdt, getrex_1d, xvcmxt3, xvcmxt3_acclim, light_inhibition, xejmxt3_acclim
sli_main calls esat, solve, slope_esat_ice, getrex, zerovars, seb, hyofs, setx, zerovars_snow, setpar_loetsch, thetalmax, setlitterpar, esat_ice, zerovars_met, setpar, setroots, tfrz
eq calls equal_dp, equal_sp
xvcmxt4 calls point2constants
photosynthesis_gm calls famdam_c3, fandan_c3, famdam_c4, fandan_c4
xgmest calls point2constants
solve calls zerovars, hyofs, setsol, sofh, hyofh, litter_props, timestep_loop
getrex calls getrex_2d, getrex_1d
xejmxt3 calls point2constants
seb calls potential_evap, hyofh, slope_csat
hyofs calls tfrz, slope_esat, igamma, dthetalmaxdt
xvcmxt4_acclim calls point2constants
xvcmxt3 calls point2constants
xvcmxt3_acclim calls point2constants
thetalmax calls tfrz
xejmxt3_acclim calls point2constants
setroots calls setroots_1d, setroots_2d
setroots_2d calls setroots_1d
getrex_2d calls getrex_1d
potential_evap calls slope_esat_ice, slope_esat
famdam_c3 calls fam_c3, fdam_c3, fabcd, fdabcd, fpq, fdpq
fandan_c3 calls fdabc, fabc, fdan_c3, fan_c3
famdam_c4 calls fdabcm, fam_c4, fdam_c4, fabcm
fandan_c4 calls fdan_c4, fan_c4, fabc_c4, fdabc_c4
litter_props calls slope_esat
timestep_loop calls litter_props, iflux_loop, isotope_vap
igamma calls gammln, gser, gcf
dthetalmaxdt calls tfrz
iflux_loop calls hyofs, litter_props, get_fluxes_and_derivs, get_and_solve_eqn, update_unknowns, estimate_timestep, snow_adjust, update_s_t
isotope_vap calls ne, tri
gser calls eq, gammln
gcf calls eq, gammln
get_fluxes_and_derivs calls zerovars, seb, flux, getfluxes_vp, getheatfluxes
get_and_solve_eqn calls tfrz, massman_sparse
update_unknowns calls jsoillayer
snow_adjust calls slope_esat_ice, thetalmax, esat_ice, tfrz, jsoillayer, rtbis_tfrozen, gtfrozen
update_s_t calls thetalmax, tfrz, jsoillayer, rtbis_tfrozen, gtfrozen, dthetalmaxdth
ne calls notequal_sp, notequal_dp
tri calls tri_2d, tri_1d
flux calls weight
getfluxes_vp calls getfluxes_vp_1d, getfluxes_vp_2d
massman_sparse calls massman_sparse_1d, massman_sparse_2d
jsoillayer calls tfrz
getheatfluxes calls getheatfluxes_1d, getheatfluxes_2d
rtbis_tfrozen calls gtfrozen
gtfrozen calls tfrz
dthetalmaxdth calls tfrz
weight calls hyofh
getfluxes_vp_1d calls eq, zerovars, hyofh, flux
massman_sparse_1d calls generic_thomas
getfluxes_vp_2d calls eq, zerovars, hyofh, flux
massman_sparse_2d calls generic_thomas
generic_thomas calls generic_thomas_1d, generic_thomas_2d
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker