delta1000 – POP
delta1000 Function
34 statements
Source File
public pure elemental function delta1000(rare, abundant, standard, default, precision)
\brief Isotopic delta value in permil. \details Elemental routine to calculate the delta value in permil from an isotope ratio or the rare and the abundant isotope concentrations relative to a given standard. The delta value can be set to a default value if the abundant isotopic concentration is below a give precision. \param[in] "real(dp) :: rare" Rare isotope concentration or isotope ratio \param[in] "real(dp), optional :: abundant" Abundant isotope concentration if rare is rare isotope concentration Default: not used. \param[in] "real(dp), optional :: standard" Isotop ratio of the standard material. Default: 1. \param[in] "real(dp), optional :: default" Set isoratio default if abundant < precision. Default: 0. \param[in] "real(dp), optional :: precision" Set isoratio default if abundant < precision. \return real(dp) :: delta — Isotopic delta value in permil: (rare / abundant / standard - 1.) * 1000. \author Written Matthias Cuntz \date Apr 2019
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: rare
real(kind=dp), intent(in), optional :: abundant
real(kind=dp), intent(in), optional :: standard
real(kind=dp), intent(in), optional :: default
real(kind=dp), intent(in), optional :: precision
Return Value real(kind=dp)
Called by
Contents
None
Call graph
c13o2_update_luc calls delta1000
c13o2_print_delta_pools calls delta1000
c13o2_print_delta_flux calls delta1000
c13o2_print_delta_luc calls delta1000
casaonly_luc calls c13o2_update_luc
cable_offline_driver calls c13o2_update_luc, c13o2_print_delta_pools, c13o2_print_delta_flux, c13o2_print_delta_luc, casaonly_luc
master_casaonly_luc calls c13o2_update_luc
mpidrv_master calls c13o2_update_luc, c13o2_print_delta_pools, c13o2_print_delta_flux, c13o2_print_delta_luc, master_casaonly_luc
mpi_driver calls mpidrv_master