diag_3d – POP
diag_3d Function
37 statements
Source File
private function diag_3d(matrix, trans)
Uses
mo_kind
mpi
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), dimension(:,:,:) :: matrix
logical, intent(in), optional :: trans
Return Value real(kind=dp),dimension(:,:),allocatable
Calls
Called by
Contents
None
Call graph
diag_3d calls mpi_abort
diag calls diag_3d
isotope_pool_model_1d calls diag
isotope_pool_model_2d calls diag
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
c13o2_update_pools calls isotope_pool_model
c13o2_update_luc calls isotope_pool_model
bgcdriver calls c13o2_update_pools
worker_spincasacnp calls c13o2_update_pools
spincasacnp calls c13o2_update_pools
worker_casaonly_luc calls c13o2_update_pools
casaonly_luc calls c13o2_update_pools, c13o2_update_luc
mpidrv_master calls c13o2_update_luc, master_casaonly_luc
master_casaonly_luc calls c13o2_update_luc
cable_offline_driver calls c13o2_update_luc, bgcdriver, spincasacnp, casaonly_luc
mpidrv_worker calls bgcdriver, worker_spincasacnp, worker_casaonly_luc
mpi_driver calls mpidrv_master, mpidrv_worker