diff_Ac_Aj – POP
diff_Ac_Aj Function
117 statements
Source File
public function diff_Ac_Aj(bjv)
Uses
cable_def_types_mod
cable_canopy_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: bjv
Return Value real
Calls
Called by
Contents
None
Call graph
diff_ac_aj calls fabc, fan_c3, xgmest, xvcmxt3_acclim, point2constants, xvcmxt3, xrdt, light_inhibition, fabcd, fpq, fam_c3, xejmxt3, xejmxt3_acclim, ej3x
xgmest calls point2constants
xvcmxt3_acclim calls point2constants
point2constants calls driver_type_ptr, cbm_type_ptr, canopy_type_ptr, albedo_type_ptr, air_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr
xvcmxt3 calls point2constants
xejmxt3 calls point2constants
xejmxt3_acclim calls point2constants
optimise_jv calls diff_ac_aj
casa_feedback calls optimise_jv
mpidrv_worker calls casa_feedback
cable_offline_driver calls casa_feedback
mpi_driver calls mpidrv_worker