dogleg – POP
dogleg Subroutine
93 statements
Source File
public subroutine dogleg(n, r, lr, diag, qtb, delta, x)
************80
DOGLEG finds the minimizing combination of Gauss-Newton and gradient steps.
Arguments
Type Intent Optional Attributes Name
integer :: n
real(kind=r_2) :: r(lr)
integer :: lr
real(kind=r_2) :: diag(n)
real(kind=r_2) :: qtb(n)
real(kind=r_2) :: delta
real(kind=r_2) :: x(n)
Calls
Called by
Contents
Call graph
dogleg calls eq, le, ne, enorm
eq calls equal_sp, equal_dp
le calls lesserequal_dp, lesserequal_sp
ne calls notequal_sp, notequal_dp
hybrd calls dogleg
hybrj calls dogleg
hybrd1 calls hybrd
hybrj1 calls hybrj