doysod2ymdhms – POP
doysod2ymdhms Subroutine
31 statements
Source File
public subroutine doysod2ymdhms(yyyy, doy, sod, mm, dd, hour, minute, second)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: yyyy
integer, intent(in) :: doy
integer, intent(in) :: sod
integer, intent(out) :: mm
integer, intent(out) :: dd
integer, intent(out), optional :: hour
integer, intent(out), optional :: minute
integer, intent(out), optional :: second
Calls
Called by
Contents
None
Call graph
doysod2ymdhms calls is_leapyear
blaze_driver calls doysod2ymdhms, run_blaze
burntime calls doysod2ymdhms
run_blaze calls doysod2ymdhms
open_met_file calls doysod2ymdhms
plume_mip_get_met calls doysod2ymdhms
cru_get_subdiurnal_met calls doysod2ymdhms
spincasacnp calls blaze_driver
worker_spincasacnp calls blaze_driver
cable_offline_driver calls blaze_driver, open_met_file, plume_mip_get_met, cru_get_subdiurnal_met, spincasacnp
mpidrv_worker calls blaze_driver, worker_spincasacnp
mpidrv_master calls open_met_file, plume_mip_get_met, cru_get_subdiurnal_met
mpi_driver calls mpidrv_worker, mpidrv_master