driver_type_ptr – POP
driver_type_ptr Subroutine
7 statements
Source File
public subroutine driver_type_ptr(C)
Arguments
Type Intent Optional Attributes Name
type(driver_type) :: C
Called by
Contents
None
Call graph
point2constants calls driver_type_ptr
mpidrv_worker calls point2constants, cbm, casa_feedback
cbm calls point2constants, init_radiation, define_canopy, soil_snow, plantcarb, surface_albedo, ruff_resist, define_air
casa_feedback calls point2constants, adjust_jv_gm, optimise_jv
adjust_jv_gm calls point2constants
init_radiation calls point2constants
define_canopy calls point2constants, ruff_resist, define_air, dryleaf
diff_ac_aj calls point2constants, xvcmxt3, xvcmxt3_acclim, xgmest, xejmxt3_acclim, xejmxt3
xvcmxt3 calls point2constants
total_photosynthesis_cost calls point2constants, xvcmxt3, xvcmxt3_acclim, xgmest, xejmxt3_acclim, xejmxt3
xvcmxt4_acclim calls point2constants
total_photosynthesis calls point2constants, xvcmxt3, xvcmxt3_acclim, xgmest, xejmxt3_acclim, xejmxt3
soil_snow calls point2constants
plantcarb calls point2constants
surface_albedo calls point2constants
ruff_resist calls point2constants
xvcmxt4 calls point2constants
optimise_jv calls point2constants, diff_ac_aj, total_photosynthesis_cost
cable_offline_driver calls point2constants, cbm, casa_feedback
xvcmxt3_acclim calls point2constants
total_an_ac_aj calls point2constants, xvcmxt3, xvcmxt3_acclim, xgmest, xejmxt3_acclim, xejmxt3
xgmest calls point2constants
xejmxt3_acclim calls point2constants
xejmxt3 calls point2constants
mpidrv_master calls point2constants
define_air calls point2constants
mpi_driver calls mpidrv_worker, mpidrv_master
dryleaf calls xvcmxt3, xvcmxt4_acclim, xvcmxt4, xvcmxt3_acclim, xgmest, xejmxt3_acclim, xejmxt3