dryLeaf – POP
dryLeaf Subroutine
448 statements
Source File
private subroutine dryLeaf(dels, rad, air, met, veg, canopy, soil, ssnow, dsx, fwsoil, tlfx, tlfy, ecy, hcy, rny, gbhu, gbhf, csx, cansat, ghwet, iter, climate)
Uses
cable_common_module
cable_def_types_mod
vh !! inserted min to avoid -ve values of GPP
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(radiation_type), intent(inout) :: rad
type(air_type), intent(inout) :: air
type(met_type), intent(inout) :: met
type(veg_parameter_type), intent(inout) :: veg
type(canopy_type), intent(inout) :: canopy
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
real, intent(inout), dimension(:) :: dsx
real, intent(inout), dimension(:) :: fwsoil
real, intent(inout), dimension(:) :: tlfx
real, intent(inout), dimension(:) :: tlfy
real(kind=r_2), intent(inout), dimension(:) :: ecy
real(kind=r_2), intent(inout), dimension(:) :: hcy
real(kind=r_2), intent(inout), dimension(:) :: rny
real(kind=r_2), intent(inout), dimension(:,:) :: gbhu
real(kind=r_2), intent(inout), dimension(:,:) :: gbhf
real(kind=r_2), intent(inout), dimension(:,:) :: csx
real, intent(in), dimension(:) :: cansat
real(kind=r_2), intent(out), dimension(:) :: ghwet
integer, intent(in) :: iter
type(climate_type), intent(in) :: climate
Calls
Called by
Contents
None
Call graph
dryleaf calls xejmxt3_acclim, xejmxt3, photosynthesis_gm, xgmest, xrdt, xvcmxt4, fwsoil_calc_std, fwsoil_calc_non_linear, xvcmxt3, fwsoil_calc_lai_katul, xvcmxt3_acclim, xvcmxt4_acclim, light_inhibition, getrex_1d, ej3x
xejmxt3_acclim calls point2constants
xejmxt3 calls point2constants
photosynthesis_gm calls fandan_c3, fandan_c4, famdam_c4, famdam_c3
xgmest calls point2constants
xvcmxt4 calls point2constants
xvcmxt3 calls point2constants
xvcmxt3_acclim calls point2constants
xvcmxt4_acclim calls point2constants
point2constants calls albedo_type_ptr, rough_type_ptr, driver_type_ptr, canopy_type_ptr, cbm_type_ptr, air_type_ptr, carbon_type_ptr, rad_type_ptr, ssnow_type_ptr
fandan_c3 calls fdan_c3, fdabc, fabc, fan_c3
fandan_c4 calls fabc_c4, fan_c4, fdan_c4, fdabc_c4
famdam_c4 calls fam_c4, fdam_c4, fdabcm, fabcm
famdam_c3 calls fam_c3, fpq, fdpq, fabcd, fdam_c3, fdabcd
define_canopy calls dryleaf
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker