ej3x – POP
ej3x Function
9 statements
Source File
public pure elemental function ej3x(parx, alpha, convex, x) result(z)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: parx
real, intent(in) :: alpha
real, intent(in) :: convex
real, intent(in) :: x
Return Value real
Called by
Contents
Call graph
diff_ac_aj calls ej3x
total_photosynthesis calls ej3x
total_photosynthesis_cost calls ej3x
dryleaf calls ej3x
total_an_ac_aj calls ej3x
optimise_jv calls diff_ac_aj, total_photosynthesis_cost
define_canopy calls dryleaf
casa_feedback calls optimise_jv
cbm calls define_canopy
mpidrv_worker calls casa_feedback, cbm
cable_offline_driver calls casa_feedback, cbm
mpi_driver calls mpidrv_worker