enorm – POP
enorm Function
8 statements
Source File
public function enorm(n, x)
************80
ENORM computes the Euclidean norm of a vector.
Arguments
Type Intent Optional Attributes Name
integer :: n
real(kind=r_2) :: x(n)
Return Value real(kind=r_2)
Called by
Contents
None
Call graph
dogleg calls enorm
hybrd calls enorm, dogleg, qrfac
qrfac calls enorm
lmder calls enorm, qrfac, lmpar
hybrj calls enorm, dogleg, qrfac
lmpar calls enorm
lmdif calls enorm, qrfac, lmpar
lmstr calls enorm, qrfac, lmpar
hybrd1 calls hybrd
hybrj1 calls hybrj
lmder1 calls lmder
lmdif1 calls lmdif
lmstr1 calls lmstr
adjust_jv_gm calls lmdif1
casa_feedback calls adjust_jv_gm
mpidrv_worker calls casa_feedback
cable_offline_driver calls casa_feedback
mpi_driver calls mpidrv_worker