enorm2 – POP
enorm2 Function
56 statements
Source File
public function enorm2(n, x)
************80
ENORM2 computes the Euclidean norm of a vector.
Arguments
Type Intent Optional Attributes Name
integer :: n
real(kind=r_2) :: x(n)
Return Value real(kind=r_2)
Calls
Contents
None
Call graph
enorm2 calls le, ne
le calls lesserequal_sp, lesserequal_dp
ne calls notequal_sp, notequal_dp