equal_sp – POP
equal_sp Function
11 statements
Source File
private pure elemental function equal_sp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: a
real(kind=sp), intent(in) :: b
Return Value logical
Called by
Contents
None
Call graph
eq calls equal_sp
equal calls equal_sp
gcf calls eq
casaonly_luc calls eq, pop_luc_casa_transfer, c13o2_update_luc, c13o2_update_pools, popdriver
cable_phenology_clim calls eq
isotope_pool_model_2d calls eq
cable_offline_driver calls eq, casaonly_luc, lucdriver, open_met_file, get_met_data, cable_bios_read_met, pop_luc_casa_transfer, cru_get_subdiurnal_met, plume_mip_get_met, cbm, bgcdriver, write_output, c13o2_update_luc, casa_feedback, spincasacnp, popdriver
interpolate_biomass_2d calls eq
lucdriver calls eq
chkder calls eq
hybrd calls eq, fdjac1, r1updt, dogleg
hybrj calls eq, r1updt, dogleg
open_met_file calls eq
fdjac2 calls eq
fdjac1 calls eq
qrsolv calls eq
getfluxes_vp_2d calls eq
r1updt calls eq
lmstr calls eq, lmpar
lmder calls eq, lmpar
get_met_data calls eq
isinloc_sp calls eq
cable_bios_read_met calls eq
gser calls eq
isotope_luc_model_1d calls eq
r8mat_print_some calls eq
getfluxes_vp_1d calls eq
define_canopy calls eq, sli_main
isotope_pool_model_1d calls eq
rtbis calls eq
lmpar calls eq, qrsolv
pop_luc_casa_transfer calls eq
isin_sp calls eq
dogleg calls eq
isosub calls eq
master_casaonly_luc calls eq, pop_luc_casa_transfer, c13o2_update_luc
cru_get_subdiurnal_met calls eq
isin_dp calls eq
rtbis_rh0 calls eq
mass_balance calls eq
isinloc_dp calls eq
lmdif calls eq, fdjac2, lmpar
plume_mip_get_met calls eq
cbm calls define_canopy, sli_main
isinloc calls isinloc_sp, isinloc_dp
r8mat_print calls r8mat_print_some
isotope_luc_model calls isotope_luc_model_1d
igamma calls gcf, gser
isotope_pool_model calls isotope_pool_model_2d, isotope_pool_model_1d
hybrd1 calls hybrd
getdiagnostics calls interpolate_biomass_2d
bgcdriver calls cable_phenology_clim, c13o2_update_pools
hybrj1 calls hybrj
mpidrv_master calls open_met_file, get_met_data, cable_bios_read_met, pop_luc_casa_transfer, lucdriver, master_casaonly_luc, cru_get_subdiurnal_met, plume_mip_get_met, write_output, c13o2_update_luc
getfluxes_vp calls getfluxes_vp_2d, getfluxes_vp_1d
lmstr1 calls lmstr
lmder1 calls lmder
lmdif1 calls lmdif
isin calls isin_sp, isin_dp
write_output calls mass_balance
optimise_jv calls rtbis
mpidrv_worker calls cbm, bgcdriver, casa_feedback, worker_spincasacnp, worker_casaonly_luc, popdriver
c13o2_update_luc calls isotope_luc_model, isotope_pool_model
c13o2_update_pools calls isotope_pool_model
hyofs calls igamma
popstep calls getdiagnostics
mpi_driver calls mpidrv_master, mpidrv_worker
get_fluxes_and_derivs calls getfluxes_vp
adjust_jv_gm calls lmdif1
casa_feedback calls optimise_jv, adjust_jv_gm
spincasacnp calls c13o2_update_pools, popdriver
iflux_loop calls hyofs, get_fluxes_and_derivs
worker_spincasacnp calls c13o2_update_pools, popdriver
sli_main calls hyofs, solve
worker_casaonly_luc calls c13o2_update_pools, popdriver
solve calls hyofs, timestep_loop
popdriver calls popstep
timestep_loop calls iflux_loop