equal_dp – POP
equal_dp Function
11 statements
Source File
private pure elemental function equal_dp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a
real(kind=dp), intent(in) :: b
Return Value logical
Called by
Contents
None
Call graph
eq calls equal_dp
equal calls equal_dp
hybrd calls eq, dogleg, r1updt, fdjac1
plume_mip_get_met calls eq
lucdriver calls eq
lmpar calls eq, qrsolv
getfluxes_vp_1d calls eq
isotope_luc_model_1d calls eq
cable_phenology_clim calls eq
lmstr calls eq, lmpar
rtbis calls eq
fdjac2 calls eq
casaonly_luc calls eq, pop_luc_casa_transfer, c13o2_update_pools, c13o2_update_luc, popdriver
cru_get_subdiurnal_met calls eq
chkder calls eq
pop_luc_casa_transfer calls eq
gser calls eq
isin_sp calls eq
r8mat_print_some calls eq
mass_balance calls eq
getfluxes_vp_2d calls eq
isin_dp calls eq
isinloc_dp calls eq
open_met_file calls eq
cable_offline_driver calls eq, plume_mip_get_met, lucdriver, casaonly_luc, cru_get_subdiurnal_met, pop_luc_casa_transfer, open_met_file, cable_bios_read_met, get_met_data, cbm, bgcdriver, write_output, c13o2_update_luc, casa_feedback, spincasacnp, popdriver
master_casaonly_luc calls eq, pop_luc_casa_transfer, c13o2_update_luc
define_canopy calls eq, sli_main
cable_bios_read_met calls eq
lmdif calls eq, lmpar, fdjac2
hybrj calls eq, dogleg, r1updt
isotope_pool_model_2d calls eq
isotope_pool_model_1d calls eq
dogleg calls eq
gcf calls eq
r1updt calls eq
lmder calls eq, lmpar
qrsolv calls eq
get_met_data calls eq
isosub calls eq
rtbis_rh0 calls eq
fdjac1 calls eq
isinloc_sp calls eq
interpolate_biomass_2d calls eq
isotope_pool_model calls isotope_pool_model_2d, isotope_pool_model_1d
isinloc calls isinloc_dp, isinloc_sp
cbm calls define_canopy, sli_main
lmdif1 calls lmdif
hybrj1 calls hybrj
getdiagnostics calls interpolate_biomass_2d
hybrd1 calls hybrd
mpidrv_master calls plume_mip_get_met, lucdriver, cru_get_subdiurnal_met, pop_luc_casa_transfer, open_met_file, master_casaonly_luc, cable_bios_read_met, get_met_data, write_output, c13o2_update_luc
isotope_luc_model calls isotope_luc_model_1d
bgcdriver calls cable_phenology_clim, c13o2_update_pools
getfluxes_vp calls getfluxes_vp_1d, getfluxes_vp_2d
lmstr1 calls lmstr
optimise_jv calls rtbis
igamma calls gser, gcf
isin calls isin_sp, isin_dp
r8mat_print calls r8mat_print_some
write_output calls mass_balance
lmder1 calls lmder
c13o2_update_pools calls isotope_pool_model
c13o2_update_luc calls isotope_pool_model, isotope_luc_model
mpidrv_worker calls cbm, bgcdriver, casa_feedback, worker_spincasacnp, worker_casaonly_luc, popdriver
adjust_jv_gm calls lmdif1
popstep calls getdiagnostics
mpi_driver calls mpidrv_master, mpidrv_worker
get_fluxes_and_derivs calls getfluxes_vp
casa_feedback calls optimise_jv, adjust_jv_gm
hyofs calls igamma
worker_spincasacnp calls c13o2_update_pools, popdriver
spincasacnp calls c13o2_update_pools, popdriver
iflux_loop calls get_fluxes_and_derivs, hyofs
worker_casaonly_luc calls c13o2_update_pools, popdriver
popdriver calls popstep
sli_main calls hyofs, solve
solve calls hyofs, timestep_loop
timestep_loop calls iflux_loop