extraRestart – POP
extraRestart Subroutine
117 statements
Source File
private subroutine extraRestart(INpatch, ssnow, canopy, bgc, bal, veg, rad, EMSOIL)
(BP Nov 2009)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: INpatch
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
type(bgc_pool_type), intent(inout) :: bgc
type(balances_type), intent(inout) :: bal
type(veg_parameter_type), intent(inout) :: veg
type(radiation_type), intent(inout) :: rad
real, intent(in) :: EMSOIL
Calls
Called by
Contents
None
Call graph
extrarestart calls nf90_inq_varid, nc_abort, readpar, nf90_get_var, redistr_r2d, redistr_r, redistr_r2, redistr_i, redistr_rd
nc_abort calls nf90_strerror, mpi_abort
readpar calls readpar_i, readpar_r2d, readpar_r, readpar_rd, readpar_r2
redistr_r2d calls mpi_abort, float
redistr_r calls mpi_abort, float
redistr_r2 calls mpi_abort, float
redistr_i calls mpi_abort
redistr_rd calls mpi_abort, float
readpar_i calls nf90_inq_varid, nc_abort, nf90_get_var, cable_abort, nf90_inquire_variable
readpar_r2d calls nf90_inq_varid, nc_abort, nf90_get_var, cable_abort, nf90_inquire_variable
readpar_r calls nf90_inq_varid, nc_abort, nf90_get_var, cable_abort, nf90_inquire_variable
readpar_rd calls nf90_inq_varid, nc_abort, nf90_get_var, cable_abort, nf90_inquire_variable
readpar_r2 calls nf90_inq_varid, nc_abort, nf90_get_var, cable_abort, nf90_inquire_variable
cable_abort calls mpi_abort
get_restart_data calls extrarestart
load_parameters calls get_restart_data
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master