fAm_c3 – POP
fAm_c3 Subroutine
12 statements
Source File
public subroutine fAm_c3(a, b, c1, d, p, q, Am)
Uses
cable_def_types_mod
mo_constants
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: a
real(kind=r_2), intent(in) :: b
real(kind=r_2), intent(in) :: c1
real(kind=r_2), intent(in) :: d
real(kind=r_2), intent(in) :: p
real(kind=r_2), intent(in) :: q
real(kind=r_2), intent(out) :: Am
Called by
Contents
Call graph
total_photosynthesis_cost calls fam_c3
total_photosynthesis calls fam_c3
total_an_ac_aj calls fam_c3
diff_ac_aj calls fam_c3
optimise_jv calls total_photosynthesis_cost, diff_ac_aj
casa_feedback calls optimise_jv