fAm_c3 – POP
fAm_c3 Subroutine
12 statements
Source File
private pure elemental subroutine fAm_c3(a, b, c1, d, p, q, Am)
Uses
mo_constants
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: a
real(kind=r_2), intent(in) :: b
real(kind=r_2), intent(in) :: c1
real(kind=r_2), intent(in) :: d
real(kind=r_2), intent(in) :: p
real(kind=r_2), intent(in) :: q
real(kind=r_2), intent(out) :: Am
Called by
Contents
None
Call graph
famdam_c3 calls fam_c3
photosynthesis_gm calls famdam_c3
dryleaf calls photosynthesis_gm
define_canopy calls dryleaf
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker