fAn_c3 – POP
fAn_c3 Subroutine
9 statements
Source File
public subroutine fAn_c3(a, b, c, A2)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: a
real(kind=r_2), intent(in) :: b
real(kind=r_2), intent(in) :: c
real(kind=r_2), intent(out) :: A2
Called by
Contents
None
Call graph
diff_ac_aj calls fan_c3
total_photosynthesis_cost calls fan_c3
total_an_ac_aj calls fan_c3
total_photosynthesis calls fan_c3
optimise_jv calls diff_ac_aj, total_photosynthesis_cost
casa_feedback calls optimise_jv
mpidrv_worker calls casa_feedback
cable_offline_driver calls casa_feedback
mpi_driver calls mpidrv_worker