GEDates – POP
GEDates Function
7 statements
Source File
public function GEDates(Date1, Date2)
Arguments
Type Intent Optional Attributes Name
type(dmydate), intent(in) :: Date1
type(dmydate), intent(in) :: Date2
Return Value logical
Calls
Called by
Contents
Call graph
gedates calls gtdates, eqdates
gtdates calls julianday
operator (gt=) calls gedates