GET_ALLOMETRY – POP
GET_ALLOMETRY Subroutine
23 statements
Source File
public subroutine GET_ALLOMETRY(ALLOM_SWITCH, biomass, density, ht, diam, basal, precip)
Arguments
Type Intent Optional Attributes Name
integer(kind=i4b), intent(in) :: ALLOM_SWITCH
real(kind=dp), intent(in) :: biomass
real(kind=dp), intent(in) :: density
real(kind=dp), intent(out) :: ht
real(kind=dp), intent(out) :: diam
real(kind=dp), intent(out) :: basal
real(kind=dp), intent(in), optional :: precip
Calls
Called by
Contents
Call graph
get_allometry calls getheight, williams_allometry, allometry
patchannualdynamics calls get_allometry, layer_recruitment
layer_recruitment calls get_allometry
layer_recruitment_single_patch calls get_allometry
getdiagnostics calls get_allometry
popstep calls patchannualdynamics, getdiagnostics, patch_disturb
pop_init_single calls layer_recruitment_single_patch
patch_disturb calls layer_recruitment_single_patch
pop_init calls layer_recruitment_single_patch
popdriver calls popstep
casaonly_luc calls pop_init_single, popdriver
popluc_init calls pop_init_single
spincasacnp calls popdriver