get_var_ncr2 – POP
get_var_ncr2 Subroutine
14 statements
Source File
public subroutine get_var_ncr2(ncid, var_name, var, n_call)
Uses
netcdf
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: var_name
real(kind=r_2), intent(out), dimension(:) :: var
integer, intent(in) :: n_call
Calls
Called by
Contents
Call graph
get_var_ncr2 calls nf90_inq_varid, nf90_get_var, stderr_nc
stderr_nc calls nf90_strerror
get_var_nc calls get_var_ncr2
read_casa_dump calls get_var_nc
master_spincasacnp calls read_casa_dump
master_casaonly_luc calls read_casa_dump
spincasacnp calls read_casa_dump
cable_offline_driver calls read_casa_dump, spincasacnp, casaonly_luc
casaonly_luc calls read_casa_dump
mpidrv_master calls master_spincasacnp, master_casaonly_luc
mpi_driver calls mpidrv_master