get_default_lai – POP
get_default_lai Subroutine
69 statements
Source File
public subroutine get_default_lai()
Arguments
None
Calls
Contents
None
Call graph
get_default_lai calls nf90_open, nf90_inquire_dimension, cable_abort, nf90_inq_dimid, nc_abort, nf90_inq_varid, nf90_get_var, nf90_close
cable_abort calls mpi_abort
nc_abort calls mpi_abort, nf90_strerror