get_parameters_met – POP
get_parameters_met Subroutine
60 statements
Source File
private subroutine get_parameters_met(soil, veg, bgc, rough, completeSet)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
type(bgc_pool_type), intent(inout) :: bgc
type(roughness_type), intent(inout) :: rough
logical, intent(out) :: completeSet
Calls
Called by
Contents
Call graph
get_parameters_met calls readpar, nf90_inq_varid
readpar calls readpar_i, readpar_rd, readpar_r2d, readpar_r2, readpar_r
readpar_i calls nf90_inq_varid, cable_abort, nf90_get_var, nc_abort, nf90_inquire_variable
readpar_rd calls nf90_inq_varid, cable_abort, nf90_get_var, nc_abort, nf90_inquire_variable
readpar_r2d calls nf90_inq_varid, cable_abort, nf90_get_var, nc_abort, nf90_inquire_variable
readpar_r2 calls nf90_inq_varid, cable_abort, nf90_get_var, nc_abort, nf90_inquire_variable
readpar_r calls nf90_inq_varid, cable_abort, nf90_get_var, nc_abort, nf90_inquire_variable
nc_abort calls nf90_strerror
load_parameters calls get_parameters_met
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master