GET_PLUME_Ndep – POP
GET_PLUME_Ndep Subroutine
45 statements
Source File
public subroutine GET_PLUME_Ndep(PLUME)
Arguments
Type Intent Optional Attributes Name
type(PLUME_MIP_TYPE), intent(inout) :: PLUME
Calls
Called by
Contents
None
Call graph
get_plume_ndep calls nf90_open, nf90_inq_varid, handle_err, nf90_get_var
handle_err calls nf90_strerror
plume_mip_get_met calls get_plume_ndep
mpidrv_master calls plume_mip_get_met
cable_offline_driver calls plume_mip_get_met
mpi_driver calls mpidrv_master