get_met_data – POP
get_met_data Subroutine
534 statements
Source File
public subroutine get_met_data(spinup, spinConv, met, rad, veg, dels, TFRZ, ktau, kstart)
Uses
mpi
mo_utils
vh_js !! use is_leapyear function here instead of multiple conditions vh_js !! corrected indices of defaultLAI
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: spinup
logical, intent(in) :: spinConv
type(met_type), intent(inout) :: met
type(radiation_type), intent(in) :: rad
type(veg_parameter_type), intent(inout) :: veg
real, intent(in) :: dels
real, intent(in) :: TFRZ
integer, intent(in) :: ktau
integer, intent(in) :: kstart
Calls
Called by
Contents
None
Call graph
get_met_data calls cable_abort, nf90_get_var, is_leapyear, nc_abort, eq, rh_sh, mpi_abort, sinbet
cable_abort calls mpi_abort
nc_abort calls mpi_abort, nf90_strerror
eq calls equal_dp, equal_sp
mpidrv_master calls get_met_data
cable_offline_driver calls get_met_data
mpi_driver calls mpidrv_master