get_default_params – POP
get_default_params Subroutine
32 statements
Source File
public subroutine get_default_params(logn, vegparmnew, LUC_EXPT)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: logn
logical, intent(in) :: vegparmnew
type(luc_expt_type), intent(inout) :: LUC_EXPT
Calls
Called by
Contents
None
Call graph
get_default_params calls get_type_parameters, read_gridinfo, get_land_index, luc_expt_set_tiles_bios, luc_expt_set_tiles, spatialsoil, read_soilcolor, countpatch
get_type_parameters calls mpi_abort
read_gridinfo calls nf90_inquire_dimension, cable_abort, nf90_inq_dimid, nf90_open, nc_abort, nf90_inq_varid, nf90_get_var, nf90_close
get_land_index calls mpi_abort
luc_expt_set_tiles_bios calls cable_bios_load_fracc4
spatialsoil calls nf90_open, nc_abort, nf90_inq_varid, nf90_get_var, nf90_close
read_soilcolor calls nf90_inquire_dimension, nf90_inq_dimid, nf90_open, nc_abort, nf90_inq_varid, nf90_get_var, nf90_close, ne
countpatch calls mpi_abort
cable_abort calls mpi_abort
nc_abort calls mpi_abort, nf90_strerror
cable_bios_load_fracc4 calls get_unit
ne calls notequal_sp, notequal_dp
load_parameters calls get_default_params
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master