get_unit – POP
get_unit Subroutine
11 statements
Source File
public subroutine get_unit(iunit)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: iunit
Called by
Contents
None
Call graph
luc_expt_init calls get_unit, cable_bios_load_biome
cable_bios_load_biome calls get_unit
site_get_co2_ndep calls get_unit
cable_bios_load_fracc4 calls get_unit
cable_bios_load_climate_params calls get_unit
get_plume_co2 calls get_unit
cable_offline_driver calls get_unit, luc_expt_init, site_get_co2_ndep, cable_bios_load_climate_params, site_init, ini_blaze, ini_simfire, cable_bios_init, plume_mip_init, cable_bios_load_params, cru_init, plume_mip_get_met, cru_get_subdiurnal_met, load_parameters, blaze_driver, spincasacnp
get_popdens calls get_unit
site_init calls get_unit
ini_blaze calls get_unit
ini_simfire calls get_unit
cable_bios_init calls get_unit
mpidrv_master calls get_unit, luc_expt_init, cable_bios_load_climate_params, ini_blaze, ini_simfire, cable_bios_init, plume_mip_init, cable_bios_load_params, cru_init, plume_mip_get_met, cru_get_subdiurnal_met, load_parameters
plume_mip_init calls get_unit
cable_bios_load_params calls get_unit
get_cru_co2 calls get_unit
cru_init calls get_unit
luc_expt_set_tiles_bios calls cable_bios_load_fracc4
simfire calls get_popdens
mpidrv_worker calls ini_blaze, ini_simfire, blaze_driver, worker_spincasacnp
mpi_driver calls mpidrv_master, mpidrv_worker
plume_mip_get_met calls get_plume_co2
cru_get_subdiurnal_met calls get_cru_co2
get_default_params calls luc_expt_set_tiles_bios
run_blaze calls simfire
load_parameters calls get_default_params
blaze_driver calls run_blaze
spincasacnp calls blaze_driver
worker_spincasacnp calls blaze_driver