GetDiagnostics – POP
GetDiagnostics Subroutine
273 statements
Source File
public subroutine GetDiagnostics(POP, LAI, Cleaf, Croot, disturbance_interval, it, precip)
assumes crown radius (m) = 0.1492 * dbh (cm) (from G. Cook, pers. comm.)
global allometry
assumes crown radius (m) = 0.1492 * dbh (cm) (from G. Cook, pers. comm.) global allometry
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
real(kind=dp), intent(in) :: LAI(:)
real(kind=dp), intent(in) :: Cleaf(:)
real(kind=dp), intent(in) :: Croot(:)
integer(kind=i4b), intent(in) :: disturbance_interval(:,:)
integer(kind=i4b), intent(in) :: it(:)
real(kind=dp), intent(in), optional :: precip(:)
Calls
Called by
Contents
Call graph
getdiagnostics calls get_allometry, interpolate_biomass_2d, smooth_flux, interpolate_biomass_1d
get_allometry calls getheight, allometry, williams_allometry
interpolate_biomass_2d calls realexponential, area_triangle, eq
smooth_flux calls regress
interpolate_biomass_1d calls realexponential
eq calls equal_sp, equal_dp
popstep calls getdiagnostics
popdriver calls popstep
worker_spincasacnp calls popdriver
mpidrv_worker calls popdriver, worker_spincasacnp, worker_casaonly_luc
worker_casaonly_luc calls popdriver
spincasacnp calls popdriver
casaonly_luc calls popdriver
cable_offline_driver calls popdriver, spincasacnp, casaonly_luc
mpi_driver calls mpidrv_worker