greaterequal_sp – POP
greaterequal_sp Function
8 statements
Source File
private pure elemental function greaterequal_sp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: a
real(kind=sp), intent(in) :: b
Return Value logical
Called by
Contents
None
Call graph
ge calls greaterequal_sp
greaterequal calls greaterequal_sp
chkder calls ge
casa_xrateplant calls ge
lmdif calls ge
lmstr calls ge
lmder calls ge
cable_phenology_clim calls ge
rtbis calls ge
biogeochem calls casa_xrateplant
lmder1 calls lmder
lmdif1 calls lmdif
lmstr1 calls lmstr
bgcdriver calls cable_phenology_clim, biogeochem
optimise_jv calls rtbis
worker_casaonly_luc calls biogeochem
adjust_jv_gm calls lmdif1
worker_spincasacnp calls biogeochem
spincasacnp calls biogeochem
casaonly_luc calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp, casa_feedback
cable_offline_driver calls bgcdriver, spincasacnp, casaonly_luc, casa_feedback
casa_feedback calls optimise_jv, adjust_jv_gm
mpi_driver calls mpidrv_worker