greaterequal_dp – POP
greaterequal_dp Function
8 statements
Source File
private pure elemental function greaterequal_dp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a
real(kind=dp), intent(in) :: b
Return Value logical
Called by
Contents
None
Call graph
ge calls greaterequal_dp
greaterequal calls greaterequal_dp
chkder calls ge
lmdif calls ge
lmder calls ge
casa_xrateplant calls ge
lmstr calls ge
cable_phenology_clim calls ge
rtbis calls ge
lmdif1 calls lmdif
lmstr1 calls lmstr
lmder1 calls lmder
biogeochem calls casa_xrateplant
bgcdriver calls cable_phenology_clim, biogeochem
optimise_jv calls rtbis
adjust_jv_gm calls lmdif1
spincasacnp calls biogeochem
worker_spincasacnp calls biogeochem
casaonly_luc calls biogeochem
worker_casaonly_luc calls biogeochem
mpidrv_worker calls bgcdriver, worker_spincasacnp, worker_casaonly_luc, casa_feedback
cable_offline_driver calls bgcdriver, spincasacnp, casaonly_luc, casa_feedback
casa_feedback calls optimise_jv, adjust_jv_gm
mpi_driver calls mpidrv_worker