hybrj – POP
hybrj Subroutine
305 statements
Source File
public subroutine hybrj(fcn, n, x, fvec, fjac, ldfjac, xtol, maxfev, diag, mode, factor, nprint, info, nfev, njev, r, lr, qtf)
************80
HYBRJ seeks a zero of N nonlinear equations in N variables.
Arguments
Type Intent Optional Attributes Name
real :: fcn
integer :: n
real(kind=r_2) :: x(n)
real(kind=r_2) :: fvec(n)
real(kind=r_2) :: fjac(ldfjac,n)
integer :: ldfjac
real(kind=r_2) :: xtol
integer :: maxfev
real(kind=r_2) :: diag(n)
integer :: mode
real(kind=r_2) :: factor
integer :: nprint
integer :: info
integer :: nfev
integer :: njev
real(kind=r_2) :: r(lr)
integer :: lr
real(kind=r_2) :: qtf(n)
Calls
Called by
Contents
None
Call graph
hybrj calls le, eq, qrfac, ne, enorm, qform, dogleg, r1updt, r1mpyq
le calls lesserequal_sp, lesserequal_dp
eq calls equal_sp, equal_dp
qrfac calls le, ne, enorm
ne calls notequal_sp, notequal_dp
qform calls ne
dogleg calls le, eq, ne, enorm
r1updt calls eq, ne
hybrj1 calls hybrj