hybrj1 – POP
hybrj1 Subroutine
42 statements
Source File
public subroutine hybrj1(fcn, n, x, fvec, fjac, ldfjac, tol, info)
************80
HYBRJ1 seeks a zero of N equations in N variables by Powell's method.
Arguments
Type Intent Optional Attributes Name
real :: fcn
integer :: n
real(kind=r_2) :: x(n)
real(kind=r_2) :: fvec(n)
real(kind=r_2) :: fjac(ldfjac,n)
integer :: ldfjac
real(kind=r_2) :: tol
integer :: info
Calls
Contents
None
Call graph
hybrj1 calls hybrj
hybrj calls le, ne, qrfac, eq, enorm, qform, dogleg, r1updt, r1mpyq
le calls lesserequal_sp, lesserequal_dp
ne calls notequal_sp, notequal_dp
qrfac calls le, ne, enorm
eq calls equal_sp, equal_dp
qform calls ne
dogleg calls le, ne, eq, enorm
r1updt calls ne, eq