hybrd1 – POP
hybrd1 Subroutine
53 statements
Source File
public subroutine hybrd1(fcn, n, x, fvec, tol, info)
************80
HYBRD1 seeks a zero of N nonlinear equations in N variables.
Arguments
Type Intent Optional Attributes Name
real :: fcn
integer :: n
real(kind=r_2) :: x(n)
real(kind=r_2) :: fvec(n)
real(kind=r_2) :: tol
integer :: info
Calls
Contents
None
Call graph
hybrd1 calls hybrd
hybrd calls le, qrfac, enorm, eq, fdjac1, ne, qform, dogleg, r1updt, r1mpyq
le calls lesserequal_sp, lesserequal_dp
qrfac calls le, enorm, ne
eq calls equal_sp, equal_dp
fdjac1 calls eq
ne calls notequal_sp, notequal_dp
qform calls ne
dogleg calls le, enorm, eq, ne
r1updt calls eq, ne