hybrd – POP
hybrd Subroutine
271 statements
Source File
public subroutine hybrd(fcn, n, x, fvec, xtol, maxfev, ml, mu, epsfcn, diag, mode, factor, nprint, info, nfev, fjac, ldfjac, r, lr, qtf)
************80
HYBRD seeks a zero of N nonlinear equations in N variables.
Arguments
Type Intent Optional Attributes Name
real :: fcn
integer :: n
real(kind=r_2) :: x(n)
real(kind=r_2) :: fvec(n)
real(kind=r_2) :: xtol
integer :: maxfev
integer :: ml
integer :: mu
real(kind=r_2) :: epsfcn
real(kind=r_2) :: diag(n)
integer :: mode
real(kind=r_2) :: factor
integer :: nprint
integer :: info
integer :: nfev
real(kind=r_2) :: fjac(ldfjac,n)
integer :: ldfjac
real(kind=r_2) :: r(lr)
integer :: lr
real(kind=r_2) :: qtf(n)
Calls
Called by
Contents
None
Call graph
hybrd calls le, enorm, qrfac, eq, fdjac1, ne, qform, dogleg, r1updt, r1mpyq
le calls lesserequal_sp, lesserequal_dp
qrfac calls le, enorm, ne
eq calls equal_sp, equal_dp
fdjac1 calls eq
ne calls notequal_sp, notequal_dp
qform calls ne
dogleg calls le, enorm, eq, ne
r1updt calls eq, ne
hybrd1 calls hybrd