INI_SIMFIRE – POP
INI_SIMFIRE Subroutine
84 statements
Source File
public subroutine INI_SIMFIRE(NCELLS, SF, modis_igbp)
Uses
netcdf
cable_IO_vars_module
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: NCELLS
type(TYPE_SIMFIRE), intent(inout) :: SF
integer, intent(in) :: modis_igbp(NCELLS)
Calls
Called by
Contents
Call graph
ini_simfire calls zero_simfire, get_unit, nf90_inq_varid, nf90_open, handle_err, nf90_get_var, nf90_close
handle_err calls nf90_strerror
mpidrv_worker calls ini_simfire
cable_offline_driver calls ini_simfire
mpidrv_master calls ini_simfire
mpi_driver calls mpidrv_worker, mpidrv_master