InitPOP2D_Poisson – POP
InitPOP2D_Poisson Subroutine
83 statements
Source File
public subroutine InitPOP2D_Poisson(POP, mean_disturbance_interval, m)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: mean_disturbance_interval(:,:)
integer(kind=i4b), intent(in), optional :: m
Calls
Called by
Contents
Call graph
initpop2d_poisson calls exponential, cumexponential
pop_init_single calls initpop2d_poisson
pop_init calls initpop2d_poisson
lucdriver calls pop_init_single
master_casaonly_luc calls pop_init_single
popluc_init calls pop_init_single
casaonly_luc calls pop_init_single
worker_pop_types calls pop_init
load_parameters calls pop_init, popluc_init
cable_offline_driver calls lucdriver, casaonly_luc, load_parameters
mpidrv_worker calls worker_pop_types
mpidrv_master calls master_casaonly_luc, lucdriver, load_parameters
mpi_driver calls mpidrv_worker, mpidrv_master