IS_CASA_TIME – POP
IS_CASA_TIME Function
47 statements
Source File
public function IS_CASA_TIME(iotype, yyyy, ktau, kstart, koffset, ktauday, logn)
Uses
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: iotype*5
integer, intent(in) :: yyyy
integer, intent(in) :: ktau
integer, intent(in) :: kstart
integer, intent(in) :: koffset
integer, intent(in) :: ktauday
integer, intent(in) :: logn
Return Value logical
Calls
Called by
Contents
Call graph
is_casa_time calls is_leapyear
mpidrv_worker calls is_casa_time
cable_offline_driver calls is_casa_time, casaonly_luc
casaonly_luc calls is_casa_time
mpidrv_master calls is_casa_time
mpi_driver calls mpidrv_worker, mpidrv_master