is_finite_sp – POP
is_finite_sp Function
8 statements
Source File
private pure elemental function is_finite_sp(a)
Uses
ieee_arithmetic
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: a
Return Value logical
Calls
Called by
Contents
Call graph
is_finite_sp calls is_nan
is_nan calls is_nan_sp, is_nan_dp
is_finite calls is_finite_sp
is_normal_dp calls is_finite
is_normal_sp calls is_finite
is_normal calls is_normal_dp, is_normal_sp