is_leapyear – POP
is_leapyear Function
7 statements
Source File
public pure elemental function is_leapyear(yyyy)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: yyyy
Return Value logical
Called by
Contents
None
Call graph
open_met_file calls is_leapyear, doysod2ymdhms, ymdhms2doysod
mpidrv_worker calls is_leapyear, blaze_driver, is_casa_time, worker_spincasacnp
run_blaze calls is_leapyear, doysod2ymdhms, simfire
blaze_driver calls is_leapyear, run_blaze, doysod2ymdhms
is_casa_time calls is_leapyear
get_met_data calls is_leapyear
doysod2ymdhms calls is_leapyear
simfire calls is_leapyear
burntime calls is_leapyear, doysod2ymdhms
leap_day calls is_leapyear
ymdhms2doysod calls is_leapyear
mpidrv_master calls is_leapyear, open_met_file, is_casa_time, get_met_data, write_output, plume_mip_get_met, cru_get_subdiurnal_met
cable_offline_driver calls is_leapyear, open_met_file, blaze_driver, is_casa_time, get_met_data, write_output, plume_mip_get_met, casaonly_luc, spincasacnp, cru_get_subdiurnal_met
write_output calls is_leapyear
mpi_driver calls mpidrv_worker, mpidrv_master
worker_spincasacnp calls blaze_driver
plume_mip_get_met calls doysod2ymdhms, open_plume_met
casaonly_luc calls is_casa_time
spincasacnp calls blaze_driver
cru_get_subdiurnal_met calls doysod2ymdhms
open_plume_met calls leap_day