is_normal_dp – POP
is_normal_dp Function
8 statements
Source File
private pure elemental function is_normal_dp(a)
Uses
ieee_arithmetic
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a
Return Value logical
Calls
Called by
Contents
None
Call graph
is_normal_dp calls is_finite
is_finite calls is_finite_sp, is_finite_dp
is_finite_sp calls is_nan
is_finite_dp calls is_nan
is_nan calls is_nan_sp, is_nan_dp
is_normal calls is_normal_dp