isosanity – POP
isosanity Subroutine
30 statements
Source File
public pure elemental subroutine isosanity(rare, abundant, precision, absolute)
\brief Set rare and abundant isotope composition to zero if any of the two is less than epsilon. \details If either the rare or the abundant concentration is less than a given precision, both concentrations are set to zero. The default precision is epsilon of the kind. The test can be done on the absolute of the concentrations if negative compositions are possible. \param[inout] "real(dp) :: rare" Rare isotope concentration \param[inout] "real(dp) :: abundant" Abundant isotope concentration \param[in] "real(dp), optional :: precision" Set rare and abundant to 0 if any of the two is < precision. Default: epsilon(1.0_dp) \param[in] "logical, optional :: absolute" If .true.: check abs(rare) and abs(abundant) < precision Default: .false. \author Written Matthias Cuntz \date May 2020
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: rare
real(kind=dp), intent(inout) :: abundant
real(kind=dp), intent(in), optional :: precision
logical, intent(in), optional :: absolute
Called by
Contents
None
Call graph
c13o2_sanity_pools calls isosanity
c13o2_sanity_luc calls isosanity
spincasacnp calls c13o2_sanity_pools
master_casaonly_luc calls c13o2_sanity_pools, c13o2_sanity_luc
mpidrv_master calls c13o2_sanity_pools, c13o2_sanity_luc, master_casaonly_luc, master_spincasacnp
worker_spincasacnp calls c13o2_sanity_pools
master_spincasacnp calls c13o2_sanity_pools
mpidrv_worker calls c13o2_sanity_pools, worker_spincasacnp, worker_casaonly_luc
worker_casaonly_luc calls c13o2_sanity_pools
cable_offline_driver calls c13o2_sanity_pools, c13o2_sanity_luc, spincasacnp
mpi_driver calls mpidrv_master, mpidrv_worker