isotope_vap – POP
isotope_vap Subroutine
413 statements
Source File
private subroutine isotope_vap(irec, isotopologue, n, nsnow, nsnow_last, ns, dx, deltaz, sig, dt, Tsoil0, dTsoil, Sliqice, deltaSliqice, Sliq, deltaSliq, Sice, deltaSice, Ts, Ta, qsig, qlsig, qvsig, qmelt, qtransfer, qprec, qprec_snow, qevap, qrunoff, qex, var_cv, var_Dv, thetasat, thetar, tortuosity, deltacv, rbw, cva, civa, cprec, cprec_snow, cali, ql0, qv0, ciso, cisoice, cisos, qiso_in, qiso_out, qiso_evap, qiso_trans, qiso_liq_adv, qiso_vap_adv, qiso_liq_diff, qiso_vap_diff)
vh ???? !! !vh!!! NB thetasat should be (thetasat-thetar)??
Arguments
Type Intent Optional Attributes Name
integer(kind=i_d), intent(in) :: irec
integer(kind=i_d), intent(in) :: isotopologue
integer(kind=i_d), intent(in) :: n
integer(kind=i_d), intent(in) :: nsnow
integer(kind=i_d), intent(in) :: nsnow_last
integer(kind=i_d), intent(in) :: ns
real(kind=r_2), intent(in), DIMENSION(ns:n) :: dx
real(kind=r_2), intent(in), DIMENSION(ns:n-1) :: deltaz
real(kind=r_2), intent(in) :: sig
real(kind=r_2), intent(in) :: dt
real(kind=r_2), intent(in), DIMENSION(ns:n) :: Tsoil0
real(kind=r_2), intent(in), DIMENSION(ns:n) :: dTsoil
real(kind=r_2), intent(in), DIMENSION(ns:n) :: Sliqice
real(kind=r_2), intent(in), DIMENSION(ns:n) :: deltaSliqice
real(kind=r_2), intent(in), DIMENSION(ns:n) :: Sliq
real(kind=r_2), intent(in), DIMENSION(ns:n) :: deltaSliq
real(kind=r_2), intent(in), DIMENSION(ns:n) :: Sice
real(kind=r_2), intent(in), DIMENSION(ns:n) :: deltaSice
real(kind=r_2), intent(in) :: Ts
real(kind=r_2), intent(in) :: Ta
real(kind=r_2), intent(in), DIMENSION(ns-1:n) :: qsig
real(kind=r_2), intent(inout), DIMENSION(ns-1:n) :: qlsig
real(kind=r_2), intent(inout), DIMENSION(ns-1:n) :: qvsig
real(kind=r_2), intent(in) :: qmelt
real(kind=r_2), intent(in) :: qtransfer
real(kind=r_2), intent(in) :: qprec
real(kind=r_2), intent(in) :: qprec_snow
real(kind=r_2), intent(in) :: qevap
real(kind=r_2), intent(in) :: qrunoff
real(kind=r_2), intent(in), DIMENSION(1:n) :: qex
real(kind=r_2), intent(in), DIMENSION(ns:n) :: var_cv
real(kind=r_2), intent(in), DIMENSION(ns:n) :: var_Dv
real(kind=r_2), intent(in), DIMENSION(ns:n) :: thetasat
real(kind=r_2), intent(in), DIMENSION(ns:n) :: thetar
real(kind=r_2), intent(in), DIMENSION(ns:n) :: tortuosity
real(kind=r_2), intent(inout), DIMENSION(ns:n) :: deltacv
real(kind=r_2), intent(in) :: rbw
real(kind=r_2), intent(in) :: cva
real(kind=r_2), intent(in) :: civa
real(kind=r_2), intent(in) :: cprec
real(kind=r_2), intent(in) :: cprec_snow
real(kind=r_2), intent(in) :: cali
real(kind=r_2), intent(inout) :: ql0
real(kind=r_2), intent(inout) :: qv0
real(kind=r_2), intent(inout), DIMENSION(ns:n) :: ciso
real(kind=r_2), intent(inout), DIMENSION(ns:n) :: cisoice
real(kind=r_2), intent(inout) :: cisos
real(kind=r_2), intent(out) :: qiso_in
real(kind=r_2), intent(out) :: qiso_out
real(kind=r_2), intent(out) :: qiso_evap
real(kind=r_2), intent(out) :: qiso_trans
real(kind=r_2), intent(out), DIMENSION(ns:n) :: qiso_liq_adv
real(kind=r_2), intent(out), DIMENSION(ns:n) :: qiso_vap_adv
real(kind=r_2), intent(out), DIMENSION(ns:n-1) :: qiso_liq_diff
real(kind=r_2), intent(out), DIMENSION(ns:n-1) :: qiso_vap_diff
Calls
Called by
Contents
Call graph
isotope_vap calls ne, tri
ne calls notequal_sp, notequal_dp
tri calls tri_2d, tri_1d
timestep_loop calls isotope_vap
solve calls timestep_loop
sli_main calls solve
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker