isotope_luc_model_1d – POP
isotope_luc_model_1d Subroutine
93 statements
Source File
private subroutine isotope_luc_model_1d(Ciso, A, dA, C, S, Rs, T, Rt, At, trash)
Uses
mpi
mo_utils
mo_kind
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout), dimension(:) :: Ciso
real(kind=dp), intent(in), dimension(:) :: A
real(kind=dp), intent(in), dimension(:,:) :: dA
real(kind=dp), intent(in), optional dimension(:) :: C
real(kind=dp), intent(in), optional dimension(:) :: S
real(kind=dp), intent(in), optional dimension(:) :: Rs
real(kind=dp), intent(in), optional dimension(:) :: T
real(kind=dp), intent(in), optional dimension(:) :: Rt
real(kind=dp), intent(in), optional dimension(:) :: At
real(kind=dp), intent(inout), optional dimension(:) :: trash
Calls
Called by
Contents
None
Call graph
isotope_luc_model_1d calls mpi_abort, eq
eq calls equal_sp, equal_dp
isotope_luc_model calls isotope_luc_model_1d
c13o2_update_luc calls isotope_luc_model
casaonly_luc calls c13o2_update_luc
master_casaonly_luc calls c13o2_update_luc
cable_offline_driver calls c13o2_update_luc, casaonly_luc
mpidrv_master calls c13o2_update_luc, master_casaonly_luc
mpi_driver calls mpidrv_master