JSoilLayer – POP
JSoilLayer Function
13 statements
Source File
public pure elemental function JSoilLayer(T, dx, theta, csoil, rhosoil, h0, thre, the, he, b)
Uses
sli_numbers
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: T
real(kind=r_2), intent(in) :: dx
real(kind=r_2), intent(in) :: theta
real(kind=r_2), intent(in) :: csoil
real(kind=r_2), intent(in) :: rhosoil
real(kind=r_2), intent(in) :: h0
real(kind=r_2), intent(in) :: thre
real(kind=r_2), intent(in) :: the
real(kind=r_2), intent(in) :: he
real(kind=r_2), intent(in) :: b
Return Value real(kind=r_2)
Calls
Called by
Contents
Call graph
jsoillayer calls tfrz
snow_adjust calls jsoillayer
update_unknowns calls jsoillayer
update_s_t calls jsoillayer
iflux_loop calls snow_adjust, update_unknowns, update_s_t
timestep_loop calls iflux_loop
solve calls timestep_loop
sli_main calls solve
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker