JulianDay – POP
JulianDay Function
14 statements
Source File
public function JulianDay(GregDate)
Arguments
Type Intent Optional Attributes Name
type(dmydate), intent(in) :: GregDate
Return Value real(kind=dp)
Called by
Contents
None
Call graph
daydifference calls julianday
addday calls julianday
subday calls julianday
ltdates calls julianday
gtdates calls julianday
cable_bios_init calls daydifference
ledates calls ltdates
operator (+) calls addday
cable_bios_read_met calls daydifference
operator (lt) calls ltdates
gedates calls gtdates
operator (gt) calls gtdates
mpidrv_master calls cable_bios_init, cable_bios_read_met
cable_offline_driver calls cable_bios_init, cable_bios_read_met
operator (lt=) calls ledates
operator (gt=) calls gedates
mpi_driver calls mpidrv_master