lesserequal_sp – POP
lesserequal_sp Function
8 statements
Source File
private pure elemental function lesserequal_sp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: a
real(kind=sp), intent(in) :: b
Return Value logical
Called by
Contents
None
Call graph
le calls lesserequal_sp
lesserequal calls lesserequal_sp
lmder calls le, lmpar, qrfac
lmpar calls le
lmdif calls le, lmpar, qrfac
locate_0d_dp calls le
rtbis calls le
locate_1d_dp calls le
locate_0d_sp calls le
casa_xrateplant calls le
enorm2 calls le
hybrd calls le, qrfac, dogleg
qrfac calls le
dogleg calls le
chkder calls le
locate_1d_sp calls le
hybrj calls le, qrfac, dogleg
lmstr calls le, lmpar, qrfac
lmder1 calls lmder
lmdif1 calls lmdif
biogeochem calls casa_xrateplant
optimise_jv calls rtbis
locate calls locate_0d_dp, locate_1d_dp, locate_0d_sp, locate_1d_sp
hybrd1 calls hybrd
hybrj1 calls hybrj
lmstr1 calls lmstr
adjust_jv_gm calls lmdif1
casaonly_luc calls biogeochem
bgcdriver calls biogeochem
worker_spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
spincasacnp calls biogeochem
casa_feedback calls optimise_jv, adjust_jv_gm
cable_offline_driver calls casaonly_luc, bgcdriver, spincasacnp, casa_feedback
mpidrv_worker calls bgcdriver, worker_spincasacnp, worker_casaonly_luc, casa_feedback
mpi_driver calls mpidrv_worker