lesserequal_dp – POP
lesserequal_dp Function
8 statements
Source File
private pure elemental function lesserequal_dp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a
real(kind=dp), intent(in) :: b
Return Value logical
Called by
Contents
None
Call graph
le calls lesserequal_dp
lesserequal calls lesserequal_dp
rtbis calls le
lmstr calls le, qrfac, lmpar
lmdif calls le, qrfac, lmpar
locate_1d_sp calls le
qrfac calls le
enorm2 calls le
locate_0d_dp calls le
locate_1d_dp calls le
hybrd calls le, qrfac, dogleg
chkder calls le
dogleg calls le
hybrj calls le, qrfac, dogleg
lmder calls le, qrfac, lmpar
locate_0d_sp calls le
lmpar calls le
casa_xrateplant calls le
optimise_jv calls rtbis
lmstr1 calls lmstr
locate calls locate_1d_sp, locate_0d_dp, locate_1d_dp, locate_0d_sp
lmdif1 calls lmdif
hybrd1 calls hybrd
hybrj1 calls hybrj
lmder1 calls lmder
biogeochem calls casa_xrateplant
casa_feedback calls optimise_jv, adjust_jv_gm
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
bgcdriver calls biogeochem
adjust_jv_gm calls lmdif1
worker_spincasacnp calls biogeochem
casaonly_luc calls biogeochem
mpidrv_worker calls casa_feedback, worker_casaonly_luc, bgcdriver, worker_spincasacnp
cable_offline_driver calls casa_feedback, spincasacnp, bgcdriver, casaonly_luc
mpi_driver calls mpidrv_worker