light_inhibition – POP
light_inhibition Function
10 statements
Source File
public function light_inhibition(APAR) result(xrd)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: APAR
Return Value real
Called by
Contents
Call graph
dryleaf calls light_inhibition
find_vcmax_jmax_lut calls light_inhibition
adjust_k_collatz calls light_inhibition
adjust_jv_gm calls light_inhibition
define_canopy calls dryleaf
casa_feedback calls find_vcmax_jmax_lut, adjust_k_collatz, adjust_jv_gm
cbm calls define_canopy
mpidrv_worker calls casa_feedback, cbm
cable_offline_driver calls casa_feedback, cbm
mpi_driver calls mpidrv_worker