litter_props – POP
litter_props Subroutine
46 statements
Source File
public pure elemental subroutine litter_props(S, Tsoil, vlit, plit, h0)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: S
real(kind=r_2), intent(in) :: Tsoil
type(vars), intent(inout) :: vlit
type(params), intent(in) :: plit
real(kind=r_2), intent(in) :: h0
Calls
Called by
Contents
Call graph
litter_props calls slope_esat
solve calls litter_props, timestep_loop
timestep_loop calls litter_props, iflux_loop
iflux_loop calls litter_props
sli_main calls solve
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker