lmder1 – POP
lmder1 Subroutine
46 statements
Source File
public subroutine lmder1(fcn, m, n, x, fvec, fjac, ldfjac, tol, info)
************80
LMDER1 minimizes M functions in N variables by Levenberg-Marquardt method.
Arguments
Type Intent Optional Attributes Name
real :: fcn
integer :: m
integer :: n
real(kind=r_2) :: x(n)
real(kind=r_2) :: fvec(m)
real(kind=r_2) :: fjac(ldfjac,n)
integer :: ldfjac
real(kind=r_2) :: tol
integer :: info
Calls
Contents
None
Call graph
lmder1 calls lmder
lmder calls le, qrfac, enorm, ne, eq, lmpar, ge
le calls lesserequal_sp, lesserequal_dp
qrfac calls le, enorm, ne
ne calls notequal_dp, notequal_sp
eq calls equal_sp, equal_dp
lmpar calls le, enorm, eq, qrsolv
ge calls greaterequal_sp, greaterequal_dp
qrsolv calls ne, eq