lmder – POP
lmder Subroutine
245 statements
Source File
public subroutine lmder(fcn, m, n, x, fvec, fjac, ldfjac, ftol, xtol, gtol, maxfev, diag, mode, factor, nprint, info, nfev, njev, ipvt, qtf)
************80
LMDER minimizes M functions in N variables by the Levenberg-Marquardt method.
Arguments
Type Intent Optional Attributes Name
real :: fcn
integer :: m
integer :: n
real(kind=r_2) :: x(n)
real(kind=r_2) :: fvec(m)
real(kind=r_2) :: fjac(ldfjac,n)
integer :: ldfjac
real(kind=r_2) :: ftol
real(kind=r_2) :: xtol
real(kind=r_2) :: gtol
integer :: maxfev
real(kind=r_2) :: diag(n)
integer :: mode
real(kind=r_2) :: factor
integer :: nprint
integer :: info
integer :: nfev
integer :: njev
integer :: ipvt(n)
real(kind=r_2) :: qtf(n)
Calls
Called by
Contents
Call graph
lmder calls le, enorm, qrfac, ne, eq, lmpar, ge
le calls lesserequal_sp, lesserequal_dp
qrfac calls le, enorm, ne
ne calls notequal_sp, notequal_dp
eq calls equal_sp, equal_dp
lmpar calls le, enorm, eq, qrsolv
ge calls greaterequal_sp, greaterequal_dp
qrsolv calls ne, eq
lmder1 calls lmder