lmdif – POP
lmdif Subroutine
256 statements
Source File
public subroutine lmdif(fcn, m, n, x, fvec, ftol, xtol, gtol, maxfev, epsfcn, diag, mode, factor, nprint, info, nfev, fjac, ldfjac, ipvt, qtf, An, Ci, Rd, Km, gammastar)
************80
LMDIF minimizes M functions in N variables by the Levenberg-Marquardt method.
Arguments
Type Intent Optional Attributes Name
real :: fcn
integer :: m
integer :: n
real(kind=r_2) :: x(n)
real(kind=r_2) :: fvec(m)
real(kind=r_2) :: ftol
real(kind=r_2) :: xtol
real(kind=r_2) :: gtol
integer :: maxfev
real(kind=r_2) :: epsfcn
real(kind=r_2) :: diag(n)
integer :: mode
real(kind=r_2) :: factor
integer :: nprint
integer :: info
integer :: nfev
real(kind=r_2) :: fjac(ldfjac,n)
integer :: ldfjac
integer :: ipvt(n)
real(kind=r_2) :: qtf(n)
real(kind=r_2) :: An(m)
real(kind=r_2) :: Ci(m)
real(kind=r_2) :: Rd
real(kind=r_2) :: Km
real(kind=r_2) :: gammastar
Calls
Called by
Contents
Call graph
lmdif calls le, qrfac, fdjac2, enorm, eq, ne, lmpar, ge
le calls lesserequal_sp, lesserequal_dp
qrfac calls le, enorm, ne
fdjac2 calls eq
eq calls equal_dp, equal_sp
ne calls notequal_sp, notequal_dp
lmpar calls le, enorm, eq, qrsolv
ge calls greaterequal_sp, greaterequal_dp
qrsolv calls eq, ne
lmdif1 calls lmdif
adjust_jv_gm calls lmdif1
casa_feedback calls adjust_jv_gm
mpidrv_worker calls casa_feedback
cable_offline_driver calls casa_feedback
mpi_driver calls mpidrv_worker