lmpar – POP
lmpar Subroutine
129 statements
Source File
public subroutine lmpar(n, r, ldr, ipvt, diag, qtb, delta, par, x, sdiag)
************80
LMPAR computes a parameter for the Levenberg-Marquardt method.
Arguments
Type Intent Optional Attributes Name
integer :: n
real(kind=r_2) :: r(ldr,n)
integer :: ldr
integer :: ipvt(n)
real(kind=r_2) :: diag(n)
real(kind=r_2) :: qtb(n)
real(kind=r_2) :: delta
real(kind=r_2) :: par
real(kind=r_2) :: x(n)
real(kind=r_2) :: sdiag(n)
Calls
Called by
Contents
None
Call graph
lmpar calls eq, qrsolv, le, enorm
eq calls equal_sp, equal_dp
qrsolv calls eq, ne
le calls lesserequal_sp, lesserequal_dp
ne calls notequal_sp, notequal_dp
lmder calls lmpar
lmdif calls lmpar
lmstr calls lmpar
lmder1 calls lmder
lmdif1 calls lmdif
lmstr1 calls lmstr
adjust_jv_gm calls lmdif1
casa_feedback calls adjust_jv_gm
mpidrv_worker calls casa_feedback
cable_offline_driver calls casa_feedback
mpi_driver calls mpidrv_worker