lmstr – POP
lmstr Subroutine
267 statements
Source File
public subroutine lmstr(fcn, m, n, x, fvec, fjac, ldfjac, ftol, xtol, gtol, maxfev, diag, mode, factor, nprint, info, nfev, njev, ipvt, qtf)
************80
LMSTR minimizes M functions in N variables using Levenberg-Marquardt method.
Arguments
Type Intent Optional Attributes Name
real :: fcn
integer :: m
integer :: n
real(kind=r_2) :: x(n)
real(kind=r_2) :: fvec(m)
real(kind=r_2) :: fjac(ldfjac,n)
integer :: ldfjac
real(kind=r_2) :: ftol
real(kind=r_2) :: xtol
real(kind=r_2) :: gtol
integer :: maxfev
real(kind=r_2) :: diag(n)
integer :: mode
real(kind=r_2) :: factor
integer :: nprint
integer :: info
integer :: nfev
integer :: njev
integer :: ipvt(n)
real(kind=r_2) :: qtf(n)
Calls
Called by
Contents
None
Call graph
lmstr calls le, qrfac, enorm, eq, rwupdt, ne, lmpar, ge
le calls lesserequal_sp, lesserequal_dp
qrfac calls le, enorm, ne
eq calls equal_sp, equal_dp
rwupdt calls ne
ne calls notequal_sp, notequal_dp
lmpar calls le, enorm, eq, qrsolv
ge calls greaterequal_sp, greaterequal_dp
qrsolv calls eq, ne
lmstr1 calls lmstr