lmstr1 – POP
lmstr1 Subroutine
60 statements
Source File
public subroutine lmstr1(fcn, m, n, x, fvec, fjac, ldfjac, tol, info)
************80
LMSTR1 minimizes M functions in N variables using Levenberg-Marquardt method.
Arguments
Type Intent Optional Attributes Name
real :: fcn
integer :: m
integer :: n
real(kind=r_2) :: x(n)
real(kind=r_2) :: fvec(m)
real(kind=r_2) :: fjac(ldfjac,n)
integer :: ldfjac
real(kind=r_2) :: tol
integer :: info
Calls
Contents
None
Call graph
lmstr1 calls lmstr
lmstr calls le, qrfac, enorm, eq, rwupdt, ne, lmpar, ge
le calls lesserequal_sp, lesserequal_dp
qrfac calls le, enorm, ne
eq calls equal_dp, equal_sp
rwupdt calls ne
ne calls notequal_sp, notequal_dp
lmpar calls le, enorm, eq, qrsolv
ge calls greaterequal_sp, greaterequal_dp
qrsolv calls eq, ne