load_parameters – POP
load_parameters Subroutine
169 statements
Source File
public subroutine load_parameters(met, air, ssnow, veg, bgc, soil, canopy, rough, rad, sum_flux, bal, logn, vegparmnew, casabiome, casapool, casaflux, sum_casapool, sum_casaflux, casamet, casabal, phen, POP, spinup, EMSOIL, TFRZ, LUC_EXPT, POPLUC, c13o2flux, c13o2pools, sum_c13o2pools, c13o2luc)
Uses
CABLE_LUC_EXPT
cable_c13o2
cable_pop_io
cable_c13o2_def
POPmodule
casaparm
POPLUC_Module
casa_inout
vh_js !! vh_js !!
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: met
type(air_type), intent(inout) :: air
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(inout) :: veg
type(bgc_pool_type), intent(inout) :: bgc
type(soil_parameter_type), intent(inout) :: soil
type(canopy_type), intent(inout) :: canopy
type(roughness_type), intent(inout) :: rough
type(radiation_type), intent(inout) :: rad
type(sum_flux_type), intent(inout) :: sum_flux
type(balances_type), intent(inout) :: bal
integer, intent(in) :: logn
logical, intent(in) :: vegparmnew
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_pool), intent(inout) :: sum_casapool
type(casa_flux), intent(inout) :: sum_casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: POP
logical, intent(in) :: spinup
real, intent(in) :: EMSOIL
real, intent(in) :: TFRZ
type(luc_expt_type), intent(inout) :: LUC_EXPT
type(POPLUC_TYPE), intent(inout) :: POPLUC
type(c13o2_flux), intent(inout) :: c13o2flux
type(c13o2_pool), intent(inout) :: c13o2pools
type(c13o2_pool), intent(inout) :: sum_c13o2pools
type(c13o2_luc), intent(inout) :: c13o2luc
Calls
Called by
Contents
None
Call graph
load_parameters calls c13o2_alloc_pools, alloc_sum_casa, zero_sum_casa, pop_io, c13o2_zero_pools, report_parameters, c13o2_init_flux, casa_init, write_default_params, get_default_params, alloc_casa_var, c13o2_zero_flux, c13o2_read_restart_pools, allocate_cable_vars, casa_readphen, pop_init, nf90_close, popluc_init, nf90_inq_dimid, derived_parameters, nc_abort, c13o2_read_restart_flux, write_cnp_params, zero_phenvariable, casa_readbiome, get_parameters_met, c13o2_alloc_flux, handle_err, zero_casa_var, nf90_open, check_parameter_values, alloc_phenvariable, cable_abort, c13o2_init_pools, nf90_inquire_dimension, c13o2_init_luc, get_restart_data
alloc_sum_casa calls alloc_casapool, alloc_casaflux
zero_sum_casa calls zero_casapool, zero_casaflux
pop_io calls nf90_close, nf90_inq_dimid, handle_err, nf90_open, nf90_inquire_dimension, nf90_def_var, nf90_inq_varid, nf90_create, nf90_def_dim, nf90_put_var, nf90_enddef, ne, mpi_abort, nf90_put_att, nf90_get_var
c13o2_init_flux calls init_sugar_pools, init_starch_pool
casa_init calls zero_casa_dump, read_casa_restart_nc
write_default_params calls cable_abort, mpi_abort, init_veg_from_vegin
get_default_params calls read_soilcolor, get_type_parameters, read_gridinfo, spatialsoil, countpatch, get_land_index, luc_expt_set_tiles, luc_expt_set_tiles_bios
alloc_casa_var calls alloc_casabiome, alloc_casapool, alloc_casaflux, alloc_casamet, alloc_casabal
c13o2_read_restart_pools calls nf90_close, nf90_open, nf90_inq_varid, c13o2_err_handler, nf90_get_var
allocate_cable_vars calls zero_cbm_var, alloc_cbm_var
popluc_init calls zero_popluc, popluc_set_params, alloc_popluc, pop_init_single, read_luc_restart_nc
nc_abort calls nf90_strerror, mpi_abort
c13o2_read_restart_flux calls nf90_close, nf90_open, nf90_inq_varid, c13o2_err_handler, nf90_get_var
get_parameters_met calls nf90_inq_varid, readpar
handle_err calls nf90_strerror, mpi_abort
zero_casa_var calls zero_casapool, zero_casabiome, zero_casabal, zero_casamet, zero_casaflux
check_parameter_values calls cable_abort
cable_abort calls mpi_abort
c13o2_init_luc calls c13o2_zero_luc, c13o2_alloc_luc, c13o2_read_restart_luc
get_restart_data calls nf90_close, nf90_inq_dimid, nc_abort, cable_abort, nf90_inquire_dimension, nf90_inq_varid, readpar, nf90_get_var, extrarestart
read_soilcolor calls nf90_close, nf90_inq_dimid, nc_abort, nf90_open, nf90_inquire_dimension, nf90_inq_varid, ne, nf90_get_var
get_type_parameters calls mpi_abort
read_gridinfo calls nf90_close, nf90_inq_dimid, nc_abort, nf90_open, cable_abort, nf90_inquire_dimension, nf90_inq_varid, nf90_get_var
spatialsoil calls nf90_close, nc_abort, nf90_open, nf90_inq_varid, nf90_get_var
countpatch calls mpi_abort
zero_cbm_var calls zero_soil_parameter_type, zero_canopy_type, zero_roughness_type, zero_met_type, zero_sum_flux_type, zero_bgc_pool_type, zero_balances_type, zero_soil_snow_type, zero_veg_parameter_type, zero_radiation_type, zero_air_type, zero_climate_type
alloc_cbm_var calls alloc_balances_type, alloc_canopy_type, alloc_soil_parameter_type, alloc_roughness_type, alloc_met_type, alloc_air_type, alloc_soil_snow_type, alloc_climate_type, alloc_veg_parameter_type, alloc_bgc_pool_type, alloc_sum_flux_type, alloc_radiation_type
readpar calls readpar_i, readpar_r2d, readpar_rd, readpar_r, readpar_r2
c13o2_read_restart_luc calls nf90_close, nf90_open, nf90_inq_varid, c13o2_err_handler, nf90_get_var
c13o2_err_handler calls mpi_abort
ne calls notequal_sp, notequal_dp
read_casa_restart_nc calls read_netcdf_casa_var, read_netcdf_phen_var
read_luc_restart_nc calls nf90_close, nf90_inq_dimid, handle_err, nf90_open, nf90_inquire_dimension, nf90_inq_varid, nf90_get_var
extrarestart calls nc_abort, nf90_inq_varid, readpar, nf90_get_var, redistr_rd, redistr_i, redistr_r2d, redistr_r, redistr_r2
get_land_index calls mpi_abort
luc_expt_set_tiles_bios calls cable_bios_load_fracc4
read_netcdf_casa_var calls read_netcdf_casabiome, read_netcdf_casapool, read_netcdf_casaflux, read_netcdf_casamet, read_netcdf_casabal
redistr_rd calls mpi_abort, float
readpar_i calls nc_abort, cable_abort, nf90_inq_varid, nf90_get_var, nf90_inquire_variable
redistr_i calls mpi_abort
cable_bios_load_fracc4 calls get_unit
readpar_r2d calls nc_abort, cable_abort, nf90_inq_varid, nf90_get_var, nf90_inquire_variable
redistr_r2d calls mpi_abort, float
redistr_r calls mpi_abort, float
readpar_rd calls nc_abort, cable_abort, nf90_inq_varid, nf90_get_var, nf90_inquire_variable
redistr_r2 calls mpi_abort, float
read_netcdf_phen_var calls nf90_close, nf90_open, nf90_inq_varid, mpi_abort, nf90_get_var, nc_err
readpar_r calls nc_abort, cable_abort, nf90_inq_varid, nf90_get_var, nf90_inquire_variable
readpar_r2 calls nc_abort, cable_abort, nf90_inq_varid, nf90_get_var, nf90_inquire_variable
read_netcdf_casabiome calls nf90_close, nf90_open, nf90_inq_varid, mpi_abort, nf90_get_var, nc_err
read_netcdf_casapool calls nf90_close, nf90_open, nf90_inq_varid, mpi_abort, nf90_get_var, nc_err
read_netcdf_casaflux calls nf90_close, nf90_open, nf90_inq_varid, mpi_abort, nf90_get_var, nc_err
read_netcdf_casamet calls nf90_close, nf90_open, nf90_inq_varid, mpi_abort, nf90_get_var, nc_err
read_netcdf_casabal calls nf90_close, nf90_open, nf90_inq_varid, mpi_abort, nf90_get_var, nc_err
nc_err calls nf90_strerror, mpi_abort
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master