LUC_EXPT_INIT – POP
LUC_EXPT_INIT Subroutine
364 statements
Source File
public subroutine LUC_EXPT_INIT(luc_expt)
Uses
cable_bios_met_obs_params
netcdf
cable_common_module
Arguments
Type Intent Optional Attributes Name
type(luc_expt_type), intent(inout) :: luc_expt
Calls
Called by
Contents
None
Call graph
luc_expt_init calls cable_bios_load_biome, nf90_close, nf90_open, nf90_inq_varid, handle_err, luc_expt_zero, get_unit, nf90_inq_dimid, nf90_inquire_dimension, nf90_get_att, nf90_get_var, read_climatefile
cable_bios_load_biome calls get_unit
handle_err calls nf90_strerror, mpi_abort
read_climatefile calls nf90_close, nf90_open, nf90_inq_dimid, nf90_inquire_dimension, nc_err, alloc_cbm_var, read_netcdf_cbm_var
nc_err calls nf90_strerror, mpi_abort
alloc_cbm_var calls alloc_balances_type, alloc_soil_snow_type, alloc_veg_parameter_type, alloc_soil_parameter_type, alloc_canopy_type, alloc_radiation_type, alloc_roughness_type, alloc_air_type, alloc_met_type, alloc_sum_flux_type, alloc_bgc_pool_type, alloc_climate_type
read_netcdf_cbm_var calls read_netcdf_climate_type
read_netcdf_climate_type calls nf90_close, nf90_open, nf90_inq_varid, nf90_get_var, mpi_abort, nc_err
mpidrv_master calls luc_expt_init
cable_offline_driver calls luc_expt_init
mpi_driver calls mpidrv_master