LUC_EXPT_SET_TILES_BIOS – POP
LUC_EXPT_SET_TILES_BIOS Subroutine
40 statements
Source File
public subroutine LUC_EXPT_SET_TILES_BIOS(inVeg, inPFrac, LUC_EXPT)
Uses
cable_bios_met_obs_params
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: inVeg(:,:,:)
real, intent(inout) :: inPFrac(:,:,:)
type(luc_expt_type), intent(inout) :: LUC_EXPT
Calls
Called by
Contents
None
Call graph
luc_expt_set_tiles_bios calls cable_bios_load_fracc4
cable_bios_load_fracc4 calls get_unit
get_default_params calls luc_expt_set_tiles_bios
load_parameters calls get_default_params
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master