LUCdriver – POP
LUCdriver Subroutine
68 statements
Source File
subroutine LUCdriver(casabiome, casapool, casaflux, POP, LUC_EXPT, POPLUC, veg, c13o2pools)
Uses
cable_carbon_module
POPLUC_Types
POP_Types
POPLUC_Module
cable_def_types_mod
cable_IO_vars_module
CABLE_LUC_EXPT
casavariable
mo_utils
casadimension
POPModule
cable_c13o2_def
cable_common_module
casaparm
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(POP_TYPE), intent(inout) :: POP
type(luc_expt_type), intent(inout) :: LUC_EXPT
type(POPLUC_TYPE), intent(inout) :: POPLUC
type(veg_parameter_type), intent(in) :: veg
type(c13o2_pool), intent(inout) :: c13o2pools
Calls
Called by
Contents
None
Call graph
lucdriver calls read_luh2, pop_init_single, popluc_weights_transfer, eq, poplucstep
read_luh2 calls nf90_get_var, handle_err
pop_init_single calls initpop2d_poisson, zeropop, layer_recruitment_single_patch
eq calls equal_sp, equal_dp
poplucstep calls increment_age, execute_luc_event
initpop2d_poisson calls exponential, cumexponential
handle_err calls nf90_strerror
layer_recruitment_single_patch calls get_allometry
get_allometry calls getheight, allometry, williams_allometry
cable_offline_driver calls lucdriver