LUCdriver – POP
LUCdriver Subroutine
69 statements
Source File
private subroutine LUCdriver(casabiome, casapool, casaflux, POP, LUC_EXPT, POPLUC, veg, c13o2pools)
Uses
casaparm
POPLUC_Module
POPLUC_Types
casavariable
POP_Types
POPModule
cable_c13o2_def
casadimension
mo_utils
cable_carbon_module
CABLE_LUC_EXPT
cable_def_types_mod
cable_common_module
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(POP_TYPE), intent(inout) :: POP
type(luc_expt_type), intent(inout) :: LUC_EXPT
type(POPLUC_TYPE), intent(inout) :: POPLUC
type(veg_parameter_type), intent(in) :: veg
type(c13o2_pool), intent(inout) :: c13o2pools
Calls
Called by
Contents
None
Call graph
lucdriver calls read_luh2, pop_init_single, poplucstep, eq, popluc_weights_transfer
read_luh2 calls nf90_get_var, handle_err
pop_init_single calls initpop2d_poisson, zeropop, layer_recruitment_single_patch
poplucstep calls increment_age, execute_luc_event
eq calls equal_sp, equal_dp
initpop2d_poisson calls exponential, cumexponential
layer_recruitment_single_patch calls get_allometry
handle_err calls nf90_strerror
get_allometry calls getheight, allometry, williams_allometry
mpidrv_master calls lucdriver
mpi_driver calls mpidrv_master