master_CASAONLY_LUC – POP
master_CASAONLY_LUC Subroutine
220 statements
Source File
private subroutine master_CASAONLY_LUC(dels, kstart, kend, veg, casabiome, casapool, casaflux, casamet, casabal, phen, pop, climate, luc_expt, popluc, c13o2flux, c13o2pools, c13o2luc, icomm, ocomm)
Uses
POP_Types
cable_c13o2
casa_cable
cable_common_module
cable_carbon_module
cable_c13o2_def
casadimension
casa_inout
phenvariable
TypeDef
CABLE_LUC_EXPT
cable_pop_io
mo_utils
cable_IO_vars_module
POPLUC_Module
casavariable
POPModule
POPLUC_Types
mpi
cable_def_types_mod
casaparm
CLN901 format(A99)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: kstart
integer, intent(in) :: kend
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: pop
type(climate_type), intent(inout) :: climate
type(luc_expt_type), intent(inout) :: luc_expt
type(POPLUC_TYPE), intent(inout) :: popluc
type(c13o2_flux), intent(inout) :: c13o2flux
type(c13o2_pool), intent(inout) :: c13o2pools
type(c13o2_luc), intent(inout) :: c13o2luc
integer, intent(in) :: icomm
integer, intent(in) :: ocomm
Calls
Called by
Contents
None
Call graph
master_casaonly_luc calls read_luh2, eq, write_luc_output_nc, pop_io, poplucstep, pop_init_single, c13o2_sanity_pools, c13o2_save_luc, alloc_casa_var, read_casa_dump, zero_phenvariable, master_send_input, c13o2_write_restart_pools, mpi_send, master_receive_pop, alloc_phenvariable, zero_casa_var, copy_save_variables, master_receive, pop_luc_casa_transfer, c13o2_update_luc, c13o2_sanity_luc, write_luc_output_grid_nc, popluc_set_patchfrac, c13o2_write_restart_luc, write_casa_restart_nc, write_luc_restart_nc, popluc_weights_transfer
read_luh2 calls nf90_get_var, handle_err
eq calls equal_dp, equal_sp
write_luc_output_nc calls nf90_close, nf90_put_var, nf90_enddef, nf90_create, handle_err, nf90_def_dim, nf90_put_att, nf90_def_var
pop_io calls nf90_open, nf90_close, nf90_get_var, nf90_put_var, nf90_enddef, nf90_inq_varid, ne, nf90_inquire_dimension, nf90_inq_dimid, nf90_create, handle_err, nf90_def_dim, nf90_put_att, nf90_def_var
poplucstep calls execute_luc_event, increment_age
pop_init_single calls initpop2d_poisson, zeropop, layer_recruitment_single_patch
c13o2_sanity_pools calls isosanity
c13o2_save_luc calls c13o2_save_casapool
alloc_casa_var calls alloc_casabiome, alloc_casabal, alloc_casaflux, alloc_casapool, alloc_casamet
read_casa_dump calls nf90_open, nf90_close, stderr_nc, get_var_nc
master_send_input calls mpi_isend, mpi_waitall
c13o2_write_restart_pools calls c13o2_err_handler, nf90_close, nf90_put_var, nf90_enddef, nf90_create, nf90_def_dim, nf90_put_att, nf90_def_var
master_receive_pop calls mpi_recv
zero_casa_var calls zero_casapool, zero_casabal, zero_casamet, zero_casabiome, zero_casaflux
master_receive calls mpi_irecv, mpi_waitall
pop_luc_casa_transfer calls eq
c13o2_update_luc calls isotope_pool_model, c13o2_save_c13o2pools, isotope_luc_model
c13o2_sanity_luc calls isosanity
write_luc_output_grid_nc calls nf90_close, nf90_put_var, nf90_enddef, nf90_redef, nf90_create, handle_err, nf90_def_dim, nf90_put_att, nf90_def_var
c13o2_write_restart_luc calls c13o2_err_handler, nf90_close, nf90_put_var, nf90_enddef, nf90_create, nf90_def_dim, nf90_put_att, nf90_def_var
write_casa_restart_nc calls write_netcdf_casa_var, write_netcdf_phen_var
write_luc_restart_nc calls nf90_close, nf90_put_var, nf90_enddef, nf90_redef, nf90_create, handle_err, nf90_def_dim, nf90_put_att, nf90_def_var
initpop2d_poisson calls exponential, cumexponential
stderr_nc calls nf90_strerror
get_var_nc calls get_var_ncr2, get_var_ncr3
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
ne calls notequal_sp, notequal_dp
isotope_luc_model calls isotope_luc_model_1d
handle_err calls nf90_strerror
write_netcdf_casa_var calls write_netcdf_casaflux, write_netcdf_casapool, write_netcdf_casabal, write_netcdf_casabiome, write_netcdf_casamet
write_netcdf_phen_var calls nf90_close, nf90_put_var, nf90_enddef, nf90_create, nf90_def_dim, nf90_def_var, nc_err
layer_recruitment_single_patch calls get_allometry
write_netcdf_casaflux calls nf90_close, nf90_put_var, nf90_enddef, nf90_create, nf90_def_dim, nf90_def_var, nc_err
write_netcdf_casapool calls nf90_close, nf90_put_var, nf90_enddef, nf90_create, nf90_def_dim, nf90_def_var, nc_err
write_netcdf_casabal calls nf90_close, nf90_put_var, nf90_enddef, nf90_create, nf90_def_dim, nf90_def_var, nc_err
get_allometry calls getheight, allometry, williams_allometry
write_netcdf_casabiome calls nf90_close, nf90_put_var, nf90_enddef, nf90_create, nf90_def_dim, nf90_def_var, nc_err
write_netcdf_casamet calls nf90_close, nf90_put_var, nf90_enddef, nf90_create, nf90_def_dim, nf90_def_var, nc_err
get_var_ncr2 calls nf90_get_var, stderr_nc, nf90_inq_varid
get_var_ncr3 calls nf90_get_var, stderr_nc, nf90_inq_varid
isotope_pool_model_1d calls eq, ne, diag, mpi_abort
isotope_pool_model_2d calls eq, ne, diag, mpi_abort
isotope_luc_model_1d calls eq, mpi_abort
nc_err calls nf90_strerror
diag calls diag_2d, diag_3d
diag_2d calls mpi_abort
diag_3d calls mpi_abort
mpidrv_master calls master_casaonly_luc
mpi_driver calls mpidrv_master