master_casa_dump_types – POP
master_casa_dump_types Subroutine
103 statements
Source File
private subroutine master_casa_dump_types(comm, casamet, casaflux, phen, climate, c13o2flux)
Uses
casavariable
phenvariable
cable_mpicommon
casadimension
cable_common_module
mpi
cable_c13o2_def
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(casa_met), intent(inout) :: casamet
type(casa_flux), intent(inout) :: casaflux
type(phen_variable), intent(inout) :: phen
type(climate_type), intent(inout) :: climate
type(c13o2_flux), intent(inout) :: c13o2flux
Calls
Called by
Contents
None
Call graph
master_casa_dump_types calls add_address_hvector, mpi_type_create_struct, mpi_abort, mpi_type_commit, mpi_type_size, mpi_type_get_extent, mpi_reduce
add_address_hvector calls add_address_hvector_3d_l, add_address_hvector_3d_r2, add_address_hvector_1d_r2, add_address_hvector_2d_i1, add_address_hvector_1d_i1, add_address_hvector_1d_l, add_address_hvector_1d_r1, add_address_hvector_2d_l, add_address_hvector_2d_r1, add_address_hvector_2d_r2, add_address_hvector_3d_i1, add_address_hvector_3d_r1
add_address_hvector_3d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_r2 calls mpi_get_address
add_address_hvector_2d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_i1 calls mpi_get_address
add_address_hvector_1d_l calls mpi_get_address
add_address_hvector_1d_r1 calls mpi_get_address
add_address_hvector_2d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r1 calls mpi_get_address, mpi_type_create_hvector
mpidrv_master calls master_casa_dump_types
mpi_driver calls mpidrv_master