master_casa_LUC_types – POP
master_casa_LUC_types Subroutine
93 statements
Source File
private subroutine master_casa_LUC_types(comm, casapool, casabal, casaflux)
Uses
casavariable
cable_mpicommon
casadimension
cable_def_types_mod
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(casa_pool), intent(in) :: casapool
type(casa_balance), intent(in) :: casabal
type(casa_flux), intent(in) :: casaflux
Calls
Called by
Contents
None
Call graph
master_casa_luc_types calls add_address_hvector, mpi_abort, mpi_type_create_struct, mpi_type_commit, mpi_type_size, mpi_type_get_extent, mpi_type_free, mpi_reduce
add_address_hvector calls add_address_hvector_3d_l, add_address_hvector_3d_r1, add_address_hvector_1d_r1, add_address_hvector_2d_i1, add_address_hvector_1d_r2, add_address_hvector_1d_i1, add_address_hvector_1d_l, add_address_hvector_2d_l, add_address_hvector_2d_r1, add_address_hvector_2d_r2, add_address_hvector_3d_i1, add_address_hvector_3d_r2
add_address_hvector_3d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_r1 calls mpi_get_address
add_address_hvector_2d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_r2 calls mpi_get_address
add_address_hvector_1d_i1 calls mpi_get_address
add_address_hvector_1d_l calls mpi_get_address
add_address_hvector_2d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r2 calls mpi_get_address, mpi_type_create_hvector
mpidrv_master calls master_casa_luc_types
mpi_driver calls mpidrv_master