master_restart_types – POP
master_restart_types Subroutine
81 statements
Source File
private subroutine master_restart_types(comm, canopy, air, veg, ssnow)
Uses
cable_mpicommon
mpi
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer :: comm
type(canopy_type), intent(in) :: canopy
type(air_type), intent(in) :: air
type(veg_parameter_type), intent(in) :: veg
type(soil_snow_type), intent(in) :: ssnow
Calls
Called by
Contents
None
Call graph
master_restart_types calls add_address_hvector, mpi_abort, mpi_type_create_struct, mpi_type_commit, mpi_type_size, mpi_type_get_extent, mpi_type_free, mpi_reduce
add_address_hvector calls add_address_hvector_3d_l, add_address_hvector_3d_r1, add_address_hvector_1d_r1, add_address_hvector_2d_i1, add_address_hvector_1d_r2, add_address_hvector_1d_i1, add_address_hvector_1d_l, add_address_hvector_2d_l, add_address_hvector_2d_r1, add_address_hvector_2d_r2, add_address_hvector_3d_i1, add_address_hvector_3d_r2
add_address_hvector_3d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_r1 calls mpi_get_address
add_address_hvector_2d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_r2 calls mpi_get_address
add_address_hvector_1d_i1 calls mpi_get_address
add_address_hvector_1d_l calls mpi_get_address
add_address_hvector_2d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r2 calls mpi_get_address, mpi_type_create_hvector
mpidrv_master calls master_restart_types
mpi_driver calls mpidrv_master