master_spincasacnp – POP
master_spincasacnp Subroutine
165 statements
Source File
private subroutine master_spincasacnp(dels, kstart, kend, mloop, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen, POP, climate, c13o2flux, c13o2pools, icomm, ocomm)
Uses
casavariable
phenvariable
cable_pop_io
casadimension
casaparm
cable_carbon_module
cable_common_module
casa_cable
casa_inout
cable_c13o2_def
cable_c13o2
cable_def_types_mod
POP_types
cln character(len=99), intent(in) :: fcnpspin CLN OPEN(91,file=fcnpspin) CLN read(91,*)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: kstart
integer, intent(in) :: kend
integer, intent(in) :: mloop
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_type), intent(inout) :: POP
type(climate_type), intent(inout) :: climate
type(c13o2_flux), intent(inout) :: c13o2flux
type(c13o2_pool), intent(inout) :: c13o2pools
integer, intent(in) :: icomm
integer, intent(in) :: ocomm
Calls
Called by
Contents
None
Call graph
master_spincasacnp calls casa_fluxout, master_receive, c13o2_write_restart_pools, c13o2_sanity_pools, pop_io, alloc_casa_var, master_receive_pop, alloc_phenvariable, read_casa_dump, zero_casa_var, zero_phenvariable, master_send_input, write_casa_restart_nc, copy_save_variables
master_receive calls mpi_irecv, mpi_waitall
c13o2_write_restart_pools calls nf90_def_dim, nf90_create, nf90_put_var, nf90_def_var, c13o2_err_handler, nf90_put_att, nf90_enddef, nf90_close
c13o2_sanity_pools calls isosanity
pop_io calls handle_err, nf90_inq_varid, nf90_inquire_dimension, nf90_get_var, nf90_open, nf90_def_dim, nf90_create, nf90_put_var, mpi_abort, ne, nf90_def_var, nf90_put_att, nf90_enddef, nf90_close, nf90_inq_dimid
alloc_casa_var calls alloc_casaflux, alloc_casabiome, alloc_casapool, alloc_casabal, alloc_casamet
master_receive_pop calls mpi_recv
read_casa_dump calls stderr_nc, nf90_open, nf90_close, get_var_nc
zero_casa_var calls zero_casaflux, zero_casabal, zero_casamet, zero_casabiome, zero_casapool
master_send_input calls mpi_waitall, mpi_isend
write_casa_restart_nc calls write_netcdf_casa_var, write_netcdf_phen_var
stderr_nc calls mpi_abort, nf90_strerror
handle_err calls mpi_abort, nf90_strerror
write_netcdf_casa_var calls write_netcdf_casaflux, write_netcdf_casapool, write_netcdf_casamet, write_netcdf_casabiome, write_netcdf_casabal
ne calls notequal_sp, notequal_dp
c13o2_err_handler calls mpi_abort
write_netcdf_phen_var calls nf90_def_dim, nf90_create, nf90_put_var, nf90_def_var, nf90_enddef, nf90_close, nc_err
get_var_nc calls get_var_ncr3, get_var_ncr2
get_var_ncr3 calls stderr_nc, nf90_inq_varid, nf90_get_var
write_netcdf_casaflux calls nf90_def_dim, nf90_create, nf90_put_var, nf90_def_var, nf90_enddef, nf90_close, nc_err
write_netcdf_casapool calls nf90_def_dim, nf90_create, nf90_put_var, nf90_def_var, nf90_enddef, nf90_close, nc_err
write_netcdf_casamet calls nf90_def_dim, nf90_create, nf90_put_var, nf90_def_var, nf90_enddef, nf90_close, nc_err
write_netcdf_casabiome calls nf90_def_dim, nf90_create, nf90_put_var, nf90_def_var, nf90_enddef, nf90_close, nc_err
write_netcdf_casabal calls nf90_def_dim, nf90_create, nf90_put_var, nf90_def_var, nf90_enddef, nf90_close, nc_err
nc_err calls mpi_abort, nf90_strerror
get_var_ncr2 calls stderr_nc, nf90_inq_varid, nf90_get_var
mpidrv_master calls master_spincasacnp
mpi_driver calls mpidrv_master