master_receive – POP
master_receive Subroutine
13 statements
Source File
private subroutine master_receive(comm, ktau, types)
Uses
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
integer, intent(in) :: ktau
integer, intent(in), DIMENSION(:) :: types
Calls
Called by
Contents
Call graph
master_receive calls mpi_irecv, mpi_waitall
master_spincasacnp calls master_receive
mpidrv_master calls master_receive, master_spincasacnp, master_casaonly_luc
master_casaonly_luc calls master_receive
mpi_driver calls mpidrv_master