master_cable_params – POP
master_cable_params Subroutine
507 statements
Source File
private subroutine master_cable_params(comm, met, air, ssnow, veg, bgc, soil, canopy, rough, rad, sum_flux, bal)
Uses
mpi
cable_mpicommon
cable_IO_vars_module
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(met_type), intent(inout) :: met
type(air_type), intent(inout) :: air
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(inout) :: veg
type(bgc_pool_type), intent(inout) :: bgc
type(soil_parameter_type), intent(inout) :: soil
type(canopy_type), intent(inout) :: canopy
type(roughness_type), intent(inout) :: rough
type(radiation_type), intent(inout) :: rad
type(sum_flux_type), intent(inout) :: sum_flux
type(balances_type), intent(inout) :: bal
Calls
Called by
Contents
None
Call graph
master_cable_params calls decomp_types, add_address_hvector, mpi_abort, mpi_type_create_struct, mpi_send, mpi_type_commit, mpi_type_size, mpi_type_get_extent, mpi_reduce, master_send_input, mpi_type_free
decomp_types calls mpi_type_create_struct, mpi_type_commit, mpi_get_address, mpi_type_create_resized
add_address_hvector calls add_address_hvector_2d_r2, add_address_hvector_3d_l, add_address_hvector_1d_i1, add_address_hvector_1d_r2, add_address_hvector_3d_r2, add_address_hvector_2d_i1, add_address_hvector_1d_r1, add_address_hvector_1d_l, add_address_hvector_2d_l, add_address_hvector_2d_r1, add_address_hvector_3d_i1, add_address_hvector_3d_r1
master_send_input calls mpi_isend, mpi_waitall
add_address_hvector_2d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_i1 calls mpi_get_address
add_address_hvector_1d_r2 calls mpi_get_address
add_address_hvector_3d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_r1 calls mpi_get_address
add_address_hvector_1d_l calls mpi_get_address
add_address_hvector_2d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r1 calls mpi_get_address, mpi_type_create_hvector
mpidrv_master calls master_cable_params
mpi_driver calls mpidrv_master