master_casa_params – POP
master_casa_params Subroutine
307 statements
Source File
private subroutine master_casa_params(comm, casabiome, casapool, casaflux, casamet, casabal, phen)
Uses
casavariable
phenvariable
cable_mpicommon
casadimension
mpi
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
None
Call graph
master_casa_params calls mpi_type_free, mpi_type_create_struct, add_address_1block, mpi_abort, add_address_hvector, mpi_type_commit, mpi_type_size, mpi_type_get_extent, mpi_reduce, mpi_barrier, master_send_input
add_address_1block calls add_address_1block_1d_l, add_address_1block_2d_i1, add_address_1block_2d_l, add_address_1block_2d_r1, add_address_1block_3d_r1, add_address_1block_1d_i1, add_address_1block_1d_r1, add_address_1block_1d_r2, add_address_1block_2d_r2, add_address_1block_3d_i1, add_address_1block_3d_l, add_address_1block_3d_r2
add_address_hvector calls add_address_hvector_3d_i1, add_address_hvector_2d_i1, add_address_hvector_1d_r1, add_address_hvector_1d_r2, add_address_hvector_1d_l, add_address_hvector_1d_i1, add_address_hvector_2d_r2, add_address_hvector_3d_l, add_address_hvector_3d_r2, add_address_hvector_2d_l, add_address_hvector_2d_r1, add_address_hvector_3d_r1
master_send_input calls mpi_waitall, mpi_isend
add_address_hvector_3d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_r1 calls mpi_get_address
add_address_hvector_1d_r2 calls mpi_get_address
add_address_hvector_1d_l calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
add_address_1block_2d_l calls mpi_get_address
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_3d_r1 calls mpi_get_address
add_address_hvector_1d_i1 calls mpi_get_address
add_address_hvector_2d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_1block_1d_i1 calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
add_address_1block_1d_r2 calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
add_address_1block_3d_i1 calls mpi_get_address
add_address_1block_3d_l calls mpi_get_address
add_address_hvector_2d_l calls mpi_get_address, mpi_type_create_hvector
add_address_1block_3d_r2 calls mpi_get_address
add_address_hvector_2d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r1 calls mpi_get_address, mpi_type_create_hvector
mpidrv_master calls master_casa_params
mpi_driver calls mpidrv_master