master_intypes – POP
master_intypes Subroutine
80 statements
Source File
private subroutine master_intypes(comm, met, veg)
Uses
cable_mpicommon
mpi
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(met_type), intent(in) :: met
type(veg_parameter_type), intent(in) :: veg
Calls
Called by
Contents
Call graph
master_intypes calls add_address_hvector, mpi_type_commit, mpi_abort, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_reduce
add_address_hvector calls add_address_hvector_3d_l, add_address_hvector_3d_r1, add_address_hvector_1d_l, add_address_hvector_1d_r1, add_address_hvector_1d_i1, add_address_hvector_2d_i1, add_address_hvector_1d_r2, add_address_hvector_2d_l, add_address_hvector_2d_r1, add_address_hvector_2d_r2, add_address_hvector_3d_i1, add_address_hvector_3d_r2
add_address_hvector_3d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_l calls mpi_get_address
add_address_hvector_1d_r1 calls mpi_get_address
add_address_hvector_1d_i1 calls mpi_get_address
add_address_hvector_2d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_r2 calls mpi_get_address
add_address_hvector_2d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r2 calls mpi_get_address, mpi_type_create_hvector
mpidrv_master calls master_intypes
mpi_driver calls mpidrv_master