master_send_input – POP
master_send_input Subroutine
13 statements
Source File
private subroutine master_send_input(comm, dtypes, ktau)
Uses
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
integer, intent(in), DIMENSION(:) :: dtypes
integer, intent(in) :: ktau
Calls
Called by
Contents
Call graph
master_send_input calls mpi_isend, mpi_waitall
master_cable_params calls master_send_input
master_c13o2_pool_params calls master_send_input
master_casa_params calls master_send_input
master_c13o2_luc_params calls master_send_input
master_c13o2_flux_params calls master_send_input
mpidrv_master calls master_send_input, master_cable_params, master_c13o2_pool_params, master_casa_params, master_c13o2_luc_params, master_c13o2_flux_params, master_spincasacnp, master_casaonly_luc
master_spincasacnp calls master_send_input
master_casaonly_luc calls master_send_input
mpi_driver calls mpidrv_master