master_outtypes – POP
master_outtypes Subroutine
489 statements
Source File
private subroutine master_outtypes(comm, met, canopy, ssnow, rad, bal, air, soil, veg)
Uses
cable_mpicommon
mpi
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer :: comm
type(met_type), intent(in) :: met
type(canopy_type), intent(in) :: canopy
type(soil_snow_type), intent(in) :: ssnow
type(radiation_type), intent(in) :: rad
type(balances_type), intent(inout) :: bal
type(air_type), intent(in) :: air
type(soil_parameter_type), intent(in) :: soil
type(veg_parameter_type), intent(in) :: veg
Calls
Called by
Contents
Call graph
master_outtypes calls mpi_get_address, mpi_abort, add_address_hvector, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_hindexed, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_reduce
add_address_hvector calls add_address_hvector_3d_l, add_address_hvector_3d_r1, add_address_hvector_1d_l, add_address_hvector_2d_i1, add_address_hvector_1d_i1, add_address_hvector_1d_r1, add_address_hvector_1d_r2, add_address_hvector_2d_l, add_address_hvector_2d_r1, add_address_hvector_2d_r2, add_address_hvector_3d_i1, add_address_hvector_3d_r2
add_address_hvector_3d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_l calls mpi_get_address
add_address_hvector_2d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_i1 calls mpi_get_address
add_address_hvector_1d_r1 calls mpi_get_address
add_address_hvector_1d_r2 calls mpi_get_address
add_address_hvector_2d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r2 calls mpi_get_address, mpi_type_create_hvector
mpidrv_master calls master_outtypes
mpi_driver calls mpidrv_master