master_c13o2_pool_params – POP
master_c13o2_pool_params Subroutine
74 statements
Source File
private subroutine master_c13o2_pool_params(comm, c13o2pools)
Uses
mpi
cable_mpicommon
cable_def_types_mod
cable_c13o2_def
casadimension
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(c13o2_pool), intent(inout) :: c13o2pools
Calls
Called by
Contents
Call graph
master_c13o2_pool_params calls add_address_hvector, mpi_abort, mpi_type_create_struct, mpi_type_size, mpi_type_commit, mpi_type_get_extent, mpi_reduce, mpi_barrier, master_send_input, mpi_type_free
add_address_hvector calls add_address_hvector_1d_i1, add_address_hvector_2d_i1, add_address_hvector_1d_l, add_address_hvector_1d_r1, add_address_hvector_1d_r2, add_address_hvector_2d_l, add_address_hvector_2d_r1, add_address_hvector_2d_r2, add_address_hvector_3d_i1, add_address_hvector_3d_l, add_address_hvector_3d_r1, add_address_hvector_3d_r2
master_send_input calls mpi_isend, mpi_waitall
add_address_hvector_1d_i1 calls mpi_get_address
add_address_hvector_2d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_l calls mpi_get_address
add_address_hvector_1d_r1 calls mpi_get_address
add_address_hvector_1d_r2 calls mpi_get_address
add_address_hvector_2d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r2 calls mpi_get_address, mpi_type_create_hvector
mpidrv_master calls master_c13o2_pool_params
mpi_driver calls mpidrv_master