master_simfire_types – POP
master_simfire_types Subroutine
179 statements
Source File
public subroutine master_simfire_types(comm, wland, wnp, mp, SF, simfire_restart_ts, simfire_inp_ts, simfire_out_ts)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(lpdecomp_t), intent(in), DIMENSION(:) :: wland
integer, intent(in) :: wnp
integer, intent(in) :: mp
type(TYPE_SIMFIRE), intent(in) :: SF
integer, intent(out), DIMENSION(:) :: simfire_restart_ts
integer, intent(out), DIMENSION(:) :: simfire_inp_ts
integer, intent(out), DIMENSION(:) :: simfire_out_ts
Calls
Contents
None
Call graph
master_simfire_types calls mpi_get_address, mpi_type_commit, mpi_type_create_hvector, mpi_type_create_struct, mpi_abort, mpi_type_size, mpi_type_get_extent, mpi_type_free, mpi_reduce