master_blaze_types – POP
master_blaze_types Subroutine
267 statements
Source File
public subroutine master_blaze_types(comm, wland, wnp, mp, BLAZE, blaze_restart_ts, blaze_in_ts, blaze_out_ts)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(lpdecomp_t), intent(in), DIMENSION(:) :: wland
integer, intent(in) :: wnp
integer, intent(in) :: mp
type(TYPE_BLAZE), intent(in) :: BLAZE
integer, intent(out), DIMENSION(:) :: blaze_restart_ts
integer, intent(out), DIMENSION(:) :: blaze_in_ts
integer, intent(out), DIMENSION(:) :: blaze_out_ts
Calls
Called by
Contents
None
Call graph
master_blaze_types calls mpi_get_address, mpi_abort, mpi_type_commit, mpi_type_size, mpi_type_create_struct, mpi_type_get_extent, mpi_type_free, mpi_reduce, mpi_type_create_hvector
mpidrv_master calls master_blaze_types
mpi_driver calls mpidrv_master