master_casa_types – POP
master_casa_types Subroutine
354 statements
Source File
private subroutine master_casa_types(comm, casabiome, casapool, casaflux, casamet, casabal, phen)
Uses
phenvariable
cable_mpicommon
mpi
cable_def_types_mod
casadimension
casavariable
Arguments
Type Intent Optional Attributes Name
integer :: comm
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
None
Call graph
master_casa_types calls add_address_hvector, mpi_type_create_struct, mpi_type_size, mpi_abort, mpi_type_commit, mpi_type_get_extent, mpi_type_free, mpi_reduce
add_address_hvector calls add_address_hvector_1d_i1, add_address_hvector_1d_l, add_address_hvector_1d_r2, add_address_hvector_2d_i1, add_address_hvector_1d_r1, add_address_hvector_2d_l, add_address_hvector_2d_r1, add_address_hvector_2d_r2, add_address_hvector_3d_i1, add_address_hvector_3d_l, add_address_hvector_3d_r1, add_address_hvector_3d_r2
add_address_hvector_1d_i1 calls mpi_get_address
add_address_hvector_1d_l calls mpi_get_address
add_address_hvector_1d_r2 calls mpi_get_address
add_address_hvector_2d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_r1 calls mpi_get_address
add_address_hvector_2d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r2 calls mpi_get_address, mpi_type_create_hvector
mpidrv_master calls master_casa_types
mpi_driver calls mpidrv_master