master_climate_types – POP
master_climate_types Subroutine
141 statements
Source File
private subroutine master_climate_types(comm, climate)
Uses
mpi
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(climate_type), intent(inout) :: climate
Calls
Called by
Contents
Call graph
master_climate_types calls mpi_get_address, mpi_type_commit, add_address_hvector, mpi_abort, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_reduce, mpi_isend, mpi_waitall
add_address_hvector calls add_address_hvector_3d_i1, add_address_hvector_3d_l, add_address_hvector_3d_r1, add_address_hvector_1d_r2, add_address_hvector_2d_i1, add_address_hvector_3d_r2, add_address_hvector_1d_i1, add_address_hvector_1d_r1, add_address_hvector_1d_l, add_address_hvector_2d_l, add_address_hvector_2d_r1, add_address_hvector_2d_r2
add_address_hvector_3d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_r2 calls mpi_get_address
add_address_hvector_2d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_i1 calls mpi_get_address
add_address_hvector_1d_r1 calls mpi_get_address
add_address_hvector_1d_l calls mpi_get_address
add_address_hvector_2d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r2 calls mpi_get_address, mpi_type_create_hvector
mpidrv_master calls master_climate_types
mpi_driver calls mpidrv_master