mpidrv_master – POP
mpidrv_master Subroutine
843 statements
Source File
public subroutine mpidrv_master(comm)
Uses
SIMFIRE_MOD
CABLE_PLUME_MIP
casavariable
POPLUC_Module
casadimension
cable_write_module
CABLE_LUC_EXPT
cable_output_module
cable_common_module
cable_input_module
BLAZE_MPI
mpi
POP_Types
phenvariable
casa_cable
cable_adjust_JV_gm_module
cable_IO_vars_module
cable_bios_met_obs_params
casa_inout
POPLUC_Types
cable_climate_mod
mo_utils
cable_cru
cable_pop_io
cable_c13o2
cable_data_module
cable_def_types_mod
BLAZE_MOD
cable_c13o2_def
vh_js !! vh_js !! suggest LALLOC should ulitmately be a switch in the .nml file
Arguments
Type Intent Optional Attributes Name
integer :: comm
Calls
Called by
Contents
None
Call graph
mpidrv_master calls master_decomp, ini_blaze, write_casa_dump, cru_init, master_intypes, close_met_file, plume_mip_get_met, master_outtypes, master_climate_types, c13o2_print_delta_flux, master_c13o2_luc_params, casa_fluxout, c13o2_update_sum_pools, luc_expt_init, cable_bios_load_params, master_casa_dump_types, master_receive_pop, report_version_no, is_casa_time, master_casa_types, pop_luc_casa_transfer, write_luc_output_nc, master_restart_types, mpi_send, read_gm_lut, c13o2_write_output, write_blaze_output_nc, load_parameters, c13o2_zero_sum_pools, pop_io, alloc_cbm_var, cru_get_subdiurnal_met, popluc_set_patchfrac, c13o2_close_output, cable_bios_init, ini_simfire, master_c13o2_luc_types, update_sum_casa, master_casa_luc_types, ne, create_restart, master_cable_params, close_luh2, c13o2_sanity_luc, c13o2_update_luc, zero_cbm_var, read_climate_restart_nc, master_send_input, master_casaonly_luc, master_c13o2_flux_params, c13o2_sanity_pools, get_unit, write_luc_restart_nc, is_leapyear, find_extents, master_casa_params, write_casa_output_nc, preparefiles, open_output_file, master_receive, master_pop_types, nullify_write, get_met_data, c13o2_create_output, point2constants, lucdriver, mpi_bcast, write_output, master_blaze_types, plume_mip_init, master_c13o2_pool_params, master_c13o2_pool_types, casa_cnpflux, write_luc_output_grid_nc, c13o2_save_luc, mpi_abort, cable_bios_load_climate_params, close_output_file, c13o2_print_delta_luc, master_end, c13o2_write_restart_flux, write_climate_restart_nc, write_casa_restart_nc, c13o2_print_delta_pools, c13o2_write_restart_pools, mpi_comm_dup, climate_init, cable_bios_read_met, zero_sum_casa, open_met_file, master_c13o2_flux_types, master_spincasacnp, c13o2_write_restart_luc
master_decomp calls mpi_send, mpi_abort, mpi_comm_size
ini_blaze calls get_unit, zero_blaze
write_casa_dump calls nf90_close, def_dims, put_var_nc, stderr_nc, nf90_create, def_vars, nf90_enddef
cru_init calls get_unit, mpi_abort, nf90_close, nf90_get_var, handle_err, nf90_inq_varid, nf90_inquire_dimension, nf90_inq_dimid, nf90_open
master_intypes calls mpi_abort, add_address_hvector, mpi_type_get_extent, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
close_met_file calls nf90_close, nc_abort
plume_mip_get_met calls nf90_close, get_plume_ndep, file_switch, handle_err, wgen_subdiurnal_met, wgen_daily_constants, doysod2ymdhms, wgen_init, rh_sh, plume_get_daily_met, open_plume_met, get_plume_co2, eq
master_outtypes calls mpi_abort, mpi_type_create_hvector, add_address_hvector, mpi_type_get_extent, mpi_get_address, mpi_type_size, mpi_type_commit, mpi_type_create_hindexed, mpi_type_create_struct, mpi_reduce
master_climate_types calls mpi_abort, add_address_hvector, mpi_type_get_extent, mpi_get_address, mpi_type_size, mpi_isend, mpi_type_commit, mpi_type_create_struct, mpi_reduce, mpi_waitall
c13o2_print_delta_flux calls ne, delta1000
master_c13o2_luc_params calls master_send_input, mpi_abort, mpi_barrier, add_address_hvector, mpi_type_get_extent, mpi_type_free, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
luc_expt_init calls get_unit, luc_expt_zero, nf90_close, nf90_get_var, handle_err, nf90_inq_varid, nf90_inquire_dimension, read_climatefile, nf90_get_att, nf90_inq_dimid, nf90_open, cable_bios_load_biome
cable_bios_load_params calls get_unit
master_casa_dump_types calls mpi_abort, add_address_hvector, mpi_type_get_extent, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
master_receive_pop calls mpi_recv
is_casa_time calls is_leapyear, mpi_abort
master_casa_types calls mpi_abort, add_address_hvector, mpi_type_get_extent, mpi_type_free, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
pop_luc_casa_transfer calls eq
write_luc_output_nc calls nf90_close, nf90_put_att, handle_err, nf90_put_var, nf90_def_var, nf90_def_dim, nf90_create, nf90_enddef
master_restart_types calls mpi_abort, add_address_hvector, mpi_type_get_extent, mpi_type_free, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
read_gm_lut calls nf90_close, nf90_get_var, nc_abort, nf90_inq_varid, nf90_inquire_dimension, nf90_inq_dimid, nf90_open
c13o2_write_output calls nf90_put_var, c13o2_err_handler
write_blaze_output_nc calls nf90_close, nf90_put_att, handle_err, nf90_put_var, nf90_def_var, nf90_def_dim, nf90_create, nf90_enddef
load_parameters calls pop_io, zero_sum_casa, alloc_sum_casa, nf90_close, pop_init, c13o2_read_restart_flux, derived_parameters, get_parameters_met, alloc_casa_var, c13o2_alloc_flux, handle_err, write_default_params, casa_readphen, c13o2_zero_pools, allocate_cable_vars, get_restart_data, c13o2_zero_flux, popluc_init, write_cnp_params, nc_abort, nf90_inquire_dimension, casa_init, alloc_phenvariable, get_default_params, zero_casa_var, cable_abort, report_parameters, c13o2_init_luc, check_parameter_values, c13o2_alloc_pools, nf90_inq_dimid, c13o2_init_pools, zero_phenvariable, c13o2_read_restart_pools, nf90_open, c13o2_init_flux, casa_readbiome
pop_io calls ne, mpi_abort, nf90_close, nf90_get_var, nf90_put_att, handle_err, nf90_put_var, nf90_def_var, nf90_def_dim, nf90_inq_varid, nf90_inquire_dimension, nf90_create, nf90_inq_dimid, nf90_open, nf90_enddef
alloc_cbm_var calls alloc_bgc_pool_type, alloc_roughness_type, alloc_climate_type, alloc_soil_snow_type, alloc_canopy_type, alloc_balances_type, alloc_air_type, alloc_soil_parameter_type, alloc_met_type, alloc_radiation_type, alloc_sum_flux_type, alloc_veg_parameter_type
cru_get_subdiurnal_met calls nf90_close, open_cru_met, get_cru_co2, handle_err, cru_get_daily_met, wgen_subdiurnal_met, wgen_daily_constants, doysod2ymdhms, wgen_init, get_cru_ndep, eq
c13o2_close_output calls nf90_close, c13o2_err_handler
cable_bios_init calls get_unit, wgen_init, readarcfltheader, daydifference
ini_simfire calls get_unit, nf90_close, nf90_get_var, handle_err, nf90_inq_varid, zero_simfire, nf90_open
master_c13o2_luc_types calls mpi_abort, add_address_hvector, mpi_type_get_extent, mpi_type_free, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
master_casa_luc_types calls mpi_abort, add_address_hvector, mpi_type_get_extent, mpi_type_free, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
ne calls notequal_dp, notequal_sp
create_restart calls nf90_close, define_ovar, nf90_put_att, nf90_put_var, nf90_def_var, nf90_def_dim, nc_abort, nf90_create, toreal4, write_ovar, nf90_enddef
master_cable_params calls mpi_send, master_send_input, mpi_abort, decomp_types, add_address_hvector, mpi_type_get_extent, mpi_type_free, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
close_luh2 calls nf90_close, handle_err
c13o2_sanity_luc calls isosanity
c13o2_update_luc calls mpi_abort, c13o2_save_c13o2pools, isotope_pool_model, delta1000, isotope_luc_model
zero_cbm_var calls zero_sum_flux_type, zero_air_type, zero_soil_parameter_type, zero_climate_type, zero_met_type, zero_canopy_type, zero_veg_parameter_type, zero_roughness_type, zero_balances_type, zero_radiation_type, zero_soil_snow_type, zero_bgc_pool_type
read_climate_restart_nc calls read_netcdf_cbm_var
master_send_input calls mpi_isend, mpi_waitall
master_casaonly_luc calls master_receive_pop, pop_luc_casa_transfer, write_luc_output_nc, mpi_send, pop_io, popluc_set_patchfrac, c13o2_sanity_luc, c13o2_update_luc, master_send_input, c13o2_sanity_pools, write_luc_restart_nc, master_receive, write_luc_output_grid_nc, c13o2_save_luc, write_casa_restart_nc, c13o2_write_restart_pools, c13o2_write_restart_luc, copy_save_variables, poplucstep, alloc_casa_var, pop_init_single, read_casa_dump, read_luh2, alloc_phenvariable, zero_casa_var, zero_phenvariable, eq, popluc_weights_transfer
master_c13o2_flux_params calls master_send_input, mpi_abort, mpi_barrier, add_address_hvector, mpi_type_get_extent, mpi_type_free, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
c13o2_sanity_pools calls isosanity
write_luc_restart_nc calls nf90_close, nf90_redef, nf90_put_att, handle_err, nf90_put_var, nf90_def_var, nf90_def_dim, nf90_create, nf90_enddef
find_extents calls mpi_get_address
master_casa_params calls master_send_input, mpi_abort, mpi_barrier, add_address_1block, add_address_hvector, mpi_type_get_extent, mpi_type_free, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
write_casa_output_nc calls nf90_close, nf90_put_att, handle_err, nf90_put_var, nf90_def_var, nf90_def_dim, nf90_create, nf90_enddef
preparefiles calls renamefiles
open_output_file calls define_ovar, nf90_put_att, nf90_put_var, nf90_def_var, nf90_def_dim, nc_abort, nf90_create, cable_abort, toreal4, write_ovar, nf90_enddef
master_receive calls mpi_irecv, mpi_waitall
master_pop_types calls mpi_send, create_pop_gridcell_type
get_met_data calls is_leapyear, mpi_abort, nf90_get_var, sinbet, nc_abort, cable_abort, rh_sh, eq
c13o2_create_output calls nf90_put_att, nf90_put_var, nf90_def_var, nf90_def_dim, c13o2_err_handler, nf90_create, nf90_enddef
point2constants calls driver_type_ptr, ssnow_type_ptr, cbm_type_ptr, air_type_ptr, rad_type_ptr, canopy_type_ptr, albedo_type_ptr, rough_type_ptr, carbon_type_ptr
lucdriver calls poplucstep, pop_init_single, read_luh2, eq, popluc_weights_transfer
write_output calls is_leapyear, energy_balance, nf90_put_var, nf90_sync, nc_abort, mass_balance, cable_abort, toreal4, write_ovar
master_blaze_types calls mpi_abort, mpi_type_create_hvector, mpi_type_get_extent, mpi_get_address, mpi_type_free, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
plume_mip_init calls get_unit, nf90_close, nf90_get_var, handle_err, nf90_inq_varid, nf90_inquire_dimension, nf90_inq_dimid, nf90_open
master_c13o2_pool_params calls master_send_input, mpi_abort, mpi_barrier, add_address_hvector, mpi_type_get_extent, mpi_type_free, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
master_c13o2_pool_types calls mpi_abort, add_address_hvector, mpi_type_get_extent, mpi_type_free, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
write_luc_output_grid_nc calls nf90_close, nf90_redef, nf90_put_att, handle_err, nf90_put_var, nf90_def_var, nf90_def_dim, nf90_create, nf90_enddef
c13o2_save_luc calls c13o2_save_casapool
cable_bios_load_climate_params calls get_unit
close_output_file calls nf90_close, nc_abort
c13o2_print_delta_luc calls ne, delta1000
master_end calls mpi_type_free
c13o2_write_restart_flux calls nf90_close, nf90_put_att, nf90_put_var, nf90_def_var, nf90_def_dim, c13o2_err_handler, nf90_create, nf90_enddef
write_climate_restart_nc calls write_netcdf_cbm_var
write_casa_restart_nc calls write_netcdf_casa_var, write_netcdf_phen_var
c13o2_print_delta_pools calls ne, delta1000
c13o2_write_restart_pools calls nf90_close, nf90_put_att, nf90_put_var, nf90_def_var, nf90_def_dim, c13o2_err_handler, nf90_create, nf90_enddef
cable_bios_read_met calls wgen_subdiurnal_met, wgen_daily_constants, daydifference, eq
zero_sum_casa calls zero_casapool, zero_casaflux
open_met_file calls is_leapyear, mpi_abort, nf90_get_var, handle_err, nc_abort, nf90_inquire_variable, nf90_inq_varid, nf90_inquire_dimension, doysod2ymdhms, cable_abort, nf90_get_att, nf90_inq_dimid, eq, nf90_open, ymdhms2doysod
master_c13o2_flux_types calls mpi_abort, add_address_hvector, mpi_type_get_extent, mpi_type_free, mpi_type_size, mpi_type_commit, mpi_type_create_struct, mpi_reduce
master_spincasacnp calls casa_fluxout, master_receive_pop, pop_io, master_send_input, c13o2_sanity_pools, master_receive, write_casa_restart_nc, c13o2_write_restart_pools, copy_save_variables, alloc_casa_var, read_casa_dump, alloc_phenvariable, zero_casa_var, zero_phenvariable
c13o2_write_restart_luc calls nf90_close, nf90_put_att, nf90_put_var, nf90_def_var, nf90_def_dim, c13o2_err_handler, nf90_create, nf90_enddef
alloc_sum_casa calls alloc_casaflux, alloc_casapool
open_cru_met calls handle_err, nf90_inq_varid, nf90_open, cru_get_filename, cru_get_metyear
define_ovar calls define_output_variable_r1, define_output_parameter_r1, define_output_parameter_r2, define_output_variable_r2
write_netcdf_cbm_var calls write_netcdf_climate_type
decomp_types calls mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized
create_pop_gridcell_type calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized, create_patch
add_address_1block calls add_address_1block_3d_r2, add_address_1block_1d_i1, add_address_1block_3d_r1, add_address_1block_3d_i1, add_address_1block_2d_l, add_address_1block_1d_r1, add_address_1block_1d_l, add_address_1block_3d_l, add_address_1block_1d_r2, add_address_1block_2d_i1, add_address_1block_2d_r2, add_address_1block_2d_r1
get_cru_co2 calls get_unit
get_plume_ndep calls nf90_get_var, handle_err, nf90_inq_varid, nf90_open
c13o2_read_restart_flux calls nf90_close, nf90_get_var, c13o2_err_handler, nf90_inq_varid, nf90_open
add_address_hvector calls add_address_hvector_2d_i1, add_address_hvector_3d_r1, add_address_hvector_2d_r2, add_address_hvector_1d_l, add_address_hvector_2d_r1, add_address_hvector_1d_i1, add_address_hvector_2d_l, add_address_hvector_3d_l, add_address_hvector_1d_r1, add_address_hvector_3d_i1, add_address_hvector_3d_r2, add_address_hvector_1d_r2
def_dims calls stderr_nc, nf90_def_dim
put_var_nc calls put_var_ncr3, put_var_ncr2, put_var_ncr1
isotope_pool_model calls isotope_pool_model_2d, isotope_pool_model_1d
get_parameters_met calls nf90_inq_varid, readpar
poplucstep calls execute_luc_event, increment_age
alloc_casa_var calls alloc_casaflux, alloc_casabal, alloc_casapool, alloc_casabiome, alloc_casamet
handle_err calls mpi_abort, nf90_strerror
write_default_params calls mpi_abort, cable_abort, init_veg_from_vegin
read_netcdf_cbm_var calls read_netcdf_climate_type
read_casa_dump calls nf90_close, stderr_nc, nf90_open, get_var_nc
cru_get_daily_met calls nf90_close, handle_err, nf90_inq_varid, nf90_inquire_dimension, nf90_inq_dimid, nf90_open, cru_read_metvals, cru_get_filename, cru_get_metyear
allocate_cable_vars calls alloc_cbm_var, zero_cbm_var
get_restart_data calls nf90_close, nf90_get_var, nc_abort, nf90_inq_varid, nf90_inquire_dimension, cable_abort, nf90_inq_dimid, readpar, extrarestart
stderr_nc calls mpi_abort, nf90_strerror
popluc_init calls pop_init_single, read_luc_restart_nc, zero_popluc, alloc_popluc, popluc_set_params
wgen_subdiurnal_met calls mpi_abort
c13o2_err_handler calls mpi_abort
nc_abort calls mpi_abort, nf90_strerror
read_climatefile calls alloc_cbm_var, nf90_close, read_netcdf_cbm_var, nf90_inquire_dimension, nf90_inq_dimid, nf90_open, nc_err
doysod2ymdhms calls is_leapyear, mpi_abort
casa_init calls zero_casa_dump, read_casa_restart_nc
write_netcdf_casa_var calls write_netcdf_casabal, write_netcdf_casamet, write_netcdf_casabiome, write_netcdf_casaflux, write_netcdf_casapool
read_luh2 calls nf90_get_var, handle_err
wgen_init calls wgen_zero
get_default_params calls spatialsoil, countpatch, get_type_parameters, luc_expt_set_tiles_bios, read_soilcolor, get_land_index, read_gridinfo, luc_expt_set_tiles
def_vars calls nf90_def_var, stderr_nc
zero_casa_var calls zero_casapool, zero_casaflux, zero_casamet, zero_casabiome, zero_casabal
cable_abort calls mpi_abort
daydifference calls julianday
toreal4 calls i2sp, dp2sp, sp2sp
c13o2_init_luc calls c13o2_read_restart_luc, c13o2_alloc_luc, c13o2_zero_luc
check_parameter_values calls cable_abort
write_ovar calls write_output_variable_r2, write_output_parameter_r1, write_output_parameter_r1d, write_output_parameter_r2d, write_output_variable_r1, write_output_parameter_r2
isotope_luc_model calls isotope_luc_model_1d
write_netcdf_phen_var calls nf90_close, nf90_put_var, nf90_def_var, nf90_def_dim, nf90_create, nf90_enddef, nc_err
plume_get_daily_met calls nf90_close, nf90_get_var, handle_err, nf90_inq_varid, nf90_inquire_dimension, nf90_inq_dimid, nf90_open, plume_get_filename
open_plume_met calls handle_err, nf90_inq_varid, nf90_get_att, nf90_open, plume_get_filename, leap_day
get_cru_ndep calls nf90_get_var, handle_err, nf90_inq_varid, nf90_open
get_plume_co2 calls get_unit
c13o2_read_restart_pools calls nf90_close, nf90_get_var, c13o2_err_handler, nf90_inq_varid, nf90_open
eq calls equal_dp, equal_sp
c13o2_init_flux calls init_sugar_pools, init_starch_pool
cable_bios_load_biome calls get_unit
ymdhms2doysod calls is_leapyear, mpi_abort
add_address_hvector_2d_i1 calls mpi_type_create_hvector, mpi_get_address
spatialsoil calls nf90_close, nf90_get_var, nc_abort, nf90_inq_varid, nf90_open
define_output_variable_r1 calls nf90_put_att, nf90_def_var, nc_abort, cable_abort
define_output_parameter_r1 calls nf90_put_att, nf90_def_var, nc_abort, cable_abort
add_address_hvector_3d_r1 calls mpi_type_create_hvector, mpi_get_address
add_address_1block_3d_r2 calls mpi_get_address
put_var_ncr3 calls nf90_put_var, stderr_nc, nf90_inq_varid
write_output_variable_r2 calls nf90_put_var, nc_abort, cable_abort, range_abort
write_output_parameter_r1 calls nf90_put_var, nc_abort, cable_abort
write_output_parameter_r1d calls nf90_put_var, nc_abort, cable_abort
write_netcdf_casabal calls nf90_close, nf90_put_var, nf90_def_var, nf90_def_dim, nf90_create, nf90_enddef, nc_err
add_address_hvector_2d_r2 calls mpi_type_create_hvector, mpi_get_address
add_address_1block_1d_i1 calls mpi_get_address
add_address_hvector_1d_l calls mpi_get_address
readpar calls readpar_i, readpar_r2d, readpar_r2, readpar_rd, readpar_r
write_output_parameter_r2d calls nf90_put_var, nc_abort, cable_abort
nc_err calls mpi_abort, nf90_strerror
add_address_1block_3d_r1 calls mpi_get_address
define_output_parameter_r2 calls nf90_put_att, nf90_def_var, nc_abort, cable_abort
define_output_variable_r2 calls nf90_put_att, nf90_def_var, nc_abort, cable_abort
write_netcdf_climate_type calls nf90_close, nf90_put_var, nf90_def_var, nf90_def_dim, nf90_create, nf90_enddef, nc_err
add_address_1block_3d_i1 calls mpi_get_address
add_address_hvector_2d_r1 calls mpi_type_create_hvector, mpi_get_address
read_luc_restart_nc calls nf90_close, nf90_get_var, handle_err, nf90_inq_varid, nf90_inquire_dimension, nf90_inq_dimid, nf90_open
add_address_hvector_1d_i1 calls mpi_get_address
get_var_nc calls get_var_ncr2, get_var_ncr3
isotope_pool_model_2d calls ne, mpi_abort, eq, diag
extrarestart calls nf90_get_var, nc_abort, nf90_inq_varid, readpar, redistr_i, redistr_rd, redistr_r2d, redistr_r, redistr_r2
execute_luc_event calls mpi_abort
add_address_hvector_2d_l calls mpi_type_create_hvector, mpi_get_address
countpatch calls mpi_abort
add_address_1block_2d_l calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
add_address_hvector_3d_l calls mpi_type_create_hvector, mpi_get_address
read_netcdf_climate_type calls mpi_abort, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open, nc_err
add_address_1block_1d_l calls mpi_get_address
cru_read_metvals calls nf90_get_var, handle_err
get_type_parameters calls mpi_abort
add_address_1block_3d_l calls mpi_get_address
write_netcdf_casamet calls nf90_close, nf90_put_var, nf90_def_var, nf90_def_dim, nf90_create, nf90_enddef, nc_err
add_address_hvector_1d_r1 calls mpi_get_address
c13o2_read_restart_luc calls nf90_close, nf90_get_var, c13o2_err_handler, nf90_inq_varid, nf90_open
write_output_variable_r1 calls nf90_put_var, nc_abort, cable_abort, range_abort
isotope_luc_model_1d calls mpi_abort, eq
write_netcdf_casabiome calls nf90_close, nf90_put_var, nf90_def_var, nf90_def_dim, nf90_create, nf90_enddef, nc_err
put_var_ncr2 calls nf90_put_var, stderr_nc, nf90_inq_varid
luc_expt_set_tiles_bios calls cable_bios_load_fracc4
add_address_hvector_3d_i1 calls mpi_type_create_hvector, mpi_get_address
add_address_1block_1d_r2 calls mpi_get_address
add_address_hvector_3d_r2 calls mpi_type_create_hvector, mpi_get_address
read_soilcolor calls ne, nf90_close, nf90_get_var, nc_abort, nf90_inq_varid, nf90_inquire_dimension, nf90_inq_dimid, nf90_open
add_address_1block_2d_i1 calls mpi_get_address
create_patch calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized, create_layer
add_address_1block_2d_r2 calls mpi_get_address
put_var_ncr1 calls nf90_put_var, stderr_nc, nf90_inq_varid
read_casa_restart_nc calls read_netcdf_phen_var, read_netcdf_casa_var
get_land_index calls mpi_abort
leap_day calls is_leapyear
write_output_parameter_r2 calls nf90_put_var, nc_abort, cable_abort
isotope_pool_model_1d calls ne, mpi_abort, eq, diag
add_address_hvector_1d_r2 calls mpi_get_address
write_netcdf_casaflux calls nf90_close, nf90_put_var, nf90_def_var, nf90_def_dim, nf90_create, nf90_enddef, nc_err
read_gridinfo calls nf90_close, nf90_get_var, nc_abort, nf90_inq_varid, nf90_inquire_dimension, cable_abort, nf90_inq_dimid, nf90_open
add_address_1block_2d_r1 calls mpi_get_address
write_netcdf_casapool calls nf90_close, nf90_put_var, nf90_def_var, nf90_def_dim, nf90_create, nf90_enddef, nc_err
cable_bios_load_fracc4 calls get_unit
read_netcdf_phen_var calls mpi_abort, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open, nc_err
create_layer calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized, create_cohort
redistr_i calls mpi_abort
redistr_rd calls mpi_abort, float
range_abort calls mpi_abort
readpar_i calls nf90_get_var, nc_abort, nf90_inquire_variable, nf90_inq_varid, cable_abort
readpar_r2d calls nf90_get_var, nc_abort, nf90_inquire_variable, nf90_inq_varid, cable_abort
readpar_r2 calls nf90_get_var, nc_abort, nf90_inquire_variable, nf90_inq_varid, cable_abort
readpar_rd calls nf90_get_var, nc_abort, nf90_inquire_variable, nf90_inq_varid, cable_abort
readpar_r calls nf90_get_var, nc_abort, nf90_inquire_variable, nf90_inq_varid, cable_abort
get_var_ncr2 calls nf90_get_var, stderr_nc, nf90_inq_varid
get_var_ncr3 calls nf90_get_var, stderr_nc, nf90_inq_varid
diag calls diag_3d, diag_2d
redistr_r2d calls mpi_abort, float
redistr_r calls mpi_abort, float
redistr_r2 calls mpi_abort, float
read_netcdf_casa_var calls read_netcdf_casabiome, read_netcdf_casaflux, read_netcdf_casamet, read_netcdf_casabal, read_netcdf_casapool
create_cohort calls mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_create_resized
diag_3d calls mpi_abort
diag_2d calls mpi_abort
read_netcdf_casabiome calls mpi_abort, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open, nc_err
read_netcdf_casaflux calls mpi_abort, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open, nc_err
read_netcdf_casamet calls mpi_abort, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open, nc_err
read_netcdf_casabal calls mpi_abort, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open, nc_err
read_netcdf_casapool calls mpi_abort, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open, nc_err
mpi_driver calls mpidrv_master