mpidrv_worker – POP
mpidrv_worker Subroutine
398 statements
Source File
public subroutine mpidrv_worker(comm)
Uses
mo_c13o2_photosynthesis
casa_cable
SIMFIRE_MOD
phenvariable
BLAZE_MPI
BLAZE_MOD
cable_c13o2_def
cable_def_types_mod
cable_adjust_JV_gm_module
cable_data_module
cable_cbm_module
cable_climate_mod
POP_Constants
casa_inout
POP_Types
casadimension
cable_IO_vars_module
mpi
casavariable
blaze_drv
mo_isotope
cable_c13o2
cable_common_module
vh_js !! vh_js !! suggest LALLOC should ulitmately be a switch in the .nml file
Arguments
Type Intent Optional Attributes Name
integer :: comm
Calls
Called by
Contents
None
Call graph
mpidrv_worker calls ini_simfire, worker_c13o2_luc_type, is_leapyear, worker_c13o2_pool_type, mpi_bcast, mpi_send, worker_casa_params, cable_climate, worker_c13o2_flux_params, worker_climate_types, mpi_comm_rank, read_gm_lut, worker_pop_types, worker_intype, worker_restart_type, casa_feedback, worker_casaonly_luc, isoratio, worker_spincasacnp, blaze_driver, point2constants, worker_blaze_types, worker_outtype, c13o2_sanity_pools, worker_cable_params, mpi_comm_dup, worker_end, blaze_accounting, worker_casa_dump_types, casa_cnpflux, bgcdriver, cbm, worker_casa_type, worker_c13o2_pool_params, worker_c13o2_luc_params, ini_blaze, mpi_recv, mpi_abort, sumcflux, is_casa_time, worker_send_pop, worker_casa_luc_types, worker_decomp, popdriver, find_extents, worker_c13o2_flux_type
ini_simfire calls zero_simfire, nf90_inq_varid, get_unit, handle_err, nf90_open, nf90_get_var, nf90_close
worker_c13o2_luc_type calls mpi_abort, mpi_type_size, mpi_type_create_struct, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit
worker_c13o2_pool_type calls mpi_abort, mpi_type_size, mpi_type_create_struct, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit
worker_casa_params calls mpi_comm_rank, mpi_recv, mpi_abort, mpi_get_count, alloc_phenvariable, zero_casa_var, mpi_type_size, mpi_type_create_struct, alloc_casa_var, zero_phenvariable, mpi_barrier, mpi_type_free, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit, mpi_unpack
cable_climate calls epsif, biome1_pft
worker_c13o2_flux_params calls mpi_comm_rank, mpi_recv, mpi_abort, mpi_get_count, mpi_type_size, mpi_type_create_struct, mpi_barrier, c13o2_zero_flux, mpi_type_free, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit, mpi_unpack, c13o2_alloc_flux
worker_climate_types calls mpi_recv, mpi_abort, mpi_get_count, mpi_type_size, mpi_type_create_struct, mpi_get_address, zero_cbm_var, alloc_cbm_var, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit, mpi_unpack
read_gm_lut calls nf90_inq_varid, nc_abort, nf90_inq_dimid, nf90_open, nf90_get_var, nf90_close, nf90_inquire_dimension
worker_pop_types calls mpi_comm_rank, mpi_recv, create_pop_gridcell_type, pop_init
worker_intype calls mpi_comm_rank, mpi_abort, mpi_type_size, mpi_type_create_struct, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit
worker_restart_type calls mpi_comm_rank, mpi_abort, mpi_type_size, mpi_type_create_struct, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit
casa_feedback calls point2constants, adjust_k_collatz, adjust_jv_gm, find_vcmax_jmax_lut, vcmax_np, optimise_jv
worker_casaonly_luc calls mpi_send, mpi_comm_rank, c13o2_sanity_pools, mpi_recv, worker_send_pop, popdriver, c13o2_save_casapool, c13o2_update_pools, biogeochem
worker_spincasacnp calls mpi_send, isoratio, blaze_driver, c13o2_sanity_pools, mpi_recv, worker_send_pop, popdriver, c13o2_save_casapool, analyticpool, c13o2_update_pools, biogeochem
blaze_driver calls is_leapyear, run_blaze, blaze_turnover, doysod2ymdhms, adjust_pop_for_fire
point2constants calls air_type_ptr, albedo_type_ptr, ssnow_type_ptr, cbm_type_ptr, rad_type_ptr, canopy_type_ptr, driver_type_ptr, rough_type_ptr, carbon_type_ptr
worker_blaze_types calls mpi_comm_rank, mpi_abort, mpi_type_size, mpi_type_create_struct, mpi_get_address, mpi_reduce, mpi_type_get_extent, mpi_type_commit
worker_outtype calls mpi_comm_rank, mpi_abort, find_extents, mpi_type_size, mpi_type_create_struct, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit
c13o2_sanity_pools calls isosanity
worker_cable_params calls mpi_comm_rank, mpi_recv, mpi_abort, mpi_get_count, mpi_type_size, mpi_type_create_struct, mpi_type_free, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit, mpi_unpack, allocate_cable_vars, decomp_types
worker_end calls mpi_type_free
worker_casa_dump_types calls mpi_comm_rank, mpi_abort, mpi_type_size, mpi_type_create_struct, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit
bgcdriver calls c13o2_save_casapool, cable_phenology_clim, c13o2_update_pools, biogeochem
cbm calls point2constants, ruff_resist, define_canopy, surface_albedo, sli_main, soilcarb, soil_snow, define_air, init_radiation, plantcarb, carbon_pl
worker_casa_type calls mpi_abort, mpi_type_size, mpi_type_create_struct, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit
worker_c13o2_pool_params calls mpi_comm_rank, mpi_recv, mpi_abort, mpi_get_count, mpi_type_size, mpi_type_create_struct, mpi_barrier, c13o2_zero_pools, c13o2_alloc_pools, mpi_type_free, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit, mpi_unpack
worker_c13o2_luc_params calls mpi_comm_rank, mpi_recv, mpi_abort, mpi_get_count, mpi_type_size, mpi_type_create_struct, mpi_barrier, mpi_type_free, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit, mpi_unpack, c13o2_zero_luc, c13o2_alloc_luc
ini_blaze calls zero_blaze, get_unit
is_casa_time calls is_leapyear
worker_send_pop calls mpi_send
worker_casa_luc_types calls mpi_comm_rank, mpi_abort, mpi_type_size, mpi_type_create_struct, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit
worker_decomp calls mpi_recv
popdriver calls popstep
find_extents calls mpi_get_address
worker_c13o2_flux_type calls mpi_abort, mpi_type_size, mpi_type_create_struct, mpi_reduce, add_address_1block, mpi_type_get_extent, mpi_type_commit
ruff_resist calls point2constants
define_canopy calls point2constants, ruff_resist, sli_main, define_air, eq, radiation, dryleaf, surf_wetness_fact
zero_casa_var calls zero_casapool, zero_casabiome, zero_casamet, zero_casaflux, zero_casabal
alloc_casa_var calls alloc_casamet, alloc_casabiome, alloc_casaflux, alloc_casabal, alloc_casapool
adjust_k_collatz calls light_inhibition
surface_albedo calls point2constants, surface_albedosn, calc_rhoch
sli_main calls setlitterpar, tfrz, esat_ice, getrex, thetalmax, solve, zerovars_met, slope_esat_ice, setpar_loetsch, zerovars, seb, esat, setx, setpar, hyofs, setroots, zerovars_snow
nc_abort calls nf90_strerror
adjust_jv_gm calls point2constants, lmdif1, light_inhibition, photosyn25
zero_cbm_var calls zero_radiation_type, zero_soil_snow_type, zero_sum_flux_type, zero_balances_type, zero_met_type, zero_canopy_type, zero_air_type, zero_roughness_type, zero_veg_parameter_type, zero_bgc_pool_type, zero_climate_type, zero_soil_parameter_type
create_pop_gridcell_type calls mpi_abort, mpi_type_create_struct, mpi_get_address, mpi_type_commit, mpi_type_create_resized, create_patch
pop_init calls zeropop, layer_recruitment_single_patch, alloc_pop, initpop2d_poisson
find_vcmax_jmax_lut calls light_inhibition
run_blaze calls is_leapyear, blaze_turnover, doysod2ymdhms, combust, simfire, avail_fuel
popstep calls patch_partial_disturb2, patch_disturb, patchannualdynamics, getdiagnostics, getpatchfrequencies, patch_partial_disturb, getuniqueagefrequencies
alloc_cbm_var calls alloc_canopy_type, alloc_met_type, alloc_roughness_type, alloc_climate_type, alloc_air_type, alloc_bgc_pool_type, alloc_balances_type, alloc_veg_parameter_type, alloc_sum_flux_type, alloc_radiation_type, alloc_soil_snow_type, alloc_soil_parameter_type
cable_phenology_clim calls eq, ge
soil_snow calls point2constants, snow_melting, snowcheck, snowl_adjust, soilfreeze_serial, hydraulic_redistribution, surfbv, snow_accum, stempv, remove_trans, snowdensity
handle_err calls nf90_strerror
add_address_1block calls add_address_1block_1d_r2, add_address_1block_3d_r1, add_address_1block_2d_r1, add_address_1block_2d_i1, add_address_1block_2d_r2, add_address_1block_3d_l, add_address_1block_1d_i1, add_address_1block_1d_r1, add_address_1block_1d_l, add_address_1block_2d_l, add_address_1block_3d_r2, add_address_1block_3d_i1
allocate_cable_vars calls zero_cbm_var, alloc_cbm_var
decomp_types calls mpi_type_create_struct, mpi_get_address, mpi_type_commit, mpi_type_create_resized
doysod2ymdhms calls is_leapyear
adjust_pop_for_fire calls topkill_collins, interpolate_firemortality
define_air calls point2constants
c13o2_update_pools calls c13o2_c13o2pools_back, c13o2_save_c13o2pools, c13o2_sinks_pools, c13o2_sources_pools, isotope_pool_model, c13o2_fluxmatrix_pools
biogeochem calls casa_cnpflux, phenology, casa_coeffsoil, casa_allocation, casa_puptake, casa_delplant, casa_xkn, casa_delsoil, casa_pdummy, casa_coeffplant, casa_ndummy, casa_cnpcycle, casa_xrateplant, casa_nuptake, avgsoil, casa_xnp, casa_cnpbal, casa_rplant, casa_xratesoil
init_radiation calls point2constants, spitter, calc_rhoch
plantcarb calls point2constants
optimise_jv calls point2constants, diff_ac_aj, total_photosynthesis_cost, rtbis, golden
getrex calls getrex_1d, getrex_2d
add_address_1block_1d_r2 calls mpi_get_address
thetalmax calls tfrz
solve calls zerovars, hyofs, hyofh, litter_props, timestep_loop, sofh, setsol
add_address_1block_3d_r1 calls mpi_get_address
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
eq calls equal_sp, equal_dp
patch_disturb calls layer_recruitment_single_patch
lmdif1 calls lmdif
add_address_1block_2d_r2 calls mpi_get_address
casa_allocation calls casa_wolf
combust calls avail_fuel
layer_recruitment_single_patch calls get_allometry
simfire calls is_leapyear, get_popdens, annual_ba
patchannualdynamics calls get_allometry, layer_recruitment
surface_albedosn calls soilcol_albedo
seb calls hyofh, slope_csat, potential_evap
add_address_1block_3d_l calls mpi_get_address
ge calls greaterequal_sp, greaterequal_dp
add_address_1block_1d_i1 calls mpi_get_address
diff_ac_aj calls point2constants, xvcmxt3_acclim, xgmest, fpq, xejmxt3_acclim, fam_c3, xrdt, xvcmxt3, ej3x, fabcd, fan_c3, fabc, light_inhibition, xejmxt3
casa_puptake calls casa_prequire
add_address_1block_1d_r1 calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
getdiagnostics calls get_allometry, smooth_flux, interpolate_biomass_1d, interpolate_biomass_2d
add_address_1block_2d_l calls mpi_get_address
hyofs calls tfrz, igamma, dthetalmaxdt, slope_esat
surfbv calls smoisturev
add_address_1block_3d_r2 calls mpi_get_address
casa_cnpcycle calls casa_poolzero
casa_xrateplant calls ge, le
casa_nuptake calls casa_nrequire
total_photosynthesis_cost calls point2constants, xvcmxt3_acclim, xgmest, fpq, xejmxt3_acclim, fam_c3, xrdt, xvcmxt3, ej3x, fabcd, fan_c3, fabc, light_inhibition, xejmxt3
stempv calls trimb
interpolate_firemortality calls realexponential
casa_xnp calls casa_nrequire, casa_prequire
rtbis calls eq, ge, le
dryleaf calls light_inhibition, xvcmxt3_acclim, photosynthesis_gm, xgmest, xejmxt3_acclim, fwsoil_calc_std, xvcmxt4_acclim, getrex_1d, xvcmxt4, xrdt, xvcmxt3, ej3x, fwsoil_calc_non_linear, xejmxt3, fwsoil_calc_lai_katul
setroots calls setroots_1d, setroots_2d
casa_rplant calls vcmax_np
create_patch calls mpi_abort, mpi_type_create_struct, mpi_get_address, mpi_type_commit, mpi_type_create_resized, create_layer
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
add_address_1block_3d_i1 calls mpi_get_address
getuniqueagefrequencies calls realexponential, cumexponential
initpop2d_poisson calls cumexponential, exponential
xvcmxt3_acclim calls point2constants
photosynthesis_gm calls famdam_c4, famdam_c3, fandan_c3, fandan_c4
get_allometry calls getheight, williams_allometry, allometry
get_popdens calls get_unit
getrex_2d calls getrex_1d
litter_props calls slope_esat
timestep_loop calls litter_props, iflux_loop, isotope_vap
xgmest calls point2constants
le calls lesserequal_dp, lesserequal_sp
xejmxt3_acclim calls point2constants
xvcmxt4_acclim calls point2constants
isotope_pool_model_1d calls mpi_abort, eq, diag, ne
igamma calls gammln, gser, gcf
dthetalmaxdt calls tfrz
smoisturev calls trimb
smooth_flux calls regress
xvcmxt4 calls point2constants
potential_evap calls slope_esat_ice, slope_esat
layer_recruitment calls get_allometry
lmdif calls eq, ge, le, qrfac, fdjac2, lmpar, ne, enorm
xvcmxt3 calls point2constants
interpolate_biomass_1d calls realexponential
create_layer calls mpi_abort, mpi_type_create_struct, mpi_get_address, mpi_type_commit, mpi_type_create_resized, create_cohort
isotope_pool_model_2d calls mpi_abort, eq, diag, ne
xejmxt3 calls point2constants
setroots_2d calls setroots_1d
interpolate_biomass_2d calls eq, realexponential, area_triangle
diag calls diag_2d, diag_3d
qrfac calls le, ne, enorm
famdam_c4 calls fdam_c4, fdabcm, fabcm, fam_c4
iflux_loop calls hyofs, litter_props, update_s_t, snow_adjust, get_and_solve_eqn, estimate_timestep, get_fluxes_and_derivs, update_unknowns
isotope_vap calls ne, tri
gser calls eq, gammln
fdjac2 calls eq
lmpar calls eq, le, enorm, qrsolv
create_cohort calls mpi_abort, mpi_type_create_struct, mpi_get_address, mpi_type_commit, mpi_type_create_resized
ne calls notequal_sp, notequal_dp
famdam_c3 calls fpq, fam_c3, fdpq, fdam_c3, fabcd, fdabcd
fandan_c3 calls fdabc, fdan_c3, fan_c3, fabc
fandan_c4 calls fabc_c4, fdan_c4, fan_c4, fdabc_c4
gcf calls eq, gammln
update_s_t calls tfrz, thetalmax, gtfrozen, rtbis_tfrozen, dthetalmaxdth, jsoillayer
tri calls tri_1d, tri_2d
diag_2d calls mpi_abort
snow_adjust calls tfrz, esat_ice, thetalmax, slope_esat_ice, gtfrozen, rtbis_tfrozen, jsoillayer
get_and_solve_eqn calls tfrz, massman_sparse
diag_3d calls mpi_abort
get_fluxes_and_derivs calls zerovars, seb, flux, getfluxes_vp, getheatfluxes
update_unknowns calls jsoillayer
qrsolv calls eq, ne
gtfrozen calls tfrz
rtbis_tfrozen calls gtfrozen
dthetalmaxdth calls tfrz
jsoillayer calls tfrz
massman_sparse calls massman_sparse_1d, massman_sparse_2d
flux calls weight
getfluxes_vp calls getfluxes_vp_1d, getfluxes_vp_2d
getheatfluxes calls getheatfluxes_1d, getheatfluxes_2d
massman_sparse_1d calls generic_thomas
weight calls hyofh
massman_sparse_2d calls generic_thomas
getfluxes_vp_1d calls eq, zerovars, hyofh, flux
getfluxes_vp_2d calls eq, zerovars, hyofh, flux
generic_thomas calls generic_thomas_1d, generic_thomas_2d
mpi_driver calls mpidrv_worker