nc_err – POP
nc_err Subroutine
12 statements
Source File
public subroutine nc_err(status, ivar)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: status
integer, intent(inout), optional :: ivar
Calls
Called by
Contents
Call graph
nc_err calls nf90_strerror
write_netcdf_casabiome calls nc_err
write_netcdf_phen_var calls nc_err
write_netcdf_casabal calls nc_err
read_netcdf_casaflux calls nc_err
read_netcdf_climate_type calls nc_err
write_netcdf_climate_type calls nc_err
write_netcdf_casamet calls nc_err
read_netcdf_casabiome calls nc_err
read_netcdf_casapool calls nc_err
read_netcdf_casamet calls nc_err
read_netcdf_casabal calls nc_err
read_netcdf_phen_var calls nc_err
write_netcdf_casaflux calls nc_err
write_netcdf_casapool calls nc_err
write_netcdf_casa_var calls write_netcdf_casabiome, write_netcdf_casabal, write_netcdf_casamet, write_netcdf_casaflux, write_netcdf_casapool
read_netcdf_casa_var calls read_netcdf_casaflux, read_netcdf_casabiome, read_netcdf_casapool, read_netcdf_casamet, read_netcdf_casabal
write_casa_restart_nc calls write_netcdf_phen_var, write_netcdf_casa_var
read_netcdf_cbm_var calls read_netcdf_climate_type
write_netcdf_cbm_var calls write_netcdf_climate_type
read_casa_restart_nc calls read_netcdf_phen_var, read_netcdf_casa_var
master_spincasacnp calls write_casa_restart_nc
mpidrv_master calls write_casa_restart_nc, master_spincasacnp, master_casaonly_luc, read_climate_restart_nc, write_climate_restart_nc, luc_expt_init, load_parameters
read_climatefile calls read_netcdf_cbm_var
cable_offline_driver calls write_casa_restart_nc, read_climate_restart_nc, write_climate_restart_nc, luc_expt_init, load_parameters
master_casaonly_luc calls write_casa_restart_nc
read_climate_restart_nc calls read_netcdf_cbm_var
write_climate_restart_nc calls write_netcdf_cbm_var
casa_init calls read_casa_restart_nc
mpi_driver calls mpidrv_master
luc_expt_init calls read_climatefile
load_parameters calls casa_init