nc_err – POP
nc_err Subroutine
15 statements
Source File
public subroutine nc_err(status, ivar)
Uses
netcdf
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: status
integer, intent(inout), optional :: ivar
Calls
Called by
Contents
None
Call graph
nc_err calls nf90_strerror, mpi_abort
write_netcdf_casabal calls nc_err
write_netcdf_casamet calls nc_err
write_netcdf_climate_type calls nc_err
read_netcdf_casabiome calls nc_err
read_netcdf_casabal calls nc_err
read_netcdf_casaflux calls nc_err
write_netcdf_phen_var calls nc_err
read_netcdf_casamet calls nc_err
read_netcdf_casapool calls nc_err
write_netcdf_casabiome calls nc_err
write_netcdf_casapool calls nc_err
write_netcdf_casaflux calls nc_err
read_netcdf_phen_var calls nc_err
read_netcdf_climate_type calls nc_err
write_netcdf_casa_var calls write_netcdf_casabal, write_netcdf_casamet, write_netcdf_casabiome, write_netcdf_casapool, write_netcdf_casaflux
write_casa_restart_nc calls write_netcdf_phen_var, write_netcdf_casa_var
read_casa_restart_nc calls read_netcdf_phen_var, read_netcdf_casa_var
write_netcdf_cbm_var calls write_netcdf_climate_type
read_netcdf_casa_var calls read_netcdf_casabiome, read_netcdf_casabal, read_netcdf_casaflux, read_netcdf_casamet, read_netcdf_casapool
read_netcdf_cbm_var calls read_netcdf_climate_type
master_spincasacnp calls write_casa_restart_nc
casa_init calls read_casa_restart_nc
master_casaonly_luc calls write_casa_restart_nc
mpidrv_master calls write_casa_restart_nc, master_spincasacnp, master_casaonly_luc, write_climate_restart_nc, read_climate_restart_nc, load_parameters, luc_expt_init
cable_offline_driver calls write_casa_restart_nc, write_climate_restart_nc, read_climate_restart_nc, load_parameters, luc_expt_init
write_climate_restart_nc calls write_netcdf_cbm_var
read_climate_restart_nc calls read_netcdf_cbm_var
read_climatefile calls read_netcdf_cbm_var
load_parameters calls casa_init
mpi_driver calls mpidrv_master
luc_expt_init calls read_climatefile