notequal_dp – POP
notequal_dp Function
11 statements
Source File
private pure elemental function notequal_dp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a
real(kind=dp), intent(in) :: b
Return Value logical
Called by
Contents
None
Call graph
ne calls notequal_dp
notequal calls notequal_dp
qrsolv calls ne
c13o2_discrimination calls ne
rwupdt calls ne
isotope_vap calls ne
read_soilcolor calls ne
enorm2 calls ne
qrfac calls ne
dogleg calls ne
r1updt calls ne
hybrj calls ne, qrfac, dogleg, r1updt, qform
lmdif calls ne, qrfac, lmpar
chkder calls ne
qform calls ne
isotope_pool_model_1d calls ne
hybrd calls ne, qrfac, dogleg, r1updt, qform
lmstr calls ne, rwupdt, qrfac, lmpar
pop_io calls ne
isotope_pool_model_2d calls ne
c13o2_print_delta_luc calls ne
mpidrv_master calls ne, pop_io, c13o2_print_delta_luc, c13o2_print_delta_pools, c13o2_print_delta_flux, load_parameters, master_casaonly_luc, master_spincasacnp, c13o2_update_luc
cable_offline_driver calls ne, pop_io, c13o2_print_delta_luc, c13o2_print_delta_pools, c13o2_print_delta_flux, load_parameters, c13o2_update_luc, casaonly_luc, bgcdriver, spincasacnp, casa_feedback, cbm
lmder calls ne, qrfac, lmpar
c13o2_print_delta_pools calls ne
c13o2_print_delta_flux calls ne
mpi_driver calls mpidrv_master, mpidrv_worker
lmder1 calls lmder
lmpar calls qrsolv
timestep_loop calls isotope_vap
get_default_params calls read_soilcolor
hybrj1 calls hybrj
lmdif1 calls lmdif
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
hybrd1 calls hybrd
lmstr1 calls lmstr
load_parameters calls pop_io, get_default_params
master_casaonly_luc calls pop_io, c13o2_update_luc
master_spincasacnp calls pop_io
solve calls timestep_loop
c13o2_update_pools calls isotope_pool_model
adjust_jv_gm calls lmdif1
c13o2_update_luc calls isotope_pool_model
sli_main calls solve
casaonly_luc calls c13o2_update_pools, c13o2_update_luc
worker_spincasacnp calls c13o2_update_pools
bgcdriver calls c13o2_update_pools
worker_casaonly_luc calls c13o2_update_pools
spincasacnp calls c13o2_update_pools
casa_feedback calls adjust_jv_gm
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls worker_spincasacnp, bgcdriver, worker_casaonly_luc, casa_feedback, cbm