open_output_file – POP
open_output_file Subroutine
788 statements
Source File
public subroutine open_output_file(dels, soil, veg, bgc, rough)
Uses
casadimension
vh_js !! vh_js !!
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_parameter_type), intent(in) :: soil
type(veg_parameter_type), intent(in) :: veg
type(bgc_pool_type), intent(in) :: bgc
type(roughness_type), intent(in) :: rough
Calls
Called by
Contents
None
Call graph
open_output_file calls toreal4, write_ovar, nf90_create, nf90_def_dim, nc_abort, nf90_def_var, nf90_put_att, define_ovar, cable_abort, nf90_enddef, nf90_put_var
toreal4 calls dp2sp, sp2sp, i2sp
write_ovar calls write_output_parameter_r1d, write_output_variable_r1, write_output_parameter_r2, write_output_parameter_r1, write_output_variable_r2, write_output_parameter_r2d
nc_abort calls nf90_strerror, mpi_abort
define_ovar calls define_output_parameter_r2, define_output_variable_r2, define_output_variable_r1, define_output_parameter_r1
cable_abort calls mpi_abort
define_output_parameter_r2 calls nc_abort, nf90_def_var, nf90_put_att, cable_abort
define_output_variable_r2 calls nc_abort, nf90_def_var, nf90_put_att, cable_abort
define_output_variable_r1 calls nc_abort, nf90_def_var, nf90_put_att, cable_abort
write_output_parameter_r1d calls nc_abort, cable_abort, nf90_put_var
write_output_variable_r1 calls nc_abort, cable_abort, nf90_put_var, range_abort
write_output_parameter_r2 calls nc_abort, cable_abort, nf90_put_var
write_output_parameter_r1 calls nc_abort, cable_abort, nf90_put_var
write_output_variable_r2 calls nc_abort, cable_abort, nf90_put_var, range_abort
write_output_parameter_r2d calls nc_abort, cable_abort, nf90_put_var
define_output_parameter_r1 calls nc_abort, nf90_def_var, nf90_put_att, cable_abort
range_abort calls mpi_abort
mpidrv_master calls open_output_file
cable_offline_driver calls open_output_file
mpi_driver calls mpidrv_master