optimise_JV – POP
optimise_JV Subroutine
135 statements
Source File
public subroutine optimise_JV(veg, climate, ktauday, bjv, relcostJ)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
type(climate_type), intent(in) :: climate
integer, intent(in) :: ktauday
real, intent(in), DIMENSION(mp) :: bjv
real, intent(in), DIMENSION(mp) :: relcostJ
Calls
Called by
Contents
None
Call graph
optimise_jv calls point2constants, total_photosynthesis_cost, golden, rtbis, diff_ac_aj
point2constants calls driver_type_ptr, cbm_type_ptr, albedo_type_ptr, canopy_type_ptr, carbon_type_ptr, rough_type_ptr, ssnow_type_ptr, air_type_ptr, rad_type_ptr
total_photosynthesis_cost calls point2constants, xvcmxt3_acclim, xrdt, fpq, light_inhibition, fam_c3, xgmest, ej3x, xvcmxt3, fabcd, xejmxt3_acclim, fan_c3, xejmxt3, fabc
rtbis calls le, ge, eq
diff_ac_aj calls point2constants, xvcmxt3_acclim, xrdt, fpq, light_inhibition, fam_c3, xgmest, ej3x, xvcmxt3, fabcd, xejmxt3_acclim, fan_c3, xejmxt3, fabc
le calls lesserequal_sp, lesserequal_dp
xvcmxt3_acclim calls point2constants
xgmest calls point2constants
xvcmxt3 calls point2constants
xejmxt3_acclim calls point2constants
xejmxt3 calls point2constants
ge calls greaterequal_sp, greaterequal_dp
eq calls equal_sp, equal_dp
casa_feedback calls optimise_jv
mpidrv_worker calls casa_feedback
cable_offline_driver calls casa_feedback
mpi_driver calls mpidrv_worker