photosynthesis_gm – POP
photosynthesis_gm Subroutine
178 statements
Source File
private subroutine photosynthesis_gm(csxz, cx1z, cx2z, gswminz, rdxz, vcmxt3z, vcmxt4z, vx3z, vx4z, gs_coeffz, vlaiz, deltlfz, anxz, fwsoilz, qs, gmes, kc4, anrubiscoz, anrubpz, ansinkz, eta, dA)
Uses
cable_def_types_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), dimension(mp,mf) :: csxz
real, intent(in), dimension(mp,mf) :: cx1z
real, intent(in), dimension(mp,mf) :: cx2z
real, intent(inout), dimension(mp,mf) :: gswminz
real, intent(in), dimension(mp,mf) :: rdxz
real, intent(in), dimension(mp,mf) :: vcmxt3z
real, intent(in), dimension(mp,mf) :: vcmxt4z
real, intent(in), dimension(mp,mf) :: vx3z
real, intent(in), dimension(mp,mf) :: vx4z
real, intent(in), dimension(mp,mf) :: gs_coeffz
real, intent(in), dimension(mp,mf) :: vlaiz
real, intent(in), dimension(mp,mf) :: deltlfz
real, intent(inout), dimension(mp,mf) :: anxz
real, intent(in), dimension(mp) :: fwsoilz
real, intent(in) :: qs
real, intent(in), dimension(mp,mf) :: gmes
real, intent(in), dimension(mp,mf) :: kc4
real, intent(inout), dimension(mp,mf) :: anrubiscoz
real, intent(inout), dimension(mp,mf) :: anrubpz
real, intent(inout), dimension(mp,mf) :: ansinkz
real(kind=r_2), intent(out), dimension(mp,mf) :: eta
real(kind=r_2), intent(out), dimension(mp,mf) :: dA
Calls
Called by
Contents
None
Call graph
photosynthesis_gm calls famdam_c3, fandan_c3, famdam_c4, fandan_c4
famdam_c3 calls fabcd, fdabcd, fam_c3, fpq, fdpq, fdam_c3
fandan_c3 calls fabc, fdan_c3, fdabc, fan_c3
famdam_c4 calls fdabcm, fdam_c4, fabcm, fam_c4
fandan_c4 calls fdan_c4, fan_c4, fabc_c4, fdabc_c4
dryleaf calls photosynthesis_gm
define_canopy calls dryleaf
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker