plantcarb – POP
plantcarb Subroutine
19 statements
Source File
public subroutine plantcarb(veg, bgc, met, canopy)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(in) :: veg
type(bgc_pool_type), intent(in) :: bgc
type(met_type), intent(in) :: met
type(canopy_type), intent(inout) :: canopy
Calls
Called by
Contents
Call graph
plantcarb calls point2constants
point2constants calls driver_type_ptr, air_type_ptr, cbm_type_ptr, canopy_type_ptr, albedo_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr
cbm calls plantcarb
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker