POP_init – POP
POP_init Subroutine
27 statements
Source File
public subroutine POP_init(POP, disturbance_interval, np, Iwood, precip)
Uses
POP_Types
TypeDef
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: disturbance_interval(:,:)
integer(kind=i4b), intent(in) :: np
integer(kind=i4b), intent(in) :: Iwood(:)
real(kind=dp), intent(in), optional :: precip(:)
Calls
Called by
Contents
None
Call graph
pop_init calls alloc_pop, zeropop, initpop2d_poisson, layer_recruitment_single_patch
initpop2d_poisson calls exponential, cumexponential
layer_recruitment_single_patch calls get_allometry
get_allometry calls getheight, allometry, williams_allometry
load_parameters calls pop_init
worker_pop_types calls pop_init
mpidrv_master calls load_parameters
mpidrv_worker calls worker_pop_types
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master, mpidrv_worker