POPdriver – POP
POPdriver Subroutine
39 statements
Source File
public subroutine POPdriver(casaflux, casabal, veg, POP)
Uses
POP_Types
casadimension
casaparm
casavariable
cable_common_module
phenvariable
POPModule
TypeDef
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(casa_flux), intent(in) :: casaflux
type(casa_balance), intent(in) :: casabal
type(veg_parameter_type), intent(in) :: veg
type(POP_TYPE), intent(inout) :: POP
Calls
Called by
Contents
None
Call graph
popdriver calls popstep
popstep calls patchannualdynamics, patch_disturb, getuniqueagefrequencies, patch_partial_disturb2, patch_partial_disturb, getpatchfrequencies, getdiagnostics
patchannualdynamics calls get_allometry, layer_recruitment
patch_disturb calls layer_recruitment_single_patch
getuniqueagefrequencies calls realexponential, cumexponential
getdiagnostics calls get_allometry, interpolate_biomass_1d, interpolate_biomass_2d, smooth_flux
get_allometry calls getheight, williams_allometry, allometry
layer_recruitment_single_patch calls get_allometry
layer_recruitment calls get_allometry
interpolate_biomass_1d calls realexponential
interpolate_biomass_2d calls realexponential, eq, area_triangle
smooth_flux calls regress
eq calls equal_sp, equal_dp
casaonly_luc calls popdriver
worker_spincasacnp calls popdriver
mpidrv_worker calls popdriver, worker_spincasacnp, worker_casaonly_luc
spincasacnp calls popdriver
worker_casaonly_luc calls popdriver
cable_offline_driver calls popdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker