POPLUCStep – POP
POPLUCStep Subroutine
26 statements
Source File
public subroutine POPLUCStep(POPLUC, year)
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(inout) :: POPLUC
integer(kind=i4b), intent(in) :: year
Calls
Called by
Contents
Call graph
poplucstep calls increment_age, execute_luc_event
lucdriver calls poplucstep
casaonly_luc calls poplucstep
master_casaonly_luc calls poplucstep
cable_offline_driver calls lucdriver, casaonly_luc
mpidrv_master calls master_casaonly_luc, lucdriver
mpi_driver calls mpidrv_master