POPStep – POP
POPStep Subroutine
61 statements
Source File
public subroutine POPStep(POP, StemNPP, disturbance_interval, disturbance_intensity, LAI, Cleaf, Croot, NPPtoGPP, StemNPP_av, frac_intensity1, precip)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
real(kind=dp), intent(in) :: StemNPP(:,:)
integer(kind=i4b), intent(in) :: disturbance_interval(:,:)
real(kind=dp), intent(in) :: disturbance_intensity(:,:)
real(kind=dp), intent(in) :: LAI(:)
real(kind=dp), intent(in) :: Cleaf(:)
real(kind=dp), intent(in) :: Croot(:)
real(kind=dp), intent(in) :: NPPtoGPP(:)
real(kind=dp), intent(in), optional :: StemNPP_av(:)
real(kind=dp), intent(in), optional :: frac_intensity1(:)
real(kind=dp), intent(in), optional :: precip(:)
Calls
Called by
Contents
Call graph
popstep calls patchannualdynamics, patch_partial_disturb2, patch_disturb, getuniqueagefrequencies, patch_partial_disturb, getpatchfrequencies, getdiagnostics
patchannualdynamics calls get_allometry, layer_recruitment
patch_disturb calls layer_recruitment_single_patch
getuniqueagefrequencies calls cumexponential, realexponential
getdiagnostics calls get_allometry, interpolate_biomass_1d, interpolate_biomass_2d, smooth_flux
get_allometry calls getheight, allometry, williams_allometry
layer_recruitment_single_patch calls get_allometry
layer_recruitment calls get_allometry
interpolate_biomass_1d calls realexponential
interpolate_biomass_2d calls realexponential, area_triangle, eq
smooth_flux calls regress
eq calls equal_sp, equal_dp
popdriver calls popstep
worker_spincasacnp calls popdriver
mpidrv_worker calls popdriver, worker_spincasacnp, worker_casaonly_luc
casaonly_luc calls popdriver
worker_casaonly_luc calls popdriver
spincasacnp calls popdriver
cable_offline_driver calls popdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker