put_var_ncr2 – POP
put_var_ncr2 Subroutine
13 statements
Source File
public subroutine put_var_ncr2(ncid, var_name, var, n_call)
Uses
netcdf
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: var_name
real(kind=r_2), intent(in), dimension(:) :: var
integer, intent(in) :: n_call
Calls
Called by
Contents
None
Call graph
put_var_ncr2 calls nf90_inq_varid, nf90_put_var, stderr_nc
stderr_nc calls nf90_strerror, mpi_abort
put_var_nc calls put_var_ncr2
write_casa_dump calls put_var_nc
mpidrv_master calls write_casa_dump
cable_offline_driver calls write_casa_dump
mpi_driver calls mpidrv_master