qrfac – POP
qrfac Subroutine
76 statements
Source File
public subroutine qrfac(m, n, a, lda, pivot, ipvt, lipvt, rdiag, acnorm)
************80
QRFAC computes a QR factorization using Householder transformations.
Arguments
Type Intent Optional Attributes Name
integer :: m
integer :: n
real(kind=r_2) :: a(lda,n)
integer :: lda
logical :: pivot
integer :: ipvt(lipvt)
integer :: lipvt
real(kind=r_2) :: rdiag(n)
real(kind=r_2) :: acnorm(n)
Calls
Called by
Contents
None
Call graph
qrfac calls enorm, ne, le
ne calls notequal_sp, notequal_dp
le calls lesserequal_sp, lesserequal_dp
hybrd calls qrfac
lmdif calls qrfac
hybrj calls qrfac
lmstr calls qrfac
lmder calls qrfac
hybrd1 calls hybrd
lmdif1 calls lmdif
lmstr1 calls lmstr
lmder1 calls lmder
hybrj1 calls hybrj
adjust_jv_gm calls lmdif1
casa_feedback calls adjust_jv_gm
mpidrv_worker calls casa_feedback
cable_offline_driver calls casa_feedback
mpi_driver calls mpidrv_worker