qrsolv – POP
qrsolv Subroutine
79 statements
Source File
public subroutine qrsolv(n, r, ldr, ipvt, diag, qtb, x, sdiag)
************80
QRSOLV solves a rectangular linear system A*x=b in the least squares sense.
Arguments
Type Intent Optional Attributes Name
integer :: n
real(kind=r_2) :: r(ldr,n)
integer :: ldr
integer :: ipvt(n)
real(kind=r_2) :: diag(n)
real(kind=r_2) :: qtb(n)
real(kind=r_2) :: x(n)
real(kind=r_2) :: sdiag(n)
Calls
Called by
Contents
None
Call graph
qrsolv calls ne, eq
ne calls notequal_sp, notequal_dp
eq calls equal_dp, equal_sp
lmpar calls qrsolv
lmder calls lmpar
lmdif calls lmpar
lmstr calls lmpar
lmder1 calls lmder
lmstr1 calls lmstr
lmdif1 calls lmdif
adjust_jv_gm calls lmdif1
casa_feedback calls adjust_jv_gm
mpidrv_worker calls casa_feedback
cable_offline_driver calls casa_feedback
mpi_driver calls mpidrv_worker