read_gm_LUT – POP
read_gm_LUT Subroutine
60 statements
Source File
public subroutine read_gm_LUT(gm_LUT_file, LUT_VcmaxJmax, LUT_gm, LUT_vcmax, LUT_Rd)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: gm_LUT_file
real(kind=dp), intent(out), dimension(:,:,:,:), allocatable :: LUT_VcmaxJmax
real(kind=dp), intent(out), dimension(:), allocatable :: LUT_gm
real(kind=dp), intent(out), dimension(:), allocatable :: LUT_vcmax
real(kind=dp), intent(out), dimension(:), allocatable :: LUT_Rd
Calls
Called by
Contents
Call graph
read_gm_lut calls nf90_open, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nc_abort, nf90_get_var, nf90_close
nc_abort calls nf90_strerror
mpidrv_worker calls read_gm_lut
cable_offline_driver calls read_gm_lut
mpidrv_master calls read_gm_lut
mpi_driver calls mpidrv_worker, mpidrv_master