read_netcdf_casamet – POP
read_netcdf_casamet Subroutine
110 statements
Source File
private subroutine read_netcdf_casamet(filename, casamet)
Uses
cable_def_types_mod
netcdf
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_met), intent(inout) :: casamet
Calls
Called by
Contents
Call graph
read_netcdf_casamet calls nf90_open, nf90_get_var, nf90_inq_varid, nc_err, nf90_close
nc_err calls nf90_strerror
read_netcdf_casa_var calls read_netcdf_casamet
read_casa_restart_nc calls read_netcdf_casa_var
casa_init calls read_casa_restart_nc
load_parameters calls casa_init
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master