read_casa_dump – POP
read_casa_dump Subroutine
178 statements
Source File
public subroutine read_casa_dump(ncfile, casamet, casaflux, phen, climate, c13o2flux, ncall, kend, allatonce)
Uses
netcdf
phenvariable
cable_diag_module
cable_c13o2_def
casavariable
cable_common_module
cable_def_types_mod
casadimension
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: ncfile
type(casa_met), intent(inout) :: casamet
type(casa_flux), intent(inout) :: casaflux
type(phen_variable), intent(inout) :: phen
type(climate_type), intent(inout) :: climate
type(c13o2_flux), intent(inout) :: c13o2flux
integer, intent(in) :: ncall
integer, intent(in) :: kend
logical, intent(in) :: allatonce
Calls
Called by
Contents
None
Call graph
read_casa_dump calls nf90_open, nf90_close, stderr_nc, get_var_nc
stderr_nc calls nf90_strerror, mpi_abort
get_var_nc calls get_var_ncr2, get_var_ncr3
get_var_ncr2 calls stderr_nc, nf90_inq_varid, nf90_get_var
get_var_ncr3 calls stderr_nc, nf90_inq_varid, nf90_get_var
casaonly_luc calls read_casa_dump
spincasacnp calls read_casa_dump
master_spincasacnp calls read_casa_dump
master_casaonly_luc calls read_casa_dump
cable_offline_driver calls read_casa_dump, casaonly_luc, spincasacnp
mpidrv_master calls master_spincasacnp, master_casaonly_luc
mpi_driver calls mpidrv_master