read_netcdf_casabiome – POP
read_netcdf_casabiome Subroutine
125 statements
Source File
private subroutine read_netcdf_casabiome(filename, casabiome)
Uses
netcdf
mpi
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_biome), intent(inout) :: casabiome
Calls
Called by
Contents
None
Call graph
read_netcdf_casabiome calls mpi_abort, nf90_inq_varid, nf90_get_var, nc_err, nf90_open, nf90_close
nc_err calls mpi_abort, nf90_strerror
read_netcdf_casa_var calls read_netcdf_casabiome
read_casa_restart_nc calls read_netcdf_casa_var
casa_init calls read_casa_restart_nc
load_parameters calls casa_init
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master