readpar_i – POP
readpar_i Subroutine
69 statements
Source File
private subroutine readpar_i(ncid, parname, completeSet, var_i, filename, npatch, dimswitch, from_restart, INpatch)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: parname
logical, intent(inout) :: completeSet
integer, intent(inout), DIMENSION(:) :: var_i
character(len=*), intent(in) :: filename
integer, intent(in) :: npatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: from_restart
integer, intent(in), optional :: INpatch
Calls
Called by
Contents
Call graph
readpar_i calls nf90_inq_varid, nf90_inquire_variable, cable_abort, nc_abort, nf90_get_var
nc_abort calls nf90_strerror
readpar calls readpar_i
extrarestart calls readpar
get_restart_data calls readpar, extrarestart
get_parameters_met calls readpar
load_parameters calls get_restart_data, get_parameters_met
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master