read_netcdf_climate_type – POP
read_netcdf_climate_type Subroutine
174 statements
Source File
private subroutine read_netcdf_climate_type(filename, climate)
Uses
netcdf
mpi
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(climate_type), intent(inout) :: climate
Calls
Called by
Contents
None
Call graph
read_netcdf_climate_type calls mpi_abort, nf90_inq_varid, nf90_get_var, nc_err, nf90_open, nf90_close
nc_err calls mpi_abort, nf90_strerror
read_netcdf_cbm_var calls read_netcdf_climate_type
read_climate_restart_nc calls read_netcdf_cbm_var
read_climatefile calls read_netcdf_cbm_var
mpidrv_master calls read_climate_restart_nc, luc_expt_init
cable_offline_driver calls read_climate_restart_nc, luc_expt_init
luc_expt_init calls read_climatefile
mpi_driver calls mpidrv_master