read_netcdf_phen_var – POP
read_netcdf_phen_var Subroutine
36 statements
Source File
public subroutine read_netcdf_phen_var(filename, phen)
Uses
cable_def_types_mod
netcdf
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
Call graph
read_netcdf_phen_var calls nf90_open, nc_err, nf90_get_var, nf90_inq_varid, nf90_close
read_casa_restart_nc calls read_netcdf_phen_var
casa_init calls read_casa_restart_nc