READ_ClimateFile – POP
READ_ClimateFile Subroutine
25 statements
Source File
public subroutine READ_ClimateFile(LUC_EXPT)
Uses
cable_climate_mod
netcdf
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(luc_expt_type), intent(inout) :: LUC_EXPT
Calls
Called by
Contents
None
Call graph
read_climatefile calls nf90_open, nf90_inq_dimid, nf90_inquire_dimension, nc_err, nf90_close, alloc_cbm_var, read_netcdf_cbm_var
nc_err calls nf90_strerror, mpi_abort
alloc_cbm_var calls alloc_roughness_type, alloc_met_type, alloc_climate_type, alloc_balances_type, alloc_bgc_pool_type, alloc_veg_parameter_type, alloc_canopy_type, alloc_soil_parameter_type, alloc_soil_snow_type, alloc_radiation_type, alloc_sum_flux_type, alloc_air_type
read_netcdf_cbm_var calls read_netcdf_climate_type
read_netcdf_climate_type calls nf90_open, nf90_close, mpi_abort, nf90_inq_varid, nf90_get_var, nc_err
luc_expt_init calls read_climatefile
mpidrv_master calls luc_expt_init
cable_offline_driver calls luc_expt_init
mpi_driver calls mpidrv_master