REALExponential – POP
REALExponential Function
10 statements
Source File
public function REALExponential(lambda, x)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: lambda
real(kind=dp), intent(in) :: x
Return Value real(kind=dp)
Called by
Contents
None
Call graph
getuniqueagefrequencies calls realexponential
interpolate_biomass_1d calls realexponential
interpolate_biomass_2d calls realexponential
interpolate_firemortality calls realexponential
popstep calls getuniqueagefrequencies, getdiagnostics
getdiagnostics calls interpolate_biomass_1d, interpolate_biomass_2d
adjust_pop_for_fire calls interpolate_firemortality
popdriver calls popstep
blaze_driver calls adjust_pop_for_fire
casaonly_luc calls popdriver
worker_spincasacnp calls popdriver, blaze_driver
mpidrv_worker calls popdriver, blaze_driver, worker_spincasacnp, worker_casaonly_luc
spincasacnp calls popdriver, blaze_driver
worker_casaonly_luc calls popdriver
cable_offline_driver calls popdriver, blaze_driver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker