REGRESS – POP
REGRESS Subroutine
36 statements
Source File
public subroutine REGRESS(x, y, n, a, b, r)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
real(kind=dp), intent(in) :: y(:)
integer(kind=i4b), intent(in) :: n
real(kind=dp), intent(out) :: a
real(kind=dp), intent(out) :: b
real(kind=dp), intent(out) :: r
Called by
Contents
Call graph
smooth_flux calls regress
smooth_flux_cat calls regress
getdiagnostics calls smooth_flux
popstep calls getdiagnostics
popdriver calls popstep
spincasacnp calls popdriver
casaonly_luc calls popdriver