rough_type_ptr – POP
rough_type_ptr Subroutine
15 statements
Source File
public subroutine rough_type_ptr(C)
Arguments
Type Intent Optional Attributes Name
type(irough_type) :: C
Called by
Contents
Call graph
point2constants calls rough_type_ptr
cbm calls point2constants, surface_albedo, define_air, ruff_resist, init_radiation, define_canopy, soil_snow, plantcarb
surface_albedo calls point2constants
define_air calls point2constants
ruff_resist calls point2constants
init_radiation calls point2constants
total_an_ac_aj calls point2constants, xvcmxt3, xgmest, xvcmxt3_acclim, xejmxt3_acclim, xejmxt3
adjust_jv_gm calls point2constants
casa_feedback calls point2constants, adjust_jv_gm, optimise_jv
xvcmxt3 calls point2constants
define_canopy calls point2constants, define_air, ruff_resist, dryleaf
total_photosynthesis calls point2constants, xvcmxt3, xgmest, xvcmxt3_acclim, xejmxt3_acclim, xejmxt3
soil_snow calls point2constants
xvcmxt4_acclim calls point2constants
xgmest calls point2constants
xvcmxt3_acclim calls point2constants
diff_ac_aj calls point2constants, xvcmxt3, xgmest, xvcmxt3_acclim, xejmxt3_acclim, xejmxt3
xejmxt3_acclim calls point2constants
optimise_jv calls point2constants, diff_ac_aj, total_photosynthesis_cost
cable_offline_driver calls point2constants, cbm, casa_feedback
plantcarb calls point2constants
mpidrv_worker calls point2constants, cbm, casa_feedback
xejmxt3 calls point2constants
xvcmxt4 calls point2constants
total_photosynthesis_cost calls point2constants, xvcmxt3, xgmest, xvcmxt3_acclim, xejmxt3_acclim, xejmxt3
mpidrv_master calls point2constants
dryleaf calls xvcmxt3, xvcmxt4_acclim, xgmest, xvcmxt3_acclim, xejmxt3_acclim, xejmxt3, xvcmxt4
mpi_driver calls mpidrv_worker, mpidrv_master