rtbis_rh0 – POP
rtbis_rh0 Function
24 statements
Source File
public pure elemental function rtbis_rh0(sol, x1, x2, xacc)
Arguments
Type Intent Optional Attributes Name
type(solve_type), intent(in) :: sol
real(kind=r_2), intent(in) :: x1
real(kind=r_2), intent(in) :: x2
real(kind=r_2), intent(in) :: xacc
Return Value real(kind=r_2)
Calls
Contents
Call graph
rtbis_rh0 calls rh0_sol, eq
rh0_sol calls csat, slope_csat, phi
eq calls equal_sp, equal_dp