rtbis_Tfrozen – POP
rtbis_Tfrozen Function
27 statements
Source File
public pure elemental function rtbis_Tfrozen(J, dxsoil, theta, csoil, rhosoil, h0, thre, the, he, b, x1, x2)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: J
real(kind=r_2), intent(in) :: dxsoil
real(kind=r_2), intent(in) :: theta
real(kind=r_2), intent(in) :: csoil
real(kind=r_2), intent(in) :: rhosoil
real(kind=r_2), intent(in) :: h0
real(kind=r_2), intent(in) :: thre
real(kind=r_2), intent(in) :: the
real(kind=r_2), intent(in) :: he
real(kind=r_2), intent(in) :: b
real(kind=r_2), intent(in) :: x1
real(kind=r_2), intent(in) :: x2
Return Value real(kind=r_2)
Calls
Called by
Contents
Call graph
rtbis_tfrozen calls gtfrozen
gtfrozen calls tfrz
snow_adjust calls rtbis_tfrozen
update_s_t calls rtbis_tfrozen
iflux_loop calls snow_adjust, update_s_t
timestep_loop calls iflux_loop
solve calls timestep_loop
sli_main calls solve
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker