rtbis – POP
rtbis Function
42 statements
Source File
public function rtbis(func, x1, x2, xacc)
Uses
mpi
mo_utils
Arguments
Type Intent Optional Attributes Name
public function func(x)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x
Return Value real
real, intent(in) :: x1
real, intent(in) :: x2
real, intent(in) :: xacc
Return Value real
Calls
Called by
Contents
None
Call graph
rtbis calls ge, eq, mpi_abort, le
ge calls greaterequal_sp, greaterequal_dp
eq calls equal_dp, equal_sp
le calls lesserequal_sp, lesserequal_dp
optimise_jv calls rtbis
casa_feedback calls optimise_jv
mpidrv_worker calls casa_feedback
cable_offline_driver calls casa_feedback
mpi_driver calls mpidrv_worker