RUN_BLAZE – POP
RUN_BLAZE Subroutine
53 statements
Source File
public subroutine RUN_BLAZE(BLAZE, SF, CPLANT_g, CPLANT_w, tstp, YYYY, doy, TO, climate)
Uses
SIMFIRE_MOD
cable_common_module
cable_def_types_mod
CRM IF (DD .EQ. 1) BLAZE%FLI(:) = 0. now in accounting
Arguments
Type Intent Optional Attributes Name
type(TYPE_BLAZE) :: BLAZE
type(TYPE_SIMFIRE) :: SF
real :: CPLANT_g(BLAZE%NCELLS,3)
real :: CPLANT_w(BLAZE%NCELLS,3)
real :: tstp
integer :: YYYY
integer :: doy
type(TYPE_TURNOVER) :: TO(BLAZE%NCELLS,7)
type(climate_type), intent(in) :: climate
Calls
Called by
Contents
None
Call graph
run_blaze calls is_leapyear, simfire, combust, avail_fuel, doysod2ymdhms, blaze_turnover
simfire calls is_leapyear, annual_ba, get_popdens
combust calls avail_fuel
doysod2ymdhms calls is_leapyear, mpi_abort
get_popdens calls get_unit
blaze_driver calls run_blaze
spincasacnp calls blaze_driver
cable_offline_driver calls blaze_driver, spincasacnp
mpidrv_worker calls blaze_driver, worker_spincasacnp
worker_spincasacnp calls blaze_driver
mpi_driver calls mpidrv_worker