SIMFIRE – POP
SIMFIRE Subroutine
25 statements
Source File
public subroutine SIMFIRE(SF, RAINF, TMAX, TMIN, DOY, MM, YEAR, AB, climate)
Uses
netcdf
cable_common_module
cable_IO_vars_module
cable_def_types_mod
$ ! convert to daily burned area using GFED climatology $ $ STATUS = NF90_OPEN(TRIM(SF%BA_CLIM_FILE), NF90_NOWRITE, F_ID) $ CALL HANDLE_ERR(STATUS, "Opening BA Clim File "//SF%BA_CLIM_FILE) $ STATUS = NF90_INQ_VARID(F_ID,'monthly_ba', V_ID) $ CALL HANDLE_ERR(STATUS, "Inquiring var monthly_ba in "//SF%BA_CLIM_FILE) $ $ STATUS = NF90_INQ_VARID(F_ID,'latitude', V_ID_lat) $ CALL HANDLE_ERR(STATUS, "Inquiring var latitude in "//SF%BA_CLIM_FILE) $ $ STATUS = NF90_INQ_VARID(F_ID,'longitude', V_ID_lon) $ CALL HANDLE_ERR(STATUS, "Inquiring var longitude in "//SF%BA_CLIM_FILE) $ $ STATUS = NF90_GET_VAR(F_ID, V_ID_lat, lat_BA, & $ start=(/1/)) $ STATUS = NF90_GET_VAR(F_ID, V_ID_lon, lon_BA, & $ start=(/1/)) $ $ ilat = MINLOC(ABS(lat_BA - SF%LAT(i)),DIM=1) $ ilon = MINLOC(ABS(lon_BA - SF%LON(i)),DIM=1) $ $ STATUS = NF90_GET_VAR(F_ID, V_ID, monthly_ba, & $ start=(/MM,ilon,ilat/)) $ CALL HANDLE_ERR(STATUS, "Reading direct from "//SF%BA_CLIM_FILE)
Arguments
Type Intent Optional Attributes Name
type(TYPE_SIMFIRE) :: SF
real, intent(in) :: RAINF(*)
real, intent(in) :: TMAX(*)
real, intent(in) :: TMIN(*)
integer :: DOY
integer, intent(in) :: MM
integer, intent(in) :: YEAR
real, intent(out) :: AB(*)
type(climate_type), intent(in) :: climate
Calls
Called by
Contents
None
Call graph
simfire calls is_leapyear, annual_ba, get_popdens
get_popdens calls get_unit
run_blaze calls simfire
blaze_driver calls run_blaze
spincasacnp calls blaze_driver
cable_offline_driver calls blaze_driver, spincasacnp
worker_spincasacnp calls blaze_driver
mpidrv_worker calls blaze_driver, worker_spincasacnp
mpi_driver calls mpidrv_worker