sli_main – POP
sli_main Subroutine
478 statements
Source File
public subroutine sli_main(ktau, dt, veg, soil, ssnow, met, canopy, air, rad, SEB_only)
Uses
cable_common_module
sli_utils
cable_def_types_mod
sli_solve
cable_IO_vars_module
sli_numbers
sli_roots
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
real, intent(in) :: dt
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(met_type), intent(inout) :: met
type(canopy_type), intent(inout) :: canopy
type(air_type), intent(inout) :: air
type(radiation_type), intent(in) :: rad
integer, intent(in) :: SEB_only
Calls
Called by
Contents
None
Call graph
sli_main calls tfrz, solve, setlitterpar, getrex, thetalmax, zerovars, hyofs, zerovars_met, setroots, setx, zerovars_snow, setpar_loetsch, setpar, slope_esat_ice, seb, esat_ice, esat
solve calls zerovars, hyofs, setsol, timestep_loop, sofh, hyofh, litter_props
getrex calls getrex_1d, getrex_2d
thetalmax calls tfrz
hyofs calls tfrz, igamma, slope_esat, dthetalmaxdt
setroots calls setroots_1d, setroots_2d
seb calls potential_evap, slope_csat, hyofh
potential_evap calls slope_esat_ice, slope_esat
timestep_loop calls litter_props, iflux_loop, isotope_vap
litter_props calls slope_esat
getrex_2d calls getrex_1d
igamma calls gammln, gcf, gser
dthetalmaxdt calls tfrz
setroots_2d calls setroots_1d
iflux_loop calls hyofs, litter_props, estimate_timestep, snow_adjust, update_unknowns, get_fluxes_and_derivs, get_and_solve_eqn, update_s_t
isotope_vap calls ne, tri
gcf calls gammln, eq
gser calls gammln, eq
snow_adjust calls tfrz, thetalmax, slope_esat_ice, esat_ice, jsoillayer, rtbis_tfrozen, gtfrozen
update_unknowns calls jsoillayer
get_fluxes_and_derivs calls zerovars, seb, getheatfluxes, flux, getfluxes_vp
get_and_solve_eqn calls tfrz, massman_sparse
update_s_t calls tfrz, thetalmax, jsoillayer, rtbis_tfrozen, gtfrozen, dthetalmaxdth
ne calls notequal_sp, notequal_dp
tri calls tri_1d, tri_2d
eq calls equal_sp, equal_dp
jsoillayer calls tfrz
rtbis_tfrozen calls gtfrozen
getheatfluxes calls getheatfluxes_1d, getheatfluxes_2d
flux calls weight
gtfrozen calls tfrz
getfluxes_vp calls getfluxes_vp_1d, getfluxes_vp_2d
massman_sparse calls massman_sparse_1d, massman_sparse_2d
dthetalmaxdth calls tfrz
getfluxes_vp_1d calls zerovars, hyofh, eq, flux
getfluxes_vp_2d calls zerovars, hyofh, eq, flux
weight calls hyofh
massman_sparse_1d calls generic_thomas
massman_sparse_2d calls generic_thomas
generic_thomas calls generic_thomas_1d, generic_thomas_2d
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker