snow_adjust – POP
snow_adjust Subroutine
420 statements
Source File
private subroutine snow_adjust(irec, mp, n, kk, ns, h0, hice, thetai, dx, vsnow, var, par, S, Tsoil, Jcol_latent_S, Jcol_latent_T, Jcol_sensible, deltaJ_sensible_S, qmelt, qtransfer, j0snow)
Arguments
Type Intent Optional Attributes Name
integer(kind=i_d), intent(in) :: irec
integer(kind=i_d), intent(in) :: mp
integer(kind=i_d), intent(in) :: n
integer(kind=i_d), intent(in) :: kk
integer(kind=i_d), intent(inout), DIMENSION(mp) :: ns
real(kind=r_2), intent(inout), DIMENSION(mp) :: h0
real(kind=r_2), intent(inout), DIMENSION(mp) :: hice
real(kind=r_2), intent(inout), DIMENSION(1:n) :: thetai
real(kind=r_2), intent(in), DIMENSION(1:n) :: dx
type(vars_snow), intent(inout), DIMENSION(1:mp) :: vsnow
type(vars), intent(inout), DIMENSION(1:n) :: var
type(params), intent(in), DIMENSION(1:n) :: par
real(kind=r_2), intent(inout), DIMENSION(1:n) :: S
real(kind=r_2), intent(inout), DIMENSION(1:n) :: Tsoil
real(kind=r_2), intent(inout), DIMENSION(1:mp) :: Jcol_latent_S
real(kind=r_2), intent(inout), DIMENSION(1:mp) :: Jcol_latent_T
real(kind=r_2), intent(inout), DIMENSION(1:mp) :: Jcol_sensible
real(kind=r_2), intent(inout), DIMENSION(1:n) :: deltaJ_sensible_S
real(kind=r_2), intent(inout), DIMENSION(nsnow_max) :: qmelt
real(kind=r_2), intent(out), DIMENSION(1:mp) :: qtransfer
real(kind=r_2), intent(inout), DIMENSION(mp) :: j0snow
Calls
Called by
Contents
Call graph
snow_adjust calls jsoillayer, rtbis_tfrozen, thetalmax, tfrz, gtfrozen, slope_esat_ice, esat_ice
jsoillayer calls tfrz
rtbis_tfrozen calls gtfrozen
thetalmax calls tfrz
gtfrozen calls tfrz
iflux_loop calls snow_adjust
timestep_loop calls iflux_loop
solve calls timestep_loop
sli_main calls solve
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker