spincasacnp – POP
spincasacnp Subroutine
371 statements
Source File
public subroutine spincasacnp(dels, kstart, kend, mloop, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen, pop, climate, lalloc, c13o2flux, c13o2pools, BLAZE, SIMFIRE)
Uses
POP_Constants
blaze_drv
POP_Types
casa_inout
cable_c13o2
phenvariable
casa_cable
mo_isotope
cable_common_module
cable_carbon_module
cable_c13o2_def
cable_def_types_mod
casadimension
casaparm
SIMFIRE_MOD
TypeDef
BLAZE_MOD
casavariable
CLN character(len=99), intent(in) :: fcnpspin vh_js !! CLN OPEN(91, file=fcnpspin) CLN read(91,*) myearspin CLN CLOSE(91)
CLN OPEN(91,file=fcnpspin) CLN read(91,*) CLN read(91,901) ncfile
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: kstart
integer, intent(in) :: kend
integer, intent(in) :: mloop
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: pop
type(climate_type), intent(inout) :: climate
integer, intent(in) :: lalloc
type(c13o2_flux), intent(inout) :: c13o2flux
type(c13o2_pool), intent(inout) :: c13o2pools
type(TYPE_BLAZE), intent(inout) :: BLAZE
type(TYPE_SIMFIRE), intent(inout) :: SIMFIRE
Calls
Called by
Contents
None
Call graph
spincasacnp calls analyticpool, write_casa_output_nc, write_blaze_output_nc, casa_fluxout, c13o2_write_output, read_casa_dump, c13o2_close_output, c13o2_save_casapool, isoratio, c13o2_update_pools, biogeochem, c13o2_sanity_pools, blaze_accounting, blaze_driver, c13o2_create_output, popdriver
write_casa_output_nc calls nf90_put_var, nf90_close, nf90_create, nf90_def_var, nf90_def_dim, nf90_put_att, handle_err, nf90_enddef
write_blaze_output_nc calls nf90_put_var, nf90_close, nf90_create, nf90_def_var, nf90_def_dim, nf90_put_att, handle_err, nf90_enddef
c13o2_write_output calls nf90_put_var, c13o2_err_handler
read_casa_dump calls stderr_nc, nf90_close, nf90_open, get_var_nc
c13o2_close_output calls nf90_close, c13o2_err_handler
c13o2_update_pools calls c13o2_fluxmatrix_pools, c13o2_sources_pools, c13o2_sinks_pools, c13o2_save_c13o2pools, c13o2_c13o2pools_back, isotope_pool_model
biogeochem calls casa_rplant, casa_allocation, casa_xkn, casa_xnp, casa_cnpflux, casa_nuptake, casa_delsoil, casa_coeffplant, casa_coeffsoil, casa_puptake, avgsoil, casa_ndummy, casa_xrateplant, casa_pdummy, casa_cnpbal, casa_delplant, casa_cnpcycle, phenology, casa_xratesoil
c13o2_sanity_pools calls isosanity
blaze_driver calls run_blaze, is_leapyear, adjust_pop_for_fire, doysod2ymdhms, blaze_turnover
c13o2_create_output calls nf90_put_var, nf90_create, nf90_def_var, nf90_def_dim, nf90_put_att, nf90_enddef, c13o2_err_handler
popdriver calls popstep
casa_rplant calls vcmax_np
casa_allocation calls casa_wolf
stderr_nc calls nf90_strerror
get_var_nc calls get_var_ncr2, get_var_ncr3
casa_xnp calls casa_prequire, casa_nrequire
run_blaze calls is_leapyear, doysod2ymdhms, blaze_turnover, combust, simfire, avail_fuel
casa_nuptake calls casa_nrequire
adjust_pop_for_fire calls topkill_collins, interpolate_firemortality
casa_puptake calls casa_prequire
casa_xrateplant calls ge, le
handle_err calls nf90_strerror
isotope_pool_model calls isotope_pool_model_2d, isotope_pool_model_1d
casa_cnpcycle calls casa_poolzero
doysod2ymdhms calls is_leapyear
popstep calls getdiagnostics, patchannualdynamics, patch_partial_disturb2, patch_partial_disturb, patch_disturb, getuniqueagefrequencies, getpatchfrequencies
getdiagnostics calls interpolate_biomass_2d, smooth_flux, get_allometry, interpolate_biomass_1d
isotope_pool_model_2d calls mpi_abort, eq, diag, ne
patchannualdynamics calls layer_recruitment, get_allometry
interpolate_firemortality calls realexponential
get_var_ncr2 calls stderr_nc, nf90_inq_varid, nf90_get_var
get_var_ncr3 calls stderr_nc, nf90_inq_varid, nf90_get_var
combust calls avail_fuel
ge calls greaterequal_dp, greaterequal_sp
simfire calls is_leapyear, get_popdens, annual_ba
le calls lesserequal_sp, lesserequal_dp
isotope_pool_model_1d calls mpi_abort, eq, diag, ne
patch_disturb calls layer_recruitment_single_patch
getuniqueagefrequencies calls cumexponential, realexponential
get_popdens calls get_unit
interpolate_biomass_2d calls eq, realexponential, area_triangle
smooth_flux calls regress
eq calls equal_dp, equal_sp
diag calls diag_2d, diag_3d
layer_recruitment calls get_allometry
get_allometry calls getheight, allometry, williams_allometry
interpolate_biomass_1d calls realexponential
ne calls notequal_sp, notequal_dp
layer_recruitment_single_patch calls get_allometry
diag_2d calls mpi_abort
diag_3d calls mpi_abort
cable_offline_driver calls spincasacnp