ssnow_type_ptr – POP
ssnow_type_ptr Subroutine
8 statements
Source File
public subroutine ssnow_type_ptr(C)
Arguments
Type Intent Optional Attributes Name
type(issnow_type) :: C
Called by
Contents
None
Call graph
point2constants calls ssnow_type_ptr
ruff_resist calls point2constants
adjust_jv_gm calls point2constants
casa_feedback calls point2constants, adjust_jv_gm, optimise_jv
total_an_ac_aj calls point2constants, xvcmxt3_acclim, xgmest, xejmxt3, xejmxt3_acclim, xvcmxt3
xvcmxt3_acclim calls point2constants
xgmest calls point2constants
xejmxt3 calls point2constants
mpidrv_master calls point2constants
xejmxt3_acclim calls point2constants
cbm calls point2constants, ruff_resist, soil_snow, define_canopy, define_air, init_radiation, surface_albedo, plantcarb
xvcmxt4 calls point2constants
soil_snow calls point2constants
define_canopy calls point2constants, ruff_resist, define_air, dryleaf
define_air calls point2constants
init_radiation calls point2constants
xvcmxt4_acclim calls point2constants
surface_albedo calls point2constants
cable_offline_driver calls point2constants, casa_feedback, cbm
mpidrv_worker calls point2constants, casa_feedback, cbm
xvcmxt3 calls point2constants
total_photosynthesis_cost calls point2constants, xvcmxt3_acclim, xgmest, xejmxt3, xejmxt3_acclim, xvcmxt3
plantcarb calls point2constants
optimise_jv calls point2constants, total_photosynthesis_cost, diff_ac_aj
diff_ac_aj calls point2constants, xvcmxt3_acclim, xgmest, xejmxt3, xejmxt3_acclim, xvcmxt3
total_photosynthesis calls point2constants, xvcmxt3_acclim, xgmest, xejmxt3, xejmxt3_acclim, xvcmxt3
dryleaf calls xvcmxt3_acclim, xgmest, xejmxt3, xejmxt3_acclim, xvcmxt4, xvcmxt4_acclim, xvcmxt3
mpi_driver calls mpidrv_master, mpidrv_worker