thetalmax – POP
thetalmax Function
12 statements
Source File
public pure elemental function thetalmax(Tin, S, he, b, thre, the)
Uses
sli_numbers
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: Tin
real(kind=r_2), intent(in) :: S
real(kind=r_2), intent(in) :: he
real(kind=r_2), intent(in) :: b
real(kind=r_2), intent(in) :: thre
real(kind=r_2), intent(in) :: the
Return Value real(kind=r_2)
Calls
Called by
Contents
Call graph
thetalmax calls tfrz
sli_main calls thetalmax, solve
update_s_t calls thetalmax
snow_adjust calls thetalmax
define_canopy calls sli_main
cbm calls sli_main, define_canopy
iflux_loop calls update_s_t, snow_adjust
mpidrv_worker calls cbm
cable_offline_driver calls cbm
timestep_loop calls iflux_loop
mpi_driver calls mpidrv_worker
solve calls timestep_loop