TopKill_Collins – POP
TopKill_Collins Function
12 statements
Source File
public function TopKill_Collins(dbh, FLI)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: dbh
real(kind=dp), intent(in) :: FLI
Return Value real(kind=dp)
Called by
Contents
None
Call graph
adjust_pop_for_fire calls topkill_collins
blaze_driver calls adjust_pop_for_fire
spincasacnp calls blaze_driver
cable_offline_driver calls blaze_driver, spincasacnp
mpidrv_worker calls blaze_driver, worker_spincasacnp
worker_spincasacnp calls blaze_driver
mpi_driver calls mpidrv_worker