total_An_Ac_Aj – POP
total_An_Ac_Aj Subroutine
94 statements
Source File
public subroutine total_An_Ac_Aj(bjv, total_An, total_Ac, total_Aj)
Uses
cable_canopy_module
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: bjv
real, intent(out) :: total_An
real, intent(out) :: total_Ac
real, intent(out) :: total_Aj
Calls
Contents
None
Call graph
total_an_ac_aj calls xejmxt3, fan_c3, ej3x, xejmxt3_acclim, xgmest, point2constants, xvcmxt3_acclim, xrdt, xvcmxt3, light_inhibition, fabcd, fpq, fam_c3, fabc
xejmxt3 calls point2constants
xejmxt3_acclim calls point2constants
xgmest calls point2constants
point2constants calls driver_type_ptr, albedo_type_ptr, cbm_type_ptr, air_type_ptr, canopy_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr
xvcmxt3_acclim calls point2constants
xvcmxt3 calls point2constants