total_photosynthesis – POP
total_photosynthesis Function
107 statements
Source File
public function total_photosynthesis(bjv)
Uses
cable_def_types_mod
cable_canopy_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: bjv
Return Value real
Calls
Contents
None
Call graph
total_photosynthesis calls ej3x, point2constants, xvcmxt3_acclim, xvcmxt3, xrdt, xgmest, light_inhibition, fabcd, fpq, fam_c3, fabc, xejmxt3, fan_c3, xejmxt3_acclim
point2constants calls driver_type_ptr, cbm_type_ptr, air_type_ptr, albedo_type_ptr, canopy_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr
xvcmxt3_acclim calls point2constants
xvcmxt3 calls point2constants
xgmest calls point2constants
xejmxt3 calls point2constants
xejmxt3_acclim calls point2constants