total_photosynthesis_cost – POP
total_photosynthesis_cost Function
113 statements
Source File
public function total_photosynthesis_cost(bjv)
Uses
cable_canopy_module
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: bjv
Return Value real
Calls
Called by
Contents
None
Call graph
total_photosynthesis_cost calls fam_c3, fabc, fpq, fan_c3, xejmxt3_acclim, xejmxt3, point2constants, xgmest, xrdt, xvcmxt3, xvcmxt3_acclim, light_inhibition, fabcd, ej3x
xejmxt3_acclim calls point2constants
xejmxt3 calls point2constants
point2constants calls driver_type_ptr, albedo_type_ptr, canopy_type_ptr, cbm_type_ptr, air_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr
xgmest calls point2constants
xvcmxt3 calls point2constants
xvcmxt3_acclim calls point2constants
optimise_jv calls total_photosynthesis_cost
casa_feedback calls optimise_jv
mpidrv_worker calls casa_feedback
cable_offline_driver calls casa_feedback
mpi_driver calls mpidrv_worker