update_sum_casa – POP
update_sum_casa Subroutine
268 statements
Source File
public subroutine update_sum_casa(sum_casapool, sum_casaflux, casapool, casaflux, sum_now, average_now, nsteps)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(inout) :: sum_casapool
type(casa_flux), intent(inout) :: sum_casaflux
type(casa_pool), intent(in) :: casapool
type(casa_flux), intent(in) :: casaflux
logical, intent(in) :: sum_now
logical, intent(in) :: average_now
integer, intent(in) :: nsteps
Called by
Contents
None
Call graph
casaonly_luc calls update_sum_casa
mpidrv_master calls update_sum_casa
cable_offline_driver calls update_sum_casa, casaonly_luc
mpi_driver calls mpidrv_master