update_s_t – POP
update_s_t Subroutine
236 statements
Source File
private subroutine update_s_t(mp, n, dx, h0, S, thetai, Tsoil, infil, nsteps, var, par, qlsig, again, ih0, ns, dt, sig, dy, qhsig, deltaS, dTsoil, dJcol_latent_S, dJcol_latent_T, dJcol_sensible, deltaJ_latent_S, deltaJ_latent_T, deltaJ_sensible_S, deltaJ_sensible_T, qrunoff, tmp1d1, tmp1d2, tmp1d3, tmp1d4, deltah0, Tfreezing, dtdT, LHS_h, i, j, k, kk, theta, cp, hice, hice_tmp, J0, tmp1, tmp2, h_ex, wpi)
$ if (h0(kk)<zero .and. var(1)%isat==0 .and. (i==1)) then ! start negative pond correction $ infil(kk) = infil(kk)+h0(kk) $ ! negative pond converted to loss of soil moisture in top two layers $ S(1) = S(1) + h0(kk)/(dx(1)par(1)%thre) dx(1)/(dx(1)+dx(2)) $ deltaS(1) = h0(kk)/(dx(1)par(1)%thre) dx(1)/(dx(1)+dx(2)) $ ! adjust flux between layer 1 and layer 2 $ qlsig(1) = qlsig(1) + h0(kk) dx(2)/(dx(1)+dx(2))/dt(kk) $ deltaS(2) = h0(kk)/(dx(2)par(2)%thre)* dx(2)/(dx(1)+dx(2)) $ if (var(2)%isat.eq.0) then $ dy(2) = dy(2) + deltaS(2) $ else $ dy(2) = deltaS(2) $ var(2)%isat = 0 $ endif $ $ deltah0(kk) = -(h0(kk)-deltah0(kk)) ! whole pond lost (new change = - original pond height) $ h0(kk) = zero ! zero pond remaining $ endif
Arguments
Type Intent Optional Attributes Name
integer(kind=i_d) :: mp
integer(kind=i_d) :: n
real(kind=r_2), DIMENSION(1:n) :: dx
real(kind=r_2), DIMENSION(1:mp) :: h0
real(kind=r_2), DIMENSION(1:n) :: S
real(kind=r_2), DIMENSION(1:n) :: thetai
real(kind=r_2), DIMENSION(1:n) :: Tsoil
real(kind=r_2), DIMENSION(1:mp) :: infil
integer(kind=i_d), DIMENSION(1:mp) :: nsteps
type(vars), DIMENSION(1:n) :: var
type(params), DIMENSION(1:n) :: par
real(kind=r_2), DIMENSION(-nsnow_max:n) :: qlsig
logical, DIMENSION(1:mp) :: again
integer(kind=i_d), DIMENSION(1:mp) :: ih0
integer(kind=i_d), DIMENSION(1:mp) :: ns
real(kind=r_2), DIMENSION(1:mp) :: dt
real(kind=r_2), DIMENSION(1:mp) :: sig
real(kind=r_2), DIMENSION(-nsnow_max+1:n) :: dy
real(kind=r_2), DIMENSION(-nsnow_max:n) :: qhsig
real(kind=r_2), DIMENSION(1:n) :: deltaS
real(kind=r_2), DIMENSION(1:n) :: dTsoil
real(kind=r_2), DIMENSION(1:mp) :: dJcol_latent_S
real(kind=r_2), DIMENSION(1:mp) :: dJcol_latent_T
real(kind=r_2), DIMENSION(1:mp) :: dJcol_sensible
real(kind=r_2), DIMENSION(1:n) :: deltaJ_latent_S
real(kind=r_2), DIMENSION(1:n) :: deltaJ_latent_T
real(kind=r_2), DIMENSION(1:n) :: deltaJ_sensible_S
real(kind=r_2), DIMENSION(1:n) :: deltaJ_sensible_T
real(kind=r_2), DIMENSION(1:mp) :: qrunoff
real(kind=r_2), DIMENSION(1:mp) :: tmp1d1
real(kind=r_2), DIMENSION(1:mp) :: tmp1d2
real(kind=r_2), DIMENSION(1:mp) :: tmp1d3
real(kind=r_2), DIMENSION(1:mp) :: tmp1d4
real(kind=r_2), DIMENSION(1:mp) :: deltah0
real(kind=r_2), DIMENSION(1:mp) :: Tfreezing
real(kind=r_2), DIMENSION(1:mp) :: dtdT
real(kind=r_2), DIMENSION(-nsnow_max+1:n) :: LHS_h
integer(kind=i_d) :: i
integer(kind=i_d) :: j
integer(kind=i_d) :: k
integer(kind=i_d) :: kk
real(kind=r_2) :: theta
real(kind=r_2), DIMENSION(1:mp) :: cp
real(kind=r_2), DIMENSION(1:mp) :: hice
real(kind=r_2), DIMENSION(1:mp) :: hice_tmp
real(kind=r_2), DIMENSION(1:n) :: J0
real(kind=r_2) :: tmp1
real(kind=r_2) :: tmp2
real(kind=r_2), DIMENSION(1:n) :: h_ex
real(kind=r_2) :: wpi
Calls
Called by
Contents
None
Call graph
update_s_t calls tfrz, jsoillayer, dthetalmaxdth, thetalmax, gtfrozen, rtbis_tfrozen
iflux_loop calls update_s_t
timestep_loop calls iflux_loop
solve calls timestep_loop
sli_main calls solve
cbm calls sli_main
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker