WGEN_INIT – POP
WGEN_INIT Subroutine
50 statements
Source File
public subroutine WGEN_INIT(WG, np, latitude, dels)
Arguments
Type Intent Optional Attributes Name
type(WEATHER_GENERATOR_TYPE) :: WG
integer, intent(in) :: np
real, intent(in) :: latitude(np)
real, intent(in) :: dels
Calls
Called by
Contents
Call graph
wgen_init calls wgen_zero
plume_mip_get_met calls wgen_init
cable_bios_init calls wgen_init
cru_get_subdiurnal_met calls wgen_init
mpidrv_master calls plume_mip_get_met, cable_bios_init, cru_get_subdiurnal_met
cable_offline_driver calls plume_mip_get_met, cable_bios_init, cru_get_subdiurnal_met
mpi_driver calls mpidrv_master