WGEN_SUBDIURNAL_MET – POP
WGEN_SUBDIURNAL_MET Subroutine
86 statements
Source File
public subroutine WGEN_SUBDIURNAL_MET(WG, np, itime)
Uses
mpi
Arguments
Type Intent Optional Attributes Name
type(WEATHER_GENERATOR_TYPE) :: WG
integer, intent(in) :: np
integer, intent(in) :: itime
Calls
Called by
Contents
None
Call graph
wgen_subdiurnal_met calls mpi_abort
plume_mip_get_met calls wgen_subdiurnal_met
cable_bios_read_met calls wgen_subdiurnal_met
cru_get_subdiurnal_met calls wgen_subdiurnal_met
mpidrv_master calls plume_mip_get_met, cable_bios_read_met, cru_get_subdiurnal_met
cable_offline_driver calls plume_mip_get_met, cable_bios_read_met, cru_get_subdiurnal_met
mpi_driver calls mpidrv_master