worker_climate_types – POP
worker_climate_types Subroutine
142 statements
Source File
private subroutine worker_climate_types(comm, climate, ktauday)
Uses
cable_mpicommon
mpi
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(climate_type), intent(inout) :: climate
integer, intent(in) :: ktauday
Calls
Called by
Contents
None
Call graph
worker_climate_types calls mpi_unpack, alloc_cbm_var, zero_cbm_var, add_address_1block, mpi_get_address, mpi_abort, mpi_type_create_struct, mpi_type_commit, mpi_type_size, mpi_type_get_extent, mpi_recv, mpi_get_count, mpi_reduce
alloc_cbm_var calls alloc_sum_flux_type, alloc_climate_type, alloc_radiation_type, alloc_met_type, alloc_soil_parameter_type, alloc_veg_parameter_type, alloc_balances_type, alloc_bgc_pool_type, alloc_canopy_type, alloc_soil_snow_type, alloc_roughness_type, alloc_air_type
zero_cbm_var calls zero_soil_snow_type, zero_roughness_type, zero_veg_parameter_type, zero_radiation_type, zero_canopy_type, zero_air_type, zero_sum_flux_type, zero_climate_type, zero_balances_type, zero_soil_parameter_type, zero_met_type, zero_bgc_pool_type
add_address_1block calls add_address_1block_1d_r2, add_address_1block_2d_r2, add_address_1block_1d_i1, add_address_1block_1d_l, add_address_1block_3d_i1, add_address_1block_3d_l, add_address_1block_3d_r2, add_address_1block_2d_l, add_address_1block_2d_i1, add_address_1block_3d_r1, add_address_1block_2d_r1, add_address_1block_1d_r1
add_address_1block_1d_r2 calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
add_address_1block_1d_i1 calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
add_address_1block_3d_i1 calls mpi_get_address
add_address_1block_3d_l calls mpi_get_address
add_address_1block_3d_r2 calls mpi_get_address
add_address_1block_2d_l calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
add_address_1block_3d_r1 calls mpi_get_address
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
mpidrv_worker calls worker_climate_types
mpi_driver calls mpidrv_worker