worker_casa_params – POP
worker_casa_params Subroutine
314 statements
Source File
private subroutine worker_casa_params(comm, casabiome, casapool, casaflux, casamet, casabal, phen)
Uses
casavariable
cable_mpicommon
casadimension
phenvariable
cable_def_types_mod
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
None
Call graph
worker_casa_params calls mpi_type_size, mpi_abort, mpi_type_create_struct, mpi_unpack, mpi_type_free, mpi_reduce, mpi_get_count, mpi_comm_rank, mpi_type_get_extent, mpi_barrier, zero_casa_var, alloc_casa_var, alloc_phenvariable, zero_phenvariable, add_address_1block, mpi_recv, mpi_type_commit
zero_casa_var calls zero_casabiome, zero_casamet, zero_casabal, zero_casaflux, zero_casapool
alloc_casa_var calls alloc_casabiome, alloc_casamet, alloc_casapool, alloc_casabal, alloc_casaflux
add_address_1block calls add_address_1block_2d_r1, add_address_1block_1d_i1, add_address_1block_3d_r1, add_address_1block_2d_l, add_address_1block_2d_r2, add_address_1block_1d_r1, add_address_1block_3d_l, add_address_1block_1d_l, add_address_1block_1d_r2, add_address_1block_2d_i1, add_address_1block_3d_r2, add_address_1block_3d_i1
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_1d_i1 calls mpi_get_address
add_address_1block_3d_r1 calls mpi_get_address
add_address_1block_2d_l calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
add_address_1block_3d_l calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
add_address_1block_1d_r2 calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
add_address_1block_3d_r2 calls mpi_get_address
add_address_1block_3d_i1 calls mpi_get_address
mpidrv_worker calls worker_casa_params
mpi_driver calls mpidrv_worker