worker_c13o2_pool_params – POP
worker_c13o2_pool_params Subroutine
71 statements
Source File
private subroutine worker_c13o2_pool_params(comm, c13o2pools)
Uses
mpi
cable_def_types_mod
cable_mpicommon
cable_c13o2_def
casadimension
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(c13o2_pool), intent(inout) :: c13o2pools
Calls
Called by
Contents
None
Call graph
worker_c13o2_pool_params calls mpi_type_get_extent, mpi_unpack, mpi_comm_rank, c13o2_alloc_pools, mpi_abort, mpi_type_free, c13o2_zero_pools, add_address_1block, mpi_type_create_struct, mpi_type_commit, mpi_type_size, mpi_barrier, mpi_get_count, mpi_recv, mpi_reduce
add_address_1block calls add_address_1block_3d_r2, add_address_1block_3d_r1, add_address_1block_1d_l, add_address_1block_1d_i1, add_address_1block_1d_r2, add_address_1block_2d_i1, add_address_1block_1d_r1, add_address_1block_2d_l, add_address_1block_2d_r1, add_address_1block_2d_r2, add_address_1block_3d_i1, add_address_1block_3d_l
add_address_1block_3d_r2 calls mpi_get_address
add_address_1block_3d_r1 calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
add_address_1block_1d_i1 calls mpi_get_address
add_address_1block_1d_r2 calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
add_address_1block_2d_l calls mpi_get_address
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
add_address_1block_3d_i1 calls mpi_get_address
add_address_1block_3d_l calls mpi_get_address
mpidrv_worker calls worker_c13o2_pool_params
mpi_driver calls mpidrv_worker