worker_c13o2_luc_params – POP
worker_c13o2_luc_params Subroutine
68 statements
Source File
private subroutine worker_c13o2_luc_params(comm, c13o2luc)
Uses
cable_mpicommon
cable_c13o2_def
mpi
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(c13o2_luc), intent(inout) :: c13o2luc
Calls
Called by
Contents
None
Call graph
worker_c13o2_luc_params calls mpi_type_get_extent, mpi_unpack, mpi_barrier, add_address_1block, mpi_comm_rank, mpi_type_free, c13o2_zero_luc, mpi_abort, c13o2_alloc_luc, mpi_type_create_struct, mpi_type_commit, mpi_recv, mpi_get_count, mpi_type_size, mpi_reduce
add_address_1block calls add_address_1block_1d_i1, add_address_1block_1d_r1, add_address_1block_1d_l, add_address_1block_2d_i1, add_address_1block_1d_r2, add_address_1block_2d_l, add_address_1block_2d_r1, add_address_1block_2d_r2, add_address_1block_3d_i1, add_address_1block_3d_l, add_address_1block_3d_r1, add_address_1block_3d_r2
add_address_1block_1d_i1 calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
add_address_1block_1d_r2 calls mpi_get_address
add_address_1block_2d_l calls mpi_get_address
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
add_address_1block_3d_i1 calls mpi_get_address
add_address_1block_3d_l calls mpi_get_address
add_address_1block_3d_r1 calls mpi_get_address
add_address_1block_3d_r2 calls mpi_get_address
mpidrv_worker calls worker_c13o2_luc_params
mpi_driver calls mpidrv_worker