worker_restart_type – POP
worker_restart_type Subroutine
61 statements
Source File
private subroutine worker_restart_type(comm, canopy, air, veg, ssnow)
Uses
mpi
cable_mpicommon
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(canopy_type), intent(inout) :: canopy
type(air_type), intent(inout) :: air
type(veg_parameter_type), intent(inout) :: veg
type(soil_snow_type), intent(inout) :: ssnow
Calls
Called by
Contents
None
Call graph
worker_restart_type calls mpi_comm_rank, mpi_abort, add_address_1block, mpi_type_commit, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_reduce
add_address_1block calls add_address_1block_3d_l, add_address_1block_3d_r1, add_address_1block_1d_l, add_address_1block_1d_r2, add_address_1block_2d_i1, add_address_1block_1d_i1, add_address_1block_1d_r1, add_address_1block_2d_l, add_address_1block_2d_r1, add_address_1block_2d_r2, add_address_1block_3d_i1, add_address_1block_3d_r2
add_address_1block_3d_l calls mpi_get_address
add_address_1block_3d_r1 calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
add_address_1block_1d_r2 calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
add_address_1block_1d_i1 calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
add_address_1block_2d_l calls mpi_get_address
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
add_address_1block_3d_i1 calls mpi_get_address
add_address_1block_3d_r2 calls mpi_get_address
mpidrv_worker calls worker_restart_type
mpi_driver calls mpidrv_worker