worker_casa_type – POP
worker_casa_type Subroutine
333 statements
Source File
private subroutine worker_casa_type(comm, casabiome, casapool, casaflux, casamet, casabal, phen)
Uses
casavariable
mpi
phenvariable
cable_mpicommon
cable_def_types_mod
casadimension
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
Calls
Called by
Contents
Call graph
worker_casa_type calls add_address_1block, mpi_type_commit, mpi_type_size, mpi_abort, mpi_type_create_struct, mpi_type_get_extent, mpi_reduce
add_address_1block calls add_address_1block_3d_l, add_address_1block_3d_r1, add_address_1block_1d_r1, add_address_1block_1d_r2, add_address_1block_1d_l, add_address_1block_1d_i1, add_address_1block_2d_i1, add_address_1block_2d_l, add_address_1block_2d_r1, add_address_1block_2d_r2, add_address_1block_3d_i1, add_address_1block_3d_r2
add_address_1block_3d_l calls mpi_get_address
add_address_1block_3d_r1 calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
add_address_1block_1d_r2 calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
add_address_1block_1d_i1 calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
add_address_1block_2d_l calls mpi_get_address
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
add_address_1block_3d_i1 calls mpi_get_address
add_address_1block_3d_r2 calls mpi_get_address
mpidrv_worker calls worker_casa_type
mpi_driver calls mpidrv_worker