worker_CASAONLY_LUC – POP
worker_CASAONLY_LUC Subroutine
112 statements
Source File
private subroutine worker_CASAONLY_LUC(dels, kstart, kend, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen, pop, climate, lalloc, c13o2flux, c13o2pools, icomm, ocomm)
Uses
mpi
casadimension
TypeDef
cable_carbon_module
casavariable
phenvariable
casaparm
cable_common_module
casa_cable
cable_c13o2
casa_inout
cable_c13o2_def
POP_Types
cable_def_types_mod
CLN CHARACTER(LEN=99), INTENT(IN) :: fcnpspin CLN BLAZE here
CLN BLAZE TURNOVER
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: kstart
integer, intent(in) :: kend
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: pop
type(climate_type), intent(inout) :: climate
integer, intent(in) :: lalloc
type(c13o2_flux), intent(inout) :: c13o2flux
type(c13o2_pool), intent(inout) :: c13o2pools
integer, intent(in) :: icomm
integer, intent(in) :: ocomm
Calls
Called by
Contents
None
Call graph
worker_casaonly_luc calls mpi_recv, c13o2_update_pools, biogeochem, c13o2_save_casapool, c13o2_sanity_pools, mpi_send, mpi_comm_rank, popdriver, worker_send_pop
c13o2_update_pools calls c13o2_save_c13o2pools, c13o2_sinks_pools, c13o2_sources_pools, isotope_pool_model, c13o2_fluxmatrix_pools, c13o2_c13o2pools_back
biogeochem calls casa_coeffsoil, casa_allocation, phenology, casa_cnpcycle, casa_cnpbal, casa_delplant, casa_delsoil, casa_pdummy, casa_rplant, casa_cnpflux, casa_coeffplant, casa_nuptake, casa_puptake, casa_ndummy, avgsoil, casa_xrateplant, casa_xnp, casa_xratesoil, casa_xkn
c13o2_sanity_pools calls isosanity
popdriver calls popstep
worker_send_pop calls mpi_send
casa_allocation calls casa_wolf
casa_cnpcycle calls casa_poolzero
casa_rplant calls vcmax_np
popstep calls patchannualdynamics, patch_partial_disturb, patch_partial_disturb2, getuniqueagefrequencies, patch_disturb, getpatchfrequencies, getdiagnostics
casa_nuptake calls casa_nrequire
casa_puptake calls casa_prequire
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
casa_xrateplant calls ge, le
casa_xnp calls casa_nrequire, casa_prequire
ge calls greaterequal_sp, greaterequal_dp
isotope_pool_model_1d calls ne, mpi_abort, diag, eq
isotope_pool_model_2d calls ne, mpi_abort, diag, eq
patchannualdynamics calls get_allometry, layer_recruitment
getuniqueagefrequencies calls cumexponential, realexponential
patch_disturb calls layer_recruitment_single_patch
getdiagnostics calls get_allometry, interpolate_biomass_2d, smooth_flux, interpolate_biomass_1d
le calls lesserequal_dp, lesserequal_sp
layer_recruitment_single_patch calls get_allometry
ne calls notequal_sp, notequal_dp
diag calls diag_2d, diag_3d
eq calls equal_sp, equal_dp
get_allometry calls getheight, williams_allometry, allometry
layer_recruitment calls get_allometry
interpolate_biomass_2d calls eq, realexponential, area_triangle
smooth_flux calls regress
interpolate_biomass_1d calls realexponential
diag_2d calls mpi_abort
diag_3d calls mpi_abort
mpidrv_worker calls worker_casaonly_luc
mpi_driver calls mpidrv_worker