worker_casa_LUC_types – POP
worker_casa_LUC_types Subroutine
70 statements
Source File
private subroutine worker_casa_LUC_types(comm, casapool, casabal, casaflux)
Uses
cable_mpicommon
mpi
cable_def_types_mod
casadimension
casavariable
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(casa_pool), intent(in) :: casapool
type(casa_balance), intent(in) :: casabal
type(casa_flux), intent(in) :: casaflux
Calls
Called by
Contents
None
Call graph
worker_casa_luc_types calls mpi_comm_rank, mpi_type_create_struct, add_address_1block, mpi_abort, mpi_type_commit, mpi_type_size, mpi_type_get_extent, mpi_reduce
add_address_1block calls add_address_1block_3d_r1, add_address_1block_1d_r1, add_address_1block_1d_l, add_address_1block_1d_r2, add_address_1block_1d_i1, add_address_1block_2d_i1, add_address_1block_2d_l, add_address_1block_2d_r1, add_address_1block_2d_r2, add_address_1block_3d_i1, add_address_1block_3d_l, add_address_1block_3d_r2
add_address_1block_3d_r1 calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
add_address_1block_1d_r2 calls mpi_get_address
add_address_1block_1d_i1 calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
add_address_1block_2d_l calls mpi_get_address
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
add_address_1block_3d_i1 calls mpi_get_address
add_address_1block_3d_l calls mpi_get_address
add_address_1block_3d_r2 calls mpi_get_address
mpidrv_worker calls worker_casa_luc_types
mpi_driver calls mpidrv_worker