worker_casa_dump_types – POP
worker_casa_dump_types Subroutine
84 statements
Source File
private subroutine worker_casa_dump_types(comm, casamet, casaflux, phen, climate, c13o2flux)
Uses
casavariable
cable_mpicommon
cable_c13o2_def
casadimension
phenvariable
cable_def_types_mod
cable_common_module
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(casa_met), intent(inout) :: casamet
type(casa_flux), intent(inout) :: casaflux
type(phen_variable), intent(inout) :: phen
type(climate_type), intent(inout) :: climate
type(c13o2_flux), intent(inout) :: c13o2flux
Calls
Called by
Contents
None
Call graph
worker_casa_dump_types calls mpi_comm_rank, mpi_type_create_struct, mpi_abort, add_address_1block, mpi_type_commit, mpi_type_size, mpi_type_get_extent, mpi_reduce
add_address_1block calls add_address_1block_3d_l, add_address_1block_3d_r1, add_address_1block_1d_i1, add_address_1block_1d_l, add_address_1block_1d_r2, add_address_1block_1d_r1, add_address_1block_2d_i1, add_address_1block_2d_l, add_address_1block_2d_r1, add_address_1block_2d_r2, add_address_1block_3d_i1, add_address_1block_3d_r2
add_address_1block_3d_l calls mpi_get_address
add_address_1block_3d_r1 calls mpi_get_address
add_address_1block_1d_i1 calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
add_address_1block_1d_r2 calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
add_address_1block_2d_l calls mpi_get_address
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
add_address_1block_3d_i1 calls mpi_get_address
add_address_1block_3d_r2 calls mpi_get_address
mpidrv_worker calls worker_casa_dump_types
mpi_driver calls mpidrv_worker