worker_send_pop – POP
worker_send_pop Subroutine
12 statements
Source File
private subroutine worker_send_pop(POP, comm)
Uses
pop_mpi
POP_Types
mpi
Arguments
Type Intent Optional Attributes Name
type(POP_type), intent(in) :: POP
integer, intent(in) :: comm
Calls
Called by
Contents
None
Call graph
worker_send_pop calls mpi_send
worker_spincasacnp calls worker_send_pop
worker_casaonly_luc calls worker_send_pop
mpidrv_worker calls worker_send_pop, worker_spincasacnp, worker_casaonly_luc
mpi_driver calls mpidrv_worker