worker_cable_params – POP
worker_cable_params Subroutine
496 statements
Source File
private subroutine worker_cable_params(comm, met, air, ssnow, veg, bgc, soil, canopy, rough, rad, sum_flux, bal)
Uses
cable_IO_vars_module
mpi
cable_mpicommon
cable_input_module
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(met_type), intent(inout) :: met
type(air_type), intent(inout) :: air
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(inout) :: veg
type(bgc_pool_type), intent(inout) :: bgc
type(soil_parameter_type), intent(inout) :: soil
type(canopy_type), intent(inout) :: canopy
type(roughness_type), intent(inout) :: rough
type(radiation_type), intent(inout) :: rad
type(sum_flux_type), intent(inout) :: sum_flux
type(balances_type), intent(inout) :: bal
Calls
Called by
Contents
None
Call graph
worker_cable_params calls mpi_type_size, mpi_get_count, mpi_recv, add_address_1block, mpi_comm_rank, mpi_reduce, allocate_cable_vars, decomp_types, mpi_abort, mpi_type_create_struct, mpi_type_commit, mpi_unpack, mpi_type_free, mpi_type_get_extent
add_address_1block calls add_address_1block_3d_l, add_address_1block_3d_i1, add_address_1block_3d_r1, add_address_1block_1d_r1, add_address_1block_3d_r2, add_address_1block_1d_r2, add_address_1block_1d_i1, add_address_1block_2d_i1, add_address_1block_1d_l, add_address_1block_2d_l, add_address_1block_2d_r1, add_address_1block_2d_r2
allocate_cable_vars calls zero_cbm_var, alloc_cbm_var
decomp_types calls mpi_type_create_struct, mpi_type_commit, mpi_get_address, mpi_type_create_resized
add_address_1block_3d_l calls mpi_get_address
zero_cbm_var calls zero_roughness_type, zero_soil_snow_type, zero_canopy_type, zero_balances_type, zero_veg_parameter_type, zero_radiation_type, zero_climate_type, zero_bgc_pool_type, zero_soil_parameter_type, zero_air_type, zero_met_type, zero_sum_flux_type
add_address_1block_3d_i1 calls mpi_get_address
add_address_1block_3d_r1 calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
add_address_1block_3d_r2 calls mpi_get_address
add_address_1block_1d_r2 calls mpi_get_address
add_address_1block_1d_i1 calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
add_address_1block_2d_l calls mpi_get_address
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
alloc_cbm_var calls alloc_balances_type, alloc_climate_type, alloc_veg_parameter_type, alloc_bgc_pool_type, alloc_canopy_type, alloc_air_type, alloc_soil_snow_type, alloc_soil_parameter_type, alloc_radiation_type, alloc_roughness_type, alloc_met_type, alloc_sum_flux_type
mpidrv_worker calls worker_cable_params
mpi_driver calls mpidrv_worker