worker_spincasacnp – POP
worker_spincasacnp Subroutine
262 statements
Source File
private subroutine worker_spincasacnp(dels, kstart, kend, mloop, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen, POP, climate, lalloc, c13o2flux, c13o2pools, icomm, ocomm)
Uses
cable_carbon_module
casaparm
cable_common_module
cable_c13o2_def
SIMFIRE_MOD
cable_def_types_mod
casavariable
cable_c13o2
POP_Types
casadimension
phenvariable
mo_isotope
casa_inout
blaze_drv
BLAZE_MOD
mpi
TypeDef
casa_cable
POP_Constants
CLN character(len=99), intent(in) :: fcnpspin vh_js !! CLN CLOSE(91)
CLN OPEN(91,file=fcnpspin) CLN read(91,*) CLN BLAZE here CLNblaze_spin_year = 1900 - myearspin + nyear
CLN BLAZE TURNOVER
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: kstart
integer, intent(in) :: kend
integer, intent(in) :: mloop
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: POP
type(climate_type), intent(inout) :: climate
integer, intent(in) :: lalloc
type(c13o2_flux), intent(inout) :: c13o2flux
type(c13o2_pool), intent(inout) :: c13o2pools
integer, intent(in) :: icomm
integer, intent(in) :: ocomm
Calls
Called by
Contents
None
Call graph
worker_spincasacnp calls mpi_send, worker_send_pop, mpi_recv, biogeochem, c13o2_update_pools, isoratio, c13o2_save_casapool, c13o2_sanity_pools, popdriver, analyticpool, blaze_driver
worker_send_pop calls mpi_send
biogeochem calls casa_xkn, casa_cnpbal, casa_pdummy, casa_delplant, casa_delsoil, casa_cnpcycle, casa_cnpflux, casa_allocation, casa_rplant, phenology, casa_coeffplant, avgsoil, casa_nuptake, casa_coeffsoil, casa_xnp, casa_xratesoil, casa_xrateplant, casa_ndummy, casa_puptake
c13o2_update_pools calls c13o2_save_c13o2pools, c13o2_sources_pools, isotope_pool_model, c13o2_sinks_pools, c13o2_fluxmatrix_pools, c13o2_c13o2pools_back
c13o2_sanity_pools calls isosanity
popdriver calls popstep
blaze_driver calls run_blaze, is_leapyear, adjust_pop_for_fire, blaze_turnover, doysod2ymdhms
casa_cnpcycle calls casa_poolzero
casa_allocation calls casa_wolf
casa_rplant calls vcmax_np
run_blaze calls is_leapyear, blaze_turnover, doysod2ymdhms, combust, simfire, avail_fuel
popstep calls patch_partial_disturb, getuniqueagefrequencies, getdiagnostics, getpatchfrequencies, patch_disturb, patchannualdynamics, patch_partial_disturb2
casa_nuptake calls casa_nrequire
casa_xnp calls casa_prequire, casa_nrequire
casa_xrateplant calls ge, le
casa_puptake calls casa_prequire
isotope_pool_model calls isotope_pool_model_2d, isotope_pool_model_1d
adjust_pop_for_fire calls interpolate_firemortality, topkill_collins
doysod2ymdhms calls is_leapyear
ge calls greaterequal_sp, greaterequal_dp
isotope_pool_model_2d calls ne, mpi_abort, diag, eq
combust calls avail_fuel
le calls lesserequal_sp, lesserequal_dp
getuniqueagefrequencies calls cumexponential, realexponential
interpolate_firemortality calls realexponential
getdiagnostics calls get_allometry, interpolate_biomass_2d, smooth_flux, interpolate_biomass_1d
isotope_pool_model_1d calls ne, mpi_abort, diag, eq
patch_disturb calls layer_recruitment_single_patch
simfire calls is_leapyear, get_popdens, annual_ba
patchannualdynamics calls get_allometry, layer_recruitment
get_allometry calls getheight, williams_allometry, allometry
get_popdens calls get_unit
layer_recruitment calls get_allometry
layer_recruitment_single_patch calls get_allometry
ne calls notequal_sp, notequal_dp
diag calls diag_2d, diag_3d
eq calls equal_sp, equal_dp
interpolate_biomass_2d calls eq, realexponential, area_triangle
smooth_flux calls regress
interpolate_biomass_1d calls realexponential
diag_2d calls mpi_abort
diag_3d calls mpi_abort
mpidrv_worker calls worker_spincasacnp
mpi_driver calls mpidrv_worker