worker_c13o2_pool_type – POP
worker_c13o2_pool_type Subroutine
51 statements
Source File
private subroutine worker_c13o2_pool_type(comm, c13o2pools)
Uses
casadimension
mpi
cable_mpicommon
cable_c13o2_def
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(c13o2_pool), intent(inout) :: c13o2pools
Calls
Called by
Contents
None
Call graph
worker_c13o2_pool_type calls add_address_1block, mpi_type_create_struct, mpi_abort, mpi_type_size, mpi_type_commit, mpi_type_get_extent, mpi_reduce
add_address_1block calls add_address_1block_3d_l, add_address_1block_3d_i1, add_address_1block_3d_r1, add_address_1block_1d_r1, add_address_1block_3d_r2, add_address_1block_1d_r2, add_address_1block_1d_i1, add_address_1block_2d_i1, add_address_1block_1d_l, add_address_1block_2d_l, add_address_1block_2d_r1, add_address_1block_2d_r2
add_address_1block_3d_l calls mpi_get_address
add_address_1block_3d_i1 calls mpi_get_address
add_address_1block_3d_r1 calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
add_address_1block_3d_r2 calls mpi_get_address
add_address_1block_1d_r2 calls mpi_get_address
add_address_1block_1d_i1 calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
add_address_1block_2d_l calls mpi_get_address
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
mpidrv_worker calls worker_c13o2_pool_type
mpi_driver calls mpidrv_worker