worker_intype – POP
worker_intype Subroutine
63 statements
Source File
private subroutine worker_intype(comm, met, veg)
Uses
cable_mpicommon
mpi
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(met_type), intent(in) :: met
type(veg_parameter_type), intent(in) :: veg
Calls
Called by
Contents
None
Call graph
worker_intype calls mpi_comm_rank, add_address_1block, mpi_type_commit, mpi_abort, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_reduce
add_address_1block calls add_address_1block_3d_r1, add_address_1block_1d_i1, add_address_1block_1d_r2, add_address_1block_2d_i1, add_address_1block_1d_l, add_address_1block_1d_r1, add_address_1block_2d_l, add_address_1block_2d_r1, add_address_1block_2d_r2, add_address_1block_3d_i1, add_address_1block_3d_l, add_address_1block_3d_r2
add_address_1block_3d_r1 calls mpi_get_address
add_address_1block_1d_i1 calls mpi_get_address
add_address_1block_1d_r2 calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
add_address_1block_2d_l calls mpi_get_address
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
add_address_1block_3d_i1 calls mpi_get_address
add_address_1block_3d_l calls mpi_get_address
add_address_1block_3d_r2 calls mpi_get_address
mpidrv_worker calls worker_intype
mpi_driver calls mpidrv_worker