worker_simfire_types – POP
worker_simfire_types Subroutine
98 statements
Source File
public subroutine worker_simfire_types(comm, mp, SF, simfire_restart_t, simfire_inp_t, simfire_out_t)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
integer, intent(in) :: mp
type(TYPE_SIMFIRE), intent(in) :: SF
integer, intent(out) :: simfire_restart_t
integer, intent(out) :: simfire_inp_t
integer, intent(out) :: simfire_out_t
Calls
Contents
Call graph
worker_simfire_types calls mpi_comm_rank, mpi_get_address, mpi_type_create_struct, mpi_type_size, mpi_type_commit, mpi_type_get_extent, mpi_reduce