worker_blaze_types – POP
worker_blaze_types Subroutine
181 statements
Source File
public subroutine worker_blaze_types(comm, mp, BLAZE, blaze_restart_t, blaze_in_t, blaze_out_t)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
integer, intent(in) :: mp
type(TYPE_BLAZE), intent(in) :: BLAZE
integer, intent(out) :: blaze_restart_t
integer, intent(out) :: blaze_in_t
integer, intent(out) :: blaze_out_t
Calls
Called by
Contents
None
Call graph
worker_blaze_types calls mpi_comm_rank, mpi_abort, mpi_get_address, mpi_type_commit, mpi_type_create_struct, mpi_type_size, mpi_type_get_extent, mpi_reduce
mpidrv_worker calls worker_blaze_types
mpi_driver calls mpidrv_worker