write_netcdf_casaflux – POP
write_netcdf_casaflux Subroutine
202 statements
Source File
private subroutine write_netcdf_casaflux(filename, casaflux)
Uses
netcdf
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_flux), intent(in) :: casaflux
Calls
Called by
Contents
Call graph
write_netcdf_casaflux calls nf90_create, nc_err, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_var, nf90_close
write_netcdf_casa_var calls write_netcdf_casaflux
write_casa_restart_nc calls write_netcdf_casa_var