write_casa_restart_nc – POP
write_casa_restart_nc Subroutine
36 statements
Source File
public subroutine write_casa_restart_nc(casabiome, casamet, casapool, casaflux, casabal, phen)
Uses
phenvariable
cable_common_module
casavariable
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(in) :: casabiome
type(casa_met), intent(in) :: casamet
type(casa_pool), intent(in) :: casapool
type(casa_flux), intent(in) :: casaflux
type(casa_balance), intent(in) :: casabal
type(phen_variable), intent(in) :: phen
Calls
Called by
Contents
None
Call graph
write_casa_restart_nc calls write_netcdf_casa_var, write_netcdf_phen_var
write_netcdf_casa_var calls write_netcdf_casabiome, write_netcdf_casamet, write_netcdf_casabal, write_netcdf_casapool, write_netcdf_casaflux
write_netcdf_phen_var calls nf90_close, nf90_put_var, nf90_create, nf90_def_dim, nf90_enddef, nf90_def_var, nc_err
write_netcdf_casabiome calls nf90_close, nf90_put_var, nf90_create, nf90_def_dim, nf90_enddef, nf90_def_var, nc_err
write_netcdf_casamet calls nf90_close, nf90_put_var, nf90_create, nf90_def_dim, nf90_enddef, nf90_def_var, nc_err
write_netcdf_casabal calls nf90_close, nf90_put_var, nf90_create, nf90_def_dim, nf90_enddef, nf90_def_var, nc_err
write_netcdf_casapool calls nf90_close, nf90_put_var, nf90_create, nf90_def_dim, nf90_enddef, nf90_def_var, nc_err
write_netcdf_casaflux calls nf90_close, nf90_put_var, nf90_create, nf90_def_dim, nf90_enddef, nf90_def_var, nc_err
nc_err calls nf90_strerror, mpi_abort
master_spincasacnp calls write_casa_restart_nc
master_casaonly_luc calls write_casa_restart_nc
cable_offline_driver calls write_casa_restart_nc
mpidrv_master calls write_casa_restart_nc, master_spincasacnp, master_casaonly_luc
mpi_driver calls mpidrv_master