write_output_parameter_r2 – POP
write_output_parameter_r2 Subroutine
377 statements
Source File
private subroutine write_output_parameter_r2(ncid, parID, pname, par_r2, prange, writepatch, dimswitch, restart)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: parID
character(len=*), intent(in) :: pname
real(kind=4), intent(in), DIMENSION(:, :) :: par_r2
real, intent(in), DIMENSION(2) :: prange
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: restart
Calls
Called by
Contents
None
Call graph
write_output_parameter_r2 calls cable_abort, nf90_put_var, nc_abort
nc_abort calls nf90_strerror
write_ovar calls write_output_parameter_r2
open_output_file calls write_ovar
write_output calls write_ovar
create_restart calls write_ovar
mpidrv_master calls open_output_file, write_output, create_restart
cable_offline_driver calls open_output_file, write_output, create_restart
mpi_driver calls mpidrv_master