write_casa_output_nc – POP
write_casa_output_nc Subroutine
419 statements
Source File
public subroutine write_casa_output_nc(veg, casamet, casapool, casabal, casaflux, casaonly, ctime, lfinal)
Uses
casavariable
cable_IO_vars_module
casadimension
cable_common_module
netcdf
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(in) :: veg
type(casa_met), intent(in) :: casamet
type(casa_pool), intent(in) :: casapool
type(casa_balance), intent(in) :: casabal
type(casa_flux), intent(in) :: casaflux
logical, intent(in) :: casaonly
integer, intent(in) :: ctime
logical, intent(in) :: lfinal
Calls
Called by
Contents
None
Call graph
write_casa_output_nc calls nf90_create, handle_err, nf90_def_var, nf90_put_att, nf90_def_dim, nf90_enddef, nf90_put_var, nf90_close
handle_err calls nf90_strerror, mpi_abort
spincasacnp calls write_casa_output_nc
mpidrv_master calls write_casa_output_nc
cable_offline_driver calls write_casa_output_nc, spincasacnp
mpi_driver calls mpidrv_master