write_netcdf_phen_var – POP
write_netcdf_phen_var Subroutine
40 statements
Source File
public subroutine write_netcdf_phen_var(filename, phen)
Uses
netcdf
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(phen_variable), intent(in) :: phen
Calls
Called by
Contents
Call graph
write_netcdf_phen_var calls nf90_create, nf90_def_var, nf90_enddef, nc_err, nf90_def_dim, nf90_put_var, nf90_close
nc_err calls nf90_strerror
write_casa_restart_nc calls write_netcdf_phen_var
master_spincasacnp calls write_casa_restart_nc
mpidrv_master calls write_casa_restart_nc, master_spincasacnp, master_casaonly_luc
cable_offline_driver calls write_casa_restart_nc
master_casaonly_luc calls write_casa_restart_nc
mpi_driver calls mpidrv_master