write_netcdf_climate_type – POP
write_netcdf_climate_type Subroutine
176 statements
Source File
private subroutine write_netcdf_climate_type(filename, climate)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(climate_type), intent(in) :: climate
Calls
Called by
Contents
None
Call graph
write_netcdf_climate_type calls nf90_create, nc_err, nf90_enddef, nf90_def_dim, nf90_def_var, nf90_put_var, nf90_close
nc_err calls nf90_strerror
write_netcdf_cbm_var calls write_netcdf_climate_type
write_climate_restart_nc calls write_netcdf_cbm_var
mpidrv_master calls write_climate_restart_nc
cable_offline_driver calls write_climate_restart_nc
mpi_driver calls mpidrv_master