WRITE_BLAZE_OUTPUT_NC – POP
WRITE_BLAZE_OUTPUT_NC Subroutine
158 statements
Source File
public subroutine WRITE_BLAZE_OUTPUT_NC(BLAZE, FINAL)
Uses
cable_common_module
netcdf
cable_IO_vars_module
$ STATUS = NF90_PUT_VAR(FILE_ID, VID1(15), BLAZE%CAvgAnnRainf, start=(/ 1, CNT /), & $ count=(/ mp, 1 /))
Arguments
Type Intent Optional Attributes Name
type(TYPE_BLAZE), intent(in) :: BLAZE
logical, intent(in) :: FINAL
Calls
Called by
Contents
None
Call graph
write_blaze_output_nc calls nf90_create, nf90_def_dim, nf90_def_var, handle_err, nf90_put_att, nf90_enddef, nf90_put_var, nf90_close
handle_err calls nf90_strerror, mpi_abort
spincasacnp calls write_blaze_output_nc
mpidrv_master calls write_blaze_output_nc
cable_offline_driver calls write_blaze_output_nc, spincasacnp
mpi_driver calls mpidrv_master