write_netcdf_casabiome – POP
write_netcdf_casabiome Subroutine
126 statements
Source File
private subroutine write_netcdf_casabiome(filename, casabiome)
Uses
cable_def_types_mod
netcdf
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_biome), intent(in) :: casabiome
Calls
Called by
Contents
Call graph
write_netcdf_casabiome calls nf90_create, nf90_def_dim, nc_err, nf90_enddef, nf90_def_var, nf90_put_var, nf90_close
nc_err calls nf90_strerror
write_netcdf_casa_var calls write_netcdf_casabiome
write_casa_restart_nc calls write_netcdf_casa_var
master_spincasacnp calls write_casa_restart_nc
cable_offline_driver calls write_casa_restart_nc
master_casaonly_luc calls write_casa_restart_nc
mpidrv_master calls write_casa_restart_nc, master_spincasacnp, master_casaonly_luc
mpi_driver calls mpidrv_master