write_casa_dump – POP
write_casa_dump Subroutine
102 statements
Source File
public subroutine write_casa_dump(ncfile, casamet, casaflux, phen, climate, c13o2flux, n_call, kend)
Uses
cable_common_module
casavariable
cable_diag_module
cable_c13o2_def
phenvariable
netcdf
cable_def_types_mod
casadimension
Arguments
Type Intent Optional Attributes Name
character(len=*) :: ncfile
type(casa_met), intent(in) :: casamet
type(casa_flux), intent(in) :: casaflux
type(phen_variable), intent(in) :: phen
type(climate_type), intent(in) :: climate
type(c13o2_flux), intent(in) :: c13o2flux
integer, intent(in) :: n_call
integer, intent(in) :: kend
Calls
Called by
Contents
None
Call graph
write_casa_dump calls nf90_create, def_vars, nf90_enddef, def_dims, stderr_nc, put_var_nc, nf90_close
def_vars calls stderr_nc, nf90_def_var
def_dims calls stderr_nc, nf90_def_dim
stderr_nc calls nf90_strerror, mpi_abort
put_var_nc calls put_var_ncr1, put_var_ncr2, put_var_ncr3
put_var_ncr1 calls stderr_nc, nf90_inq_varid, nf90_put_var
put_var_ncr2 calls stderr_nc, nf90_inq_varid, nf90_put_var
put_var_ncr3 calls stderr_nc, nf90_inq_varid, nf90_put_var
mpidrv_master calls write_casa_dump
cable_offline_driver calls write_casa_dump
mpi_driver calls mpidrv_master