write_output – POP
write_output Subroutine
1037 statements
Source File
public subroutine write_output(dels, ktau, met, canopy, casaflux, casapool, casamet, ssnow, rad, bal, air, soil, veg, SBOLTZ, EMLEAF, EMSOIL, c13o2pools, c13o2flux)
vh_js !! vh_js !! vh_js !! output calc of soil albedo based on colour? - Ticket #27
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: ktau
type(met_type), intent(in) :: met
type(canopy_type), intent(in) :: canopy
type(casa_flux), intent(in) :: casaflux
type(casa_pool), intent(in) :: casapool
type(casa_met), intent(in) :: casamet
type(soil_snow_type), intent(in) :: ssnow
type(radiation_type), intent(in) :: rad
type(balances_type), intent(inout) :: bal
type(air_type), intent(in) :: air
type(soil_parameter_type), intent(in) :: soil
type(veg_parameter_type), intent(in) :: veg
real, intent(in) :: SBOLTZ
real, intent(in) :: EMLEAF
real, intent(in) :: EMSOIL
type(c13o2_pool), intent(in) :: c13o2pools
type(c13o2_flux), intent(in) :: c13o2flux
Calls
Called by
Contents
None
Call graph
write_output calls mass_balance, cable_abort, nf90_put_var, energy_balance, is_leapyear, nc_abort, toreal4, write_ovar, nf90_sync
cable_abort calls mpi_abort
nc_abort calls mpi_abort, nf90_strerror
toreal4 calls i2sp, dp2sp, sp2sp
write_ovar calls write_output_parameter_r2d, write_output_variable_r1, write_output_variable_r2, write_output_parameter_r1d, write_output_parameter_r1, write_output_parameter_r2
write_output_parameter_r2d calls cable_abort, nf90_put_var, nc_abort
write_output_variable_r1 calls cable_abort, nf90_put_var, nc_abort, range_abort
write_output_variable_r2 calls cable_abort, nf90_put_var, nc_abort, range_abort
write_output_parameter_r1d calls cable_abort, nf90_put_var, nc_abort
write_output_parameter_r1 calls cable_abort, nf90_put_var, nc_abort
write_output_parameter_r2 calls cable_abort, nf90_put_var, nc_abort
range_abort calls mpi_abort
mpidrv_master calls write_output
cable_offline_driver calls write_output
mpi_driver calls mpidrv_master