write_netcdf_casapool – POP
write_netcdf_casapool Subroutine
104 statements
Source File
private subroutine write_netcdf_casapool(filename, casapool)
Uses
cable_def_types_mod
netcdf
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_pool), intent(in) :: casapool
Calls
Called by
Contents
None
Call graph
write_netcdf_casapool calls nf90_create, nc_err, nf90_def_var, nf90_def_dim, nf90_enddef, nf90_put_var, nf90_close
nc_err calls nf90_strerror
write_netcdf_casa_var calls write_netcdf_casapool
write_casa_restart_nc calls write_netcdf_casa_var
master_spincasacnp calls write_casa_restart_nc
master_casaonly_luc calls write_casa_restart_nc
mpidrv_master calls write_casa_restart_nc, master_spincasacnp, master_casaonly_luc
cable_offline_driver calls write_casa_restart_nc
mpi_driver calls mpidrv_master