WRITE_CLIMATE_RESTART_NC – POP
WRITE_CLIMATE_RESTART_NC Subroutine
14 statements
Source File
public subroutine WRITE_CLIMATE_RESTART_NC(climate)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(climate_type), intent(in) :: climate
Calls
Called by
Contents
None
Call graph
write_climate_restart_nc calls write_netcdf_cbm_var
write_netcdf_cbm_var calls write_netcdf_climate_type
write_netcdf_climate_type calls nf90_create, nf90_enddef, nf90_def_dim, nc_err, nf90_def_var, nf90_put_var, nf90_close
nc_err calls nf90_strerror, mpi_abort
mpidrv_master calls write_climate_restart_nc
cable_offline_driver calls write_climate_restart_nc
mpi_driver calls mpidrv_master