xvcmxt3 – POP
xvcmxt3 Function
11 statements
Source File
public function xvcmxt3(Tk) result(z)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: Tk
Return Value real
Calls
Called by
Contents
Call graph
xvcmxt3 calls point2constants
point2constants calls driver_type_ptr, air_type_ptr, canopy_type_ptr, cbm_type_ptr, albedo_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr
dryleaf calls xvcmxt3
diff_ac_aj calls xvcmxt3
total_an_ac_aj calls xvcmxt3
total_photosynthesis calls xvcmxt3
total_photosynthesis_cost calls xvcmxt3
define_canopy calls dryleaf
optimise_jv calls diff_ac_aj, total_photosynthesis_cost
cbm calls define_canopy
casa_feedback calls optimise_jv
mpidrv_worker calls cbm, casa_feedback
cable_offline_driver calls cbm, casa_feedback
mpi_driver calls mpidrv_worker