zero_casa_dump – POP
zero_casa_dump Subroutine
50 statements
Source File
public subroutine zero_casa_dump(casamet, phen)
Uses
phenvariable
casavariable
cable_def_types_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
type(casa_met), intent(inout) :: casamet
type(phen_variable), intent(inout) :: phen
Called by
Contents
None
Call graph
casa_init calls zero_casa_dump
load_parameters calls casa_init
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master