zero_casapool – POP
zero_casapool Subroutine
47 statements
Source File
private subroutine zero_casapool(casapool)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(inout) :: casapool
Called by
Contents
Call graph
zero_sum_casa calls zero_casapool
zero_casa_var calls zero_casapool
load_parameters calls zero_sum_casa, zero_casa_var
mpidrv_master calls zero_sum_casa, load_parameters, master_casaonly_luc, master_spincasacnp
cable_offline_driver calls zero_sum_casa, load_parameters, casaonly_luc
worker_casa_params calls zero_casa_var
casaonly_luc calls zero_sum_casa
master_casaonly_luc calls zero_casa_var
master_spincasacnp calls zero_casa_var
mpi_driver calls mpidrv_master, mpidrv_worker
mpidrv_worker calls worker_casa_params