zero_casamet – POP
zero_casamet Subroutine
52 statements
Source File
private subroutine zero_casamet(casamet)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(casa_met), intent(inout) :: casamet
Called by
Contents
Call graph
zero_casa_var calls zero_casamet
load_parameters calls zero_casa_var
master_spincasacnp calls zero_casa_var
master_casaonly_luc calls zero_casa_var
worker_casa_params calls zero_casa_var
mpidrv_master calls load_parameters, master_spincasacnp, master_casaonly_luc
cable_offline_driver calls load_parameters
mpidrv_worker calls worker_casa_params
mpi_driver calls mpidrv_master, mpidrv_worker