zero_phenvariable – POP
zero_phenvariable Subroutine
15 statements
Source File
public subroutine zero_phenvariable(phen)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(phen_variable), intent(inout) :: phen
Called by
Contents
None
Call graph
load_parameters calls zero_phenvariable
worker_casa_params calls zero_phenvariable
master_spincasacnp calls zero_phenvariable
master_casaonly_luc calls zero_phenvariable
mpidrv_master calls load_parameters, master_spincasacnp, master_casaonly_luc
mpidrv_worker calls worker_casa_params
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master, mpidrv_worker