alloc_air_type – CABLE
alloc_air_type Subroutine
13 statements
Source File
public subroutine alloc_air_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(air_type), intent(inout) :: var
integer, intent(in) :: mp
Called by
Contents
None
Call graph
alloc_cbm_var calls alloc_air_type
alloc_cable_types calls alloc_cbm_var
mpidrv_master calls alloc_cbm_var, load_parameters
allocate_cable_vars calls alloc_cbm_var
climate_init calls alloc_cbm_var
interface_um_data calls alloc_cable_types
mpi_driver calls mpidrv_master
cable_offline_driver calls climate_init, load_parameters
load_parameters calls allocate_cable_vars
cable_explicit_driver calls interface_um_data