alloc_cable_types – CABLE
alloc_cable_types Subroutine
21 statements
Source File
public subroutine alloc_cable_types()
Uses
cable_um_tech_mod
allocate_veg_params_mod
allocate_soil_params_mod
cable_soil_snow_type_mod
cable_canopy_type_mod
cable_def_types_mod
Arguments
None
Calls
Called by
Contents
None
Call graph
alloc_cable_types calls alloc_cbm_var, alloc_soil_snow_type, allocate_soil_parameter_type, alloc_canopy_type, allocate_veg_parameter_type
alloc_cbm_var calls alloc_soil_snow_type, alloc_met_type, alloc_veg_parameter_type, alloc_canopy_type, alloc_balances_type, alloc_soil_parameter_type, alloc_radiation_type, alloc_roughness_type, alloc_air_type, alloc_sum_flux_type, alloc_climate_type
interface_um_data calls alloc_cable_types
cable_explicit_driver calls interface_um_data