bgcdriver – CABLE
bgcdriver Subroutine
114 statements
Source File
public subroutine bgcdriver(ktau, kstart, kend, dels, met, ssnow, canopy, veg, soil, climate, casabiome, casapool, casaflux, casamet, casabal, phen, POP, spinConv, spinup, ktauday, idoy, LOY, dump_read, dump_write, LALLOC)
Uses
casaparm
casadimension
TypeDef
phenvariable
POP_TYPES
casa_inout_module
cable_common_module
POPMODULE
casavariable
cable_def_types_mod
cable_phenology_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
integer, intent(in) :: kstart
integer, intent(in) :: kend
real, intent(in) :: dels
type(met_type), intent(inout) :: met
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(climate_type), intent(in) :: climate
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(inout) :: POP
logical, intent(in) :: spinConv
logical, intent(in) :: spinup
integer, intent(in) :: ktauday
integer, intent(in) :: idoy
integer, intent(in) :: LOY
logical, intent(in) :: dump_read
logical, intent(in) :: dump_write
integer, intent(in) :: LALLOC
Calls
Called by
Contents
None
Call graph
bgcdriver calls float, biogeochem, cable_phenology_clim
biogeochem calls casa_xratesoil, casa_allocation, casa_pdummy, casa_cnpcycle, casa_cnpflux, casa_xnp, 20, casa_xkn, casa_delplant, avgsoil, casa_xrateplant, casa_cnpbal, casa_coeffplant, casa_nuptake, casa_ndummy, phenology, casa_rplant1, casa_coeffsoil, casa_puptake, casa_delsoil
casa_cnpcycle calls casa_poolzero
casa_xnp calls casa_nrequire, casa_prequire
casa_cnpbal calls 10, 100
casa_nuptake calls casa_nrequire, 100
casa_puptake calls casa_prequire
mpidrv_worker calls bgcdriver
cable_offline_driver calls bgcdriver
mpi_driver calls mpidrv_worker