biogeochem – CABLE
biogeochem Subroutine
101 statements
Source File
public subroutine biogeochem(ktau, dels, idoy, LALLOC, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen, POP, climate, xnplimit, xkNlimiting, xklitter, xksoil, xkleaf, xkleafcold, xkleafdry, cleaf2met, cleaf2str, croot2met, croot2str, cwood2cwd, nleaf2met, nleaf2str, nroot2met, nroot2str, nwood2cwd, pleaf2met, pleaf2str, proot2met, proot2str, pwood2cwd)
Uses
cable_def_types_mod
POP_TYPES
casa_cnp_module
casadimension
$if (idoy.eq.365) then $ write(667,) pop%LU $ write(667,) veg%ilu $ write(667,991) casaflux%FluxCtohwp(POP%Iwood,1) $ write(667,991) POP%pop_grid(:)%cat_mortality/POP%pop_grid(:)%cmass_sum_old $ write(667,991)max(min((POP%pop_grid(:)%cat_mortality & $ /POP%pop_grid(:)%cmass_sum_old),0.99),0.0)(1.0/365.0) $ write(667,991) (1.0 - (1.0 -max(min((POP%pop_grid(:)%cat_mortality & $ /POP%pop_grid(:)%cmass_sum_old),0.99), 0.0))(1.0/365.0)) $write(667,*) $ endif $
vh_js !!
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
real, intent(in) :: dels
integer, intent(in) :: idoy
integer, intent(in) :: LALLOC
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
type(POP_TYPE), intent(in) :: POP
type(climate_type), intent(in) :: climate
real(kind=r_2), DIMENSION(mp) :: xnplimit
real(kind=r_2), DIMENSION(mp) :: xkNlimiting
real(kind=r_2), DIMENSION(mp) :: xklitter
real(kind=r_2), DIMENSION(mp) :: xksoil
real(kind=r_2), DIMENSION(mp) :: xkleaf
real(kind=r_2), DIMENSION(mp) :: xkleafcold
real(kind=r_2), DIMENSION(mp) :: xkleafdry
real, intent(out), DIMENSION(mp) :: cleaf2met
real, intent(out), DIMENSION(mp) :: cleaf2str
real, intent(out), DIMENSION(mp) :: croot2met
real, intent(out), DIMENSION(mp) :: croot2str
real, intent(out), DIMENSION(mp) :: cwood2cwd
real, intent(out), DIMENSION(mp) :: nleaf2met
real, intent(out), DIMENSION(mp) :: nleaf2str
real, intent(out), DIMENSION(mp) :: nroot2met
real, intent(out), DIMENSION(mp) :: nroot2str
real, intent(out), DIMENSION(mp) :: nwood2cwd
real, intent(out), DIMENSION(mp) :: pleaf2met
real, intent(out), DIMENSION(mp) :: pleaf2str
real, intent(out), DIMENSION(mp) :: proot2met
real, intent(out), DIMENSION(mp) :: proot2str
real, intent(out), DIMENSION(mp) :: pwood2cwd
Calls
Called by
Contents
None
Call graph
biogeochem calls casa_xratesoil, casa_allocation, casa_pdummy, casa_cnpcycle, casa_cnpflux, casa_xnp, 20, casa_xkn, casa_delplant, avgsoil, casa_xrateplant, casa_cnpbal, casa_coeffplant, casa_nuptake, casa_ndummy, phenology, casa_rplant1, casa_coeffsoil, casa_puptake, casa_delsoil
casa_cnpcycle calls casa_poolzero
casa_xnp calls casa_nrequire, casa_prequire
casa_cnpbal calls 10, 100
casa_nuptake calls casa_nrequire, 100
casa_puptake calls casa_prequire
spincasacnp calls biogeochem
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
cable_offline_driver calls spincasacnp, bgcdriver, casaonly_luc
mpidrv_worker calls bgcdriver
mpi_driver calls mpidrv_worker