cable_climate – CABLE
cable_climate Subroutine
145 statements
Source File
public subroutine cable_climate(ktau, kstart, kend, ktauday, idoy, LOY, met, climate, canopy, air, rad, dels, np)
$! * Find irradiances, available energy, equilibrium latent heat flux $PPc = Gaero / (Gaero + 4.0SBoltz((TempA+273.16)3)/(RhoACapp)) $ ! PPc = Ga/(Ga+Gr) [-] $EpsA = Epsif(TempA, Pmb) ! Epsi at TempA [-] $PhiSd = SolarMJ * 1.0e6 / (DayltFracSecDay) ! daylt down solar [W/m2] $PhiLd = 335.97 * (((TempA + 273.16) / 293.0)6) ! daylt down thermal [W/m2] $ ! (Swinbank formula) $PhiAi = (1.0-Albedo)PhiSd + Emis * & ! daylt iso-avail engy [W/m2] $ (PhiLd - SBoltz((TempA + 273.16)4)) ! (veg + soil) $PhiEq = PhiAi * (PPcEpsA) / (PPcEpsA + 1.0) ! equil ltnt heat flux [W/m2] $PhiEq = max(PhiEq, 1.0) ! PhiEq > +1 W/m2, so non-negative $ ! precipitation [m/day] $FWPT = CoeffPT * PhiEq * ((DayltFracSecDay) / (RhoWRlat))
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
integer, intent(in) :: kstart
integer, intent(in) :: kend
integer, intent(in) :: ktauday
integer, intent(in) :: idoy
integer, intent(in) :: LOY
type(met_type), intent(in) :: met
type(climate_type), intent(inout) :: climate
type(canopy_type), intent(in) :: canopy
type(air_type), intent(in) :: air
type(radiation_type), intent(in) :: rad
real, intent(in) :: dels
integer, intent(in) :: np
Calls
Called by
Contents
None
Call graph
cable_climate calls epsif, biome1_pft, float
mpidrv_worker calls cable_climate
cable_offline_driver calls cable_climate
mpi_driver calls mpidrv_worker