cable_um_runtime_vars – CABLE
cable_um_runtime_vars Subroutine
43 statements
Source File
public subroutine cable_um_runtime_vars(runtime_vars_file)
Uses
casadimension
casavariable
cable_common_module
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: runtime_vars_file
Calls
Called by
Contents
None
Call graph
cable_um_runtime_vars calls check_nmlvar
check_nmlvar calls check_chvar, check_intvar, check_lgvar
cable_explicit_driver calls cable_um_runtime_vars