cable_fprintf1 – CABLE
cable_fprintf1 Subroutine
13 statements
Source File
public subroutine cable_fprintf1(iDiag, basename, knode, ktau, L_fprint)
Uses
cable_common_module
cable_fFile_module
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: basename
integer :: knode
integer :: ktau
logical :: L_fprint
Calls
Called by
Contents
None
Call graph
cable_fprintf1 calls open_file_per_node, cable_print1
open_file_per_node calls open_idiag
cable_fprintf calls cable_fprintf1