cable_rad_driver – CABLE
cable_rad_driver Subroutine
67 statements
Source File
subroutine cable_rad_driver(surf_down_sw, cos_zenith_angle, SNOW_TILE, SNOW_TMP3L, SNOW_RHO1L, TSOIL_TILE, isnow_flg3l, ALBSOIL, LAND_ALBEDO_CABLE, ALB_TILE, LAND_ALB_CABLE)
Uses
cable_um_init_subrs_mod
cable_other_constants_mod
cable_um_tech_mod
cable_common_module
cable_math_constants_mod
cable_def_types_mod
cbl_masks_mod
cbl_albedo_mod
Arguments
Type Intent Optional Attributes Name
real, DIMENSION(um1%row_length,um1%rows,4) :: surf_down_sw
real, DIMENSION(um1%row_length,um1%rows) :: cos_zenith_angle
real, DIMENSION(um1%LAND_PTS,um1%NTILES) :: SNOW_TILE
real, DIMENSION(um1%LAND_PTS, um1%NTILES, 3) :: SNOW_TMP3L
real, DIMENSION(um1%LAND_PTS,um1%NTILES) :: SNOW_RHO1L
real, DIMENSION(um1%LAND_PTS, um1%NTILES, um1%SM_LEVELS) :: TSOIL_TILE
integer, DIMENSION(um1%LAND_PTS,um1%NTILES) :: isnow_flg3l
real :: ALBSOIL(um1%LAND_PTS)
real, DIMENSION(um1%row_length,um1%rows,4) :: LAND_ALBEDO_CABLE
real, DIMENSION(um1%LAND_PTS, um1%NTILES, 4) :: ALB_TILE
real, DIMENSION(um1%row_length,um1%rows) :: LAND_ALB_CABLE
Calls
Contents
None
Call graph
cable_rad_driver calls update_kblum_radiation, albedo, um2cable_lp, um2cable_met_rad
albedo calls surface_albedosn
um2cable_met_rad calls um2cable_rr