casa_readpoint_pk – CABLE
casa_readpoint_pk Subroutine
45 statements
Source File
public subroutine casa_readpoint_pk(sin_theta_latitude, veg, soil, casaflux, casamet, nidep, nifix, pwea, pdust, soil_order)
Uses
casaparm
cable_um_init_subrs_mod
cable_um_tech_mod
cable_data_module
casavariable
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in), DIMENSION(um1%row_length,um1%rows) :: sin_theta_latitude
type(veg_parameter_type) :: veg
type(soil_parameter_type) :: soil
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
real, DIMENSION(um1%land_pts) :: nidep
real, DIMENSION(um1%land_pts) :: nifix
real, DIMENSION(um1%land_pts) :: pwea
real, DIMENSION(um1%land_pts) :: pdust
real, DIMENSION(um1%land_pts) :: soil_order
Calls
Called by
Contents
None
Call graph
casa_readpoint_pk calls um2cable_rr, um2cable_ilp, um2cable_lp
init_casacnp calls casa_readpoint_pk
interface_um_data calls init_casacnp
cable_explicit_driver calls interface_um_data