casa_xkN – CABLE
casa_xkN Subroutine
58 statements
Source File
public subroutine casa_xkN(xkNlimiting, casapool, casaflux, casamet, veg)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(inout), DIMENSION(mp) :: xkNlimiting
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(veg_parameter_type), intent(in) :: veg
Called by
Contents
None
Call graph
biogeochem calls casa_xkn
bgcdriver calls biogeochem
spincasacnp calls biogeochem
casaonly_luc calls biogeochem
cable_implicit_driver calls bgcdriver
mpidrv_worker calls bgcdriver
cable_offline_driver calls bgcdriver, spincasacnp, casaonly_luc
mpi_driver calls mpidrv_worker