casa_feedback – CABLE
casa_feedback Subroutine
54 statements
Source File
public subroutine casa_feedback(ktau, veg, casabiome, casapool, casamet)
Uses
casaparm
casadimension
cable_common_module
cable_def_types_mod
casavariable
casa_cnp_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(in) :: casapool
type(casa_met), intent(in) :: casamet
Calls
Called by
Contents
None
Call graph
casa_feedback calls vcmax_np
mpidrv_worker calls casa_feedback
cable_offline_driver calls casa_feedback
mpi_driver calls mpidrv_worker