casa_init_pk – CABLE
casa_init_pk Subroutine
115 statements
Source File
public subroutine casa_init_pk(casabiome, casaflux, casamet, casapool, casabal, veg, canopy, phen, cpool_tile, npool_tile, ppool_tile, WOOD_HVEST_C, WOOD_HVEST_N, WOOD_HVEST_P, WOOD_FLUX_C, WOOD_FLUX_N, WOOD_FLUX_P, WRESP_C, WRESP_N, WRESP_P, THINNING, GLAI, PHENPHASE, PREV_YR_SFRAC, idoy)
Uses
casaparm
cable_um_tech_mod
casadimension
phenvariable
cable_common_module
casavariable
cable_def_types_mod
USE define_dimensions ! mp, r_2
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(in) :: casabiome
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_pool), intent(inout) :: casapool
type(casa_balance), intent(inout) :: casabal
type(veg_parameter_type), intent(inout) :: veg
type(canopy_type), intent(inout) :: canopy
type(phen_variable), intent(inout) :: phen
real, intent(inout) :: cpool_tile(um1%land_pts,um1%ntiles,10)
real, intent(inout) :: npool_tile(um1%land_pts,um1%ntiles,10)
real, intent(inout) :: ppool_tile(um1%land_pts,um1%ntiles,12)
real, intent(inout) :: WOOD_HVEST_C(um1%land_pts,um1%ntiles,3)
real, intent(inout) :: WOOD_HVEST_N(um1%land_pts,um1%ntiles,3)
real, intent(inout) :: WOOD_HVEST_P(um1%land_pts,um1%ntiles,3)
real, intent(inout) :: WOOD_FLUX_C(um1%land_pts,um1%ntiles)
real, intent(inout) :: WOOD_FLUX_N(um1%land_pts,um1%ntiles)
real, intent(inout) :: WOOD_FLUX_P(um1%land_pts,um1%ntiles)
real, intent(inout) :: WRESP_C(um1%land_pts,um1%ntiles,3)
real, intent(inout) :: WRESP_N(um1%land_pts,um1%ntiles,3)
real, intent(inout) :: WRESP_P(um1%land_pts,um1%ntiles,3)
real, intent(inout) :: THINNING(um1%land_pts,um1%ntiles)
real, intent(inout) :: GLAI(um1%land_pts,um1%ntiles)
real, intent(inout) :: PHENPHASE(um1%land_pts,um1%ntiles)
real, intent(inout) :: PREV_YR_SFRAC(um1%land_pts,um1%ntiles)
integer :: idoy
Calls
Called by
Contents
None
Call graph
casa_init_pk calls casa_reinit_pk, pack_cnppool
casa_reinit_pk calls pack_cnppool, newplant, newlitter_thin, newsoil, casa_feedback, newlitter
init_casacnp calls casa_init_pk
interface_um_data calls init_casacnp
cable_explicit_driver calls interface_um_data