casa_Nrequire – CABLE
casa_Nrequire Subroutine
34 statements
Source File
public subroutine casa_Nrequire(xnCnpp, Nreqmin, Nreqmax, NtransPtoP, veg, casabiome, casapool, casaflux, casamet)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(mp) :: xnCnpp
real(kind=r_2), intent(inout), DIMENSION(mp,mplant) :: Nreqmin
real(kind=r_2), intent(inout), DIMENSION(mp,mplant) :: Nreqmax
real(kind=r_2), intent(inout), DIMENSION(mp,mplant) :: NtransPtoP
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
Called by
Contents
None
Call graph
casa_xnp calls casa_nrequire
casa_nuptake calls casa_nrequire
biogeochem calls casa_xnp, casa_nuptake
bgcdriver calls biogeochem
spincasacnp calls biogeochem
casaonly_luc calls biogeochem
cable_implicit_driver calls bgcdriver
mpidrv_worker calls bgcdriver
cable_offline_driver calls bgcdriver, spincasacnp, casaonly_luc
mpi_driver calls mpidrv_worker