casa_cnpflux – CABLE
casa_cnpflux Subroutine
71 statements
Source File
public subroutine casa_cnpflux(casaflux, casapool, casabal, zeroflux)
Uses
cable_def_types_mod
casaparm
casadimension
casavariable
Arguments
Type Intent Optional Attributes Name
type(casa_flux), intent(inout) :: casaflux
type(casa_pool), intent(inout) :: casapool
type(casa_balance), intent(inout) :: casabal
logical :: zeroflux
Called by
Contents
None
Call graph
biogeochem calls casa_cnpflux
cable_offline_driver calls casa_cnpflux, spincasacnp, bgcdriver, casaonly_luc
spincasacnp calls biogeochem
bgcdriver calls biogeochem
casaonly_luc calls biogeochem
mpidrv_worker calls bgcdriver
mpi_driver calls mpidrv_worker