create_new_gridinfo – CABLE
create_new_gridinfo Subroutine
532 statements
Source File
subroutine create_new_gridinfo(fgridold, fgridnew, mlon, mlat, landmask, patchfrac_new)
Uses
landuse_constant
cable_IO_vars_module
cable_common_module
netcdf
cable_def_types_mod
cable_abort_module
Arguments
Type Intent Optional Attributes Name
character(len=500) :: fgridold
character(len=500) :: fgridnew
integer :: mlon
integer :: mlat
integer, dimension(mlon,mlat) :: landmask
real(kind=r_2), dimension(mlon,mlat,mvmax) :: patchfrac_new
Calls
Called by
Contents
None
Call graph
create_new_gridinfo calls nc_abort, nf90_get_var, nf90_close, nf90_def_var, nf90_def_dim, nf90_enddef, nf90_put_var, sort, nf90_inq_varid, nf90_open, nf90_create, nf90_put_att, rangechk3, rangechk2
nc_abort calls nf90_strerror
mpidrv_master calls create_new_gridinfo
cable_offline_driver calls create_new_gridinfo
mpi_driver calls mpidrv_master