decomp_types – CABLE
decomp_types Subroutine
43 statements
Source File
public subroutine decomp_types(landpt_t, patch_t)
Uses
mpi
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: landpt_t
integer, intent(out) :: patch_t
Calls
Contents
None
Call graph
decomp_types calls mpi_get_address, mpi_type_create_struct, mpi_type_commit, mpi_type_create_resized