def_var_atts – CABLE
def_var_atts Subroutine
19 statements
Source File
public subroutine def_var_atts(ncfile_in, ncid, varID)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: ncfile_in
integer, intent(in) :: ncid
integer, intent(in), dimension(:) :: varID
Calls
Contents
None
Call graph
def_var_atts calls nf90_put_att, stderr_nc
stderr_nc calls nf90_strerror