def_dims – CABLE
def_dims Subroutine
14 statements
Source File
public subroutine def_dims(nd, ncid, dimID, dim_len, dim_name)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nd
integer, intent(in) :: ncid
integer, intent(out), dimension(:) :: dimID
integer, intent(in), dimension(:) :: dim_len
character(len=*), intent(in), dimension(:) :: dim_name
Calls
Called by
Contents
None
Call graph
def_dims calls nf90_def_dim, stderr_nc
stderr_nc calls nf90_strerror
write_casa_dump calls def_dims
mpidrv_master calls write_casa_dump
cable_offline_driver calls write_casa_dump
mpi_driver calls mpidrv_master