get_restart_data – CABLE
get_restart_data Subroutine
157 statements
Source File
public subroutine get_restart_data(logn, ssnow, canopy, rough, bgc, bal, veg, soil, rad, vegparmnew, EMSOIL)
(BP Nov 2009) $ IF(cable_user%SOIL_STRUC=='sli'.or.cable_user%FWSOIL_SWITCH=='Haverd2013') THEN $ CALL readpar(ncid_rin,'gamma',dummy,veg%gamma,filename%restart_in, & $ max_vegpatches,'def',from_restart,mp) $ ENDIF
$ CALL readpar(ncid_rin,'ZR',dummy,veg%ZR, & $ filename%restart_in,max_vegpatches,'def',from_restart,mp) $ CALL readpar(ncid_rin,'F10',dummy,veg%F10, & $ filename%restart_in,max_vegpatches,'def',from_restart,mp) $ CALL readpar(ncid_rin,'zeta',dummy,soil%zeta,filename%restart_in, & $ max_vegpatches,'def',from_restart,mp) $ CALL readpar(ncid_rin,'fsatmax',dummy,soil%fsatmax,filename%restart_in, & $ max_vegpatches,'def',from_restart,mp) $ CALL readpar(ncid_rin,'nhorizons',dummy,soil%nhorizons,filename%restart_in, & $ max_vegpatches,'def',from_restart,mp) $ ALLOCATE(var_r2(mp,ms)) $ CALL readpar(ncid_rin,'ishorizon',dummy,var_r2,filename%restart_in, & $ max_vegpatches,'ms',from_restart,mp) $ soil%ishorizon = int(var_r2) $ DEALLOCATE(var_r2) $ CALL readpar(ncid_rin,'clitt',dummy,veg%clitt,filename%restart_in, & $ max_vegpatches,'def',from_restart,mp) getting rid of spurious veg types in Antarctica from the CCAM2Mk3L process Doing it once will fix the problem in the restart file in subsequent runs
end of fix to spurious veg types
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: logn
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
type(roughness_type), intent(inout) :: rough
type(bgc_pool_type), intent(inout) :: bgc
type(balances_type), intent(inout) :: bal
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(radiation_type), intent(inout) :: rad
logical, intent(in) :: vegparmnew
real, intent(in) :: EMSOIL
Calls
Called by
Contents
None
Call graph
get_restart_data calls nf90_get_var, nf90_close, nc_abort, nf90_inquire_dimension, nf90_inq_dimid, nf90_inq_varid, readpar
nc_abort calls nf90_strerror
load_parameters calls get_restart_data
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master