GET_CRU_Ndep – CABLE
GET_CRU_Ndep Subroutine
40 statements
Source File
public subroutine GET_CRU_Ndep(CRU)
Arguments
Type Intent Optional Attributes Name
type(CRU_TYPE), intent(inout) :: CRU
Calls
Called by
Contents
None
Call graph
get_cru_ndep calls nf90_open, handle_err, nf90_inq_varid, nf90_get_var
handle_err calls nf90_strerror
cru_get_subdiurnal_met calls get_cru_ndep
mpidrv_master calls cru_get_subdiurnal_met
cable_offline_driver calls cru_get_subdiurnal_met
mpi_driver calls mpidrv_master