init_casacnp – CABLE
init_casacnp Subroutine
38 statements
Source File
public subroutine init_casacnp(sin_theta_latitude, cpool_tile, npool_tile, ppool_tile, soil_order, nidep, nifix, pwea, pdust, WOOD_HVEST_C, WOOD_HVEST_N, WOOD_HVEST_P, WOOD_FLUX_C, WOOD_FLUX_N, WOOD_FLUX_P, WRESP_C, WRESP_N, WRESP_P, THINNING, GLAI, PHENPHASE, PREV_YR_SFRAC, idoy)
Uses
casa_types_mod
cable_um_tech_mod
phenvariable
casavariable
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in), DIMENSION(um1%row_length,um1%rows) :: sin_theta_latitude
real, intent(inout) :: cpool_tile(um1%land_pts,um1%ntiles,10)
real, intent(inout) :: npool_tile(um1%land_pts,um1%ntiles,10)
real, intent(inout) :: ppool_tile(um1%land_pts,um1%ntiles,12)
real, intent(inout) :: soil_order(um1%land_pts)
real, intent(inout) :: nidep(um1%land_pts)
real, intent(inout) :: nifix(um1%land_pts)
real, intent(inout) :: pwea(um1%land_pts)
real, intent(inout) :: pdust(um1%land_pts)
real, intent(inout) :: WOOD_HVEST_C(um1%land_pts,um1%ntiles,3)
real, intent(inout) :: WOOD_HVEST_N(um1%land_pts,um1%ntiles,3)
real, intent(inout) :: WOOD_HVEST_P(um1%land_pts,um1%ntiles,3)
real, intent(inout) :: WOOD_FLUX_C(um1%land_pts,um1%ntiles)
real, intent(inout) :: WOOD_FLUX_N(um1%land_pts,um1%ntiles)
real, intent(inout) :: WOOD_FLUX_P(um1%land_pts,um1%ntiles)
real, intent(inout) :: WRESP_C(um1%land_pts,um1%ntiles,3)
real, intent(inout) :: WRESP_N(um1%land_pts,um1%ntiles,3)
real, intent(inout) :: WRESP_P(um1%land_pts,um1%ntiles,3)
real, intent(inout) :: THINNING(um1%land_pts,um1%ntiles)
real, intent(inout) :: GLAI(um1%land_pts,um1%ntiles)
real, intent(inout) :: PHENPHASE(um1%land_pts,um1%ntiles)
real, intent(inout) :: PREV_YR_SFRAC(um1%land_pts,um1%ntiles)
integer :: idoy
casafile%cnpmetin ='/home/599/lxs599/surface_data/casametDH.csv'
Calls
Called by
Contents
None
Call graph
init_casacnp calls alloc_casavariable, casa_readphen, casa_readpoint_pk, alloc_phenvariable, casa_readbiome, casa_init_pk
casa_readpoint_pk calls um2cable_rr, um2cable_ilp, um2cable_lp
casa_init_pk calls pack_cnppool, casa_reinit_pk
casa_reinit_pk calls pack_cnppool, newplant, newlitter_thin, newsoil, casa_feedback, newlitter
interface_um_data calls init_casacnp
cable_explicit_driver calls interface_um_data