initialize_soilsnow – CABLE
initialize_soilsnow Subroutine
121 statements
Source File
public subroutine initialize_soilsnow(smvcst, tsoil_tile, sthf_tile, smcl_tile, snow_tile, snow_rho1l, snage_tile, isnow_flg3l, snow_rho3l, snow_cond, snow_depth3l, snow_mass3l, snow_tmp3l, fland, sin_theta_latitude)
Uses
cable_def_types_mod
cable_data_module
cable_um_tech_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in), DIMENSION(um1%land_pts) :: smvcst
real, intent(in), DIMENSION(um1%land_pts, um1%ntiles, um1%sm_levels) :: tsoil_tile
real, intent(in), DIMENSION(um1%land_pts, um1%ntiles, um1%sm_levels) :: sthf_tile
real, intent(in), DIMENSION(um1%land_pts, um1%ntiles, um1%sm_levels) :: smcl_tile
real, intent(inout), DIMENSION(um1%land_pts, um1%ntiles) :: snow_tile
real, intent(in), DIMENSION(um1%land_pts, um1%ntiles) :: snow_rho1l
real, intent(in), DIMENSION(um1%land_pts, um1%ntiles) :: snage_tile
integer, intent(in), DIMENSION(um1%land_pts, um1%ntiles) :: isnow_flg3l
real, intent(in), DIMENSION(um1%land_pts, um1%ntiles,3) :: snow_rho3l
real, intent(inout), DIMENSION(um1%land_pts, um1%ntiles,3) :: snow_cond
real, intent(in), DIMENSION(um1%land_pts, um1%ntiles,3) :: snow_depth3l
real, intent(in), DIMENSION(um1%land_pts, um1%ntiles,3) :: snow_mass3l
real, intent(in), DIMENSION(um1%land_pts, um1%ntiles,3) :: snow_tmp3l
real, intent(in), DIMENSION(um1%land_pts) :: fland
real, intent(in), DIMENSION(um1%row_length, um1%rows) :: sin_theta_latitude
Calls
Called by
Contents
None
Call graph
initialize_soilsnow calls um2cable_lp
interface_um_data calls initialize_soilsnow
cable_explicit_driver calls interface_um_data