initialize_radiation – CABLE
initialize_radiation Subroutine
53 statements
Source File
public subroutine initialize_radiation(sw_down, lw_down, cos_zenith_angle, surf_down_sw, sin_theta_latitude, ls_rain, ls_snow, tl_1, qw_1, vshr_land, pstar, co2_mmr, CO2_3D, CO2_DIM_LEN, CO2_DIM_ROW, L_CO2_INTERACTIVE)
Uses
cable_def_types_mod
cable_data_module
cable_um_tech_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(inout), DIMENSION(um1%row_length, um1%rows) :: sw_down
real, intent(in), DIMENSION(um1%row_length, um1%rows) :: lw_down
real, intent(inout), DIMENSION(um1%row_length, um1%rows) :: cos_zenith_angle
real, intent(in), DIMENSION(um1%row_length, um1%rows, 4) :: surf_down_sw
real, intent(in), DIMENSION(um1%row_length, um1%rows) :: sin_theta_latitude
real, intent(in), DIMENSION(um1%row_length, um1%rows) :: ls_rain
real, intent(in), DIMENSION(um1%row_length, um1%rows) :: ls_snow
real, intent(in), DIMENSION(um1%row_length, um1%rows) :: tl_1
real, intent(in), DIMENSION(um1%row_length, um1%rows) :: qw_1
real, intent(in), DIMENSION(um1%row_length, um1%rows) :: vshr_land
real, intent(in), DIMENSION(um1%row_length, um1%rows) :: pstar
real, intent(in) :: co2_mmr
real, intent(in) :: CO2_3D(CO2_DIM_LEN,CO2_DIM_ROW)
integer, intent(in) :: CO2_DIM_LEN
integer, intent(in) :: CO2_DIM_ROW
logical, intent(in) :: L_CO2_INTERACTIVE
Calls
Called by
Contents
None
Call graph
initialize_radiation calls update_kblum_radiation, um2cable_met_rad, um2cable_rr
um2cable_met_rad calls um2cable_rr
interface_um_data calls initialize_radiation
cable_explicit_driver calls interface_um_data