initialize_veg – CABLE
initialize_veg Subroutine
36 statements
Source File
public subroutine initialize_veg(clobbered_htveg, land_pts, npft, ntiles, ms, mp, canht_ft, lai_ft, soil_zse, veg, tile_pts, tile_index, tile_frac, L_tile_pts, CLAI_thresh)
Uses
cbl_LAI_canopy_height_mod
cable_def_types_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
real :: clobbered_htveg(land_pts,ntiles)
integer :: land_pts
integer :: npft
integer :: ntiles
integer :: ms
integer :: mp
real, intent(in) :: canht_ft(land_pts,npft)
real, intent(in) :: lai_ft(land_pts,npft)
real :: soil_zse(ms)
type(veg_parameter_type), intent(inout) :: veg
integer :: tile_pts(ntiles)
integer :: tile_index(land_pts,ntiles)
real :: tile_frac(land_pts,ntiles)
logical :: L_tile_pts(land_pts,ntiles)
real :: CLAI_thresh
Calls
Called by
Contents
None
Call graph
initialize_veg calls init_veg_pars_fr_vegin, limit_hgt_lai
init_veg_pars_fr_vegin calls init_veg_from_vegin
interface_um_data calls initialize_veg
cable_explicit_driver calls interface_um_data