init_veg_pars_fr_vegin – CABLE
init_veg_pars_fr_vegin Subroutine
18 statements
Source File
public subroutine init_veg_pars_fr_vegin(soil_zse)
Uses
cable_def_types_mod
cable_um_tech_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, dimension(ms) :: soil_zse
Calls
Called by
Contents
None
Call graph
init_veg_pars_fr_vegin calls init_veg_from_vegin
initialize_veg calls init_veg_pars_fr_vegin
interface_um_data calls initialize_veg
cable_explicit_driver calls interface_um_data