initialize_soil – CABLE
initialize_soil Subroutine
52 statements
Source File
public subroutine initialize_soil(bexp, hcon, satcon, sathh, smvcst, smvcwt, smvccl, albsoil, tsoil_tile, sthu, sthu_tile, dzsoil)
Uses
cable_def_types_mod
cable_um_tech_mod
cable_params_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in), DIMENSION(um1%land_pts) :: bexp
real, intent(in), DIMENSION(um1%land_pts) :: hcon
real, intent(in), DIMENSION(um1%land_pts) :: satcon
real, intent(in), DIMENSION(um1%land_pts) :: sathh
real, intent(in), DIMENSION(um1%land_pts) :: smvcst
real, intent(in), DIMENSION(um1%land_pts) :: smvcwt
real, intent(in), DIMENSION(um1%land_pts) :: smvccl
real, intent(in), DIMENSION(um1%land_pts) :: albsoil
real, intent(in), DIMENSION(um1%land_pts, um1%ntiles, um1%sm_levels) :: tsoil_tile
real, intent(in), DIMENSION(um1%land_pts, um1%sm_levels) :: sthu
real, intent(in), DIMENSION(um1%land_pts, um1%ntiles, um1%sm_levels) :: sthu_tile
real, intent(in), DIMENSION(um1%sm_levels) :: dzsoil
Calls
Called by
Contents
None
Call graph
initialize_soil calls um2cable_lp
interface_um_data calls initialize_soil
cable_explicit_driver calls interface_um_data