interface_UM_data – CABLE
interface_UM_data Subroutine
101 statements
Source File
public subroutine interface_UM_data(row_length, rows, land_pts, ntiles, npft, sm_levels, itimestep, latitude, longitude, land_index, tile_frac, tile_pts, tile_index, bexp, hcon, satcon, sathh, smvcst, smvcwt, smvccl, albsoil, snow_tile, snow_rho1l, snage_tile, isnow_flg3l, snow_rho3l, snow_cond, snow_depth3l, snow_tmp3l, snow_mass3l, sw_down, lw_down, cos_zenith_angle, surf_down_sw, ls_rain, ls_snow, tl_1, qw_1, vshr_land, pstar, z1_tq, z1_uv, rho_water, L_tile_pts, canopy_tile, fland, co2_mmr, CO2_3D, CO2_DIM_LEN, CO2_DIM_ROW, L_CO2_INTERACTIVE, sthu_tile, smcl_tile, sthf_tile, sthu, tsoil_tile, canht_ft, lai_ft, sin_theta_latitude, dzsoil, CPOOL_TILE, NPOOL_TILE, PPOOL_TILE, SOIL_ORDER, NIDEP, NIFIX, PWEA, PDUST, GLAI, PHENPHASE, WOOD_HVEST_C, WOOD_HVEST_N, WOOD_HVEST_P, WOOD_FLUX_C, WOOD_FLUX_N, WOOD_FLUX_P, WRESP_C, WRESP_N, WRESP_P, THINNING, PREV_YR_SFRAC, NPP_FT_ACC, RESP_W_FT_ACC, RESP_S_ACC, iday)
Uses
cable_um_init_subrs_mod
cable_um_tech_mod
cable_pft_params_mod
cable_other_constants_mod
cable_soil_params_mod
casa_um_inout_mod
cable_common_module
cable_def_types_mod
cbl_ssnow_data_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: row_length
integer, intent(in) :: rows
integer, intent(in) :: land_pts
integer, intent(in) :: ntiles
integer, intent(in) :: npft
integer, intent(in) :: sm_levels
integer, intent(in) :: itimestep
real, intent(in), DIMENSION(row_length,rows) :: latitude
real, intent(in), DIMENSION(row_length,rows) :: longitude
integer, intent(in), DIMENSION(land_pts) :: land_index
real, intent(in), DIMENSION(land_pts, ntiles) :: tile_frac
integer, intent(in), DIMENSION(ntiles) :: tile_pts
integer, intent(in), DIMENSION(land_pts, ntiles) :: tile_index
real, intent(in), DIMENSION(land_pts) :: bexp
real, intent(in), DIMENSION(land_pts) :: hcon
real, intent(in), DIMENSION(land_pts) :: satcon
real, intent(in), DIMENSION(land_pts) :: sathh
real, intent(in), DIMENSION(land_pts) :: smvcst
real, intent(in), DIMENSION(land_pts) :: smvcwt
real, intent(in), DIMENSION(land_pts) :: smvccl
real, intent(in), DIMENSION(land_pts) :: albsoil
real, intent(inout), DIMENSION(land_pts, ntiles) :: snow_tile
real, intent(in), DIMENSION(land_pts, ntiles) :: snow_rho1l
real, intent(in), DIMENSION(land_pts, ntiles) :: snage_tile
integer, intent(in), DIMENSION(land_pts, ntiles) :: isnow_flg3l
real, intent(in), DIMENSION(land_pts, ntiles,3) :: snow_rho3l
real, intent(inout), DIMENSION(land_pts, ntiles,3) :: snow_cond
real, intent(in), DIMENSION(land_pts, ntiles,3) :: snow_depth3l
real, intent(in), DIMENSION(land_pts, ntiles,3) :: snow_tmp3l
real, intent(in), DIMENSION(land_pts, ntiles,3) :: snow_mass3l
real, intent(inout), DIMENSION(row_length,rows) :: sw_down
real, intent(in), DIMENSION(row_length,rows) :: lw_down
real, intent(inout), DIMENSION(row_length,rows) :: cos_zenith_angle
real, intent(in), DIMENSION(row_length, rows, 4) :: surf_down_sw
real, intent(in), DIMENSION(row_length,rows) :: ls_rain
real, intent(in), DIMENSION(row_length,rows) :: ls_snow
real, intent(in), DIMENSION(row_length,rows) :: tl_1
real, intent(in), DIMENSION(row_length,rows) :: qw_1
real, intent(in), DIMENSION(row_length,rows) :: vshr_land
real, intent(in), DIMENSION(row_length,rows) :: pstar
real, intent(in), DIMENSION(row_length,rows) :: z1_tq
real, intent(in), DIMENSION(row_length,rows) :: z1_uv
real, intent(in) :: rho_water
logical, intent(inout), DIMENSION(land_pts, ntiles) :: L_tile_pts
real, intent(in), DIMENSION(land_pts, ntiles) :: canopy_tile
real, intent(in), DIMENSION(land_pts) :: fland
real, intent(in) :: co2_mmr
real, intent(in) :: CO2_3D(CO2_DIM_LEN,CO2_DIM_ROW)
integer, intent(in) :: CO2_DIM_LEN
integer, intent(in) :: CO2_DIM_ROW
logical, intent(in) :: L_CO2_INTERACTIVE
real, intent(in), DIMENSION(land_pts, ntiles, sm_levels) :: sthu_tile
real, intent(in), DIMENSION(land_pts, ntiles, sm_levels) :: smcl_tile
real, intent(in), DIMENSION(land_pts, ntiles, sm_levels) :: sthf_tile
real, intent(in), DIMENSION(land_pts, sm_levels) :: sthu
real, intent(in), DIMENSION(land_pts, ntiles, sm_levels) :: tsoil_tile
real, intent(in), DIMENSION(land_pts, npft) :: canht_ft
real, intent(in), DIMENSION(land_pts, npft) :: lai_ft
real, intent(in), DIMENSION(row_length,rows) :: sin_theta_latitude
real, intent(in), DIMENSION(sm_levels) :: dzsoil
real, intent(inout), DIMENSION(land_pts,ntiles,10) :: CPOOL_TILE
real, intent(inout), DIMENSION(land_pts,ntiles,10) :: NPOOL_TILE
real, intent(inout), DIMENSION(land_pts,ntiles,12) :: PPOOL_TILE
real, intent(inout), DIMENSION(land_pts) :: SOIL_ORDER
real, intent(inout), DIMENSION(land_pts) :: NIDEP
real, intent(inout), DIMENSION(land_pts) :: NIFIX
real, intent(inout), DIMENSION(land_pts) :: PWEA
real, intent(inout), DIMENSION(land_pts) :: PDUST
real, intent(inout), DIMENSION(land_pts,ntiles) :: GLAI
real, intent(inout), DIMENSION(land_pts,ntiles) :: PHENPHASE
real, intent(inout), DIMENSION(land_pts,ntiles,3) :: WOOD_HVEST_C
real, intent(inout), DIMENSION(land_pts,ntiles,3) :: WOOD_HVEST_N
real, intent(inout), DIMENSION(land_pts,ntiles,3) :: WOOD_HVEST_P
real, intent(inout), DIMENSION(land_pts,ntiles) :: WOOD_FLUX_C
real, intent(inout), DIMENSION(land_pts,ntiles) :: WOOD_FLUX_N
real, intent(inout), DIMENSION(land_pts,ntiles) :: WOOD_FLUX_P
real, intent(inout), DIMENSION(land_pts,ntiles,3) :: WRESP_C
real, intent(inout), DIMENSION(land_pts,ntiles,3) :: WRESP_N
real, intent(inout), DIMENSION(land_pts,ntiles,3) :: WRESP_P
real, intent(inout), DIMENSION(land_pts,ntiles) :: THINNING
real, intent(inout), DIMENSION(land_pts,ntiles) :: PREV_YR_SFRAC
real, intent(inout), DIMENSION(land_pts,ntiles) :: NPP_FT_ACC
real, intent(inout), DIMENSION(land_pts,ntiles) :: RESP_W_FT_ACC
real, intent(inout), DIMENSION(land_pts,ntiles) :: RESP_S_ACC
integer, intent(in) :: iday
Calls
Called by
Contents
None
Call graph
interface_um_data calls alloc_cable_types, init_bgc_vars, initialize_canopy, cable_soil_params, initialize_soilsnow, init_sumflux_zero, init_casacnp, alloc_um_interface_types, initialize_veg, cable_pft_params, initialize_soil, initialize_roughness, initialize_radiation, init_respiration, casa_ndep_pk
alloc_cable_types calls alloc_cbm_var, alloc_soil_snow_type, allocate_soil_parameter_type, alloc_canopy_type, allocate_veg_parameter_type
initialize_soilsnow calls um2cable_lp
init_casacnp calls alloc_casavariable, casa_readpoint_pk, casa_readphen, alloc_phenvariable, casa_readbiome, casa_init_pk
initialize_veg calls init_veg_pars_fr_vegin, limit_hgt_lai
initialize_soil calls um2cable_lp
initialize_roughness calls um2cable_rr
initialize_radiation calls um2cable_rr, update_kblum_radiation, um2cable_met_rad
casa_ndep_pk calls um2cable_lp
alloc_cbm_var calls alloc_soil_snow_type, alloc_met_type, alloc_veg_parameter_type, alloc_canopy_type, alloc_balances_type, alloc_soil_parameter_type, alloc_radiation_type, alloc_roughness_type, alloc_air_type, alloc_sum_flux_type, alloc_climate_type
casa_readpoint_pk calls um2cable_lp, um2cable_rr, um2cable_ilp
init_veg_pars_fr_vegin calls init_veg_from_vegin
casa_init_pk calls casa_reinit_pk, pack_cnppool
um2cable_met_rad calls um2cable_rr
casa_reinit_pk calls pack_cnppool, newplant, newlitter_thin, newsoil, casa_feedback, newlitter
cable_explicit_driver calls interface_um_data