landuse_deallocate_mp – CABLE
landuse_deallocate_mp Subroutine
24 statements
Source File
public subroutine landuse_deallocate_mp(mpx, ms, msn, nrb, mplant, mlitter, msoil, mwood, lucmp)
Arguments
Type Intent Optional Attributes Name
integer :: mpx
integer :: ms
integer :: msn
integer :: nrb
integer :: mplant
integer :: mlitter
integer :: msoil
integer :: mwood
type(landuse_mp), intent(inout) :: lucmp
Called by
Contents
None
Call graph
landuse_driver calls landuse_deallocate_mp
cable_offline_driver calls landuse_deallocate_mp, landuse_driver
mpidrv_master calls landuse_deallocate_mp, landuse_driver
mpi_driver calls mpidrv_master