landuse_driver – CABLE
landuse_driver Subroutine
188 statements
Source File
subroutine landuse_driver(mlon, mlat, landmask, arealand, ssnow, soil, veg, bal, canopy, phen, casapool, casabal, casamet, casabiome, casaflux, bgc, rad, cstart, cend, nap, lucmp)
Uses
casadimension
phenvariable
cable_IO_vars_module
landuse_variable
casavariable
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer :: mlon
integer :: mlat
integer, dimension(mlon,mlat) :: landmask
real(kind=r_2), dimension(mland) :: arealand
type(soil_snow_type) :: ssnow
type(soil_parameter_type) :: soil
type(veg_parameter_type) :: veg
type(balances_type) :: bal
type(canopy_type) :: canopy
type(phen_variable) :: phen
type(casa_pool) :: casapool
type(casa_balance) :: casabal
type(casa_met) :: casamet
type(casa_biome) :: casabiome
type(casa_flux) :: casaflux
type(bgc_pool_type) :: bgc
type(radiation_type) :: rad
integer, dimension(mland) :: cstart
integer, dimension(mland) :: cend
integer, dimension(mland) :: nap
type(landuse_mp) :: lucmp
Calls
Called by
Contents
None
Call graph
landuse_driver calls landuse_deallocate_mp, landuse_update_mland, landuse_land2mpx, landuse_checks, landuse_allocate_mland, landuse_allocate_mp, landuse_mp2land, landuse_transitx, landuse_deallocate_mland
landuse_checks calls 20
landuse_transitx calls landuse_redistribution
mpidrv_master calls landuse_driver
cable_offline_driver calls landuse_driver
mpi_driver calls mpidrv_master