landuse_getxluh2 – CABLE
landuse_getxluh2 Subroutine
43 statements
Source File
subroutine landuse_getxluh2(mlat, mlon, landmask, fxluh2cable, luc_xluh2cable)
Uses
landuse_constant
cable_def_types_mod
netcdf
Arguments
Type Intent Optional Attributes Name
integer :: mlat
integer :: mlon
integer, dimension(mlon,mlat) :: landmask
character(len=500) :: fxluh2cable
real(kind=r_2), dimension(mland,mvmax,mstate) :: luc_xluh2cable
Calls
Called by
Contents
None
Call graph
landuse_getxluh2 calls nf90_open, nf90_get_var, nf90_close, nf90_inq_varid
landuse_data calls landuse_getxluh2
mpidrv_master calls landuse_data
cable_offline_driver calls landuse_data
mpi_driver calls mpidrv_master