OPEN_CRU_MET – CABLE
OPEN_CRU_MET Subroutine
58 statements
Source File
public subroutine OPEN_CRU_MET(CRU)
Uses
cable_IO_vars_module
$ IF (TRIM(CRU%Run) .EQ. 'S0_TRENDY' .OR. (TRIM(CRU%Run) .EQ. 'S1_TRENDY')) THEN $ MetYear = 1901 + MOD(CRU%CYEAR-RunStartYear,30) $ ELSE IF (TRIM(CRU%Run) .EQ. 'S2_TRENDY') THEN $ MetYear = CRU%CYEAR $ ENDIF
Arguments
Type Intent Optional Attributes Name
type(CRU_TYPE), intent(inout) :: CRU
Calls
Called by
Contents
None
Call graph
open_cru_met calls cru_get_filename, handle_err, nf90_open, nf90_inq_varid
handle_err calls nf90_strerror
cru_get_subdiurnal_met calls open_cru_met
mpidrv_master calls cru_get_subdiurnal_met
cable_offline_driver calls cru_get_subdiurnal_met
mpi_driver calls mpidrv_master