open_iDiag – CABLE
open_iDiag Subroutine
9 statements
Source File
public subroutine open_iDiag(iDiag, infilename, gopenstatus)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: infilename
integer :: gopenstatus
Called by
Contents
None
Call graph
open_file_per_node calls open_idiag
fprint_fland calls open_file_per_node
cable_iprintf2 calls open_file_per_node
cable_iprintf1 calls open_file_per_node
cable_fprintf3 calls open_file_per_node
cable_fprintf2 calls open_file_per_node
cable_lprintf2 calls open_file_per_node
cable_fprintf calls cable_iprintf2, cable_iprintf1, cable_fprintf3, cable_fprintf2, cable_lprintf2