PLUME_MIP_GET_MET – CABLE
PLUME_MIP_GET_MET Subroutine
77 statements
Source File
public subroutine PLUME_MIP_GET_MET(PLUME, MET, CurYear, ktau, kend, islast)
Uses
cable_checks_module
cable_IO_vars_module
CABLE_WEATHERGENERATOR
casa_ncdf_module
cable_def_types_mod
!! this only works with CANBERRA cable_driver, as ktau !!!! !! restarts on Jan 1 !!!!
$write(,) "met", met%precip(1), & $met%precip_sn (is:ie) , & $ met%fld (is:ie), & $ met%fsd (is:ie,1), & $ met%fsd (is:ie,2), & $ met%tk (is:ie) , & $ met%ua (is:ie) , & $ met%coszen (is:ie)
Arguments
Type Intent Optional Attributes Name
type(PLUME_MIP_TYPE) :: PLUME
type(met_type) :: MET
integer, intent(in) :: CurYear
integer, intent(in) :: ktau
integer, intent(in) :: kend
logical, intent(in) :: islast
Calls
Called by
Contents
None
Call graph
plume_mip_get_met calls open_plume_met, nf90_close, get_plume_co2, doysod2ymdhms, handle_err, wgen_init, file_switch, plume_get_daily_met, wgen_daily_constants, wgen_subdiurnal_met
open_plume_met calls handle_err, plume_get_filename, nf90_open, nf90_get_att, leap_day, nf90_inq_varid
get_plume_co2 calls get_unit
doysod2ymdhms calls is_leapyear
handle_err calls nf90_strerror
plume_get_daily_met calls nf90_close, handle_err, plume_get_filename, nf90_get_var, nf90_inquire_dimension, nf90_open, nf90_inq_varid, nf90_inq_dimid
leap_day calls is_leapyear
mpidrv_master calls plume_mip_get_met
cable_offline_driver calls plume_mip_get_met
mpi_driver calls mpidrv_master