put_var_ncr1 – CABLE
put_var_ncr1 Subroutine
13 statements
Source File
public subroutine put_var_ncr1(ncid, var_name, var)
Uses
cable_def_types_mod
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: var_name
real, intent(in), dimension(:) :: var
Calls
Called by
Contents
None
Call graph
put_var_ncr1 calls nf90_inq_varid, nf90_put_var, stderr_nc
stderr_nc calls nf90_strerror
write_casa_dump calls put_var_ncr1
put_var_nc calls put_var_ncr1
mpidrv_master calls write_casa_dump
cable_offline_driver calls write_casa_dump
mpi_driver calls mpidrv_master