put_var_ncr3 – CABLE
put_var_ncr3 Subroutine
14 statements
Source File
public subroutine put_var_ncr3(ncid, var_name, var, n_call, nl)
Uses
cable_def_types_mod
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: var_name
real(kind=r_2), intent(in), dimension(:,:) :: var
integer, intent(in) :: n_call
integer, intent(in) :: nl
Calls
Called by
Contents
None
Call graph
put_var_ncr3 calls nf90_inq_varid, nf90_put_var, stderr_nc
stderr_nc calls nf90_strerror
put_var_nc calls put_var_ncr3