read_cable_progs – CABLE
read_cable_progs Subroutine
76 statements
Source File
public subroutine read_cable_progs()
Uses
ancil_info
missing_data_mod
errormessagelength_mod
string_utils_mod
templating_mod
input_mod
io_constants
logging_mod
model_interface_mod
Arguments
None
Calls
Called by
Contents
None
Call graph
read_cable_progs calls log_info, populate_var, tpl_has_var_name, log_fatal, fill_variables_from_file, to_string, get_var_id, log_warn, tpl_substitute_var
init_cable_progs calls read_cable_progs