report_parameters – CABLE
report_parameters Subroutine
218 statements
Source File
public subroutine report_parameters(logn, soil, veg, bgc, rough, ssnow, canopy, casamet, casapool, casaflux, phen, vegparmnew, verbose)
Uses
cable_soil_params_mod
cable_pft_params_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: logn
type(soil_parameter_type), intent(in) :: soil
type(veg_parameter_type), intent(in) :: veg
type(bgc_pool_type), intent(in) :: bgc
type(roughness_type), intent(in) :: rough
type(soil_snow_type), intent(in) :: ssnow
type(canopy_type), intent(in) :: canopy
type(casa_met), intent(in) :: casamet
type(casa_pool), intent(in) :: casapool
type(casa_flux), intent(in) :: casaflux
type(phen_variable), intent(in) :: phen
logical, intent(in) :: vegparmnew
logical, intent(in) :: verbose
Calls
Called by
Contents
None
Call graph
report_parameters calls cable_pft_params, cable_soil_params
load_parameters calls report_parameters
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master