um2cable_lp – CABLE
um2cable_lp Subroutine
31 statements
Source File
public subroutine um2cable_lp(umvar, defaultin, cablevar, soiltype, skip)
Uses
cable_def_types_mod
cable_um_tech_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in), DIMENSION(um1%land_pts) :: umvar
real, intent(in), DIMENSION(mstype) :: defaultin
real, intent(inout), DIMENSION(mp) :: cablevar
integer, intent(inout), DIMENSION(mp) :: soiltype
logical, optional :: skip
Called by
Contents
None
Call graph
cable_rad_driver calls um2cable_lp
casa_readpoint_pk calls um2cable_lp
initialize_soilsnow calls um2cable_lp
casa_ndep_pk calls um2cable_lp
initialize_soil calls um2cable_lp
init_casacnp calls casa_readpoint_pk
interface_um_data calls initialize_soilsnow, casa_ndep_pk, initialize_soil, init_casacnp
cable_explicit_driver calls interface_um_data