um2cable_rr – CABLE
um2cable_rr Subroutine
18 statements
Source File
public subroutine um2cable_rr(umvar, cablevar)
Uses
cable_def_types_mod
cable_um_tech_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in), DIMENSION(um1%row_length, um1%rows) :: umvar
real, intent(inout), DIMENSION(mp) :: cablevar
Called by
Contents
None
Call graph
casa_readpoint_pk calls um2cable_rr
initialize_roughness calls um2cable_rr
initialize_radiation calls um2cable_rr, um2cable_met_rad
cable_implicit_driver calls um2cable_rr
um2cable_met_rad calls um2cable_rr
init_casacnp calls casa_readpoint_pk
cable_rad_driver calls um2cable_met_rad
interface_um_data calls initialize_roughness, initialize_radiation, init_casacnp
cable_explicit_driver calls interface_um_data