um2cable_ilp – CABLE
um2cable_ilp Subroutine
33 statements
Source File
public subroutine um2cable_ilp(umvar, defaultin, cablevar, soiltype, skip)
Uses
cable_def_types_mod
cable_um_tech_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in), DIMENSION(um1%land_pts) :: umvar
integer, intent(in), DIMENSION(10) :: defaultin
integer, intent(inout), DIMENSION(mp) :: cablevar
integer, intent(inout), DIMENSION(mp) :: soiltype
logical, optional :: skip
Called by
Contents
None
Call graph
casa_readpoint_pk calls um2cable_ilp
init_casacnp calls casa_readpoint_pk
interface_um_data calls init_casacnp
cable_explicit_driver calls interface_um_data