write_cnp_params – CABLE
write_cnp_params Subroutine
29 statements
Source File
public subroutine write_cnp_params(veg, casaflux, casamet)
Uses
casaparm
vh !! fluxes shouldn't be weighted by patch frac.
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(in) :: veg
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
Called by
Contents
None
Call graph
load_parameters calls write_cnp_params
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master