WRITE_LANDUSE_CASA_RESTART_NC – CABLE
WRITE_LANDUSE_CASA_RESTART_NC Subroutine
162 statements
Source File
subroutine WRITE_LANDUSE_CASA_RESTART_NC(mpx, lucmp, CASAONLY)
Uses
cable_IO_vars_module
cable_common_module
landuse_variable
netcdf
casa_ncdf_module
casavariable
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: mpx
type(landuse_mp) :: lucmp
logical :: CASAONLY
Calls
Called by
Contents
None
Call graph
write_landuse_casa_restart_nc calls handle_err, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_redef, nf90_put_var, nf90_close, nf90_create, nf90_put_att
handle_err calls nf90_strerror
mpidrv_master calls write_landuse_casa_restart_nc
cable_offline_driver calls write_landuse_casa_restart_nc
mpi_driver calls mpidrv_master