YMDHMS2DOYSOD – CABLE
YMDHMS2DOYSOD Subroutine
16 statements
Source File
public subroutine YMDHMS2DOYSOD(YYYY, MM, DD, HOUR, MINUTE, SECOND, DOY, SOD)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: YYYY
integer, intent(in) :: MM
integer, intent(in) :: DD
integer, intent(in) :: HOUR
integer, intent(in) :: MINUTE
integer, intent(in) :: SECOND
integer, intent(out) :: DOY
integer, intent(out) :: SOD
Calls
Called by
Contents
None
Call graph
ymdhms2doysod calls is_leapyear
open_met_file calls ymdhms2doysod
mpidrv_master calls open_met_file
cable_offline_driver calls open_met_file
mpi_driver calls mpidrv_master