add_address_hvector – POP
add_address_hvector Interface
3 statements
Source File
public interface add_address_hvector
Calls
Called by
Contents
Module Procedures
add_address_hvector_1d_i1 add_address_hvector_1d_l add_address_hvector_1d_r1 add_address_hvector_1d_r2 add_address_hvector_2d_i1 add_address_hvector_2d_l add_address_hvector_2d_r1 add_address_hvector_2d_r2 add_address_hvector_3d_i1 add_address_hvector_3d_l add_address_hvector_3d_r1 add_address_hvector_3d_r2
Module Procedures
private subroutine add_address_hvector_1d_i1(var, off, cnt, stride, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer, intent(in) :: stride
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_hvector_1d_l(var, off, cnt, stride, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
logical, intent(in), dimension(:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer, intent(in) :: stride
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_hvector_1d_r1(var, off, cnt, stride, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer, intent(in) :: stride
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_hvector_1d_r2(var, off, cnt, stride, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), dimension(:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer, intent(in) :: stride
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_hvector_2d_i1(var, off, cnt, stride, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer, intent(in) :: stride
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_hvector_2d_l(var, off, cnt, stride, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
logical, intent(in), dimension(:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer, intent(in) :: stride
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_hvector_2d_r1(var, off, cnt, stride, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer, intent(in) :: stride
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_hvector_2d_r2(var, off, cnt, stride, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), dimension(:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer, intent(in) :: stride
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_hvector_3d_i1(var, off, cnt, stride, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:,:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer, intent(in) :: stride
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_hvector_3d_l(var, off, cnt, stride, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
logical, intent(in), dimension(:,:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer, intent(in) :: stride
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_hvector_3d_r1(var, off, cnt, stride, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(:,:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer, intent(in) :: stride
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_hvector_3d_r2(var, off, cnt, stride, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), dimension(:,:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer, intent(in) :: stride
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
Call graph
add_address_hvector calls add_address_hvector_3d_l, add_address_hvector_3d_r2, add_address_hvector_1d_r2, add_address_hvector_2d_i1, add_address_hvector_1d_i1, add_address_hvector_1d_l, add_address_hvector_1d_r1, add_address_hvector_2d_l, add_address_hvector_2d_r1, add_address_hvector_2d_r2, add_address_hvector_3d_i1, add_address_hvector_3d_r1
add_address_hvector_3d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_r2 calls mpi_get_address
add_address_hvector_2d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_1d_i1 calls mpi_get_address
add_address_hvector_1d_l calls mpi_get_address
add_address_hvector_1d_r1 calls mpi_get_address
add_address_hvector_2d_l calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_2d_r2 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_i1 calls mpi_get_address, mpi_type_create_hvector
add_address_hvector_3d_r1 calls mpi_get_address, mpi_type_create_hvector
master_casa_types calls add_address_hvector
master_restart_types calls add_address_hvector
master_cable_params calls add_address_hvector
master_c13o2_flux_params calls add_address_hvector
master_casa_params calls add_address_hvector
master_c13o2_pool_params calls add_address_hvector
master_climate_types calls add_address_hvector
master_c13o2_luc_params calls add_address_hvector
master_intypes calls add_address_hvector
master_outtypes calls add_address_hvector
master_c13o2_flux_types calls add_address_hvector
master_casa_dump_types calls add_address_hvector
master_c13o2_pool_types calls add_address_hvector
master_casa_luc_types calls add_address_hvector
master_c13o2_luc_types calls add_address_hvector
mpidrv_master calls master_casa_types, master_restart_types, master_cable_params, master_c13o2_flux_params, master_casa_params, master_c13o2_pool_params, master_climate_types, master_c13o2_luc_params, master_intypes, master_outtypes, master_c13o2_flux_types, master_casa_dump_types, master_c13o2_pool_types, master_casa_luc_types, master_c13o2_luc_types
mpi_driver calls mpidrv_master