add_address_1block – POP
add_address_1block Interface
3 statements
Source File
public interface add_address_1block
Calls
Called by
Contents
Module Procedures
add_address_1block_1d_i1 add_address_1block_1d_l add_address_1block_1d_r1 add_address_1block_1d_r2 add_address_1block_2d_i1 add_address_1block_2d_l add_address_1block_2d_r1 add_address_1block_2d_r2 add_address_1block_3d_i1 add_address_1block_3d_l add_address_1block_3d_r1 add_address_1block_3d_r2
Module Procedures
private subroutine add_address_1block_1d_i1(var, off, cnt, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_1block_1d_l(var, off, cnt, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
logical, intent(in), dimension(:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_1block_1d_r1(var, off, cnt, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_1block_1d_r2(var, off, cnt, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), dimension(:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_1block_2d_i1(var, off, cnt, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_1block_2d_l(var, off, cnt, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
logical, intent(in), dimension(:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_1block_2d_r1(var, off, cnt, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_1block_2d_r2(var, off, cnt, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), dimension(:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_1block_3d_i1(var, off, cnt, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:,:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_1block_3d_l(var, off, cnt, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
logical, intent(in), dimension(:,:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_1block_3d_r1(var, off, cnt, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(:,:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
private subroutine add_address_1block_3d_r2(var, off, cnt, addr, blen, typ, idx)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), dimension(:,:,:) :: var
integer, intent(in) :: off
integer, intent(in) :: cnt
integer(kind=MPI_Address_kind), intent(inout), dimension(:) :: addr
integer, intent(inout), dimension(:) :: blen
integer, intent(inout), dimension(:) :: typ
integer, intent(inout) :: idx
Call graph
add_address_1block calls add_address_1block_3d_l, add_address_1block_3d_r1, add_address_1block_1d_l, add_address_1block_1d_r2, add_address_1block_2d_i1, add_address_1block_1d_i1, add_address_1block_1d_r1, add_address_1block_2d_l, add_address_1block_2d_r1, add_address_1block_2d_r2, add_address_1block_3d_i1, add_address_1block_3d_r2
add_address_1block_3d_l calls mpi_get_address
add_address_1block_3d_r1 calls mpi_get_address
add_address_1block_1d_l calls mpi_get_address
add_address_1block_1d_r2 calls mpi_get_address
add_address_1block_2d_i1 calls mpi_get_address
add_address_1block_1d_i1 calls mpi_get_address
add_address_1block_1d_r1 calls mpi_get_address
add_address_1block_2d_l calls mpi_get_address
add_address_1block_2d_r1 calls mpi_get_address
add_address_1block_2d_r2 calls mpi_get_address
add_address_1block_3d_i1 calls mpi_get_address
add_address_1block_3d_r2 calls mpi_get_address
worker_intype calls add_address_1block
worker_c13o2_flux_type calls add_address_1block
worker_restart_type calls add_address_1block
worker_casa_type calls add_address_1block
worker_c13o2_luc_type calls add_address_1block
worker_casa_dump_types calls add_address_1block
master_casa_params calls add_address_1block
worker_casa_params calls add_address_1block
worker_c13o2_flux_params calls add_address_1block
worker_cable_params calls add_address_1block
worker_climate_types calls add_address_1block
worker_c13o2_pool_params calls add_address_1block
worker_c13o2_luc_params calls add_address_1block
worker_outtype calls add_address_1block
worker_c13o2_pool_type calls add_address_1block
worker_casa_luc_types calls add_address_1block
mpidrv_worker calls worker_intype, worker_c13o2_flux_type, worker_restart_type, worker_casa_type, worker_c13o2_luc_type, worker_casa_dump_types, worker_casa_params, worker_c13o2_flux_params, worker_cable_params, worker_climate_types, worker_c13o2_pool_params, worker_c13o2_luc_params, worker_outtype, worker_c13o2_pool_type, worker_casa_luc_types
mpidrv_master calls master_casa_params
mpi_driver calls mpidrv_worker, mpidrv_master