alloc_cbm_var – POP
alloc_cbm_var Interface
3 statements
Source File
public interface alloc_cbm_var
Calls
Called by
Contents
Module Procedures
alloc_balances_type alloc_soil_parameter_type alloc_soil_snow_type alloc_veg_parameter_type alloc_canopy_type alloc_radiation_type alloc_roughness_type alloc_air_type alloc_met_type alloc_sum_flux_type alloc_bgc_pool_type alloc_climate_type
Module Procedures
private subroutine alloc_balances_type(bal, mp)
Arguments
Type Intent Optional Attributes Name
type(balances_type), intent(inout) :: bal
integer, intent(in) :: mp
private subroutine alloc_soil_parameter_type(soil, mp)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: soil
integer, intent(in) :: mp
private subroutine alloc_soil_snow_type(ssnow, mp)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
integer, intent(in) :: mp
private subroutine alloc_veg_parameter_type(veg, mp)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
integer, intent(in) :: mp
private subroutine alloc_canopy_type(canopy, mp)
Arguments
Type Intent Optional Attributes Name
type(canopy_type), intent(inout) :: canopy
integer, intent(in) :: mp
private subroutine alloc_radiation_type(rad, mp)
Arguments
Type Intent Optional Attributes Name
type(radiation_type), intent(inout) :: rad
integer, intent(in) :: mp
private subroutine alloc_roughness_type(rough, mp)
Arguments
Type Intent Optional Attributes Name
type(roughness_type), intent(inout) :: rough
integer, intent(in) :: mp
private subroutine alloc_air_type(air, mp)
Arguments
Type Intent Optional Attributes Name
type(air_type), intent(inout) :: air
integer, intent(in) :: mp
private subroutine alloc_met_type(met, mp)
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: met
integer, intent(in) :: mp
private subroutine alloc_sum_flux_type(sum_flux, mp)
Arguments
Type Intent Optional Attributes Name
type(sum_flux_type), intent(inout) :: sum_flux
integer, intent(in) :: mp
private subroutine alloc_bgc_pool_type(bgc, mp)
Arguments
Type Intent Optional Attributes Name
type(bgc_pool_type), intent(inout) :: bgc
integer, intent(in) :: mp
private subroutine alloc_climate_type(climate, mp, ktauday)
Arguments
Type Intent Optional Attributes Name
type(climate_type), intent(inout) :: climate
integer, intent(in) :: mp
integer, intent(in) :: ktauday
Call graph
alloc_cbm_var calls alloc_balances_type, alloc_soil_parameter_type, alloc_veg_parameter_type, alloc_soil_snow_type, alloc_canopy_type, alloc_radiation_type, alloc_roughness_type, alloc_air_type, alloc_met_type, alloc_sum_flux_type, alloc_climate_type, alloc_bgc_pool_type
read_climatefile calls alloc_cbm_var
allocate_cable_vars calls alloc_cbm_var
cable_offline_driver calls alloc_cbm_var, luc_expt_init, load_parameters
mpidrv_master calls alloc_cbm_var, luc_expt_init, load_parameters
worker_climate_types calls alloc_cbm_var
luc_expt_init calls read_climatefile
worker_cable_params calls allocate_cable_vars
mpi_driver calls mpidrv_master, mpidrv_worker
mpidrv_worker calls worker_climate_types, worker_cable_params
load_parameters calls allocate_cable_vars