alloc_casa_var – POP
alloc_casa_var Interface
3 statements
Source File
public interface alloc_casa_var
Calls
Called by
Contents
Module Procedures
alloc_casabiome alloc_casapool alloc_casaflux alloc_casamet alloc_casabal
Module Procedures
private subroutine alloc_casabiome(casabiome)
vh_js !!
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(inout) :: casabiome
private subroutine alloc_casapool(casapool, arraysize)
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(inout) :: casapool
integer, intent(in) :: arraysize
private subroutine alloc_casaflux(casaflux, arraysize)
Arguments
Type Intent Optional Attributes Name
type(casa_flux), intent(inout) :: casaflux
integer, intent(in) :: arraysize
private subroutine alloc_casamet(casamet, arraysize)
Arguments
Type Intent Optional Attributes Name
type(casa_met), intent(inout) :: casamet
integer, intent(in) :: arraysize
private subroutine alloc_casabal(casabal, arraysize)
Arguments
Type Intent Optional Attributes Name
type(casa_balance), intent(inout) :: casabal
integer, intent(in) :: arraysize
Call graph
alloc_casa_var calls alloc_casabiome, alloc_casaflux, alloc_casabal, alloc_casapool, alloc_casamet
load_parameters calls alloc_casa_var
master_spincasacnp calls alloc_casa_var
master_casaonly_luc calls alloc_casa_var
worker_casa_params calls alloc_casa_var
mpidrv_master calls load_parameters, master_spincasacnp, master_casaonly_luc
cable_offline_driver calls load_parameters
mpidrv_worker calls worker_casa_params
mpi_driver calls mpidrv_master, mpidrv_worker