arange – POP
arange Interface
3 statements
Source File
public interface arange
\brief Numbers within a given range. \details Gives array with numbers in a given interval, i.e. \f[ arange(1) = lower \f] \f[ arange(2) = lower+1 \f] ... \f[ arange(n) = upper \f] Default is lower=1. Output array has kind of lower. \param[in] "integer(i4/i8)/real(sp/dp) :: lower" Start of interval if upper is given, Otherwise end of interval and start of interval is 1. \param[in] "integer(i4/i8)/real(sp/dp) :: upper End of interval" \return kind(arr) :: arange(upper-lower+1) — 1D array with values within given interval. \authors Matthias Cuntz \date Jun 2016
Calls
Called by
Contents
Module Procedures
arange_i4 arange_i8 arange_dp arange_sp
Module Procedures
private function arange_i4(lower, upper)
Arguments
Type Intent Optional Attributes Name
integer(kind=i4), intent(in) :: lower
integer(kind=i4), intent(in), optional :: upper
Return Value integer(kind=i4), dimension(:), allocatable
private function arange_i8(lower, upper)
Arguments
Type Intent Optional Attributes Name
integer(kind=i8), intent(in) :: lower
integer(kind=i8), intent(in), optional :: upper
Return Value integer(kind=i8), dimension(:), allocatable
private function arange_dp(lower, upper)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: lower
real(kind=dp), intent(in), optional :: upper
Return Value real(kind=dp), dimension(:), allocatable
private function arange_sp(lower, upper)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: lower
real(kind=sp), intent(in), optional :: upper
Return Value real(kind=sp), dimension(:), allocatable
Call graph
arange calls arange_i4, arange_dp, arange_i8, arange_sp
linspace_i4 calls arange
linspace_i8 calls arange
linspace_sp calls arange
linspace_dp calls arange
linspace calls linspace_i4, linspace_i8, linspace_sp, linspace_dp