dealloc_cbm_var – POP
dealloc_cbm_var Interface
3 statements
Source File
public interface dealloc_cbm_var
Calls
Contents
Module Procedures
dealloc_balances_type dealloc_soil_parameter_type dealloc_soil_snow_type dealloc_veg_parameter_type dealloc_canopy_type dealloc_radiation_type dealloc_roughness_type dealloc_air_type dealloc_met_type dealloc_sum_flux_type dealloc_bgc_pool_type
Module Procedures
private subroutine dealloc_balances_type(bal)
Arguments
Type Intent Optional Attributes Name
type(balances_type), intent(inout) :: bal
private subroutine dealloc_soil_parameter_type(soil)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: soil
private subroutine dealloc_soil_snow_type(ssnow)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
private subroutine dealloc_veg_parameter_type(veg)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
private subroutine dealloc_canopy_type(canopy)
vh_js !! litter resistances to heat and vapour transfer
Arguments
Type Intent Optional Attributes Name
type(canopy_type), intent(inout) :: canopy
private subroutine dealloc_radiation_type(rad)
Arguments
Type Intent Optional Attributes Name
type(radiation_type), intent(inout) :: rad
private subroutine dealloc_roughness_type(rough)
Arguments
Type Intent Optional Attributes Name
type(roughness_type), intent(inout) :: rough
private subroutine dealloc_air_type(air)
Arguments
Type Intent Optional Attributes Name
type(air_type), intent(inout) :: air
private subroutine dealloc_met_type(met)
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: met
private subroutine dealloc_sum_flux_type(sum_flux)
Arguments
Type Intent Optional Attributes Name
type(sum_flux_type), intent(inout) :: sum_flux
private subroutine dealloc_bgc_pool_type(bgc)
Arguments
Type Intent Optional Attributes Name
type(bgc_pool_type), intent(inout) :: bgc
Call graph
dealloc_cbm_var calls dealloc_balances_type, dealloc_soil_parameter_type, dealloc_soil_snow_type, dealloc_veg_parameter_type, dealloc_canopy_type, dealloc_radiation_type, dealloc_roughness_type, dealloc_air_type, dealloc_met_type, dealloc_sum_flux_type, dealloc_bgc_pool_type