diag – POP
diag Interface
3 statements
Source File
private interface diag
Calls
Called by
Contents
Module Procedures
diag_2d diag_3d
Module Procedures
private function diag_2d(matrix)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), dimension(:,:) :: matrix
Return Value real(kind=dp), dimension(:), allocatable
private function diag_3d(matrix, trans)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), dimension(:,:,:) :: matrix
logical, intent(in), optional :: trans
Return Value real(kind=dp), dimension(:,:), allocatable
Call graph
diag calls diag_2d, diag_3d
diag_2d calls mpi_abort
diag_3d calls mpi_abort
isotope_pool_model_1d calls diag
isotope_pool_model_2d calls diag
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
c13o2_update_pools calls isotope_pool_model
c13o2_update_luc calls isotope_pool_model
worker_spincasacnp calls c13o2_update_pools
worker_casaonly_luc calls c13o2_update_pools
spincasacnp calls c13o2_update_pools
casaonly_luc calls c13o2_update_pools, c13o2_update_luc
bgcdriver calls c13o2_update_pools
master_casaonly_luc calls c13o2_update_luc
cable_offline_driver calls c13o2_update_luc, spincasacnp, casaonly_luc, bgcdriver
mpidrv_master calls c13o2_update_luc, master_casaonly_luc
mpidrv_worker calls worker_spincasacnp, worker_casaonly_luc, bgcdriver
mpi_driver calls mpidrv_master, mpidrv_worker