eq – POP
eq Interface
3 statements
Source File
public interface eq
Calls
Called by
Contents
Module Procedures
equal_sp equal_dp
Module Procedures
private pure elemental function equal_sp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: a
real(kind=sp), intent(in) :: b
Return Value logical
private pure elemental function equal_dp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a
real(kind=dp), intent(in) :: b
Return Value logical
Call graph
eq calls equal_sp, equal_dp
lmpar calls eq, qrsolv
isin_sp calls eq
gser calls eq
isosub calls eq
cable_phenology_clim calls eq
mass_balance calls eq
isotope_pool_model_1d calls eq
dogleg calls eq
fdjac2 calls eq
hybrd calls eq, dogleg, fdjac1, r1updt
getfluxes_vp_1d calls eq
fdjac1 calls eq
lucdriver calls eq
r8mat_print_some calls eq
interpolate_biomass_2d calls eq
qrsolv calls eq
define_canopy calls eq, sli_main
open_met_file calls eq
get_met_data calls eq
getfluxes_vp_2d calls eq
isinloc_dp calls eq
isin_dp calls eq
cable_offline_driver calls eq, lucdriver, open_met_file, get_met_data, casaonly_luc, plume_mip_get_met, pop_luc_casa_transfer, cru_get_subdiurnal_met, cable_bios_read_met, bgcdriver, write_output, cbm, c13o2_update_luc, casa_feedback, spincasacnp, popdriver
rtbis_rh0 calls eq
gcf calls eq
casaonly_luc calls eq, pop_luc_casa_transfer, c13o2_update_luc, c13o2_update_pools, popdriver
lmdif calls eq, lmpar, fdjac2
isotope_pool_model_2d calls eq
rtbis calls eq
hybrj calls eq, dogleg, r1updt
plume_mip_get_met calls eq
master_casaonly_luc calls eq, pop_luc_casa_transfer, c13o2_update_luc
pop_luc_casa_transfer calls eq
chkder calls eq
lmder calls eq, lmpar
isinloc_sp calls eq
lmstr calls eq, lmpar
isotope_luc_model_1d calls eq
r1updt calls eq
cru_get_subdiurnal_met calls eq
cable_bios_read_met calls eq
lmder1 calls lmder
isotope_luc_model calls isotope_luc_model_1d
isinloc calls isinloc_dp, isinloc_sp
hybrj1 calls hybrj
lmdif1 calls lmdif
optimise_jv calls rtbis
isin calls isin_sp, isin_dp
igamma calls gser, gcf
bgcdriver calls cable_phenology_clim, c13o2_update_pools
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
write_output calls mass_balance
hybrd1 calls hybrd
getfluxes_vp calls getfluxes_vp_1d, getfluxes_vp_2d
r8mat_print calls r8mat_print_some
getdiagnostics calls interpolate_biomass_2d
cbm calls define_canopy, sli_main
mpidrv_master calls open_met_file, get_met_data, plume_mip_get_met, master_casaonly_luc, pop_luc_casa_transfer, cru_get_subdiurnal_met, lucdriver, cable_bios_read_met, write_output, c13o2_update_luc
lmstr1 calls lmstr
c13o2_update_luc calls isotope_luc_model, isotope_pool_model
adjust_jv_gm calls lmdif1
mpidrv_worker calls bgcdriver, cbm, casa_feedback, worker_casaonly_luc, worker_spincasacnp, popdriver
casa_feedback calls optimise_jv, adjust_jv_gm
hyofs calls igamma
c13o2_update_pools calls isotope_pool_model
get_fluxes_and_derivs calls getfluxes_vp
popstep calls getdiagnostics
mpi_driver calls mpidrv_master, mpidrv_worker
sli_main calls hyofs, solve
spincasacnp calls c13o2_update_pools, popdriver
worker_casaonly_luc calls c13o2_update_pools, popdriver
solve calls hyofs, timestep_loop
iflux_loop calls hyofs, get_fluxes_and_derivs
worker_spincasacnp calls c13o2_update_pools, popdriver
popdriver calls popstep
timestep_loop calls iflux_loop