ge – POP
ge Interface
3 statements
Source File
public interface ge
Calls
Called by
Contents
Module Procedures
greaterequal_sp greaterequal_dp
Module Procedures
private pure elemental function greaterequal_sp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: a
real(kind=sp), intent(in) :: b
Return Value logical
private pure elemental function greaterequal_dp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a
real(kind=dp), intent(in) :: b
Return Value logical
Call graph
ge calls greaterequal_sp, greaterequal_dp
chkder calls ge
lmder calls ge
lmstr calls ge
casa_xrateplant calls ge
lmdif calls ge
cable_phenology_clim calls ge
rtbis calls ge
lmder1 calls lmder
biogeochem calls casa_xrateplant
lmstr1 calls lmstr
bgcdriver calls cable_phenology_clim, biogeochem
lmdif1 calls lmdif
optimise_jv calls rtbis
spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
mpidrv_worker calls bgcdriver, worker_casaonly_luc, worker_spincasacnp, casa_feedback
casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
cable_offline_driver calls bgcdriver, spincasacnp, casaonly_luc, casa_feedback
adjust_jv_gm calls lmdif1
casa_feedback calls optimise_jv, adjust_jv_gm
mpi_driver calls mpidrv_worker