get_var_nc – POP
get_var_nc Interface
3 statements
Source File
public interface get_var_nc
Calls
Called by
Contents
Module Procedures
get_var_ncr2 get_var_ncr3
Module Procedures
public subroutine get_var_ncr2(ncid, var_name, var, n_call)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: var_name
real(kind=r_2), intent(out), dimension(:) :: var
integer, intent(in) :: n_call
public subroutine get_var_ncr3(ncid, var_name, var, n_call, nl)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: var_name
real(kind=r_2), intent(out), dimension(:,:) :: var
integer, intent(in) :: n_call
integer, intent(in) :: nl
Call graph
get_var_nc calls get_var_ncr2, get_var_ncr3
get_var_ncr2 calls nf90_inq_varid, nf90_get_var, stderr_nc
get_var_ncr3 calls nf90_inq_varid, nf90_get_var, stderr_nc
stderr_nc calls nf90_strerror, mpi_abort
read_casa_dump calls get_var_nc
casaonly_luc calls read_casa_dump
spincasacnp calls read_casa_dump
cable_offline_driver calls read_casa_dump, casaonly_luc, spincasacnp
master_spincasacnp calls read_casa_dump
master_casaonly_luc calls read_casa_dump
mpidrv_master calls master_spincasacnp, master_casaonly_luc
mpi_driver calls mpidrv_master