getfluxes_vp – POP
getfluxes_vp Interface
4 statements
Source File
public interface getfluxes_vp
Calls
Called by
Contents
Module Procedures
getfluxes_vp_1d getfluxes_vp_2d
Module Procedures
private subroutine getfluxes_vp_1d(n, dx, vtop, vbot, parin, var, hint, phimin, q, qya, qyb, qTa, qTb, ql, qlya, qlyb, qv, qvT, qvh, qvya, qvyb, iflux, init, getq0, getqn, Tsoil, T0, nsat, nsatlast)
Arguments
Type Intent Optional Attributes Name
integer(kind=i_d), intent(in) :: n
real(kind=r_2), intent(in), DIMENSION(1:n) :: dx
type(vars), intent(in) :: vtop
type(vars), intent(in) :: vbot
type(params), intent(in), DIMENSION(1:n) :: parin
type(vars), intent(inout), DIMENSION(1:n) :: var
real(kind=r_2), intent(inout), DIMENSION(1:n) :: hint
real(kind=r_2), intent(inout), DIMENSION(1:n) :: phimin
real(kind=r_2), intent(inout), DIMENSION(0:n) :: q
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qya
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qyb
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qTa
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qTb
real(kind=r_2), intent(inout), DIMENSION(0:n) :: ql
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qlya
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qlyb
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qv
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qvT
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qvh
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qvya
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qvyb
integer(kind=i_d), intent(in) :: iflux
logical, intent(in) :: init
logical, intent(in) :: getq0
logical, intent(in) :: getqn
real(kind=r_2), intent(in), DIMENSION(1:n) :: Tsoil
real(kind=r_2), intent(in) :: T0
integer(kind=i_d), intent(in) :: nsat
integer(kind=i_d), intent(in) :: nsatlast
private subroutine getfluxes_vp_2d(dx, vtop, vbot, parin, var, hint, phimin, i_q, i_qya, i_qyb, i_qTa, i_qTb, i_ql, i_qlya, i_qlyb, i_qv, i_qvT, i_qvh, i_qvya, i_qvyb, iflux, init, getq0, getqn, Tsoil, T0, nsat, nsatlast)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(:,:) :: dx
type(vars), intent(in), DIMENSION(:) :: vtop
type(vars), intent(in), DIMENSION(:) :: vbot
type(params), intent(in), DIMENSION(:,:) :: parin
type(vars), intent(in), DIMENSION(:,:) :: var
real(kind=r_2), intent(inout), DIMENSION(:,:) :: hint
real(kind=r_2), intent(inout), DIMENSION(:,:) :: phimin
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_q
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qya
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qyb
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qTa
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qTb
real(kind=r_2), intent(out), DIMENSION(:,:) :: i_ql
real(kind=r_2), intent(out), DIMENSION(:,:) :: i_qlya
real(kind=r_2), intent(out), DIMENSION(:,:) :: i_qlyb
real(kind=r_2), intent(out), DIMENSION(:,:) :: i_qv
real(kind=r_2), intent(out), DIMENSION(:,:) :: i_qvT
real(kind=r_2), intent(out), DIMENSION(:,:) :: i_qvh
real(kind=r_2), intent(out), DIMENSION(:,:) :: i_qvya
real(kind=r_2), intent(out), DIMENSION(:,:) :: i_qvyb
integer(kind=i_d), intent(in), DIMENSION(:) :: iflux
logical, intent(in), DIMENSION(:) :: init
logical, intent(in), DIMENSION(:) :: getq0
logical, intent(in), DIMENSION(:) :: getqn
real(kind=r_2), intent(in), DIMENSION(:,:) :: Tsoil
real(kind=r_2), intent(in), DIMENSION(:) :: T0
integer(kind=i_d), intent(in), DIMENSION(:) :: nsat
integer(kind=i_d), intent(in), DIMENSION(:) :: nsatlast
Call graph
getfluxes_vp calls getfluxes_vp_1d, getfluxes_vp_2d
getfluxes_vp_1d calls zerovars, flux, eq, hyofh
getfluxes_vp_2d calls zerovars, flux, eq, hyofh
flux calls weight
eq calls equal_dp, equal_sp
weight calls hyofh
get_fluxes_and_derivs calls getfluxes_vp
iflux_loop calls get_fluxes_and_derivs
timestep_loop calls iflux_loop
solve calls timestep_loop
sli_main calls solve
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker