getheatfluxes – POP
getheatfluxes Interface
4 statements
Source File
public interface getheatfluxes
Calls
Called by
Contents
Module Procedures
getheatfluxes_1d getheatfluxes_2d
Module Procedures
private subroutine getheatfluxes_1d(n, dx, qh, qhya, qhyb, qhTa, qhTb, var, T, q, qya, qyb, qTa, qTb, qadv, qadvya, qadvyb, qadvTa, qadvTb, advection)
Arguments
Type Intent Optional Attributes Name
integer(kind=i_d), intent(in) :: n
real(kind=r_2), intent(in), DIMENSION(1:n) :: dx
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qh
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qhya
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qhyb
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qhTa
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qhTb
type(vars), intent(in), DIMENSION(1:n) :: var
real(kind=r_2), intent(in), DIMENSION(1:n) :: T
real(kind=r_2), intent(inout), DIMENSION(0:n) :: q
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qya
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qyb
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qTa
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qTb
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qadv
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qadvya
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qadvyb
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qadvTa
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qadvTb
integer(kind=i_d), intent(in) :: advection
private subroutine getheatfluxes_2d(dx, i_qh, i_qhya, i_qhyb, i_qhTa, i_qhTb, var, T, i_q, i_qya, i_qyb, i_qTa, i_qTb, i_qadv, i_qadvya, i_qadvyb, i_qadvTa, i_qadvTb, advection)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(:,:) :: dx
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qh
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qhya
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qhyb
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qhTa
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qhTb
type(vars), intent(in), DIMENSION(:,:) :: var
real(kind=r_2), intent(in), DIMENSION(:,:) :: T
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_q
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qya
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qyb
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qTa
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qTb
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qadv
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qadvya
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qadvyb
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qadvTa
real(kind=r_2), intent(inout), DIMENSION(:,:) :: i_qadvTb
integer(kind=i_d), intent(in) :: advection
Call graph
getheatfluxes calls getheatfluxes_1d, getheatfluxes_2d
get_fluxes_and_derivs calls getheatfluxes
iflux_loop calls get_fluxes_and_derivs
timestep_loop calls iflux_loop
solve calls timestep_loop
sli_main calls solve
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker