is_normal – POP
is_normal Interface
3 statements
Source File
public interface is_normal
Calls
Contents
Module Procedures
is_normal_sp is_normal_dp
Module Procedures
private pure elemental function is_normal_sp(a)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: a
Return Value logical
private pure elemental function is_normal_dp(a)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a
Return Value logical
Call graph
is_normal calls is_normal_sp, is_normal_dp
is_normal_sp calls is_finite
is_normal_dp calls is_finite
is_finite calls is_finite_sp, is_finite_dp
is_finite_sp calls is_nan
is_finite_dp calls is_nan
is_nan calls is_nan_sp, is_nan_dp