isinloc – POP
isinloc Interface
3 statements
Source File
public interface isinloc
\brief First index location of scalar in array. \details Returns the first index location in an array where an array element matches a given scalar. Returns 0 if the element is not present in the array.\n Leading and trailing blank characters are removed from strings. \param[in] "integer(i4/i8)/real(sp/dp)/character(len=) :: scalar" Single scalar value \param[in] "integer(i4/i8)/real(sp/dp)/character(len=) :: array(:)" Input vector \param[in] "logical :: mask(:)" If present, only those locations in array corresponding to the true values in mask are searched for the scalar value. \param[in] "logical :: ignore_case" If .true., ignore case in comparison of strings; if .false., comparison case sensitive (default: .true.) \return integer(i4) :: isinloc — First index location of scalar in array, 0 otherwise \authors Matthias Cuntz \date Jan 2017
Calls
Contents
Module Procedures
isinloc_i4 isinloc_i8 isinloc_sp isinloc_dp isinloc_char
Module Procedures
private function isinloc_i4(sca, arr, mask)
Arguments
Type Intent Optional Attributes Name
integer(kind=i4), intent(in) :: sca
integer(kind=i4), intent(in), dimension(:) :: arr
logical, intent(in), optional, dimension(:) :: mask
Return Value integer(kind=i4)
private function isinloc_i8(sca, arr, mask)
Arguments
Type Intent Optional Attributes Name
integer(kind=i8), intent(in) :: sca
integer(kind=i8), intent(in), dimension(:) :: arr
logical, intent(in), optional, dimension(:) :: mask
Return Value integer(kind=i8)
private function isinloc_sp(sca, arr, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: sca
real(kind=sp), intent(in), dimension(:) :: arr
logical, intent(in), optional, dimension(:) :: mask
Return Value integer(kind=i4)
private function isinloc_dp(sca, arr, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: sca
real(kind=dp), intent(in), dimension(:) :: arr
logical, intent(in), optional, dimension(:) :: mask
Return Value integer(kind=i4)
private function isinloc_char(sca, arr, mask, ignore_case)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: sca
character(len=*), intent(in), dimension(:) :: arr
logical, intent(in), optional, dimension(:) :: mask
logical, intent(in), optional :: ignore_case
Return Value integer(kind=i4)
Call graph
isinloc calls isinloc_i4, isinloc_dp, isinloc_char, isinloc_i8, isinloc_sp
isinloc_dp calls eq
isinloc_char calls itoupper
isinloc_sp calls eq
eq calls equal_sp, equal_dp