isotope_luc_model – POP
isotope_luc_model Interface
3 statements
Source File
public interface isotope_luc_model
\brief Generic isotopic land-use change model \details Next explicit time step of the isotopic composition of a generic land-use change model, given all fluxes, area changes between land use classes, sources and sinks. The generic isotopic land-use model does not include any fractionations, yet. The land-use change model for land-use class i is: \n d(A(i)C(i)) = -C(i)sum(dA(i,:)) + sum(dA(:,i)C(:)) + S(i) - T(i) \n where \n C [kg/m^2] are the carbon concentrations in the land-use classes, \n A [m^2] are the areas of the land-use classes, \n dA [m^2] are the area changes between land-use classes for the time step (A>0, A(i,i)=0), \n S [kg] are sources other than contributions from other land use classes, and \n T [kg] are sinks other than contributions to other land use classes. \n S and T could be source and sinks between carbon pools, for example. Note: \n dA is change per time step in [m^2], NOT per second.\n S and T are sources and sinks in total mass in [kg], NOT per area. The land-use model is then solved from time step t to t+dt \n A(i,t+dt)C(i,t+dt) - A(i,t)C(i,t) = -C(i,t)sum(dA(i,:)) + sum(dA(:,i)C(:,t)) + S(i,dt) - T(i,dt) \n C(i,t+dt) = (C(i,t)(A(i,t)-sum(dA(i,:))) + sum(dA(:,i)C(:,t)) + S(i,dt) - T(i,dt)) / A(i,t+dt) \n with S(i,dt), T(i,dt) the total sources and sinks during the time step. The isotopic land-use model is then: A(i,t+dt)C'(i,t+dt) - A(i,t)C'(i,t) = -C'(i,t)sum(dA(i,:)) + sum(dA(:,i)C'(:,t)) + Rs(i,dt)S(i,dt) - R(i,t)T(i,dt) \n C'(i,t+dt) = (C'(i,t)(A(i,t)-sum(dA(i,:))) + sum(dA(:,i)C'(:,t)) + Rs(i,dt)S(i,dt) - R(i,t)T(i,dt)) / A(i,t+dt) \n with C' the isotope carbon concentrations, R the carbon isotope ratio C'/C, and Rs is the carbon isotope ratio of the source S during the time step. This can also be written with carbon concentrations C at time t as \n R(i,t) = C'(i,t) / C(i,t) \n A(i,t+dt)C'(i,t+dt) - A(i,t)R(i,t)C(i,t) = -R(i,t)C(i,t)sum(dA(i,:)) + sum(dA(:,i)R(:,t)C(:,t)) + Rs(i,dt)S(i,dt) - R(i,t)T(i,dt) \n C'(i,t+dt) = (R(i,t)C(i,t)(A(i,t)-sum(dA(i,:))) + sum(dA(:,i)R(:,t)C(:,t)) + Rs(i,dt)S(i,dt) - R(i,t)T(i,dt)) / A(i,t+dt) \param[inout] "real(dp) :: Ciso(1:n)" On entry: isotope concentrations in land-use classes at time step t-1 [kg/m^2] On exit: updated isotope concentrations of land-use classes at time step t [kg/m^2] \param[in] "real(dp) :: A(1:n)" Areas of land-use classes at time step t-1 [m^2] \param[in] "real(dp) :: dA(1:n,1:n)" Change from each land-use class to the others during the time step [m^2] \param[in] "real(dp), optional :: C(1:n)" Non-isotope concentrations in land-use classes at time step t-1 [kg/m^2] (default: not used) \param[in] "real(dp), optional :: S(1:n)" Sources other than contributions from other land use classes, for example from other carbon pool [kg/m^2] (default: 0.) \param[in] "real(dp), optional :: Rs(1:n)" Isotope ratio of sources (default: 1.) \param[in] "real(dp), optional :: T(1:n)" Sinks other than contributions from other land use classes, for example to other carbon pool [kg/m^2] (default: 0.) \param[in] "real(dp), optional :: Rt(1:n)" Isotope ratio of sinks (default: isotope ratio of pool and land use class) \param[in] "real(dp), optional :: At(1:n)" Areas of land-use classes at time step t [m^2] (default: calculated from A and dA) \param[inout] "real(dp), optional :: trash(1:n)" Container to store possible inconsistencies, might be numeric, between non-isotope and isotope model [kg/m^2]. Consistency checks are only performed if trash is given in call. \author Written Matthias Cuntz \date Apr 2019
Calls
Called by
Contents
Module Procedures
isotope_luc_model_1d
Module Procedures
private subroutine isotope_luc_model_1d(Ciso, A, dA, C, S, Rs, T, Rt, At, trash)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout), dimension(:) :: Ciso
real(kind=dp), intent(in), dimension(:) :: A
real(kind=dp), intent(in), dimension(:,:) :: dA
real(kind=dp), intent(in), optional dimension(:) :: C
real(kind=dp), intent(in), optional dimension(:) :: S
real(kind=dp), intent(in), optional dimension(:) :: Rs
real(kind=dp), intent(in), optional dimension(:) :: T
real(kind=dp), intent(in), optional dimension(:) :: Rt
real(kind=dp), intent(in), optional dimension(:) :: At
real(kind=dp), intent(inout), optional dimension(:) :: trash
Call graph
isotope_luc_model calls isotope_luc_model_1d
isotope_luc_model_1d calls mpi_abort, eq
eq calls equal_sp, equal_dp
c13o2_update_luc calls isotope_luc_model
casaonly_luc calls c13o2_update_luc
master_casaonly_luc calls c13o2_update_luc
cable_offline_driver calls c13o2_update_luc, casaonly_luc
mpidrv_master calls c13o2_update_luc, master_casaonly_luc
mpi_driver calls mpidrv_master