isotope_pool_model – POP
isotope_pool_model Interface
3 statements
Source File
public interface isotope_pool_model
\brief Generic isotopic pool model \details Next explicit time step of the isotopic composition of a generic pool model, given sink, sources and all the fluxes between all pools, together associated fractionation factors. The pool model for pool i is: \n dC(i)/dt = sum(F(:,i)) - sum(F(i,:)) + S(i) - T(i) \n where C are the pools, F the fluxes between pools (F>0, F(i,i)=0), S a pool-independent source term, and T a sink term, which can be pool-independent or pool-dependent, i.e. T(i) = beta(i)C(i) The isotope model for pool i is then:\n dC'(i)/dt = sum(alpha(:,i)R(:)F(:,i)) - R(i)sum(alpha(i,:)F(i,:)) + Rs(i)S(i) - alpha(i,i)Rt(i)T(i) \n with C' the isotope pools. R are the isotope ratios of the pools at time t-dt, and alpha are possible fractionation factors. If Rt is not given, it is taken as the isotopic composition of the pool R(i). All pools can have either dimension (n) or (n,m) with n pools and m land points (or fractions). Fluxes and fractionation factors have dimensions (n,n) or (n,n,m). \param[in] "real(dp) :: dt" Time step \param[inout] "real(dp) :: Ciso(1:n[,1:m])" Isotope concentrations in pools \param[in] "real(dp) :: C(1:n[,1:m])" Non-isotope concentrations in pools at time step t-1 \param[in] "real(dp) :: F(1:n,1:n[,1:m])" Non-isotope fluxes between pools (F(i,i)=0) \n F(i,j) positive flux from pool i to pool j \n Isotope flux is alpha(i,j)R(i)F(i,j) \param[in] "real(dp), optional :: S(1:n[,1:m])" Non-isotope source fluxes to pools (other than between pools) \n Default: 0. \param[in] "real(dp), optional :: Rs(1:n[,1:m])" Isotopic compositions of source fluxes \n Any fractionations during source processes should be included in Rs. \n Default: 1. \param[in] "real(dp), optional :: T(1:n[,1:m])" Non-isotope sinks of pools (other than between pools) \n Isotope flux is alpha(i,i)Rt(i)T(i) or alpha(i,i)R(i)T(i) \n Default: 0. \param[in] "real(dp), optional :: Rt(1:n[,1:m])" Isotopic compositions of sink fluxes. \n If not given, the isotopic composition of the pool R(i) is taken. \n Default: R(i) \param[in] "real(dp), optional :: alpha(1:n,1:n[,1:m])" Isotopic fractionation factors associated with fluxes F between pools (alpha(i,j) i/=j) and of sinks T (other than between pools) (alpha(i,i)) \n Default: 1. \param[in] "real(dp), optional :: beta(1:n[,1:m])" Either T or beta can be given. \n If beta is given then T(i) = beta(i)*C(i). \n T supercedes beta, i.e. T will be taken if beta and T are given. \param[inout] "real(dp), optional :: trash(1:n[,1:m])" Container to store possible inconsistencies, might be numeric, between non-isotope and isotope model. \n Consistency checks are only performed if trash is given in call. \param[inout] "logical, optional :: trans" Assumed order of pools and fluxes in 2D case \n If .true., input order is [m,n] for pools and [m,n,n] for fluxes \n If .false., input order is [n,m] for pools and [n,n,m] for fluxes \n Default: .false. \author Written Matthias Cuntz \date Apr 2019
Calls
Called by
Contents
Module Procedures
isotope_pool_model_1d isotope_pool_model_2d
Module Procedures
private subroutine isotope_pool_model_1d(dt, Ciso, C, F, S, Rs, T, Rt, alpha, beta, trash)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: dt
real(kind=dp), intent(inout), dimension(:) :: Ciso
real(kind=dp), intent(in), dimension(:) :: C
real(kind=dp), intent(in), dimension(:,:) :: F
real(kind=dp), intent(in), optional, dimension(:) :: S
real(kind=dp), intent(in), optional, dimension(:) :: Rs
real(kind=dp), intent(in), optional, dimension(:) :: T
real(kind=dp), intent(in), optional, dimension(:) :: Rt
real(kind=dp), intent(in), optional, dimension(:,:) :: alpha
real(kind=dp), intent(in), optional, dimension(:) :: beta
real(kind=dp), intent(inout), optional, dimension(:) :: trash
private subroutine isotope_pool_model_2d(dt, Ciso, C, F, S, Rs, T, Rt, alpha, beta, trash, trans)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: dt
real(kind=dp), intent(inout), dimension(:,:) :: Ciso
real(kind=dp), intent(in), dimension(:,:) :: C
real(kind=dp), intent(in), dimension(:,:,:) :: F
real(kind=dp), intent(in), optional, dimension(:,:) :: S
real(kind=dp), intent(in), optional, dimension(:,:) :: Rs
real(kind=dp), intent(in), optional, dimension(:,:) :: T
real(kind=dp), intent(in), optional, dimension(:,:) :: Rt
real(kind=dp), intent(in), optional, dimension(:,:,:) :: alpha
real(kind=dp), intent(in), optional, dimension(:,:) :: beta
real(kind=dp), intent(inout), optional, dimension(:,:) :: trash
logical, intent(in), optional :: trans
Call graph
isotope_pool_model calls isotope_pool_model_1d, isotope_pool_model_2d
isotope_pool_model_1d calls mpi_abort, ne, diag, eq
isotope_pool_model_2d calls mpi_abort, ne, diag, eq
ne calls notequal_sp, notequal_dp
diag calls diag_2d, diag_3d
eq calls equal_sp, equal_dp
diag_2d calls mpi_abort
diag_3d calls mpi_abort
c13o2_update_pools calls isotope_pool_model
c13o2_update_luc calls isotope_pool_model
worker_spincasacnp calls c13o2_update_pools
bgcdriver calls c13o2_update_pools
casaonly_luc calls c13o2_update_pools, c13o2_update_luc
spincasacnp calls c13o2_update_pools
worker_casaonly_luc calls c13o2_update_pools
master_casaonly_luc calls c13o2_update_luc
mpidrv_master calls c13o2_update_luc, master_casaonly_luc
cable_offline_driver calls c13o2_update_luc, bgcdriver, casaonly_luc, spincasacnp
mpidrv_worker calls worker_spincasacnp, bgcdriver, worker_casaonly_luc
mpi_driver calls mpidrv_master, mpidrv_worker