le – POP
le Interface
3 statements
Source File
public interface le
Calls
Called by
Contents
Module Procedures
lesserequal_sp lesserequal_dp
Module Procedures
private pure elemental function lesserequal_sp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: a
real(kind=sp), intent(in) :: b
Return Value logical
private pure elemental function lesserequal_dp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a
real(kind=dp), intent(in) :: b
Return Value logical
Call graph
le calls lesserequal_sp, lesserequal_dp
locate_1d_sp calls le
locate_1d_dp calls le
lmder calls le, lmpar, qrfac
dogleg calls le
casa_xrateplant calls le
lmstr calls le, lmpar, qrfac
hybrd calls le, dogleg, qrfac
hybrj calls le, dogleg, qrfac
lmdif calls le, lmpar, qrfac
lmpar calls le
rtbis calls le
qrfac calls le
locate_0d_dp calls le
locate_0d_sp calls le
chkder calls le
enorm2 calls le
locate calls locate_1d_sp, locate_1d_dp, locate_0d_dp, locate_0d_sp
lmder1 calls lmder
hybrd1 calls hybrd
lmstr1 calls lmstr
biogeochem calls casa_xrateplant
hybrj1 calls hybrj
lmdif1 calls lmdif
optimise_jv calls rtbis
worker_spincasacnp calls biogeochem
spincasacnp calls biogeochem
bgcdriver calls biogeochem
worker_casaonly_luc calls biogeochem
casaonly_luc calls biogeochem
adjust_jv_gm calls lmdif1
casa_feedback calls optimise_jv, adjust_jv_gm
mpidrv_worker calls worker_spincasacnp, bgcdriver, worker_casaonly_luc, casa_feedback
cable_offline_driver calls spincasacnp, bgcdriver, casaonly_luc, casa_feedback
mpi_driver calls mpidrv_worker