linspace – POP
linspace Interface
3 statements
Source File
public interface linspace
\brief Evenly spaced numbers in interval. \details Return N evenly spaced numbers over a specified interval [lower,upper]. \f[ linspace(lower,upper,N) = lower + arange(0,N-1)/(N-1) * (upper-lower) \f] Output array has kind of lower. \param[in] "integer(i4/i8)/real(sp/dp) :: lower" Start of interval. \param[in] "integer(i4/i8)/real(sp/dp) :: upper" End of interval. \param[in] "integer(i4) :: nstep" Number of steps. \return kind(lower) :: linspace(N) — 1D array with evenly spaced numbers between lower and upper. \authors Matthias Cuntz \date Jun 2016
Calls
Contents
Module Procedures
linspace_i4 linspace_i8 linspace_dp linspace_sp
Module Procedures
private function linspace_i4(lower, upper, nstep)
Arguments
Type Intent Optional Attributes Name
integer(kind=i4), intent(in) :: lower
integer(kind=i4), intent(in) :: upper
integer(kind=i4), intent(in) :: nstep
Return Value integer(kind=i4),dimension(nstep)
private function linspace_i8(lower, upper, nstep)
Arguments
Type Intent Optional Attributes Name
integer(kind=i8), intent(in) :: lower
integer(kind=i8), intent(in) :: upper
integer(kind=i4), intent(in) :: nstep
Return Value integer(kind=i8),dimension(nstep)
private function linspace_dp(lower, upper, nstep)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: lower
real(kind=dp), intent(in) :: upper
integer(kind=i4), intent(in) :: nstep
Return Value real(kind=dp),dimension(nstep)
private function linspace_sp(lower, upper, nstep)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: lower
real(kind=sp), intent(in) :: upper
integer(kind=i4), intent(in) :: nstep
Return Value real(kind=sp),dimension(nstep)
Call graph
linspace calls linspace_i4, linspace_sp, linspace_dp, linspace_i8
linspace_i4 calls arange
linspace_sp calls arange
linspace_dp calls arange
linspace_i8 calls arange
arange calls arange_i4, arange_sp, arange_dp, arange_i8