locate – POP
locate Interface
3 statements
Source File
public interface locate
\brief Find closest values in a monotonic series, returns the indexes. \details Given an array x(1:n), and given a value y, returns a value j such that y is between x(j) and x(j+1).\n x must be monotonically increasing.\n j=0 or j=N is returned to indicate that x is out of range. \param[in] "real(dp/sp) :: x(:)" Sorted array \param[in] "real(dp/sp) :: y[(:)]" Value(s) of which the closest match in x(:) is wanted \return integer(i4) :: index[(:)] — index(es) of x so that y is between x(index) and x(index+1) \note x must be monotonically increasing.\n \author Matthias Cuntz \date May 2014
Calls
Contents
Module Procedures
locate_0d_dp locate_0d_sp locate_1d_dp locate_1d_sp
Module Procedures
private function locate_0d_dp(x, y)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(:) :: x
real(kind=dp), intent(in) :: y
Return Value integer(kind=i4)
private function locate_0d_sp(x, y)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in), DIMENSION(:) :: x
real(kind=sp), intent(in) :: y
Return Value integer(kind=i4)
private function locate_1d_dp(x, y)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), DIMENSION(:) :: x
real(kind=dp), intent(in), DIMENSION(:) :: y
Return Value integer(kind=i4), DIMENSION(:), allocatable
private function locate_1d_sp(x, y)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in), DIMENSION(:) :: x
real(kind=sp), intent(in), DIMENSION(:) :: y
Return Value integer(kind=i4), DIMENSION(:), allocatable
Call graph
locate calls locate_0d_dp, locate_1d_sp, locate_1d_dp, locate_0d_sp
locate_0d_dp calls le
locate_1d_sp calls le
locate_1d_dp calls le
locate_0d_sp calls le
le calls lesserequal_sp, lesserequal_dp