ne – POP
ne Interface
3 statements
Source File
public interface ne
Calls
Called by
Contents
Module Procedures
notequal_sp notequal_dp
Module Procedures
private pure elemental function notequal_sp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: a
real(kind=sp), intent(in) :: b
Return Value logical
private pure elemental function notequal_dp(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a
real(kind=dp), intent(in) :: b
Return Value logical
Call graph
ne calls notequal_sp, notequal_dp
c13o2_discrimination calls ne
read_soilcolor calls ne
pop_io calls ne
c13o2_print_delta_flux calls ne
lmstr calls ne, qrfac, rwupdt, lmpar
c13o2_print_delta_pools calls ne
enorm2 calls ne
qrfac calls ne
chkder calls ne
qform calls ne
isotope_vap calls ne
rwupdt calls ne
hybrd calls ne, qrfac, qform, dogleg, r1updt
lmdif calls ne, qrfac, lmpar
isotope_pool_model_2d calls ne
isotope_pool_model_1d calls ne
dogleg calls ne
lmder calls ne, qrfac, lmpar
qrsolv calls ne
c13o2_print_delta_luc calls ne
cable_offline_driver calls ne, pop_io, c13o2_print_delta_flux, c13o2_print_delta_pools, c13o2_print_delta_luc, load_parameters, c13o2_update_luc, bgcdriver, casa_feedback, casaonly_luc, spincasacnp, cbm
r1updt calls ne
mpidrv_master calls ne, pop_io, c13o2_print_delta_flux, c13o2_print_delta_pools, c13o2_print_delta_luc, master_spincasacnp, load_parameters, master_casaonly_luc, c13o2_update_luc
hybrj calls ne, qrfac, qform, dogleg, r1updt
hybrj1 calls hybrj
mpi_driver calls mpidrv_master, mpidrv_worker
lmpar calls qrsolv
get_default_params calls read_soilcolor
master_spincasacnp calls pop_io
load_parameters calls pop_io, get_default_params
lmstr1 calls lmstr
master_casaonly_luc calls pop_io, c13o2_update_luc
timestep_loop calls isotope_vap
hybrd1 calls hybrd
lmdif1 calls lmdif
isotope_pool_model calls isotope_pool_model_2d, isotope_pool_model_1d
lmder1 calls lmder
solve calls timestep_loop
adjust_jv_gm calls lmdif1
c13o2_update_luc calls isotope_pool_model
c13o2_update_pools calls isotope_pool_model
sli_main calls solve
worker_spincasacnp calls c13o2_update_pools
bgcdriver calls c13o2_update_pools
casa_feedback calls adjust_jv_gm
casaonly_luc calls c13o2_update_luc, c13o2_update_pools
worker_casaonly_luc calls c13o2_update_pools
spincasacnp calls c13o2_update_pools
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls worker_spincasacnp, bgcdriver, casa_feedback, worker_casaonly_luc, cbm