print_cbm_var – POP
print_cbm_var Interface
3 statements
Source File
public interface print_cbm_var
Calls
Contents
Module Procedures
print_balances_type print_soil_parameter_type print_soil_snow_type print_veg_parameter_type print_canopy_type print_radiation_type print_roughness_type print_air_type print_met_type print_sum_flux_type print_bgc_pool_type print_climate_type
Module Procedures
private subroutine print_balances_type(bal)
Arguments
Type Intent Optional Attributes Name
type(balances_type), intent(in) :: bal
private subroutine print_soil_parameter_type(soil)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(in) :: soil
private subroutine print_soil_snow_type(ssnow)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(in) :: ssnow
private subroutine print_veg_parameter_type(veg)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(in) :: veg
private subroutine print_canopy_type(canopy)
Arguments
Type Intent Optional Attributes Name
type(canopy_type), intent(in) :: canopy
private subroutine print_radiation_type(rad)
Arguments
Type Intent Optional Attributes Name
type(radiation_type), intent(in) :: rad
private subroutine print_roughness_type(rought)
Arguments
Type Intent Optional Attributes Name
type(roughness_type), intent(in) :: rought
private subroutine print_air_type(air)
Arguments
Type Intent Optional Attributes Name
type(air_type), intent(in) :: air
private subroutine print_met_type(met)
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(in) :: met
private subroutine print_sum_flux_type(sum_flux)
Arguments
Type Intent Optional Attributes Name
type(sum_flux_type), intent(in) :: sum_flux
private subroutine print_bgc_pool_type(bgc)
Arguments
Type Intent Optional Attributes Name
type(bgc_pool_type), intent(in) :: bgc
private subroutine print_climate_type(met)
Arguments
Type Intent Optional Attributes Name
type(climate_type), intent(in) :: met
Call graph
print_cbm_var calls print_bgc_pool_type, print_soil_parameter_type, print_balances_type, print_soil_snow_type, print_canopy_type, print_veg_parameter_type, print_radiation_type, print_roughness_type, print_air_type, print_met_type, print_climate_type, print_sum_flux_type