print_casa_var – POP
print_casa_var Interface
3 statements
Source File
public interface print_casa_var
Calls
Contents
Module Procedures
print_casabiome print_casapool print_casaflux print_casamet print_casabal
Module Procedures
private subroutine print_casabiome(casabiome)
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(in) :: casabiome
private subroutine print_casapool(casapool)
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(in) :: casapool
private subroutine print_casaflux(casaflux)
Arguments
Type Intent Optional Attributes Name
type(casa_flux), intent(in) :: casaflux
private subroutine print_casamet(casamet)
Arguments
Type Intent Optional Attributes Name
type(casa_met), intent(in) :: casamet
private subroutine print_casabal(casabal)
Arguments
Type Intent Optional Attributes Name
type(casa_balance), intent(in) :: casabal
Call graph
print_casa_var calls print_casabiome, print_casapool, print_casaflux, print_casabal, print_casamet