read_netcdf_casa_var – POP
read_netcdf_casa_var Interface
3 statements
Source File
public interface read_netcdf_casa_var
Calls
Called by
Contents
Module Procedures
read_netcdf_casabiome read_netcdf_casapool read_netcdf_casaflux read_netcdf_casamet read_netcdf_casabal
Module Procedures
private subroutine read_netcdf_casabiome(filename, casabiome)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_biome), intent(inout) :: casabiome
private subroutine read_netcdf_casapool(filename, casapool)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_pool), intent(inout) :: casapool
private subroutine read_netcdf_casaflux(filename, casaflux)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_flux), intent(inout) :: casaflux
private subroutine read_netcdf_casamet(filename, casamet)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_met), intent(inout) :: casamet
private subroutine read_netcdf_casabal(filename, casabal)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_balance), intent(inout) :: casabal
Call graph
read_netcdf_casa_var calls read_netcdf_casabiome, read_netcdf_casapool, read_netcdf_casaflux, read_netcdf_casamet, read_netcdf_casabal
read_netcdf_casabiome calls mpi_abort, nf90_open, nc_err, nf90_inq_varid, nf90_get_var, nf90_close
read_netcdf_casapool calls mpi_abort, nf90_open, nc_err, nf90_inq_varid, nf90_get_var, nf90_close
read_netcdf_casaflux calls mpi_abort, nf90_open, nc_err, nf90_inq_varid, nf90_get_var, nf90_close
read_netcdf_casamet calls mpi_abort, nf90_open, nc_err, nf90_inq_varid, nf90_get_var, nf90_close
read_netcdf_casabal calls mpi_abort, nf90_open, nc_err, nf90_inq_varid, nf90_get_var, nf90_close
nc_err calls mpi_abort, nf90_strerror
read_casa_restart_nc calls read_netcdf_casa_var
casa_init calls read_casa_restart_nc
load_parameters calls casa_init
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master