read_netcdf_cbm_var – POP
read_netcdf_cbm_var Interface
3 statements
Source File
public interface read_netcdf_cbm_var
Calls
Called by
Contents
Module Procedures
read_netcdf_climate_type
Module Procedures
private subroutine read_netcdf_climate_type(filename, climate)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(climate_type), intent(inout) :: climate
Call graph
read_netcdf_cbm_var calls read_netcdf_climate_type
read_netcdf_climate_type calls mpi_abort, nf90_inq_varid, nc_err, nf90_get_var, nf90_open, nf90_close
nc_err calls mpi_abort, nf90_strerror
read_climate_restart_nc calls read_netcdf_cbm_var
read_climatefile calls read_netcdf_cbm_var
mpidrv_master calls read_climate_restart_nc, luc_expt_init
cable_offline_driver calls read_climate_restart_nc, luc_expt_init
luc_expt_init calls read_climatefile
mpi_driver calls mpidrv_master