swap – POP
swap Interface
3 statements
Source File
public interface swap
\brief Swap two values or exchange two elements in array. \details Swaps either two entities, i.e. scalars, vectors, matrices, or exchanges two elements in a vector. If an optinal mask is given, the only elements with mask==.true. will be exchanged.\n The call is either \n call swap(x, y, mask=mask) \n or \n call swap(vec, i, j, mask=mask) \param[in] "integer(i4) :: i" Index of first element to be swapped with second [case swap(vec,i,j)] \param[in] "integer(i4) :: j" Index of second element to be swapped with first [case swap(vec,i,j)] \param[inout] "real(sp/dp)/integer(i4)/complex(spc/dpc) :: x[(:,...)]" First scalar or array to swap with second [case swap(x,y)] \param[inout] "real(sp/dp)/integer(i4)/complex(spc/dpc) :: y[(:[,:])]" Second scalar or array to swap with first [case swap(x,y)]
\param[inout] "real(sp/dp)/integer(i4)/complex(spc/dpc) :: x(:)" Vector of which to elements are swapped [case swap(vec,i,j)] \param[in] "logical, optional :: mask[(:,...)]" scalar or array logical mask\n If present, only those elements will be swapped where mask==.true. \author Matthias Cuntz \date May 2014
Calls
Contents
Module Procedures
swap_xy_dp swap_xy_sp swap_xy_i4 swap_xy_dpc swap_xy_spc swap_xy_mask_dp swap_xy_mask_sp swap_xy_mask_i4 swap_xy_mask_dpc swap_xy_mask_spc swap_vec_dp swap_vec_sp swap_vec_i4 swap_vec_dpc swap_vec_spc swap_vec_mask_dp swap_vec_mask_sp swap_vec_mask_i4 swap_vec_mask_dpc swap_vec_mask_spc
Module Procedures
private pure elemental subroutine swap_xy_dp(x, y)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: x
real(kind=dp), intent(inout) :: y
private pure elemental subroutine swap_xy_sp(x, y)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout) :: x
real(kind=sp), intent(inout) :: y
private pure elemental subroutine swap_xy_i4(x, y)
Arguments
Type Intent Optional Attributes Name
integer(kind=i4), intent(inout) :: x
integer(kind=i4), intent(inout) :: y
private pure elemental subroutine swap_xy_dpc(x, y)
Arguments
Type Intent Optional Attributes Name
complex(kind=dpc), intent(inout) :: x
complex(kind=dpc), intent(inout) :: y
private pure elemental subroutine swap_xy_spc(x, y)
Arguments
Type Intent Optional Attributes Name
complex(kind=spc), intent(inout) :: x
complex(kind=spc), intent(inout) :: y
private pure elemental subroutine swap_xy_mask_dp(x, y, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: x
real(kind=dp), intent(inout) :: y
logical, intent(in) :: mask
private pure elemental subroutine swap_xy_mask_sp(x, y, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout) :: x
real(kind=sp), intent(inout) :: y
logical, intent(in) :: mask
private pure elemental subroutine swap_xy_mask_i4(x, y, mask)
Arguments
Type Intent Optional Attributes Name
integer(kind=i4), intent(inout) :: x
integer(kind=i4), intent(inout) :: y
logical, intent(in) :: mask
private pure elemental subroutine swap_xy_mask_dpc(x, y, mask)
Arguments
Type Intent Optional Attributes Name
complex(kind=dpc), intent(inout) :: x
complex(kind=dpc), intent(inout) :: y
logical, intent(in) :: mask
private pure elemental subroutine swap_xy_mask_spc(x, y, mask)
Arguments
Type Intent Optional Attributes Name
complex(kind=spc), intent(inout) :: x
complex(kind=spc), intent(inout) :: y
logical, intent(in) :: mask
private subroutine swap_vec_dp(x, i1, i2)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout), dimension(:) :: x
integer(kind=i4), intent(in) :: i1
integer(kind=i4), intent(in) :: i2
private subroutine swap_vec_sp(x, i1, i2)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout), dimension(:) :: x
integer(kind=i4), intent(in) :: i1
integer(kind=i4), intent(in) :: i2
private subroutine swap_vec_i4(x, i1, i2)
Arguments
Type Intent Optional Attributes Name
integer(kind=i4), intent(inout), dimension(:) :: x
integer(kind=i4), intent(in) :: i1
integer(kind=i4), intent(in) :: i2
private subroutine swap_vec_dpc(x, i1, i2)
Arguments
Type Intent Optional Attributes Name
complex(kind=dpc), intent(inout), dimension(:) :: x
integer(kind=i4), intent(in) :: i1
integer(kind=i4), intent(in) :: i2
private subroutine swap_vec_spc(x, i1, i2)
Arguments
Type Intent Optional Attributes Name
complex(kind=spc), intent(inout), dimension(:) :: x
integer(kind=i4), intent(in) :: i1
integer(kind=i4), intent(in) :: i2
private subroutine swap_vec_mask_dp(x, i1, i2, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout), dimension(:) :: x
integer(kind=i4), intent(in) :: i1
integer(kind=i4), intent(in) :: i2
logical, intent(in) :: mask
private subroutine swap_vec_mask_sp(x, i1, i2, mask)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout), dimension(:) :: x
integer(kind=i4), intent(in) :: i1
integer(kind=i4), intent(in) :: i2
logical, intent(in) :: mask
private subroutine swap_vec_mask_i4(x, i1, i2, mask)
Arguments
Type Intent Optional Attributes Name
integer(kind=i4), intent(inout), dimension(:) :: x
integer(kind=i4), intent(in) :: i1
integer(kind=i4), intent(in) :: i2
logical, intent(in) :: mask
private subroutine swap_vec_mask_dpc(x, i1, i2, mask)
Arguments
Type Intent Optional Attributes Name
complex(kind=dpc), intent(inout), dimension(:) :: x
integer(kind=i4), intent(in) :: i1
integer(kind=i4), intent(in) :: i2
logical, intent(in) :: mask
private subroutine swap_vec_mask_spc(x, i1, i2, mask)
Arguments
Type Intent Optional Attributes Name
complex(kind=spc), intent(inout), dimension(:) :: x
integer(kind=i4), intent(in) :: i1
integer(kind=i4), intent(in) :: i2
logical, intent(in) :: mask
Call graph
swap calls swap_vec_mask_dpc, swap_vec_mask_sp, swap_xy_i4, swap_xy_dp, swap_xy_mask_dp, swap_xy_mask_sp, swap_xy_mask_dpc, swap_xy_mask_spc, swap_vec_dp, swap_vec_dpc, swap_vec_mask_dp, swap_vec_mask_spc, swap_xy_dpc, swap_vec_spc, swap_xy_spc, swap_vec_sp, swap_vec_i4, swap_xy_sp, swap_xy_mask_i4, swap_vec_mask_i4