toreal4 – POP
toreal4 Interface
3 statements
Source File
private interface toreal4
Calls
Called by
Contents
Module Procedures
dp2sp i2sp sp2sp
Module Procedures
private pure elemental function dp2sp(var)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: var
Return Value real(kind=4)
private pure elemental function i2sp(var)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: var
Return Value real(kind=4)
private pure elemental function sp2sp(var)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: var
Return Value real(kind=4)
Call graph
toreal4 calls dp2sp, i2sp, sp2sp
open_output_file calls toreal4
write_output calls toreal4
create_restart calls toreal4
mpidrv_master calls open_output_file, write_output, create_restart
cable_offline_driver calls open_output_file, write_output, create_restart
mpi_driver calls mpidrv_master