write_netcdf_cbm_var – POP
write_netcdf_cbm_var Interface
3 statements
Source File
public interface write_netcdf_cbm_var
Calls
Called by
Contents
Module Procedures
write_netcdf_climate_type
Module Procedures
private subroutine write_netcdf_climate_type(filename, climate)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(climate_type), intent(in) :: climate
Call graph
write_netcdf_cbm_var calls write_netcdf_climate_type
write_netcdf_climate_type calls nf90_create, nc_err, nf90_enddef, nf90_def_dim, nf90_def_var, nf90_put_var, nf90_close
nc_err calls nf90_strerror
write_climate_restart_nc calls write_netcdf_cbm_var
mpidrv_master calls write_climate_restart_nc
cable_offline_driver calls write_climate_restart_nc
mpi_driver calls mpidrv_master