write_netcdf_casa_var – POP
write_netcdf_casa_var Interface
3 statements
Source File
public interface write_netcdf_casa_var
Calls
Called by
Contents
Module Procedures
write_netcdf_casabiome write_netcdf_casapool write_netcdf_casaflux write_netcdf_casamet write_netcdf_casabal
Module Procedures
private subroutine write_netcdf_casabiome(filename, casabiome)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_biome), intent(in) :: casabiome
private subroutine write_netcdf_casapool(filename, casapool)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_pool), intent(in) :: casapool
private subroutine write_netcdf_casaflux(filename, casaflux)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_flux), intent(in) :: casaflux
private subroutine write_netcdf_casamet(filename, casamet)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_met), intent(in) :: casamet
private subroutine write_netcdf_casabal(filename, casabal)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(casa_balance), intent(in) :: casabal
Call graph
write_netcdf_casa_var calls write_netcdf_casabiome, write_netcdf_casaflux, write_netcdf_casapool, write_netcdf_casamet, write_netcdf_casabal
write_netcdf_casabiome calls nf90_create, nc_err, nf90_def_dim, nf90_enddef, nf90_def_var, nf90_put_var, nf90_close
write_netcdf_casaflux calls nf90_create, nc_err, nf90_def_dim, nf90_enddef, nf90_def_var, nf90_put_var, nf90_close
write_netcdf_casapool calls nf90_create, nc_err, nf90_def_dim, nf90_enddef, nf90_def_var, nf90_put_var, nf90_close
write_netcdf_casamet calls nf90_create, nc_err, nf90_def_dim, nf90_enddef, nf90_def_var, nf90_put_var, nf90_close
write_netcdf_casabal calls nf90_create, nc_err, nf90_def_dim, nf90_enddef, nf90_def_var, nf90_put_var, nf90_close
nc_err calls nf90_strerror
write_casa_restart_nc calls write_netcdf_casa_var
master_spincasacnp calls write_casa_restart_nc
cable_offline_driver calls write_casa_restart_nc
master_casaonly_luc calls write_casa_restart_nc
mpidrv_master calls write_casa_restart_nc, master_spincasacnp, master_casaonly_luc
mpi_driver calls mpidrv_master