zero_cbm_var – POP
zero_cbm_var Interface
3 statements
Source File
public interface zero_cbm_var
Calls
Called by
Contents
Module Procedures
zero_balances_type zero_soil_parameter_type zero_soil_snow_type zero_veg_parameter_type zero_canopy_type zero_radiation_type zero_roughness_type zero_air_type zero_met_type zero_sum_flux_type zero_bgc_pool_type zero_climate_type
Module Procedures
private subroutine zero_balances_type(bal)
Arguments
Type Intent Optional Attributes Name
type(balances_type), intent(inout) :: bal
private subroutine zero_soil_parameter_type(soil)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: soil
private subroutine zero_soil_snow_type(ssnow)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
private subroutine zero_veg_parameter_type(veg)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
private subroutine zero_canopy_type(canopy)
Arguments
Type Intent Optional Attributes Name
type(canopy_type), intent(inout) :: canopy
private subroutine zero_radiation_type(rad)
Arguments
Type Intent Optional Attributes Name
type(radiation_type), intent(inout) :: rad
private subroutine zero_roughness_type(rought)
Arguments
Type Intent Optional Attributes Name
type(roughness_type), intent(inout) :: rought
private subroutine zero_air_type(air)
Arguments
Type Intent Optional Attributes Name
type(air_type), intent(inout) :: air
private subroutine zero_met_type(met)
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: met
private subroutine zero_sum_flux_type(sum_flux)
Arguments
Type Intent Optional Attributes Name
type(sum_flux_type), intent(inout) :: sum_flux
private subroutine zero_bgc_pool_type(bgc)
Arguments
Type Intent Optional Attributes Name
type(bgc_pool_type), intent(inout) :: bgc
private subroutine zero_climate_type(climate)
Arguments
Type Intent Optional Attributes Name
type(climate_type), intent(inout) :: climate
Call graph
zero_cbm_var calls zero_climate_type, zero_veg_parameter_type, zero_balances_type, zero_soil_snow_type, zero_canopy_type, zero_soil_parameter_type, zero_radiation_type, zero_roughness_type, zero_air_type, zero_met_type, zero_sum_flux_type, zero_bgc_pool_type
allocate_cable_vars calls zero_cbm_var
mpidrv_master calls zero_cbm_var, load_parameters
cable_offline_driver calls zero_cbm_var, load_parameters
worker_climate_types calls zero_cbm_var
load_parameters calls allocate_cable_vars
worker_cable_params calls allocate_cable_vars
mpi_driver calls mpidrv_master, mpidrv_worker
mpidrv_worker calls worker_climate_types, worker_cable_params