zero_casa_var – POP
zero_casa_var Interface
3 statements
Source File
public interface zero_casa_var
Calls
Called by
Contents
Module Procedures
zero_casabiome zero_casapool zero_casaflux zero_casamet zero_casabal
Module Procedures
private subroutine zero_casabiome(casabiome)
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(inout) :: casabiome
private subroutine zero_casapool(casapool)
Arguments
Type Intent Optional Attributes Name
type(casa_pool), intent(inout) :: casapool
private subroutine zero_casaflux(casaflux)
Arguments
Type Intent Optional Attributes Name
type(casa_flux), intent(inout) :: casaflux
private subroutine zero_casamet(casamet)
Arguments
Type Intent Optional Attributes Name
type(casa_met), intent(inout) :: casamet
private subroutine zero_casabal(casabal)
Arguments
Type Intent Optional Attributes Name
type(casa_balance), intent(inout) :: casabal
Call graph
zero_casa_var calls zero_casabiome, zero_casapool, zero_casaflux, zero_casabal, zero_casamet
load_parameters calls zero_casa_var
master_casaonly_luc calls zero_casa_var
worker_casa_params calls zero_casa_var
master_spincasacnp calls zero_casa_var
mpidrv_master calls load_parameters, master_casaonly_luc, master_spincasacnp
mpidrv_worker calls worker_casa_params
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master, mpidrv_worker