#!/bin/bash

# Name the arguments to increase readability
FC=$1
CFLAGS=$2
LDFLAGS=$3
LD=$4
NCMOD=$5

export CINC="-I$NCMOD"
export supr=' -warn nostderrors -diag-disable 10145 '
mkdir -p tmpo
rm -f cable_driver.o

cp *.o tmpo/
export FOBJS=`ls tmpo/`

# this is the executable we are building
PROG=cable

$FC $supr $CFLAGS $LDFLAGS $LD -o $PROG cable_driver.F90 $FOBJS $CINC 

rm -fr tmpo/
