cable_Pyfprintf – CABLE
cable_Pyfprintf Interface
3 statements
Source File
public interface cable_Pyfprintf
Calls
Contents
Module Procedures
cable_Pyfprintf1 cable_Pyfprintf2
Module Procedures
public subroutine cable_Pyfprintf1(iDiag, basename, var1, dimx, L_fprint)
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: basename
real, dimension(dimx) :: var1
integer :: dimx
logical :: L_fprint
public subroutine cable_Pyfprintf2(iDiag, basename, var1, dimx, dimy, L_fprint)
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: basename
real, dimension(dimx,dimy) :: var1
integer :: dimx
integer :: dimy
logical :: L_fprint
Call graph
cable_pyfprintf calls cable_pyfprintf1, cable_pyfprintf2
cable_pyfprintf1 calls open_file_per_node, cable_pyprint1
cable_pyfprintf2 calls open_file_per_node, cable_pyprint2
open_file_per_node calls open_idiag