cable_farray – CABLE
cable_farray Interface
3 statements
Source File
public interface cable_farray
Calls
Contents
Module Procedures
cable_farray1 cable_farray2
Module Procedures
public subroutine cable_farray1(mp, CheckNames, CheckFields, n1, f1, n2, f2, n3, f3, n4, f4, n5, f5, n6, f6, n7, f7, n8, f8, n9, f9, n10, f10, n11, f11, n12, f12, n13, f13, n14, f14, n15, f15, n16, f16, n17, f17, n18, f18, n19, f19, n20, f20, n21, f21, n22, f22, n23, f23, n24, f24, n25, f25, n26, f26, n27, f27, n28, f28, n29, f29, n30, f30, n31, f31, n32, f32, n33, f33, n34, f34, n35, f35, n36, f36, n37, f37, n38, f38, n39, f39, n40, f40, n41, f41, n42, f42, n43, f43, n44, f44, n45, f45, n46, f46, n47, f47, n48, f48, n49, f49, n50, f50)
Arguments
Type Intent Optional Attributes Name
integer :: mp
character(len=30), dimension(:), allocatable :: CheckNames
real, dimension(:,:), allocatable :: CheckFields
character(len=*), optional :: n1
real, optional dimension(:) :: f1
character(len=*), optional :: n2
real, optional dimension(:) :: f2
character(len=*), optional :: n3
real, optional dimension(:) :: f3
character(len=*), optional :: n4
real, optional dimension(:) :: f4
character(len=*), optional :: n5
real, optional dimension(:) :: f5
character(len=*), optional :: n6
real, optional dimension(:) :: f6
character(len=*), optional :: n7
real, optional dimension(:) :: f7
character(len=*), optional :: n8
real, optional dimension(:) :: f8
character(len=*), optional :: n9
real, optional dimension(:) :: f9
character(len=*), optional :: n10
real, optional dimension(:) :: f10
character(len=*), optional :: n11
real, optional dimension(:) :: f11
character(len=*), optional :: n12
real, optional dimension(:) :: f12
character(len=*), optional :: n13
real, optional dimension(:) :: f13
character(len=*), optional :: n14
real, optional dimension(:) :: f14
character(len=*), optional :: n15
real, optional dimension(:) :: f15
character(len=*), optional :: n16
real, optional dimension(:) :: f16
character(len=*), optional :: n17
real, optional dimension(:) :: f17
character(len=*), optional :: n18
real, optional dimension(:) :: f18
character(len=*), optional :: n19
real, optional dimension(:) :: f19
character(len=*), optional :: n20
real, optional dimension(:) :: f20
character(len=*), optional :: n21
real, optional dimension(:) :: f21
character(len=*), optional :: n22
real, optional dimension(:) :: f22
character(len=*), optional :: n23
real, optional dimension(:) :: f23
character(len=*), optional :: n24
real, optional dimension(:) :: f24
character(len=*), optional :: n25
real, optional dimension(:) :: f25
character(len=*), optional :: n26
real, optional dimension(:) :: f26
character(len=*), optional :: n27
real, optional dimension(:) :: f27
character(len=*), optional :: n28
real, optional dimension(:) :: f28
character(len=*), optional :: n29
real, optional dimension(:) :: f29
character(len=*), optional :: n30
real, optional dimension(:) :: f30
character(len=*), optional :: n31
real, optional dimension(:) :: f31
character(len=*), optional :: n32
real, optional dimension(:) :: f32
character(len=*), optional :: n33
real, optional dimension(:) :: f33
character(len=*), optional :: n34
real, optional dimension(:) :: f34
character(len=*), optional :: n35
real, optional dimension(:) :: f35
character(len=*), optional :: n36
real, optional dimension(:) :: f36
character(len=*), optional :: n37
real, optional dimension(:) :: f37
character(len=*), optional :: n38
real, optional dimension(:) :: f38
character(len=*), optional :: n39
real, optional dimension(:) :: f39
character(len=*), optional :: n40
real, optional dimension(:) :: f40
character(len=*), optional :: n41
real, optional dimension(:) :: f41
character(len=*), optional :: n42
real, optional dimension(:) :: f42
character(len=*), optional :: n43
real, optional dimension(:) :: f43
character(len=*), optional :: n44
real, optional dimension(:) :: f44
character(len=*), optional :: n45
real, optional dimension(:) :: f45
character(len=*), optional :: n46
real, optional dimension(:) :: f46
character(len=*), optional :: n47
real, optional dimension(:) :: f47
character(len=*), optional :: n48
real, optional dimension(:) :: f48
character(len=*), optional :: n49
real, optional dimension(:) :: f49
character(len=*), optional :: n50
real, optional dimension(:) :: f50
public subroutine cable_farray2(mp, np, CheckNames, CheckFields, n1, f1, n2, f2, n3, f3, n4, f4, n5, f5, n6, f6, n7, f7, n8, f8, n9, f9, n10, f10, n11, f11, n12, f12, n13, f13, n14, f14, n15, f15, n16, f16, n17, f17, n18, f18, n19, f19, n20, f20, n21, f21, n22, f22, n23, f23, n24, f24, n25, f25, n26, f26, n27, f27, n28, f28, n29, f29, n30, f30, n31, f31, n32, f32, n33, f33, n34, f34, n35, f35, n36, f36, n37, f37, n38, f38, n39, f39, n40, f40, n41, f41, n42, f42, n43, f43, n44, f44, n45, f45, n46, f46, n47, f47, n48, f48, n49, f49, n50, f50)
Arguments
Type Intent Optional Attributes Name
integer :: mp
integer :: np
character(len=30), dimension(:), allocatable :: CheckNames
real, dimension(:,:,:), allocatable :: CheckFields
character(len=*), optional :: n1
real, optional dimension(:,:) :: f1
character(len=*), optional :: n2
real, optional dimension(:,:) :: f2
character(len=*), optional :: n3
real, optional dimension(:,:) :: f3
character(len=*), optional :: n4
real, optional dimension(:,:) :: f4
character(len=*), optional :: n5
real, optional dimension(:,:) :: f5
character(len=*), optional :: n6
real, optional dimension(:,:) :: f6
character(len=*), optional :: n7
real, optional dimension(:,:) :: f7
character(len=*), optional :: n8
real, optional dimension(:,:) :: f8
character(len=*), optional :: n9
real, optional dimension(:,:) :: f9
character(len=*), optional :: n10
real, optional dimension(:,:) :: f10
character(len=*), optional :: n11
real, optional dimension(:,:) :: f11
character(len=*), optional :: n12
real, optional dimension(:,:) :: f12
character(len=*), optional :: n13
real, optional dimension(:,:) :: f13
character(len=*), optional :: n14
real, optional dimension(:,:) :: f14
character(len=*), optional :: n15
real, optional dimension(:,:) :: f15
character(len=*), optional :: n16
real, optional dimension(:,:) :: f16
character(len=*), optional :: n17
real, optional dimension(:,:) :: f17
character(len=*), optional :: n18
real, optional dimension(:,:) :: f18
character(len=*), optional :: n19
real, optional dimension(:,:) :: f19
character(len=*), optional :: n20
real, optional dimension(:,:) :: f20
character(len=*), optional :: n21
real, optional dimension(:,:) :: f21
character(len=*), optional :: n22
real, optional dimension(:,:) :: f22
character(len=*), optional :: n23
real, optional dimension(:,:) :: f23
character(len=*), optional :: n24
real, optional dimension(:,:) :: f24
character(len=*), optional :: n25
real, optional dimension(:,:) :: f25
character(len=*), optional :: n26
real, optional dimension(:,:) :: f26
character(len=*), optional :: n27
real, optional dimension(:,:) :: f27
character(len=*), optional :: n28
real, optional dimension(:,:) :: f28
character(len=*), optional :: n29
real, optional dimension(:,:) :: f29
character(len=*), optional :: n30
real, optional dimension(:,:) :: f30
character(len=*), optional :: n31
real, optional dimension(:,:) :: f31
character(len=*), optional :: n32
real, optional dimension(:,:) :: f32
character(len=*), optional :: n33
real, optional dimension(:,:) :: f33
character(len=*), optional :: n34
real, optional dimension(:,:) :: f34
character(len=*), optional :: n35
real, optional dimension(:,:) :: f35
character(len=*), optional :: n36
real, optional dimension(:,:) :: f36
character(len=*), optional :: n37
real, optional dimension(:,:) :: f37
character(len=*), optional :: n38
real, optional dimension(:,:) :: f38
character(len=*), optional :: n39
real, optional dimension(:,:) :: f39
character(len=*), optional :: n40
real, optional dimension(:,:) :: f40
character(len=*), optional :: n41
real, optional dimension(:,:) :: f41
character(len=*), optional :: n42
real, optional dimension(:,:) :: f42
character(len=*), optional :: n43
real, optional dimension(:,:) :: f43
character(len=*), optional :: n44
real, optional dimension(:,:) :: f44
character(len=*), optional :: n45
real, optional dimension(:,:) :: f45
character(len=*), optional :: n46
real, optional dimension(:,:) :: f46
character(len=*), optional :: n47
real, optional dimension(:,:) :: f47
character(len=*), optional :: n48
real, optional dimension(:,:) :: f48
character(len=*), optional :: n49
real, optional dimension(:,:) :: f49
character(len=*), optional :: n50
real, optional dimension(:,:) :: f50
Call graph
cable_farray calls cable_farray1, cable_farray2
cable_farray1 calls fill_farray
cable_farray2 calls fill_farray2