brook_corey_hysteresis_swc_smp – GW
brook_corey_hysteresis_swc_smp Subroutine
33 statements
Source File
private subroutine brook_corey_hysteresis_swc_smp(soil, ssnow)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
Called by
Contents
None
Call graph
calc_soil_hydraulic_props calls brook_corey_hysteresis_swc_smp
soil_snow_gw calls brook_corey_hysteresis_swc_smp, swc_hyst_direction, smoistgw
swc_hyst_direction calls brook_corey_hysteresis_swc_smp
smoistgw calls calc_soil_hydraulic_props
cbm calls soil_snow_gw, sli_hydrology
sli_hydrology calls calc_soil_hydraulic_props
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker