carbon_type_ptr – GW
carbon_type_ptr Subroutine
4 statements
Source File
public subroutine carbon_type_ptr(C)
Arguments
Type Intent Optional Attributes Name
type(icarbon_type) :: C
Called by
Contents
Call graph
point2constants calls carbon_type_ptr
snowcheck calls point2constants
surfbv calls point2constants, smoisturev
snow_processes_soil_thermal calls point2constants, snowcheck, snow_melting, snowdensity, snowl_adjust, snow_accum, gwstempv
define_canopy calls point2constants, ruff_resist, define_air
snowdensity calls point2constants
snow_melting calls point2constants
cable_offline_driver calls point2constants, spec_init_soil_snow, cbm
snowl_adjust calls point2constants
mpidrv_worker calls point2constants, spec_init_soil_snow, cbm
spec_init_soil_snow calls point2constants
ruff_resist calls point2constants
stempv calls point2constants
snow_accum calls point2constants
init_radiation calls point2constants
plantcarb calls point2constants
smoisturev calls point2constants
define_air calls point2constants
soilfreeze calls point2constants
mpidrv_master calls point2constants
remove_trans calls point2constants
hydraulic_redistribution calls point2constants
gwstempv calls point2constants
soil_snow calls point2constants, snowcheck, surfbv, snow_melting, snowdensity, snowl_adjust, stempv, soilfreeze, snow_accum, hydraulic_redistribution, remove_trans
cbm calls point2constants, define_canopy, ruff_resist, init_radiation, plantcarb, define_air, soil_snow, surface_albedo, soil_snow_gw
surface_albedo calls point2constants
soil_snow_gw calls snow_processes_soil_thermal
mpi_driver calls mpidrv_worker, mpidrv_master