casa_allocation – GW
casa_allocation Subroutine
162 statements
Source File
public subroutine casa_allocation(veg, soil, casabiome, casaflux, casapool, casamet, phen, LALLOC)
vh_js !! vh_js !! as long as biomass is positive, adjust allocation to be proportional to stock when NPP -ve (Ticket#108) vh !! don't require this fix for LALLOC = 3 (POP allocation scheme) Thiss fix can lead to over-allocation to roots, in turn bumping up N-uptake , leading to decline in mineral nitrogen availability and spikes in fracCalloc, causing spikes in tree mortality and lack of model convergence in productive regions where LAI is hitting LAImax.
vh_js !! Ticket#108
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_flux), intent(inout) :: casaflux
type(casa_pool), intent(inout) :: casapool
type(casa_met), intent(inout) :: casamet
type(phen_variable), intent(inout) :: phen
integer, intent(in) :: LALLOC
Calls
Called by
Contents
Call graph
casa_allocation calls casa_wolf, 1166
biogeochem calls casa_allocation
casaonly_luc calls biogeochem
worker_casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
bgcdriver calls biogeochem
spincasacnp calls biogeochem
cable_offline_driver calls casaonly_luc, bgcdriver, spincasacnp
mpidrv_worker calls worker_casaonly_luc, worker_spincasacnp, bgcdriver
mpi_driver calls mpidrv_worker