cbm – GW
cbm Subroutine
112 statements
Source File
public subroutine cbm(ktau, dels, air, bgc, canopy, met, bal, rad, rough, soil, ssnow, sum_flux, veg, climate)
Uses
cable_data_module
cable_gw_hydro_module
cbl_soil_snow_main_module
cable_roughness_module
cable_canopy_module
cable_common_module
cable_air_module
cable_radiation_module
casadimension
cable_albedo_module
sli_main_mod
cable_carbon_module
cable_def_types_mod
vh_js !!
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
real, intent(in) :: dels
type(air_type), intent(inout) :: air
type(bgc_pool_type), intent(inout) :: bgc
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(balances_type), intent(inout) :: bal
type(radiation_type), intent(inout) :: rad
type(roughness_type), intent(inout) :: rough
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(sum_flux_type), intent(inout) :: sum_flux
type(veg_parameter_type), intent(inout) :: veg
type(climate_type), intent(in) :: climate
Calls
Called by
Contents
None
Call graph
cbm calls sli_hydrology, plantcarb, soilcarb, define_air, ruff_resist, point2constants, surface_albedo, init_radiation, define_canopy, soil_snow_gw, soil_snow, sli_main, carbon_pl
sli_hydrology calls aquifer_recharge, calc_soil_hydraulic_props, subsurface_drainage, iterative_wtd, ovrlndflx
plantcarb calls point2constants
define_air calls point2constants
ruff_resist calls point2constants
point2constants calls rad_type_ptr, gwhydro_type_ptr, carbon_type_ptr, driver_type_ptr, albedo_type_ptr, air_type_ptr, rough_type_ptr, ssnow_type_ptr, cbm_type_ptr, canopy_type_ptr
surface_albedo calls point2constants, calc_rhoch, surface_albedosn
init_radiation calls point2constants, spitter, calc_rhoch
define_canopy calls define_air, ruff_resist, point2constants, sli_main, pore_space_relative_humidity, set_den_rat, radiation, surf_wetness_fact, or_soil_evap_resistance, dryleaf
soil_snow_gw calls swc_hyst_direction, brook_corey_hysteresis_swc_smp, set_den_rat, remove_transgw, iterative_wtd, ovrlndflx, hutson_cass_swc_smp, gwsoilfreeze, snow_processes_soil_thermal, smoistgw, brook_corey_swc_smp
soil_snow calls point2constants, hydraulic_redistribution, snow_melting, snowl_adjust, surfbv, soilfreeze, snowdensity, snow_accum, stempv, remove_trans, snowcheck
sli_main calls esat_ice, setpar, setx, setlitterpar, tfrz, setroots, setpar_loetsch, esat, seb, hyofs, solve, thetalmax, slope_esat_ice, getrex
hydraulic_redistribution calls point2constants
snow_melting calls point2constants
swc_hyst_direction calls brook_corey_hysteresis_swc_smp, hutson_cass_swc_smp, brook_corey_swc_smp
calc_soil_hydraulic_props calls brook_corey_hysteresis_swc_smp, hutson_cass_swc_smp, brook_corey_swc_smp
surface_albedosn calls soilcol_albedo
snowl_adjust calls point2constants
surfbv calls point2constants, smoisturev
setroots calls setroots_2d, setroots_1d
soilfreeze calls point2constants
snowdensity calls point2constants
seb calls slope_csat, potential_evap, hyofh
snow_accum calls point2constants
hyofs calls tfrz, slope_esat, igamma, dthetalmaxdt
ovrlndflx calls saturated_fraction
surf_wetness_fact calls calc_srf_wet_fraction
or_soil_evap_resistance calls my_gamma
dryleaf calls xvcmxt4, fwsoil_calc_std, ej3x, ej4x, photosynthesis, fwsoil_calc_non_linear, fwsoil_calc_lai_ktaul, xvcmxt3, getrex_1d, xejmxt3, xrdt
stempv calls point2constants, trimb, old_soil_conductivity, total_soil_conductivity
remove_trans calls point2constants
solve calls hyofs, zerovars, timestep_loop, hyofh, litter_props, sofh, setsol
snowcheck calls point2constants
thetalmax calls tfrz
snow_processes_soil_thermal calls point2constants, snow_melting, snowl_adjust, snowdensity, snow_accum, snowcheck, gwstempv
smoistgw calls aquifer_recharge, calc_soil_hydraulic_props, subsurface_drainage, trimb, calc_equilibrium_water_content
getrex calls getrex_2d, getrex_1d
calc_srf_wet_fraction calls saturated_fraction
saturated_fraction calls my_erf
my_gamma calls my_gamma
smoisturev calls point2constants, trimb
getrex_2d calls getrex_1d
gwstempv calls point2constants, trimb, old_soil_conductivity, total_soil_conductivity
timestep_loop calls litter_props, iflux_loop, isotope_vap
setroots_2d calls setroots_1d
potential_evap calls slope_esat_ice, slope_esat
igamma calls gcf, gammln, gser
dthetalmaxdt calls tfrz
litter_props calls slope_esat
iflux_loop calls hyofs, litter_props, estimate_timestep, get_fluxes_and_derivs, get_and_solve_eqn, update_unknowns, snow_adjust, update_s_t
isotope_vap calls tri
gcf calls gammln
gser calls gammln
get_fluxes_and_derivs calls seb, zerovars, flux, getfluxes_vp, getheatfluxes
get_and_solve_eqn calls tfrz, massman_sparse
update_unknowns calls jsoillayer
snow_adjust calls esat_ice, tfrz, thetalmax, slope_esat_ice, jsoillayer, gtfrozen, rtbis_tfrozen
update_s_t calls tfrz, thetalmax, jsoillayer, gtfrozen, rtbis_tfrozen, dthetalmaxdth
tri calls tri_1d, tri_2d
flux calls weight
getfluxes_vp calls getfluxes_vp_2d, getfluxes_vp_1d
jsoillayer calls tfrz
getheatfluxes calls getheatfluxes_2d, getheatfluxes_1d
massman_sparse calls massman_sparse_1d, massman_sparse_2d
gtfrozen calls tfrz
rtbis_tfrozen calls gtfrozen
dthetalmaxdth calls tfrz
weight calls hyofh
getfluxes_vp_2d calls zerovars, hyofh, flux
getfluxes_vp_1d calls zerovars, hyofh, flux
massman_sparse_1d calls generic_thomas
massman_sparse_2d calls generic_thomas
generic_thomas calls generic_thomas_1d, generic_thomas_2d
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker