create_patch – GW
create_patch Subroutine
175 statements
Source File
public subroutine create_patch(patch_t, comm)
Uses
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: patch_t
integer, intent(in) :: comm
Calls
Called by
Contents
Call graph
create_patch calls create_layer, mpi_abort, mpi_type_commit, mpi_type_create_struct, mpi_get_address, mpi_type_create_resized
create_layer calls mpi_abort, mpi_type_commit, mpi_type_create_struct, mpi_get_address, mpi_type_create_resized, create_cohort
create_cohort calls mpi_abort, mpi_type_commit, mpi_type_create_struct, mpi_get_address, mpi_type_create_resized
create_pop_gridcell_type calls create_patch
worker_pop_types calls create_pop_gridcell_type
master_pop_types calls create_pop_gridcell_type
mpidrv_worker calls worker_pop_types
mpidrv_master calls master_pop_types
mpi_driver calls mpidrv_worker, mpidrv_master