create_pop_gridcell_type – GW
create_pop_gridcell_type Subroutine
270 statements
Source File
public subroutine create_pop_gridcell_type(gcell_t, comm)
Uses
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: gcell_t
integer, intent(in) :: comm
Calls
Called by
Contents
Call graph
create_pop_gridcell_type calls create_patch, mpi_get_address, mpi_type_create_struct, mpi_type_commit, mpi_abort, mpi_type_create_resized
create_patch calls mpi_get_address, mpi_type_create_struct, mpi_type_commit, mpi_abort, mpi_type_create_resized, create_layer
create_layer calls mpi_get_address, mpi_type_create_struct, mpi_type_commit, mpi_abort, mpi_type_create_resized, create_cohort
create_cohort calls mpi_get_address, mpi_type_create_struct, mpi_type_commit, mpi_abort, mpi_type_create_resized
master_pop_types calls create_pop_gridcell_type
worker_pop_types calls create_pop_gridcell_type
mpidrv_master calls master_pop_types
mpidrv_worker calls worker_pop_types
mpi_driver calls mpidrv_master, mpidrv_worker