define_air – GW
define_air Subroutine
17 statements
Source File
public subroutine define_air(met, air)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(in) :: met
type(air_type), intent(inout) :: air
Calls
Called by
Contents
None
Call graph
define_air calls point2constants
point2constants calls driver_type_ptr, cbm_type_ptr, air_type_ptr, albedo_type_ptr, canopy_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr, gwhydro_type_ptr
cbm calls define_air, define_canopy
define_canopy calls define_air
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker