find_extents – GW
find_extents Subroutine
23 statements
Source File
public subroutine find_extents()
Uses
cable_def_types_mod
mpi
Arguments
None
Calls
Called by
Contents
None
Call graph
find_extents calls mpi_get_address
mpidrv_worker calls find_extents, worker_outtype
mpidrv_master calls find_extents
worker_outtype calls find_extents
mpi_driver calls mpidrv_worker, mpidrv_master