fprint_fland – GW
fprint_fland Subroutine
41 statements
Source File
public subroutine fprint_fland(iDiag, dir, basename, node)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: dir
character(len=*) :: basename
integer :: node
Calls
Contents
None
Call graph
fprint_fland calls open_file_per_node, remove_empty_file
open_file_per_node calls open_idiag