getfluxes_vp_1d – GW
getfluxes_vp_1d Subroutine
196 statements
Source File
private subroutine getfluxes_vp_1d(n, dx, vtop, vbot, parin, var, hint, phimin, q, qya, qyb, qTa, qTb, ql, qlya, qlyb, qv, qvT, qvh, qvya, qvyb, iflux, init, getq0, getqn, Tsoil, T0, nsat, nsatlast)
Arguments
Type Intent Optional Attributes Name
integer(kind=i_d), intent(in) :: n
real(kind=r_2), intent(in), DIMENSION(1:n) :: dx
type(vars), intent(in) :: vtop
type(vars), intent(in) :: vbot
type(params), intent(in), DIMENSION(1:n) :: parin
type(vars), intent(inout), DIMENSION(1:n) :: var
real(kind=r_2), intent(inout), DIMENSION(1:n) :: hint
real(kind=r_2), intent(inout), DIMENSION(1:n) :: phimin
real(kind=r_2), intent(inout), DIMENSION(0:n) :: q
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qya
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qyb
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qTa
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qTb
real(kind=r_2), intent(inout), DIMENSION(0:n) :: ql
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qlya
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qlyb
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qv
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qvT
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qvh
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qvya
real(kind=r_2), intent(inout), DIMENSION(0:n) :: qvyb
integer(kind=i_d), intent(in) :: iflux
logical, intent(in) :: init
logical, intent(in) :: getq0
logical, intent(in) :: getqn
real(kind=r_2), intent(in), DIMENSION(1:n) :: Tsoil
real(kind=r_2), intent(in) :: T0
integer(kind=i_d), intent(in) :: nsat
integer(kind=i_d), intent(in) :: nsatlast
Calls
Called by
Contents
Call graph
getfluxes_vp_1d calls zerovars, flux, hyofh
flux calls weight
weight calls hyofh
getfluxes_vp calls getfluxes_vp_1d
get_fluxes_and_derivs calls getfluxes_vp
iflux_loop calls get_fluxes_and_derivs
timestep_loop calls iflux_loop
solve calls timestep_loop
sli_main calls solve
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker