getrex_1d – GW
getrex_1d Subroutine
59 statements
Source File
private subroutine getrex_1d(S, rex, fws, Fs, thetaS, thetaw, Etrans, gamma, dx, dt)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(:) :: S
real(kind=r_2), intent(out), DIMENSION(:) :: rex
real(kind=r_2), intent(inout) :: fws
real(kind=r_2), intent(in), DIMENSION(:) :: Fs
real(kind=r_2), intent(in), DIMENSION(:) :: thetaS
real(kind=r_2), intent(in), DIMENSION(:) :: thetaw
real(kind=r_2), intent(in) :: Etrans
real(kind=r_2), intent(in) :: gamma
real(kind=r_2), intent(in), DIMENSION(:) :: dx
real(kind=r_2), intent(in) :: dt
Called by
Contents
Call graph
getrex_2d calls getrex_1d
getrex calls getrex_1d, getrex_2d
sli_main calls getrex
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker