gwhydro_type_ptr – GW
gwhydro_type_ptr Subroutine
13 statements
Source File
public subroutine gwhydro_type_ptr(C)
Arguments
Type Intent Optional Attributes Name
type(igwhydro_type) :: C
Called by
Contents
None
Call graph
point2constants calls gwhydro_type_ptr
remove_trans calls point2constants
snow_accum calls point2constants
snowl_adjust calls point2constants
snow_processes_soil_thermal calls point2constants, snowdensity, snow_melting, snowcheck, gwstempv, snow_accum, snowl_adjust
smoisturev calls point2constants
hydraulic_redistribution calls point2constants
ruff_resist calls point2constants
init_radiation calls point2constants
define_canopy calls point2constants, ruff_resist, define_air
snowcheck calls point2constants
surface_albedo calls point2constants
snow_melting calls point2constants
gwstempv calls point2constants
spec_init_soil_snow calls point2constants
soil_snow calls point2constants, remove_trans, snow_accum, snowl_adjust, hydraulic_redistribution, snowcheck, snow_melting, soilfreeze, snowdensity, surfbv, stempv
soilfreeze calls point2constants
mpidrv_master calls point2constants
surfbv calls point2constants, smoisturev
snowdensity calls point2constants
plantcarb calls point2constants
stempv calls point2constants
cbm calls point2constants, ruff_resist, init_radiation, define_canopy, surface_albedo, soil_snow, plantcarb, define_air, soil_snow_gw
mpidrv_worker calls point2constants, spec_init_soil_snow, cbm
cable_offline_driver calls point2constants, spec_init_soil_snow, cbm
define_air calls point2constants
mpi_driver calls mpidrv_master, mpidrv_worker
soil_snow_gw calls snow_processes_soil_thermal