GWspatialParameters – GW
GWspatialParameters Subroutine
147 statements
Source File
public subroutine GWspatialParameters(logn, soil, ssnow)
Uses
cable_common_module
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: logn
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
Calls
Called by
Contents
None
Call graph
gwspatialparameters calls nf90_open, nf90_inq_dimid, nf90_inquire_dimension, get_gw_data, nf90_close
get_gw_data calls get_gw_2d_var_constdef, get_gw_2d_var, get_gw_3d_var_constdef, get_gw_3d_var, get_gw_4d_var_constdef, get_gw_4d_var
get_gw_2d_var_constdef calls nf90_inq_varid, nf90_get_var
get_gw_2d_var calls nf90_inq_varid, nf90_get_var
get_gw_3d_var_constdef calls nf90_inq_varid, nf90_get_var
get_gw_3d_var calls nf90_inq_varid, nf90_get_var
get_gw_4d_var_constdef calls nf90_inq_varid, nf90_get_var
get_gw_4d_var calls nf90_inq_varid, nf90_get_var
load_parameters calls gwspatialparameters
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master