hyofh – GW
hyofh Subroutine
16 statements
Source File
public pure elemental subroutine hyofh(h, lam, eta, Ke, he, K, Kh, phi)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: h
real(kind=r_2), intent(in) :: lam
real(kind=r_2), intent(in) :: eta
real(kind=r_2), intent(in) :: Ke
real(kind=r_2), intent(in) :: he
real(kind=r_2), intent(out) :: K
real(kind=r_2), intent(out) :: Kh
real(kind=r_2), intent(out) :: phi
Called by
Contents
Call graph
seb calls hyofh
weight calls hyofh
solve calls hyofh, timestep_loop
getfluxes_vp_1d calls hyofh, flux
getfluxes_vp_2d calls hyofh, flux
seb_fr calls hyofh
sli_main calls seb, solve
get_fluxes_and_derivs calls seb, getfluxes_vp, flux
getfluxes_vp calls getfluxes_vp_1d, getfluxes_vp_2d
flux calls weight
define_canopy calls sli_main
iflux_loop calls get_fluxes_and_derivs
cbm calls sli_main, define_canopy
timestep_loop calls iflux_loop
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker