igamma – GW
igamma Function
13 statements
Source File
public pure elemental function igamma(a, x)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: a
real(kind=r_2), intent(in) :: x
Return Value real(kind=r_2)
Calls
Called by
Contents
Call graph
igamma calls gammln, gser, gcf
gser calls gammln
gcf calls gammln
hyofs calls igamma
sli_main calls hyofs, solve
iflux_loop calls hyofs
solve calls hyofs, timestep_loop
define_canopy calls sli_main
timestep_loop calls iflux_loop
cbm calls sli_main, define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker