layer_recruitment_single_patch – GW
layer_recruitment_single_patch Subroutine
38 statements
Source File
public subroutine layer_recruitment_single_patch(POP, index, grid_index, precip)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: index
integer(kind=i4b), intent(in) :: grid_index
real(kind=dp), intent(in), optional :: precip(:)
Calls
Called by
Contents
None
Call graph
layer_recruitment_single_patch calls get_allometry
get_allometry calls getheight, allometry, williams_allometry
pop_init_single calls layer_recruitment_single_patch
patch_disturb calls layer_recruitment_single_patch
pop_init calls layer_recruitment_single_patch
casaonly_luc calls pop_init_single, popdriver
master_casaonly_luc calls pop_init_single
lucdriver calls pop_init_single
popluc_init calls pop_init_single
popstep calls patch_disturb
load_parameters calls pop_init, popluc_init
worker_pop_types calls pop_init
cable_offline_driver calls casaonly_luc, lucdriver, load_parameters, popdriver, spincasacnp
mpidrv_worker calls worker_pop_types, popdriver, worker_casaonly_luc, worker_spincasacnp
popdriver calls popstep
mpidrv_master calls master_casaonly_luc, lucdriver, load_parameters
mpi_driver calls mpidrv_worker, mpidrv_master
spincasacnp calls popdriver
worker_casaonly_luc calls popdriver
worker_spincasacnp calls popdriver