or_soil_evap_resistance – GW
or_soil_evap_resistance Subroutine
70 statements
Source File
public subroutine or_soil_evap_resistance(soil, air, met, canopy, ssnow, veg, rough)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: soil
type(air_type), intent(inout) :: air
type(met_type), intent(inout) :: met
type(canopy_type), intent(inout) :: canopy
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(inout) :: veg
type(roughness_type), intent(inout) :: rough
Calls
Called by
Contents
Call graph
or_soil_evap_resistance calls my_gamma
my_gamma calls my_gamma
define_canopy calls or_soil_evap_resistance
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker