potential_evap – GW
potential_evap Subroutine
37 statements
Source File
public subroutine potential_evap(Rn, rbh, rbw, Ta, rha, Tsoil, k, dz, lambdav, Ts, E, H, G, dEdrha, dEdTs, dEdTsoil, dGdTa, dGdTsoil, iice)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: Rn
real(kind=r_2), intent(in) :: rbh
real(kind=r_2), intent(in) :: rbw
real(kind=r_2), intent(in) :: Ta
real(kind=r_2), intent(in) :: rha
real(kind=r_2), intent(in) :: Tsoil
real(kind=r_2), intent(in) :: k
real(kind=r_2), intent(in) :: dz
real(kind=r_2), intent(in) :: lambdav
real(kind=r_2), intent(out) :: Ts
real(kind=r_2), intent(out) :: E
real(kind=r_2), intent(out) :: H
real(kind=r_2), intent(out) :: G
real(kind=r_2), intent(out) :: dEdrha
real(kind=r_2), intent(out) :: dEdTs
real(kind=r_2), intent(out) :: dEdTsoil
real(kind=r_2), intent(out) :: dGdTa
real(kind=r_2), intent(out) :: dGdTsoil
logical, intent(in), optional :: iice
Calls
Called by
Contents
None
Call graph
potential_evap calls slope_esat_ice, slope_esat
seb calls potential_evap
seb_fr calls potential_evap
sli_main calls seb, solve
get_fluxes_and_derivs calls seb
define_canopy calls sli_main
cbm calls sli_main, define_canopy
iflux_loop calls get_fluxes_and_derivs
mpidrv_worker calls cbm
timestep_loop calls iflux_loop
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker
solve calls timestep_loop