readpar_r2d – GW
readpar_r2d Subroutine
98 statements
Source File
private subroutine readpar_r2d(ncid, parname, completeSet, var_r2d, filename, npatch, dimswitch, from_restart, INpatch)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: parname
logical, intent(inout) :: completeSet
real(kind=r_2), intent(inout), DIMENSION(:, :) :: var_r2d
character(len=*), intent(in) :: filename
integer, intent(in) :: npatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: from_restart
integer, intent(in), optional :: INpatch
Calls
Called by
Contents
Call graph
readpar_r2d calls nf90_inq_varid, nc_abort, nf90_get_var, nf90_inquire_variable
nc_abort calls nf90_strerror
readpar calls readpar_r2d
extrarestart calls readpar
get_restart_data calls readpar, extrarestart
get_parameters_met calls readpar
load_parameters calls get_restart_data, get_parameters_met
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master