READ_CLIMATE_RESTART_NC – GW
READ_CLIMATE_RESTART_NC Subroutine
184 statements
Source File
public subroutine READ_CLIMATE_RESTART_NC(climate, ktauday)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
type(climate_type), intent(inout) :: climate
integer, intent(in) :: ktauday
Calls
Called by
Contents
None
Call graph
read_climate_restart_nc calls nf90_open, handle_err, nf90_inq_dimid, nf90_inquire_dimension, nf90_inq_varid, nf90_get_var, nf90_close
handle_err calls nf90_strerror
climate_init calls read_climate_restart_nc
master_climate_types calls read_climate_restart_nc, climate_init
cable_offline_driver calls read_climate_restart_nc, climate_init
worker_climate_types calls climate_init
mpidrv_master calls master_climate_types
mpidrv_worker calls worker_climate_types
mpi_driver calls mpidrv_master, mpidrv_worker