readpar_r2 – GW
readpar_r2 Subroutine
111 statements
Source File
private subroutine readpar_r2(ncid, parname, completeSet, var_r2, filename, npatch, dimswitch, from_restart, INpatch)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: parname
logical, intent(inout) :: completeSet
real(kind=4), intent(inout), DIMENSION(:,:) :: var_r2
character(len=*), intent(in) :: filename
integer, intent(in) :: npatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: from_restart
integer, intent(in), optional :: INpatch
Calls
Called by
Contents
Call graph
readpar_r2 calls nf90_inq_varid, nf90_inquire_variable, nf90_get_var, nc_abort
nc_abort calls nf90_strerror
readpar calls readpar_r2
extrarestart calls readpar
get_restart_data calls readpar, extrarestart
get_parameters_met calls readpar
load_parameters calls get_restart_data, get_parameters_met
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master