read_gridinfo – GW
read_gridinfo Subroutine
167 statements
Source File
private subroutine read_gridinfo(nlon, nlat, npatch)
Uses
cable_common_module
netcdf
vh_js !!
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: nlon
integer, intent(out) :: nlat
integer, intent(inout) :: npatch
Calls
Called by
Contents
Call graph
read_gridinfo calls nf90_open, nf90_inq_dimid, nc_abort, nf90_inquire_dimension, nf90_inq_varid, nf90_get_var, vegpatch_metfile, nf90_close
nc_abort calls nf90_strerror
get_default_params calls read_gridinfo
load_parameters calls get_default_params
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master