READ_LUH2 – GW
READ_LUH2 Subroutine
57 statements
Source File
public subroutine READ_LUH2(LUC_EXPT)
Arguments
Type Intent Optional Attributes Name
type(LUC_EXPT_TYPE), intent(inout) :: LUC_EXPT
Calls
Called by
Contents
None
Call graph
read_luh2 calls nf90_get_var, handle_err
handle_err calls nf90_strerror
casaonly_luc calls read_luh2
master_casaonly_luc calls read_luh2
lucdriver calls read_luh2
cable_offline_driver calls casaonly_luc, lucdriver
mpidrv_master calls master_casaonly_luc, lucdriver
mpi_driver calls mpidrv_master