sli_hydrology – GW
sli_hydrology Subroutine
16 statements
Source File
public subroutine sli_hydrology(dels, ssnow, soil, veg, canopy)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
type(canopy_type), intent(inout) :: canopy
Calls
Called by
Contents
None
Call graph
sli_hydrology calls iterative_wtd, aquifer_recharge, calc_soil_hydraulic_props, ovrlndflx, subsurface_drainage
calc_soil_hydraulic_props calls brook_corey_hysteresis_swc_smp, hutson_cass_swc_smp, brook_corey_swc_smp
ovrlndflx calls saturated_fraction
saturated_fraction calls my_erf
cbm calls sli_hydrology
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker