slope_esat – GW
slope_esat Function
8 statements
Source File
public pure elemental function slope_esat(T)
Uses
sli_numbers
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: T
Return Value real(kind=r_2)
Called by
Contents
Call graph
hyofs calls slope_esat
litter_props calls slope_esat
potential_evap calls slope_esat
sli_main calls hyofs, seb, solve
iflux_loop calls hyofs, litter_props, get_fluxes_and_derivs
seb calls potential_evap
timestep_loop calls litter_props, iflux_loop
solve calls hyofs, litter_props, timestep_loop
seb_fr calls potential_evap
define_canopy calls sli_main
cbm calls sli_main, define_canopy
get_fluxes_and_derivs calls seb
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker