slope_csat – GW
slope_csat Function
8 statements
Source File
public pure elemental function slope_csat(T)
Uses
sli_numbers
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: T
Return Value real(kind=r_2)
Called by
Contents
Call graph
seb calls slope_csat
rh0_sol calls slope_csat
seb_fr calls slope_csat
sli_main calls seb, solve
get_fluxes_and_derivs calls seb
rtbis_rh0 calls rh0_sol
define_canopy calls sli_main
cbm calls sli_main, define_canopy
iflux_loop calls get_fluxes_and_derivs
mpidrv_worker calls cbm
timestep_loop calls iflux_loop
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker
solve calls timestep_loop