smoisturev – GW
smoisturev Subroutine
184 statements
Source File
public subroutine smoisturev(dels, ssnow, soil, veg)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(in) :: veg
Calls
Called by
Contents
Call graph
smoisturev calls point2constants, trimb
point2constants calls driver_type_ptr, cbm_type_ptr, canopy_type_ptr, albedo_type_ptr, air_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr, gwhydro_type_ptr
surfbv calls smoisturev
soil_snow calls surfbv
cbm calls soil_snow
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker