smoistgw – GW
smoistgw Subroutine
183 statements
Source File
private subroutine smoistgw(dels, ktau, ssnow, soil, veg, canopy)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
integer, intent(in) :: ktau
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(inout) :: veg
type(canopy_type), intent(inout) :: canopy
Calls
Called by
Contents
Call graph
smoistgw calls calc_soil_hydraulic_props, calc_equilibrium_water_content, aquifer_recharge, subsurface_drainage, trimb
calc_soil_hydraulic_props calls brook_corey_hysteresis_swc_smp, hutson_cass_swc_smp, brook_corey_swc_smp
soil_snow_gw calls smoistgw
cbm calls soil_snow_gw
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker