snow_melting – GW
snow_melting Subroutine
51 statements
Source File
public subroutine snow_melting(dels, snowmlt, ssnow, soil)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
real, intent(out), DIMENSION(mp) :: snowmlt
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
Calls
Called by
Contents
None
Call graph
snow_melting calls point2constants
point2constants calls driver_type_ptr, air_type_ptr, cbm_type_ptr, albedo_type_ptr, canopy_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr, gwhydro_type_ptr
snow_processes_soil_thermal calls snow_melting