snowl_adjust – GW
snowl_adjust Subroutine
62 statements
Source File
public subroutine snowl_adjust(dels, ssnow, canopy)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
Calls
Called by
Contents
Call graph
snowl_adjust calls point2constants
point2constants calls driver_type_ptr, cbm_type_ptr, canopy_type_ptr, albedo_type_ptr, air_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr, gwhydro_type_ptr
snow_processes_soil_thermal calls snowl_adjust