soil_snow_gw – GW
soil_snow_gw Subroutine
124 statements
Source File
public subroutine soil_snow_gw(dels, soil, ssnow, canopy, met, bal, veg)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(balances_type), intent(inout) :: bal
type(veg_parameter_type), intent(inout) :: veg
Calls
Called by
Contents
None
Call graph
soil_snow_gw calls set_den_rat, gwsoilfreeze, iterative_wtd, remove_transgw, snow_processes_soil_thermal, ovrlndflx, smoistgw, swc_hyst_direction, brook_corey_hysteresis_swc_smp, hutson_cass_swc_smp, brook_corey_swc_smp
snow_processes_soil_thermal calls point2constants, snowcheck, snow_melting, snowdensity, snow_accum, snowl_adjust, gwstempv
ovrlndflx calls saturated_fraction
smoistgw calls aquifer_recharge, calc_equilibrium_water_content, calc_soil_hydraulic_props, subsurface_drainage, trimb
swc_hyst_direction calls brook_corey_hysteresis_swc_smp, hutson_cass_swc_smp, brook_corey_swc_smp
point2constants calls driver_type_ptr, cbm_type_ptr, albedo_type_ptr, canopy_type_ptr, air_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr, gwhydro_type_ptr
snowcheck calls point2constants
snow_melting calls point2constants
snowdensity calls point2constants
snow_accum calls point2constants
snowl_adjust calls point2constants
gwstempv calls point2constants, trimb, total_soil_conductivity, old_soil_conductivity
saturated_fraction calls my_erf
calc_soil_hydraulic_props calls brook_corey_hysteresis_swc_smp, hutson_cass_swc_smp, brook_corey_swc_smp
cbm calls soil_snow_gw
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker