soil_snow – GW
soil_snow Subroutine
137 statements
Source File
public subroutine soil_snow(dels, soil, ssnow, canopy, met, bal, veg)
Uses
cable_common_module
cbl_soil_snow_subrs_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(balances_type), intent(inout) :: bal
type(veg_parameter_type), intent(inout) :: veg
Calls
Called by
Contents
Call graph
soil_snow calls hydraulic_redistribution, point2constants, snowdensity, snowcheck, snow_melting, snow_accum, snowl_adjust, stempv, remove_trans, soilfreeze, surfbv
hydraulic_redistribution calls point2constants
point2constants calls driver_type_ptr, air_type_ptr, albedo_type_ptr, canopy_type_ptr, cbm_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr, gwhydro_type_ptr
snowdensity calls point2constants
snowcheck calls point2constants
snow_melting calls point2constants
snow_accum calls point2constants
snowl_adjust calls point2constants
stempv calls point2constants, trimb, old_soil_conductivity, total_soil_conductivity
remove_trans calls point2constants
soilfreeze calls point2constants
surfbv calls point2constants, smoisturev
smoisturev calls point2constants, trimb
cbm calls soil_snow
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker