spec_init_soil_snow – GW
spec_init_soil_snow Subroutine
60 statements
Source File
public subroutine spec_init_soil_snow(dels, soil, ssnow, canopy, met, bal, veg)
Uses
cable_common_module
cbl_soil_snow_subrs_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(balances_type), intent(inout) :: bal
type(veg_parameter_type), intent(inout) :: veg
Calls
Called by
Contents
Call graph
spec_init_soil_snow calls point2constants
point2constants calls driver_type_ptr, canopy_type_ptr, air_type_ptr, cbm_type_ptr, albedo_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr, gwhydro_type_ptr
mpidrv_worker calls spec_init_soil_snow
cable_offline_driver calls spec_init_soil_snow
mpi_driver calls mpidrv_worker