stempv – GW
stempv Subroutine
115 statements
Source File
public subroutine stempv(dels, canopy, ssnow, soil)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(canopy_type), intent(inout) :: canopy
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
Calls
Called by
Contents
None
Call graph
stempv calls point2constants, trimb, total_soil_conductivity, old_soil_conductivity
point2constants calls driver_type_ptr, cbm_type_ptr, albedo_type_ptr, air_type_ptr, canopy_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr, gwhydro_type_ptr
soil_snow calls stempv
cbm calls soil_snow
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker