surfbv – GW
surfbv Subroutine
70 statements
Source File
public subroutine surfbv(dels, met, ssnow, soil, veg, canopy)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(met_type), intent(inout) :: met
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(in) :: veg
type(canopy_type), intent(in) :: canopy
Calls
Contents
Call graph
surfbv calls point2constants, smoisturev
point2constants calls driver_type_ptr, canopy_type_ptr, albedo_type_ptr, cbm_type_ptr, air_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr, gwhydro_type_ptr
smoisturev calls point2constants, trimb