Surf_wetness_fact – GW
Surf_wetness_fact Subroutine
23 statements
Source File
private subroutine Surf_wetness_fact(cansat, canopy, ssnow, veg, met, soil, dels)
Uses
cable_common_module
cable_gw_hydro_module
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in), DIMENSION(:) :: cansat
type(canopy_type), intent(inout) :: canopy
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(inout) :: veg
type(met_type), intent(inout) :: met
type(soil_parameter_type), intent(inout) :: soil
real, intent(in) :: dels
Calls
Called by
Contents
Call graph
surf_wetness_fact calls calc_srf_wet_fraction
calc_srf_wet_fraction calls saturated_fraction
saturated_fraction calls my_erf
define_canopy calls surf_wetness_fact
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker