surface_albedo – GW
surface_albedo Subroutine
39 statements
Source File
public subroutine surface_albedo(ssnow, veg, met, rad, soil, canopy)
Uses
cable_common_module
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(inout) :: veg
type(met_type), intent(inout) :: met
type(radiation_type), intent(inout) :: rad
type(soil_parameter_type), intent(inout) :: soil
type(canopy_type), intent(in) :: canopy
Calls
Called by
Contents
Call graph
surface_albedo calls point2constants, calc_rhoch, surface_albedosn
point2constants calls driver_type_ptr, cbm_type_ptr, air_type_ptr, canopy_type_ptr, albedo_type_ptr, carbon_type_ptr, rad_type_ptr, rough_type_ptr, ssnow_type_ptr, gwhydro_type_ptr
surface_albedosn calls soilcol_albedo
cbm calls surface_albedo
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker