swc_hyst_direction – GW
swc_hyst_direction Subroutine
62 statements
Source File
private subroutine swc_hyst_direction(soil, ssnow, veg)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(inout) :: veg
Calls
Called by
Contents
Call graph
swc_hyst_direction calls brook_corey_hysteresis_swc_smp, hutson_cass_swc_smp, brook_corey_swc_smp
soil_snow_gw calls swc_hyst_direction
cbm calls soil_snow_gw
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker