vcmax_np – GW
vcmax_np Function
6 statements
Source File
public function vcmax_np(nleaf, pleaf)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: nleaf
real, intent(in) :: pleaf
Return Value real
Called by
Contents
None
Call graph
casa_rplant calls vcmax_np
casa_feedback calls vcmax_np
biogeochem calls casa_rplant
mpidrv_worker calls casa_feedback, worker_spincasacnp, bgcdriver, worker_casaonly_luc
cable_offline_driver calls casa_feedback, casaonly_luc, spincasacnp, bgcdriver
casaonly_luc calls biogeochem
spincasacnp calls biogeochem
worker_spincasacnp calls biogeochem
bgcdriver calls biogeochem
worker_casaonly_luc calls biogeochem
mpi_driver calls mpidrv_worker