weight – GW
weight Function
25 statements
Source File
public pure elemental function weight(parin, h, K, phi, dz)
Arguments
Type Intent Optional Attributes Name
type(params), intent(in) :: parin
real(kind=r_2), intent(in) :: h
real(kind=r_2), intent(in) :: K
real(kind=r_2), intent(in) :: phi
real(kind=r_2), intent(in) :: dz
Return Value real(kind=r_2)
Calls
Called by
Contents
Call graph
weight calls hyofh
flux calls weight
getfluxes_vp_1d calls flux
getfluxes_vp_2d calls flux
get_fluxes_and_derivs calls flux, getfluxes_vp
getfluxes_vp calls getfluxes_vp_1d, getfluxes_vp_2d
iflux_loop calls get_fluxes_and_derivs
timestep_loop calls iflux_loop
solve calls timestep_loop
sli_main calls solve
define_canopy calls sli_main
cbm calls sli_main, define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker