Williams_Allometry – GW
Williams_Allometry Subroutine
13 statements
Source File
public subroutine Williams_Allometry(agbiomass, density, height, dbh, basal)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: agbiomass
real(kind=dp), intent(in) :: density
real(kind=dp), intent(out) :: height
real(kind=dp), intent(out) :: dbh
real(kind=dp), intent(out) :: basal
Called by
Contents
None
Call graph
get_allometry calls williams_allometry
layer_recruitment_single_patch calls get_allometry
getdiagnostics calls get_allometry
patchannualdynamics calls get_allometry, layer_recruitment
layer_recruitment calls get_allometry
pop_init_single calls layer_recruitment_single_patch
pop_init calls layer_recruitment_single_patch
popstep calls getdiagnostics, patchannualdynamics, patch_disturb
patch_disturb calls layer_recruitment_single_patch
casaonly_luc calls pop_init_single, popdriver
lucdriver calls pop_init_single
master_casaonly_luc calls pop_init_single
popluc_init calls pop_init_single
load_parameters calls pop_init, popluc_init
worker_pop_types calls pop_init
popdriver calls popstep
cable_offline_driver calls casaonly_luc, lucdriver, load_parameters, popdriver, spincasacnp
mpidrv_master calls master_casaonly_luc, lucdriver, load_parameters
worker_casaonly_luc calls popdriver
worker_spincasacnp calls popdriver
mpidrv_worker calls worker_pop_types, popdriver, worker_casaonly_luc, worker_spincasacnp
spincasacnp calls popdriver
mpi_driver calls mpidrv_master, mpidrv_worker