worker_decomp – GW
worker_decomp Subroutine
10 statements
Source File
private subroutine worker_decomp(comm)
Uses
cable_def_types_mod
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
Calls
Called by
Contents
Call graph
worker_decomp calls mpi_recv
mpidrv_worker calls worker_decomp
mpi_driver calls mpidrv_worker