WRITE_LUC_RESTART_NC – GW
WRITE_LUC_RESTART_NC Subroutine
87 statements
Source File
public subroutine WRITE_LUC_RESTART_NC(POPLUC, ctime)
Uses
cable_common_module
netcdf
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(in) :: POPLUC
integer, intent(in) :: ctime
Calls
Called by
Contents
None
Call graph
write_luc_restart_nc calls nf90_create, nf90_put_att, handle_err, nf90_redef, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_put_var, nf90_close
handle_err calls nf90_strerror
casaonly_luc calls write_luc_restart_nc
mpidrv_master calls write_luc_restart_nc, master_casaonly_luc
master_casaonly_luc calls write_luc_restart_nc
cable_offline_driver calls write_luc_restart_nc, casaonly_luc
mpi_driver calls mpidrv_master