write_default_params – GW
write_default_params Subroutine
232 statements
Source File
public subroutine write_default_params(met, air, ssnow, veg, bgc, soil, canopy, rough, rad, logn, vegparmnew, month, TFRZ, LUC_EXPT)
Uses
cable_common_module
vh_js !! vh_js !!
vh_js !! neeed to remove this if to enable the code below
vh_js !!
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: met
type(air_type), intent(inout) :: air
type(soil_snow_type), intent(inout) :: ssnow
type(veg_parameter_type), intent(inout) :: veg
type(bgc_pool_type), intent(inout) :: bgc
type(soil_parameter_type), intent(inout) :: soil
type(canopy_type), intent(inout) :: canopy
type(roughness_type), intent(inout) :: rough
type(radiation_type), intent(inout) :: rad
integer, intent(in) :: logn
logical, intent(in) :: vegparmnew
integer, intent(in) :: month
real, intent(in) :: TFRZ
type(LUC_EXPT_TYPE), intent(in) :: LUC_EXPT
Calls
Called by
Contents
Call graph
write_default_params calls vegpatch_metfile, soiltype_metfile, init_veg_from_vegin
load_parameters calls write_default_params
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master