ZeroPOP – GW
ZeroPOP Subroutine
130 statements
Source File
public subroutine ZeroPOP(POP, n)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer, intent(in), optional :: n
Called by
Contents
None
Call graph
pop_init_single calls zeropop
pop_init calls zeropop
casaonly_luc calls pop_init_single
popluc_init calls pop_init_single
lucdriver calls pop_init_single
master_casaonly_luc calls pop_init_single
load_parameters calls pop_init, popluc_init
worker_pop_types calls pop_init
cable_offline_driver calls casaonly_luc, lucdriver, load_parameters
mpidrv_master calls lucdriver, master_casaonly_luc, load_parameters
mpidrv_worker calls worker_pop_types
mpi_driver calls mpidrv_master, mpidrv_worker