name: Build docs
description: Build mkdocs and API docs
inputs:
  name:
    required: false
    description: "Name"

outputs:
  random:
    description: "Random number output"
    value: ${{ steps.step1.outputs.random }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies for mkdocs
      run: | 
        pip install -r documentation/mkdocs-requirements.txt
      shell: bash

    - name: Build documentation
      working-directory: documentation
      run: |
        # outputs to "site" directory
        mkdocs build -f mkdocs.yml
      shell: bash

    - name: Install dependencies for ford
      run: | 
        pip install -r documentation/ford-requirements.txt
      shell: bash

    # Builds without call graphs for faster result
    - name: Build API documentation
      working-directory: documentation
      run: |
        # outputs to "site/api" directory
        ford cable_ford.md
      shell: bash

    - name: Build POP API documentation
      working-directory: documentation
      run: |
        # outputs to "site/pop/api" directory
        ford pop_ford.md
      shell: bash

    - name: Build GW API documentation
      working-directory: documentation
      run: |
        # outputs to "site/gw/api" directory
        ford GW_ford.md
      shell: bash
