name: Build docs
description: Build mkdocs and API docs
inputs:
  name:
    required: false
    description: "Name"

outputs:
  random:
    description: "Random number output"
    value: ${{ steps.step1.outputs.random }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
      
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies for mkdocs
      run: | 
        pip install -r documentation/mkdocs-requirements.txt
      shell: bash

    - name: Build documentation
      working-directory: documentation
      run: |
        # outputs to "site" directory
        mkdocs build -f mkdocs.yml
      shell: bash

    # FORD documentation
    # Installation
    - name: Install dependencies for ford
      run: | 
        pip install -r documentation/ford-requirements.txt
      shell: bash

    # Create config file to build modified files only.
    - name: Create cable_ford.md
      run: |
        .github/actions/preview/FORD_exclude_files.sh ${{ github.event.pull_request.base.sha }} ${{ github.sha }}
      shell: bash

    # Builds without call graphs for faster result
    - name: Build API documentation
      working-directory: documentation
      run: |
        # outputs to "site/api" directory
        ford --no-search cable_ford.md
      shell: bash

    - name: Build POP API documentation
      working-directory: documentation
      run: |
        # outputs to "site/pop/api" directory
        ford --no-search pop_ford.md
      shell: bash

    - name: Build GW API documentation
      working-directory: documentation
      run: |
        # outputs to "site/gw/api" directory
        ford --no-search GW_ford.md
      shell: bash
