# Generate a Fortran module that returns the contents of a text file.
#
#   cable_embed_text(<input_file> <module_name> <output_file>)
#
# creates <output_file> defining `module <module_name>` with one function,
# `<module_name>_get()`, returning the text. The file is regenerated by CMake
# whenever <input_file> changes. Lines are split into short chunks so that they
# stay within Fortran's free-form line length limits. The text is processed with
# string(SUBSTRING) rather than lists, because it may contain semicolons.
function(cable_embed_text input_file module_name output_file)
    # Re-run CMake (and so regenerate the Fortran) whenever the text file changes.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${input_file}")
    file(READ "${input_file}" text)
    # Fortran source lines have a length limit on some compilers, so long text
    # lines are cut into pieces of at most this many characters.
    set(chunk_length 72)
    # `statements` collects the generated Fortran, one line at a time.
    set(statements "")
    string(LENGTH "${text}" text_length)
    set(position 0)
    # Outer loop: take the text one line at a time. `position` is how far
    # through the text we are. Substrings are used instead of splitting into a
    # CMake list, because a list would break the text at any semicolon in it.
    while(position LESS text_length)
        math(EXPR remaining "${text_length} - ${position}")
        string(SUBSTRING "${text}" ${position} ${remaining} rest)
        # The line runs from here to the next newline. On the last line there
        # may be no newline, so the whole of what is left is taken.
        string(FIND "${rest}" "\n" newline_position)
        if(newline_position EQUAL -1)
            set(line "${rest}")
            set(consumed ${remaining})
        else()
            string(SUBSTRING "${rest}" 0 ${newline_position} line)
            # Skip over the newline itself as well.
            math(EXPR consumed "${newline_position} + 1")
        endif()
        math(EXPR position "${position} + ${consumed}")
        # The line will sit inside a Fortran string in single quotes, where a
        # single quote is written twice.
        string(REPLACE "'" "''" line "${line}")
        string(LENGTH "${line}" line_length)
        # Inner loop: cut the line into pieces of at most `chunk_length`
        # characters, each becoming one Fortran statement that appends to `text`.
        set(offset 0)
        while(offset LESS line_length)
            math(EXPR left "${line_length} - ${offset}")
            if(left GREATER chunk_length)
                set(size ${chunk_length})
            else()
                set(size ${left})
            endif()
            string(SUBSTRING "${line}" ${offset} ${size} chunk)
            string(APPEND statements "    text = text // '${chunk}'\n")
            math(EXPR offset "${offset} + ${size}")
        endwhile()
        # After the last piece of a line, append the line break itself.
        string(APPEND statements "    text = text // new_line('a')\n")
    endwhile()
    # Wrap the statements in a small module with one function returning the text.
    set(content
"! Generated by cmake/EmbedText.cmake from ${input_file}. Do not edit.
module ${module_name}
  implicit none
  private
  public :: ${module_name}_get
contains
  function ${module_name}_get() result(text)
    character(:), allocatable :: text
    text = ''
${statements}  end function ${module_name}_get
end module ${module_name}
")
    # Write to a temporary file and copy it over only if it differs, so the
    # generated file's timestamp (and therefore the compile) is untouched when
    # the text has not changed.
    file(WRITE "${output_file}.tmp" "${content}")
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${output_file}.tmp" "${output_file}")
    file(REMOVE "${output_file}.tmp")
endfunction()
