Albedo – CABLE
Albedo Subroutine
54 statements
Source File
public subroutine Albedo(AlbSnow, AlbSoil, mp, nrb, jls_radiation, veg_mask, sunlit_mask, sunlit_veg_mask, Ccoszen_tols, Cgauss_w, surface_type, soil_type, VegRefl, VegTaul, coszen, reducedLAIdue2snow, SnowDepth, SnowDensity, SoilTemp, SnowAge, xk, c1, rhoch, RadFbeam, RadAlbedo, ExtCoeff_dif, ExtCoeff_beam, EffExtCoeff_dif, EffExtCoeff_beam, CanopyRefl_dif, CanopyRefl_beam, CanopyTransmit_dif, CanopyTransmit_beam, EffSurfRefl_dif, EffSurfRefl_beam)
Uses
cbl_snow_albedo_module
Arguments
Type Intent Optional Attributes Name
real :: AlbSnow(mp,nrb)
real :: AlbSoil(mp,nrb)
integer :: mp
integer :: nrb
logical :: jls_radiation
logical :: veg_mask(mp)
logical :: sunlit_mask(mp)
logical :: sunlit_veg_mask(mp)
real :: Ccoszen_tols
real :: Cgauss_w(nrb)
integer :: surface_type(mp)
integer :: soil_type(mp)
real :: VegRefl(mp,nrb)
real :: VegTaul(mp,nrb)
real :: coszen(mp)
real :: reducedLAIdue2snow(mp)
real :: SnowDepth(mp)
real :: SnowDensity(mp)
real :: SoilTemp(mp)
real :: SnowAge(mp)
real :: xk(mp,nrb)
real :: c1(mp,nrb)
real :: rhoch(mp,nrb)
real :: RadFbeam(mp,nrb)
real :: RadAlbedo(mp,nrb)
real :: ExtCoeff_dif(mp)
real :: ExtCoeff_beam(mp)
real :: EffExtCoeff_dif(mp,nrb)
real :: EffExtCoeff_beam(mp,nrb)
real :: CanopyRefl_dif(mp,nrb)
real :: CanopyRefl_beam(mp,nrb)
real :: CanopyTransmit_dif(mp,nrb)
real :: CanopyTransmit_beam(mp,nrb)
real :: EffSurfRefl_dif(mp,nrb)
real :: EffSurfRefl_beam(mp,nrb)
Calls
Called by
Contents
Call graph
albedo calls surface_albedosn, fbeamradalbedo, canopyreflectance, canopytransmitance, effectivesurfacereflectance
canopyreflectance calls canopyreflectance_beam, canopyreflectance_dif
canopytransmitance calls canopytransmitance_dif, canopytransmitance_beam
effectivesurfacereflectance calls effectivereflectance
cbm calls albedo
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker