allocate_soil_parameter_type – CABLE
allocate_soil_parameter_type Subroutine
86 statements
Source File
public subroutine allocate_soil_parameter_type(var, mp)
Uses
cable_other_constants_mod
cable_params_mod
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: var
integer, intent(in) :: mp
Called by
Contents
None
Call graph
alloc_cable_types calls allocate_soil_parameter_type
interface_um_data calls alloc_cable_types
cable_explicit_driver calls interface_um_data