Allometry – CABLE
Allometry Subroutine
13 statements
Source File
public subroutine Allometry(height, biomass, density, diam, basal)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: height
real(kind=dp), intent(in) :: biomass
real(kind=dp), intent(in) :: density
real(kind=dp), intent(out) :: diam
real(kind=dp), intent(out) :: basal
Called by
Contents
None
Call graph
get_allometry calls allometry
layer_recruitment_single_patch calls get_allometry
layer_recruitment calls get_allometry
getdiagnostics calls get_allometry
patchannualdynamics calls get_allometry, layer_recruitment
pop_init_single calls layer_recruitment_single_patch
patch_disturb calls layer_recruitment_single_patch
pop_init calls layer_recruitment_single_patch
popstep calls getdiagnostics, patchannualdynamics, patch_disturb
lucdriver calls pop_init_single
casaonly_luc calls pop_init_single, popdriver
master_casaonly_luc calls pop_init_single
popluc_init calls pop_init_single
load_parameters calls pop_init, popluc_init
worker_pop_types calls pop_init
popdriver calls popstep
cable_offline_driver calls lucdriver, casaonly_luc, load_parameters, popdriver, spincasacnp
mpidrv_worker calls worker_pop_types, popdriver, worker_casaonly_luc, worker_spincasacnp
spincasacnp calls popdriver
mpidrv_master calls master_casaonly_luc, lucdriver, load_parameters
worker_casaonly_luc calls popdriver
worker_spincasacnp calls popdriver
mpi_driver calls mpidrv_worker, mpidrv_master