BeamFraction – CABLE
BeamFraction Subroutine
17 statements
Source File
private subroutine BeamFraction(RadFbeam, mp, nrb, Cpi, Ccoszen_tols_huge, metDoY, coszen, SW_down)
Uses
cbl_spitter_module
Arguments
Type Intent Optional Attributes Name
real :: RadFbeam(mp,nrb)
integer :: mp
integer :: nrb
real :: Cpi
real :: Ccoszen_tols_huge
integer :: metDoY(mp)
real :: coszen(mp)
real :: SW_down(mp,nrb)
Calls
Called by
Contents
Call graph
beamfraction calls spitter
init_radiation calls beamfraction
cbm calls init_radiation
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker