cable_fprintf2 – CABLE
cable_fprintf2 Subroutine
13 statements
Source File
public subroutine cable_fprintf2(iDiag, basename, msg, L_fprint)
Uses
cable_common_module
cable_fFile_module
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: basename
character(len=*) :: msg
logical :: L_fprint
Calls
Called by
Contents
None
Call graph
cable_fprintf2 calls open_file_per_node, cable_print2
open_file_per_node calls open_idiag
cable_fprintf calls cable_fprintf2