cable_iprintf1 – CABLE
cable_iprintf1 Subroutine
36 statements
Source File
public subroutine cable_iprintf1(iDiag, basename, dimx, timestep, node, dir, var1)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
character(len=*) :: basename
integer :: dimx
integer :: timestep
integer :: node
character(len=*) :: dir
integer, dimension(dimx) :: var1
Calls
Called by
Contents
Call graph
cable_iprintf1 calls open_file_per_node, check_timestep
open_file_per_node calls open_idiag
cable_fprintf calls cable_iprintf1