cable_diag1 – CABLE
cable_diag1 Subroutine
12 statements
Source File
public subroutine cable_diag1(Nvars, basename, dimx, dimy, timestep, node, vname1, var1)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Nvars
character(len=*), intent(in) :: basename
integer, intent(in) :: dimx
integer, intent(in) :: dimy
integer, intent(in) :: timestep
integer, intent(in) :: node
character(len=*), intent(in) :: vname1
real, intent(in), dimension(:) :: var1
Calls
Called by
Contents
None
Call graph
cable_diag1 calls cable_diag_desc1, cable_diag_data1
cable_diag calls cable_diag1