cable_implicit_driver – CABLE
cable_implicit_driver Subroutine
76 statements
Source File
subroutine cable_implicit_driver(LS_RAIN, CON_RAIN, LS_SNOW, CONV_SNOW, DTL_1, DQW_1, TSOIL, TSOIL_TILE, SMCL, SMCL_TILE, timestep, SMVCST, STHF, STHF_TILE, STHU, STHU_TILE, SNOW_TILE, SNOW_RHO1L, ISNOW_FLG3L, SNOW_DEPTH3L, SNOW_MASS3L, SNOW_RHO3L, SNOW_TMP3L, SNOW_COND, FTL_TILE_CAB, FTL_CAB, LE_TILE_CAB, LE_CAB, FTL_1, FTL_TILE, FQW_1, FQW_TILE, TSTAR_TILE, TSTAR_TILE_CAB, TSTAR_CAB, SMCL_CAB, TSOIL_CAB, SURF_HTF_CAB, SURF_HT_FLUX_LAND, ECAN_TILE, ESOIL_TILE, EI_TILE, RADNET_TILE, TOT_ALB, SNAGE_TILE, CANOPY_TILE, GS, GS_TILE, T1P5M_TILE, Q1P5M_TILE, CANOPY_GB, FLAND, MELT_TILE, DIM_CS1, DIM_CS2, NPP, NPP_FT, GPP, GPP_FT, RESP_S, RESP_S_TOT, RESP_S_TILE, RESP_P, RESP_P_FT, G_LEAF, TRANSP_TILE, CPOOL_TILE, NPOOL_TILE, PPOOL_TILE, GLAI, PHENPHASE, NPP_FT_ACC, RESP_W_FT_ACC, RESP_S_ACC, FNSNET, FNLEACH, FNUP, FNLOSS, FNDEP, FNFIX, idoy)
Uses
cable_um_tech_mod
cable_um_init_subrs_mod
cable_data_module
sumcflux_mod
cable_cbm_module
casa_um_inout_mod
phenvariable
bgcdriver_mod
casavariable
casa_types_mod
cable_def_types_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, DIMENSION(um1%ROW_LENGTH,um1%ROWS) :: LS_RAIN
real, DIMENSION(um1%ROW_LENGTH,um1%ROWS) :: CON_RAIN
real, DIMENSION(um1%ROW_LENGTH,um1%ROWS) :: LS_SNOW
real, DIMENSION(um1%ROW_LENGTH,um1%ROWS) :: CONV_SNOW
real, DIMENSION(um1%ROW_LENGTH,um1%ROWS) :: DTL_1
real, DIMENSION(um1%ROW_LENGTH,um1%ROWS) :: DQW_1
real, dimension(um1%land_pts,um1%sm_levels) :: TSOIL
real, dimension(um1%land_pts,um1%ntiles,um1%sm_levels) :: TSOIL_TILE
real, dimension(um1%land_pts,um1%sm_levels) :: SMCL
real, dimension(um1%land_pts,um1%ntiles,um1%sm_levels) :: SMCL_TILE
real :: timestep
real, DIMENSION(um1%land_pts) :: SMVCST
real, dimension(um1%land_pts,um1%sm_levels) :: STHF
real, dimension(um1%land_pts,um1%ntiles,um1%sm_levels) :: STHF_TILE
real, dimension(um1%land_pts,um1%sm_levels) :: STHU
real, dimension(um1%land_pts,um1%ntiles,um1%sm_levels) :: STHU_TILE
real, DIMENSION(um1%land_pts,um1%ntiles) :: SNOW_TILE
real, DIMENSION(um1%land_pts,um1%ntiles) :: SNOW_RHO1L
integer :: ISNOW_FLG3L(um1%LAND_PTS,um1%NTILES)
real, dimension(um1%land_pts,um1%ntiles,3) :: SNOW_DEPTH3L
real, dimension(um1%land_pts,um1%ntiles,3) :: SNOW_MASS3L
real, dimension(um1%land_pts,um1%ntiles,3) :: SNOW_RHO3L
real, dimension(um1%land_pts,um1%ntiles,3) :: SNOW_TMP3L
real, dimension(um1%land_pts,um1%ntiles,3) :: SNOW_COND
real, DIMENSION(um1%land_pts,um1%ntiles) :: FTL_TILE_CAB
real, DIMENSION(um1%land_pts) :: FTL_CAB
real, DIMENSION(um1%land_pts,um1%ntiles) :: LE_TILE_CAB
real, DIMENSION(um1%land_pts) :: LE_CAB
real, DIMENSION(um1%ROW_LENGTH,um1%ROWS) :: FTL_1
real, DIMENSION(um1%land_pts,um1%ntiles) :: FTL_TILE
real, DIMENSION(um1%ROW_LENGTH,um1%ROWS) :: FQW_1
real, DIMENSION(um1%land_pts,um1%ntiles) :: FQW_TILE
real, DIMENSION(um1%land_pts,um1%ntiles) :: TSTAR_TILE
real, DIMENSION(um1%land_pts,um1%ntiles) :: TSTAR_TILE_CAB
real, DIMENSION(um1%land_pts) :: TSTAR_CAB
real, dimension(um1%land_pts,um1%sm_levels) :: SMCL_CAB
real, dimension(um1%land_pts,um1%sm_levels) :: TSOIL_CAB
real, DIMENSION(um1%land_pts) :: SURF_HTF_CAB
real, DIMENSION(um1%ROW_LENGTH,um1%ROWS) :: SURF_HT_FLUX_LAND
real, DIMENSION(um1%land_pts,um1%ntiles) :: ECAN_TILE
real, DIMENSION(um1%land_pts,um1%ntiles) :: ESOIL_TILE
real, DIMENSION(um1%land_pts,um1%ntiles) :: EI_TILE
real, DIMENSION(um1%land_pts,um1%ntiles) :: RADNET_TILE
real, DIMENSION(um1%land_pts,um1%ntiles) :: TOT_ALB
real, DIMENSION(um1%land_pts,um1%ntiles) :: SNAGE_TILE
real, DIMENSION(um1%land_pts,um1%ntiles) :: CANOPY_TILE
real, DIMENSION(um1%land_pts) :: GS
real, DIMENSION(um1%land_pts,um1%ntiles) :: GS_TILE
real, DIMENSION(um1%land_pts,um1%ntiles) :: T1P5M_TILE
real, DIMENSION(um1%land_pts,um1%ntiles) :: Q1P5M_TILE
real, DIMENSION(um1%land_pts) :: CANOPY_GB
real, DIMENSION(um1%land_pts) :: FLAND
real, DIMENSION(um1%land_pts,um1%ntiles) :: MELT_TILE
integer :: DIM_CS1
integer :: DIM_CS2
real, DIMENSION(um1%land_pts) :: NPP
real, DIMENSION(um1%land_pts,um1%ntiles) :: NPP_FT
real, DIMENSION(um1%land_pts) :: GPP
real, DIMENSION(um1%land_pts,um1%ntiles) :: GPP_FT
real :: RESP_S(um1%LAND_PTS,DIM_CS1)
real :: RESP_S_TOT(DIM_CS2)
real, DIMENSION(um1%land_pts,um1%ntiles) :: RESP_S_TILE
real, DIMENSION(um1%land_pts) :: RESP_P
real, DIMENSION(um1%land_pts,um1%ntiles) :: RESP_P_FT
real, DIMENSION(um1%land_pts,um1%ntiles) :: G_LEAF
real, DIMENSION(um1%land_pts,um1%ntiles) :: TRANSP_TILE
real, DIMENSION(um1%LAND_PTS,um1%NTILES,10) :: CPOOL_TILE
real, DIMENSION(um1%LAND_PTS,um1%NTILES,10) :: NPOOL_TILE
real, DIMENSION(um1%LAND_PTS,um1%NTILES,12) :: PPOOL_TILE
real, DIMENSION(um1%LAND_PTS,um1%NTILES) :: GLAI
real, DIMENSION(um1%LAND_PTS,um1%NTILES) :: PHENPHASE
real, DIMENSION(um1%LAND_PTS,um1%NTILES) :: NPP_FT_ACC
real, DIMENSION(um1%LAND_PTS,um1%NTILES) :: RESP_W_FT_ACC
real, DIMENSION(um1%LAND_PTS,um1%NTILES) :: RESP_S_ACC
real, DIMENSION(um1%land_pts,um1%ntiles) :: FNSNET
real, DIMENSION(um1%land_pts,um1%ntiles) :: FNLEACH
real, DIMENSION(um1%land_pts,um1%ntiles) :: FNUP
real, DIMENSION(um1%land_pts,um1%ntiles) :: FNLOSS
real, DIMENSION(um1%land_pts,um1%ntiles) :: FNDEP
real, DIMENSION(um1%land_pts,um1%ntiles) :: FNFIX
integer :: idoy
Calls
Contents
None
Call graph
cable_implicit_driver calls um2cable_rr, bgcdriver, sumcflux, implicit_unpack, cbm, casa_poolout_unpk
bgcdriver calls float, biogeochem
cbm calls snow_aging, define_canopy, soil_snow, define_air, point2constants, ruff_resist, fsunlit_mask, fveg_mask, fsunlit_veg_mask, init_radiation, albedo
casa_poolout_unpk calls unpack_cnppool
define_canopy calls define_air, ruff_resist, qsatfjh, surf_wetness_fact, radiation, comp_friction_vel, psis, psim, wetleaf, humidity_deficit_method, penman_monteith, dryleaf, within_canopy, latent_heat_flux, update_zetar
soil_snow calls snowcheck, snow_accum, stempv, snow_melting, remove_trans, surfbv, snowdensity, snowl_adjust, soilfreeze, hydraulic_redistribution
point2constants calls canopy_type_ptr, albedo_type_ptr, rad_type_ptr, carbon_type_ptr, air_type_ptr, cbm_type_ptr, ssnow_type_ptr, rough_type_ptr, driver_type_ptr
biogeochem calls casa_rplant, casa_ndummy, casa_delsoil, casa_nuptake, casa_xkn, casa_coeffplant, casa_xnp, phenology, casa_delplant, casa_cnpcycle, casa_cnpbal, casa_xratesoil, casa_coeffsoil, casa_allocation, casa_pdummy, casa_puptake, casa_xrateplant, casa_cnpflux, avgsoil
ruff_resist calls hgtabovesnow, lai_eff
albedo calls surface_albedosn
stempv calls total_soil_conductivity, trimb, old_soil_conductivity
comp_friction_vel calls psim
psis calls alog
psim calls alog
casa_nuptake calls casa_nrequire, 100
casa_xnp calls casa_nrequire, casa_prequire
casa_cnpcycle calls casa_poolzero
casa_cnpbal calls 100, 10
surfbv calls smoisturev
penman_monteith calls qsatfjh
dryleaf calls fwsoil_calc_lai_ktaul, fwsoil_calc_std, fwsoil_calc_non_linear, photosynthesis
within_canopy calls qsatfjh2
casa_puptake calls casa_prequire
smoisturev calls trimb