cable_explicit_driver – CABLE
cable_explicit_driver Subroutine
96 statements
Source File
subroutine cable_explicit_driver(row_length, rows, land_pts, ntiles, npft, sm_levels, timestep, latitude, longitude, land_index, tile_frac, tile_pts, tile_index, bexp, hcon, satcon, sathh, smvcst, smvcwt, smvccl, albsoil, snow_tile, snow_rho1l, snage_tile, isnow_flg3l, snow_rho3l, snow_cond, snow_depth3l, snow_tmp3l, snow_mass3l, sw_down, lw_down, cos_zenith_angle, surf_down_sw, ls_rain, ls_snow, tl_1, qw_1, vshr_land, pstar, z1_tq, z1_uv, rho_water, L_tile_pts, canopy_tile, fland, co2_mmr, CO2_3D, CO2_DIM_LEN, CO2_DIM_ROW, L_CO2_INTERACTIVE, sthu_tile, smcl_tile, sthf_tile, sthu, tsoil_tile, canht_ft, lai_ft, sin_theta_latitude, dzsoil, land_mask, FTL_TILE_CAB, FTL_CAB, FTL_TILE, FQW_TILE, LE_TILE_CAB, LE_CAB, TSTAR_TILE, TSTAR_TILE_CAB, TSTAR_CAB, U_S, U_S_STD_TILE, U_S_CAB, CH_CAB, CD_CAB, CD_TILE, CH_TILE, RADNET_TILE, FRACA, RESFS, RESFT, Z0H_TILE, Z0M_TILE, RECIP_L_MO_TILE, EPOT_TILE, CPOOL_TILE, NPOOL_TILE, PPOOL_TILE, SOIL_ORDER, NIDEP, NIFIX, PWEA, PDUST, GLAI, PHENPHASE, PREV_YR_SFRAC, WOOD_HVEST_C, WOOD_HVEST_N, WOOD_HVEST_P, WOOD_FLUX_C, WOOD_FLUX_N, WOOD_FLUX_P, WRESP_C, WRESP_N, WRESP_P, THINNING, NPP_FT_ACC, RESP_W_FT_ACC, RESP_S_ACC, iday, endstep, timestep_number, mype)
Uses
cable_um_tech_mod
cable_um_init_mod
cable_cbm_module
casa_um_inout_mod
feedback_mod
casavariable
casa_types_mod
cable_def_types_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: row_length
integer, intent(in) :: rows
integer, intent(in) :: land_pts
integer, intent(in) :: ntiles
integer, intent(in) :: npft
integer, intent(in) :: sm_levels
real, intent(in) :: timestep
real, intent(in), DIMENSION(row_length,rows) :: latitude
real, intent(in), DIMENSION(row_length,rows) :: longitude
integer, intent(in), DIMENSION(land_pts) :: land_index
real, intent(inout), DIMENSION(land_pts, ntiles) :: tile_frac
integer, intent(in), DIMENSION(ntiles) :: tile_pts
integer, intent(inout), DIMENSION(land_pts, ntiles) :: tile_index
real, intent(in), DIMENSION(land_pts) :: bexp
real, intent(in), DIMENSION(land_pts) :: hcon
real, intent(in), DIMENSION(land_pts) :: satcon
real, intent(in), DIMENSION(land_pts) :: sathh
real, intent(in), DIMENSION(land_pts) :: smvcst
real, intent(in), DIMENSION(land_pts) :: smvcwt
real, intent(in), DIMENSION(land_pts) :: smvccl
real, intent(in), DIMENSION(land_pts) :: albsoil
real, intent(inout), DIMENSION(land_pts, ntiles) :: snow_tile
real, intent(inout), DIMENSION(land_pts, ntiles) :: snow_rho1l
real, intent(inout), DIMENSION(land_pts, ntiles) :: snage_tile
integer, intent(inout), DIMENSION(land_pts, ntiles) :: isnow_flg3l
real, intent(inout), DIMENSION(land_pts, ntiles,3) :: snow_rho3l
real, intent(inout), DIMENSION(land_pts, ntiles,3) :: snow_cond
real, intent(inout), DIMENSION(land_pts, ntiles,3) :: snow_depth3l
real, intent(inout), DIMENSION(land_pts, ntiles,3) :: snow_tmp3l
real, intent(inout), DIMENSION(land_pts, ntiles,3) :: snow_mass3l
real, intent(inout), DIMENSION(row_length,rows) :: sw_down
real, intent(in), DIMENSION(row_length,rows) :: lw_down
real, intent(inout), DIMENSION(row_length,rows) :: cos_zenith_angle
real, intent(in), DIMENSION(row_length, rows, 4) :: surf_down_sw
real, intent(in), DIMENSION(row_length,rows) :: ls_rain
real, intent(in), DIMENSION(row_length,rows) :: ls_snow
real, intent(in), DIMENSION(row_length,rows) :: tl_1
real, intent(in), DIMENSION(row_length,rows) :: qw_1
real, intent(in), DIMENSION(row_length,rows) :: vshr_land
real, intent(in), DIMENSION(row_length,rows) :: pstar
real, intent(in), DIMENSION(row_length,rows) :: z1_tq
real, intent(in), DIMENSION(row_length,rows) :: z1_uv
real, intent(in) :: rho_water
logical, intent(inout), DIMENSION(land_pts, ntiles) :: L_tile_pts
real, intent(inout), DIMENSION(land_pts, ntiles) :: canopy_tile
real, intent(in), DIMENSION(land_pts) :: fland
real, intent(in) :: co2_mmr
real, intent(in) :: CO2_3D(CO2_DIM_LEN,CO2_DIM_ROW)
integer, intent(in) :: CO2_DIM_LEN
integer, intent(in) :: CO2_DIM_ROW
logical, intent(in) :: L_CO2_INTERACTIVE
real, intent(inout), DIMENSION(land_pts, ntiles, sm_levels) :: sthu_tile
real, intent(inout), DIMENSION(land_pts, ntiles, sm_levels) :: smcl_tile
real, intent(inout), DIMENSION(land_pts, ntiles, sm_levels) :: sthf_tile
real, intent(in), DIMENSION(land_pts, sm_levels) :: sthu
real, intent(inout), DIMENSION(land_pts, ntiles, sm_levels) :: tsoil_tile
real, intent(in), DIMENSION(land_pts, npft) :: canht_ft
real, intent(in), DIMENSION(land_pts, npft) :: lai_ft
real :: sin_theta_latitude(row_length,rows)
real, intent(in), DIMENSION(sm_levels) :: dzsoil
logical, DIMENSION(row_length,rows) :: land_mask
real, intent(out), DIMENSION(land_pts,ntiles) :: FTL_TILE_CAB
real, intent(out), DIMENSION(land_pts) :: FTL_CAB
real, intent(out), DIMENSION(land_pts,ntiles) :: FTL_TILE
real, intent(out), DIMENSION(land_pts,ntiles) :: FQW_TILE
real, intent(out), DIMENSION(land_pts,ntiles) :: LE_TILE_CAB
real, intent(out), DIMENSION(land_pts) :: LE_CAB
real, intent(out), DIMENSION(land_pts,ntiles) :: TSTAR_TILE
real, intent(out), DIMENSION(land_pts,ntiles) :: TSTAR_TILE_CAB
real, intent(out), DIMENSION(land_pts) :: TSTAR_CAB
real, intent(out), DIMENSION(row_length,rows) :: U_S
real, intent(out), DIMENSION(land_pts,ntiles) :: U_S_STD_TILE
real, intent(out), DIMENSION(land_pts) :: U_S_CAB
real, intent(out), DIMENSION(land_pts) :: CH_CAB
real, intent(out), DIMENSION(land_pts) :: CD_CAB
real, intent(out), DIMENSION(land_pts,ntiles) :: CD_TILE
real, intent(out), DIMENSION(land_pts,ntiles) :: CH_TILE
real, intent(out), DIMENSION(land_pts,ntiles) :: RADNET_TILE
real, intent(out), DIMENSION(land_pts,ntiles) :: FRACA
real, intent(out), DIMENSION(land_pts,ntiles) :: RESFS
real, intent(out), DIMENSION(land_pts,ntiles) :: RESFT
real, intent(out), DIMENSION(land_pts,ntiles) :: Z0H_TILE
real, intent(out), DIMENSION(land_pts,ntiles) :: Z0M_TILE
real, intent(out), DIMENSION(land_pts,ntiles) :: RECIP_L_MO_TILE
real, intent(out), DIMENSION(land_pts,ntiles) :: EPOT_TILE
real, intent(inout), DIMENSION(land_pts,ntiles,10) :: CPOOL_TILE
real, intent(inout), DIMENSION(land_pts,ntiles,10) :: NPOOL_TILE
real, intent(inout), DIMENSION(land_pts,ntiles,12) :: PPOOL_TILE
real, intent(inout), DIMENSION(land_pts) :: SOIL_ORDER
real, intent(inout), DIMENSION(land_pts) :: NIDEP
real, intent(inout), DIMENSION(land_pts) :: NIFIX
real, intent(inout), DIMENSION(land_pts) :: PWEA
real, intent(inout), DIMENSION(land_pts) :: PDUST
real, intent(inout), DIMENSION(land_pts,ntiles) :: GLAI
real, intent(inout), DIMENSION(land_pts,ntiles) :: PHENPHASE
real, intent(inout), DIMENSION(land_pts,ntiles) :: PREV_YR_SFRAC
real, intent(inout), DIMENSION(land_pts,ntiles,3) :: WOOD_HVEST_C
real, intent(inout), DIMENSION(land_pts,ntiles,3) :: WOOD_HVEST_N
real, intent(inout), DIMENSION(land_pts,ntiles,3) :: WOOD_HVEST_P
real, intent(inout), DIMENSION(land_pts,ntiles) :: WOOD_FLUX_C
real, intent(inout), DIMENSION(land_pts,ntiles) :: WOOD_FLUX_N
real, intent(inout), DIMENSION(land_pts,ntiles) :: WOOD_FLUX_P
real, intent(inout), DIMENSION(land_pts,ntiles,3) :: WRESP_C
real, intent(inout), DIMENSION(land_pts,ntiles,3) :: WRESP_N
real, intent(inout), DIMENSION(land_pts,ntiles,3) :: WRESP_P
real, intent(inout), DIMENSION(land_pts,ntiles) :: THINNING
real, intent(inout), DIMENSION(land_pts,ntiles) :: NPP_FT_ACC
real, intent(inout), DIMENSION(land_pts,ntiles) :: RESP_W_FT_ACC
real, intent(inout), DIMENSION(land_pts,ntiles) :: RESP_S_ACC
integer, intent(in) :: iday
integer, intent(in) :: endstep
integer, intent(in) :: timestep_number
integer, intent(in) :: mype
Calls
Contents
None
Call graph
cable_explicit_driver calls cable_um_runtime_vars, redistr_luc, interface_um_data, casa_feedback, cbm, cable_expl_unpack
cable_um_runtime_vars calls check_nmlvar
interface_um_data calls initialize_roughness, initialize_soilsnow, init_casacnp, init_respiration, alloc_cable_types, initialize_veg, initialize_soil, initialize_radiation, initialize_canopy, casa_ndep_pk, alloc_um_interface_types, cable_soil_params, cable_pft_params, init_bgc_vars, init_sumflux_zero
cbm calls define_canopy, soil_snow, point2constants, fsunlit_veg_mask, albedo, fsunlit_mask, ruff_resist, define_air, fveg_mask, snow_aging, init_radiation
define_canopy calls ruff_resist, define_air, qsatfjh, surf_wetness_fact, radiation, comp_friction_vel, psis, psim, wetleaf, humidity_deficit_method, penman_monteith, dryleaf, within_canopy, latent_heat_flux, update_zetar
soil_snow calls snowcheck, snow_accum, stempv, snow_melting, remove_trans, surfbv, snowdensity, snowl_adjust, soilfreeze, hydraulic_redistribution
initialize_roughness calls um2cable_rr
initialize_soilsnow calls um2cable_lp
point2constants calls canopy_type_ptr, albedo_type_ptr, rad_type_ptr, carbon_type_ptr, air_type_ptr, cbm_type_ptr, ssnow_type_ptr, rough_type_ptr, driver_type_ptr
check_nmlvar calls check_lgvar, check_chvar, check_intvar
init_casacnp calls casa_init_pk, alloc_casavariable, casa_readpoint_pk, casa_readphen, alloc_phenvariable, casa_readbiome
alloc_cable_types calls alloc_soil_snow_type, allocate_soil_parameter_type, allocate_veg_parameter_type, alloc_cbm_var, alloc_canopy_type
initialize_veg calls init_veg_pars_fr_vegin, limit_hgt_lai
initialize_soil calls um2cable_lp
albedo calls surface_albedosn
ruff_resist calls hgtabovesnow, lai_eff
initialize_radiation calls um2cable_rr, update_kblum_radiation, um2cable_met_rad
casa_ndep_pk calls um2cable_lp
init_veg_pars_fr_vegin calls init_veg_from_vegin
stempv calls total_soil_conductivity, trimb, old_soil_conductivity
comp_friction_vel calls psim
psis calls alog
psim calls alog
casa_init_pk calls casa_reinit_pk, pack_cnppool
casa_readpoint_pk calls um2cable_rr, um2cable_lp, um2cable_ilp
surfbv calls smoisturev
penman_monteith calls qsatfjh
dryleaf calls fwsoil_calc_lai_ktaul, fwsoil_calc_std, photosynthesis, fwsoil_calc_non_linear
within_canopy calls qsatfjh2
um2cable_met_rad calls um2cable_rr
alloc_cbm_var calls alloc_air_type, alloc_radiation_type, alloc_sum_flux_type, alloc_roughness_type, alloc_met_type, alloc_balances_type
smoisturev calls trimb
casa_reinit_pk calls casa_feedback, pack_cnppool, newplant, newsoil, newlitter, newlitter_thin