CanopyReflectance_beam – CABLE
CanopyReflectance_beam Subroutine
16 statements
Source File
private subroutine CanopyReflectance_beam(CanopyRefl_beam, mp, nrb, sunlit_veg_mask, ExtCoeff_beam, ExtCoeff_dif, rhoch)
Arguments
Type Intent Optional Attributes Name
real :: CanopyRefl_beam(mp,nrb)
integer :: mp
integer :: nrb
logical :: sunlit_veg_mask(mp)
real :: ExtCoeff_beam(mp)
real :: ExtCoeff_dif(mp)
real :: rhoch(mp,nrb)
Called by
Contents
Call graph
canopyreflectance calls canopyreflectance_beam
albedo calls canopyreflectance
cbm calls albedo
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker