casa_readbiome – CABLE
casa_readbiome Subroutine
247 statements
Source File
public subroutine casa_readbiome(veg, soil, casabiome, casapool, casaflux, casamet, phen)
Uses
casaparm
phenvariable
casadimension
casavariable
cable_def_types_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(phen_variable), intent(inout) :: phen
Called by
Contents
None
Call graph
load_parameters calls casa_readbiome
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master