casa_rplant – CABLE
casa_rplant Subroutine
107 statements
Source File
public subroutine casa_rplant(veg, casabiome, casapool, casaflux, casamet, climate)
Uses
casa_cnp_module
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(climate_type), intent(in) :: climate
Calls
Called by
Contents
Call graph
casa_rplant calls vcmax_np
biogeochem calls casa_rplant
casaonly_luc calls biogeochem
worker_spincasacnp calls biogeochem
worker_casaonly_luc calls biogeochem
bgcdriver calls biogeochem
spincasacnp calls biogeochem
cable_offline_driver calls casaonly_luc, bgcdriver, spincasacnp
mpidrv_worker calls worker_spincasacnp, worker_casaonly_luc, bgcdriver
mpi_driver calls mpidrv_worker