casa_poolout – CABLE
casa_poolout Subroutine
91 statements
Source File
public subroutine casa_poolout(ktau, veg, soil, casabiome, casapool, casaflux, casamet, casabal, phen)
Uses
casaparm
phenvariable
casadimension
casavariable
cable_def_types_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
type(veg_parameter_type), intent(inout) :: veg
type(soil_parameter_type), intent(inout) :: soil
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(casa_balance), intent(inout) :: casabal
type(phen_variable), intent(inout) :: phen
Calls
Contents
None
Call graph
casa_poolout calls 5, 2, 100