casa_reinit_pk – CABLE
casa_reinit_pk Subroutine
266 statements
Source File
public subroutine casa_reinit_pk(casabiome, casamet, casapool, casabal, veg, phen, cpool_tile, npool_tile, ppool_tile, woodhvest_c, woodhvest_n, woodhvest_p, logc, logn, logp, wresp_c, wresp_n, wresp_p, thinning, GLAI, PHENPHASE, PREV_YR_SFRAC)
Uses
cable_def_types_mod
cable_common_module
casadimension
casaparm
cable_um_tech_mod
phenvariable
casavariable
!! DEBUG START !!!
!! DEBUG END !!!!!
Re-calculate soil C, N, P pools
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(in) :: casabiome
type(casa_met), intent(inout) :: casamet
type(casa_pool), intent(inout) :: casapool
type(casa_balance), intent(inout) :: casabal
type(veg_parameter_type), intent(inout) :: veg
type(phen_variable), intent(inout) :: phen
real, intent(inout) :: cpool_tile(um1%land_pts,um1%ntiles,10)
real, intent(inout) :: npool_tile(um1%land_pts,um1%ntiles,10)
real, intent(inout) :: ppool_tile(um1%land_pts,um1%ntiles,12)
real(kind=r_2) :: woodhvest_c(um1%land_pts,um1%ntiles,3)
real(kind=r_2) :: woodhvest_n(um1%land_pts,um1%ntiles,3)
real(kind=r_2) :: woodhvest_p(um1%land_pts,um1%ntiles,3)
real(kind=r_2) :: logc(um1%land_pts,um1%ntiles)
real(kind=r_2) :: logn(um1%land_pts,um1%ntiles)
real(kind=r_2) :: logp(um1%land_pts,um1%ntiles)
real(kind=r_2) :: wresp_c(um1%land_pts,um1%ntiles,3)
real(kind=r_2) :: wresp_n(um1%land_pts,um1%ntiles,3)
real(kind=r_2) :: wresp_p(um1%land_pts,um1%ntiles,3)
real(kind=r_2) :: thinning(um1%land_pts,um1%ntiles)
real, intent(inout) :: GLAI(um1%land_pts,um1%ntiles)
real, intent(inout) :: PHENPHASE(um1%land_pts,um1%ntiles)
real, intent(inout) :: PREV_YR_SFRAC(um1%land_pts,um1%ntiles)
Calls
Called by
Contents
None
Call graph
casa_reinit_pk calls newplant, pack_cnppool, newsoil, newlitter_thin, newlitter, casa_feedback
casa_init_pk calls casa_reinit_pk
init_casacnp calls casa_init_pk
interface_um_data calls init_casacnp
cable_explicit_driver calls interface_um_data