casa_coeffplant – CABLE
casa_coeffplant Subroutine
30 statements
Source File
public subroutine casa_coeffplant(xkleafcold, xkleafdry, xkleaf, veg, casabiome, casapool, casaflux, casamet, phen)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(mp) :: xkleafcold
real(kind=r_2), intent(in), DIMENSION(mp) :: xkleafdry
real(kind=r_2), intent(in), DIMENSION(mp) :: xkleaf
type(veg_parameter_type), intent(inout) :: veg
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_met), intent(inout) :: casamet
type(phen_variable), intent(in) :: phen
Called by
Contents
Call graph
biogeochem calls casa_coeffplant
spincasacnp calls biogeochem
casaonly_luc calls biogeochem
worker_casaonly_luc calls biogeochem
bgcdriver calls biogeochem
worker_spincasacnp calls biogeochem
cable_offline_driver calls spincasacnp, casaonly_luc, bgcdriver
mpidrv_worker calls worker_casaonly_luc, bgcdriver, worker_spincasacnp
mpi_driver calls mpidrv_worker