cbm – CABLE
cbm Subroutine
76 statements
Source File
public subroutine cbm(ktau, dels, air, bgc, canopy, met, bal, rad, rough, soil, ssnow, sum_flux, veg, climate, xk, c1, rhoch)
Uses
cbl_albedo_mod
cable_phys_constants_mod
cable_canopy_module
snow_aging_mod
cable_air_module
cbl_masks_mod
cable_roughness_module
cable_math_constants_mod
cable_carbon_module
cable_def_types_mod
casadimension
cable_gw_hydro_module
cbl_init_radiation_module
sli_main_mod
cable_other_constants_mod
cbl_soil_snow_main_module
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
real, intent(in) :: dels
type(air_type), intent(inout) :: air
type(bgc_pool_type), intent(inout) :: bgc
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(balances_type), intent(inout) :: bal
type(radiation_type), intent(inout) :: rad
type(roughness_type), intent(inout) :: rough
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(sum_flux_type), intent(inout) :: sum_flux
type(veg_parameter_type), intent(inout) :: veg
type(climate_type), intent(in) :: climate
real :: xk(mp,nrb)
real :: c1(mp,nrb)
real :: rhoch(mp,nrb)
Calls
Contents
None
Call graph
cbm calls soil_snow, soilcarb, define_air, fsunlit_veg_mask, ruff_resist, fsunlit_mask, fveg_mask, init_radiation, snow_aging, albedo, define_canopy, plantcarb, carbon_pl
soil_snow calls snowcheck, snow_accum, snow_melting, stempv, remove_trans, surfbv, snowl_adjust, snowdensity, soilfreeze, hydraulic_redistribution
ruff_resist calls hgtabovesnow, lai_eff
albedo calls surface_albedosn
define_canopy calls define_air, ruff_resist, wetleaf, qsatfjh, comp_friction_vel, surf_wetness_fact, radiation, update_zetar, psis, humidity_deficit_method, penman_monteith, dryleaf, within_canopy, latent_heat_flux, psim
comp_friction_vel calls psim
stempv calls total_soil_conductivity, trimb, old_soil_conductivity
surfbv calls smoisturev
psis calls alog
penman_monteith calls qsatfjh
dryleaf calls fwsoil_calc_std, fwsoil_calc_lai_ktaul, fwsoil_calc_non_linear, photosynthesis
within_canopy calls qsatfjh2
psim calls alog
smoisturev calls trimb