climate_init – CABLE
climate_init Subroutine
37 statements
Source File
public subroutine climate_init(climate, np, ktauday)
Arguments
Type Intent Optional Attributes Name
type(climate_type), intent(inout) :: climate
integer, intent(in) :: np
integer, intent(in) :: ktauday
Calls
Called by
Contents
None
Call graph
climate_init calls alloc_cbm_var, read_climate_restart_nc
alloc_cbm_var calls alloc_veg_parameter_type, alloc_soil_snow_type, alloc_balances_type, alloc_radiation_type, alloc_roughness_type, alloc_air_type, alloc_met_type, alloc_bgc_pool_type, alloc_climate_type, alloc_canopy_type, alloc_soil_parameter_type, alloc_sum_flux_type
read_climate_restart_nc calls nf90_inq_varid, nf90_close, nf90_open, nf90_get_var, handle_err, nf90_inquire_dimension, nf90_inq_dimid
handle_err calls nf90_strerror
master_climate_types calls climate_init
cable_offline_driver calls climate_init
worker_climate_types calls climate_init
mpidrv_master calls master_climate_types
mpidrv_worker calls worker_climate_types
mpi_driver calls mpidrv_master, mpidrv_worker