create_layer – CABLE
create_layer Subroutine
65 statements
Source File
public subroutine create_layer(layer_t, comm)
Uses
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: layer_t
integer, intent(in) :: comm
Calls
Called by
Contents
Call graph
create_layer calls create_cohort, mpi_get_address, mpi_type_create_struct, mpi_abort, mpi_type_commit, mpi_type_create_resized
create_cohort calls mpi_get_address, mpi_type_create_struct, mpi_abort, mpi_type_commit, mpi_type_create_resized
create_patch calls create_layer
create_pop_gridcell_type calls create_patch
worker_pop_types calls create_pop_gridcell_type
master_pop_types calls create_pop_gridcell_type
mpidrv_worker calls worker_pop_types
mpidrv_master calls master_pop_types
mpi_driver calls mpidrv_worker, mpidrv_master