CRU_GET_FILENAME – CABLE
CRU_GET_FILENAME Subroutine
33 statements
Source File
public subroutine CRU_GET_FILENAME(CRU, cyear, par, FN)
Arguments
Type Intent Optional Attributes Name
type(CRU_TYPE), intent(inout) :: CRU
integer, intent(in) :: cyear
integer, intent(in) :: par
character(len=200), intent(out) :: FN
Called by
Contents
None
Call graph
open_cru_met calls cru_get_filename
cru_get_daily_met calls cru_get_filename
cru_get_subdiurnal_met calls open_cru_met, cru_get_daily_met
mpidrv_master calls cru_get_subdiurnal_met
cable_offline_driver calls cru_get_subdiurnal_met
mpi_driver calls mpidrv_master