dthetalmaxdT – CABLE
dthetalmaxdT Function
14 statements
Source File
public pure elemental function dthetalmaxdT(Tin, S, he, b, thre, the)
Uses
sli_numbers
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: Tin
real(kind=r_2), intent(in) :: S
real(kind=r_2), intent(in) :: he
real(kind=r_2), intent(in) :: b
real(kind=r_2), intent(in) :: thre
real(kind=r_2), intent(in) :: the
Return Value real(kind=r_2)
Calls
Called by
Contents
Call graph
dthetalmaxdt calls tfrz
hyofs calls dthetalmaxdt
iflux_loop calls hyofs
solve calls hyofs, timestep_loop
sli_main calls hyofs, solve
timestep_loop calls iflux_loop