EffectiveExtinctCoeff – CABLE
EffectiveExtinctCoeff Subroutine
18 statements
Source File
private subroutine EffectiveExtinctCoeff(Eff_ExtCoeff, mp, ExtCoeff, c1, mask)
Arguments
Type Intent Optional Attributes Name
real :: Eff_ExtCoeff(mp,2)
integer :: mp
real :: ExtCoeff(mp)
real :: c1(mp,2)
logical, optional :: mask(mp)
Called by
Contents
Call graph
effectiveextinctcoeffs calls effectiveextinctcoeff
init_radiation calls effectiveextinctcoeffs
cbm calls init_radiation
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker