Exponential – CABLE
Exponential Function
10 statements
Source File
public function Exponential(lambda, x)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: lambda
integer(kind=i4b), intent(in) :: x
Return Value real(kind=dp)
Called by
Contents
Call graph
initpop2d_poisson calls exponential
pop_init_single calls initpop2d_poisson
pop_init calls initpop2d_poisson
casaonly_luc calls pop_init_single
popluc_init calls pop_init_single
lucdriver calls pop_init_single
master_casaonly_luc calls pop_init_single
worker_pop_types calls pop_init
load_parameters calls pop_init, popluc_init
cable_offline_driver calls casaonly_luc, lucdriver, load_parameters
mpidrv_worker calls worker_pop_types
mpidrv_master calls master_casaonly_luc, lucdriver, load_parameters
mpi_driver calls mpidrv_worker, mpidrv_master