find_metvarid – CABLE
find_metvarid Subroutine
13 statements
Source File
public subroutine find_metvarid(file_id, possible_names, varid, status)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: file_id
character(len=*), intent(in), DIMENSION(:) :: possible_names
integer, intent(out) :: varid
integer, intent(out) :: status
Calls
Called by
Contents
None
Call graph
find_metvarid calls nf90_inq_varid
open_met_file calls find_metvarid
mpidrv_master calls open_met_file
cable_offline_driver calls open_met_file
mpi_driver calls mpidrv_master