flux – CABLE
flux Subroutine
38 statements
Source File
public pure elemental subroutine flux(parin, v1, v2, dz, q, qya, qyb, qTa, qTb)
Arguments
Type Intent Optional Attributes Name
type(params), intent(in) :: parin
type(vars), intent(in) :: v1
type(vars), intent(in) :: v2
real(kind=r_2), intent(in) :: dz
real(kind=r_2), intent(out) :: q
real(kind=r_2), intent(out) :: qya
real(kind=r_2), intent(out) :: qyb
real(kind=r_2), intent(out) :: qTa
real(kind=r_2), intent(out) :: qTb
Calls
Called by
Contents
Call graph
flux calls weight
weight calls hyofh
getfluxes_vp_1d calls flux
getfluxes_vp_2d calls flux
get_fluxes_and_derivs calls flux, getfluxes_vp
getfluxes_vp calls getfluxes_vp_1d, getfluxes_vp_2d
iflux_loop calls get_fluxes_and_derivs
timestep_loop calls iflux_loop
solve calls timestep_loop
sli_main calls solve