get_var_ncr3 – CABLE
get_var_ncr3 Subroutine
15 statements
Source File
public subroutine get_var_ncr3(ncid, var_name, var, n_call, nl)
Uses
cable_def_types_mod
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: var_name
real(kind=r_2), intent(out), dimension(:,:) :: var
integer, intent(in) :: n_call
integer, intent(in) :: nl
Calls
Called by
Contents
None
Call graph
get_var_ncr3 calls nf90_inq_varid, stderr_nc, nf90_get_var
stderr_nc calls nf90_strerror
read_casa_dump calls get_var_ncr3
get_var_nc calls get_var_ncr3
casaonly_luc calls read_casa_dump
spincasacnp calls read_casa_dump
master_spincasacnp calls read_casa_dump
master_casaonly_luc calls read_casa_dump
cable_offline_driver calls read_casa_dump, casaonly_luc, spincasacnp
mpidrv_master calls master_spincasacnp, master_casaonly_luc
mpi_driver calls mpidrv_master