GetHeight – CABLE
GetHeight Function
34 statements
Source File
public function GetHeight(precip, biomass, density)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: precip
real(kind=dp), intent(in) :: biomass
real(kind=dp), intent(in) :: density
Return Value real(kind=dp)
Called by
Contents
None
Call graph
get_allometry calls getheight
layer_recruitment_single_patch calls get_allometry
patchannualdynamics calls get_allometry, layer_recruitment
getdiagnostics calls get_allometry
layer_recruitment calls get_allometry
pop_init_single calls layer_recruitment_single_patch
pop_init calls layer_recruitment_single_patch
popstep calls patchannualdynamics, getdiagnostics, patch_disturb
patch_disturb calls layer_recruitment_single_patch
lucdriver calls pop_init_single
popluc_init calls pop_init_single
load_parameters calls pop_init, popluc_init
casaonly_luc calls pop_init_single, popdriver
popdriver calls popstep
cable_offline_driver calls lucdriver, load_parameters, casaonly_luc, popdriver, spincasacnp
mpidrv_master calls load_parameters
mpidrv_worker calls popdriver
spincasacnp calls popdriver
mpi_driver calls mpidrv_master, mpidrv_worker