GWstempv – CABLE
GWstempv Subroutine
113 statements
Source File
public subroutine GWstempv(dels, canopy, ssnow, soil)
Uses
cable_common_module
trimb_mod
total_soil_conductivity_mod
old_soil_conductivity_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(canopy_type), intent(inout) :: canopy
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
Calls
Called by
Contents
None
Call graph
gwstempv calls total_soil_conductivity, trimb, old_soil_conductivity
snow_processes_soil_thermal calls gwstempv
soil_snow_gw calls snow_processes_soil_thermal