HANDLE_ERR – CABLE
HANDLE_ERR Subroutine
11 statements
Source File
public subroutine HANDLE_ERR(status, msg)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
integer :: status
character(len=*), intent(in), optional :: msg
Calls
Called by
Contents
None
Call graph
handle_err calls nf90_strerror
cru_init calls handle_err
plume_mip_get_met calls handle_err, open_plume_met, plume_get_daily_met
open_cru_met calls handle_err
write_climate_restart_nc calls handle_err
load_parameters calls handle_err, pop_io, popluc_init, casa_init
read_luc_restart_nc calls handle_err
open_plume_met calls handle_err
write_landuse_casa_restart_nc calls handle_err
read_luh2 calls handle_err
write_luc_output_grid_nc calls handle_err
read_climatefile calls handle_err
read_climate_restart_nc calls handle_err
write_luc_restart_nc calls handle_err
plume_mip_init calls handle_err
read_casa_restart_nc calls handle_err
pop_io calls handle_err
open_met_file calls handle_err
plume_get_daily_met calls handle_err
write_casa_output_nc calls handle_err
luc_expt_init calls handle_err, read_climatefile
write_luc_output_nc calls handle_err
get_cru_ndep calls handle_err
cru_get_daily_met calls handle_err
cru_get_subdiurnal_met calls handle_err, open_cru_met, get_cru_ndep, cru_get_daily_met
write_casa_restart_nc calls handle_err
master_spincasacnp calls pop_io, write_casa_restart_nc
mpidrv_master calls cru_init, plume_mip_get_met, write_climate_restart_nc, load_parameters, write_landuse_casa_restart_nc, write_luc_output_grid_nc, write_luc_restart_nc, plume_mip_init, pop_io, open_met_file, write_casa_output_nc, luc_expt_init, write_luc_output_nc, cru_get_subdiurnal_met, write_casa_restart_nc, master_spincasacnp, lucdriver, master_casaonly_luc, master_climate_types
cable_offline_driver calls cru_init, plume_mip_get_met, write_climate_restart_nc, load_parameters, write_landuse_casa_restart_nc, read_climate_restart_nc, write_luc_restart_nc, plume_mip_init, pop_io, open_met_file, write_casa_output_nc, luc_expt_init, write_luc_output_nc, cru_get_subdiurnal_met, write_casa_restart_nc, lucdriver, casaonly_luc, climate_init
popluc_init calls read_luc_restart_nc
lucdriver calls read_luh2
casaonly_luc calls read_luh2, write_luc_output_grid_nc, write_luc_restart_nc, pop_io, write_casa_output_nc
master_casaonly_luc calls read_luh2, write_luc_output_grid_nc, write_luc_restart_nc, pop_io, write_luc_output_nc, write_casa_restart_nc
climate_init calls read_climate_restart_nc
master_climate_types calls read_climate_restart_nc, climate_init
casa_init calls read_casa_restart_nc
mpi_driver calls mpidrv_master, mpidrv_worker
worker_climate_types calls climate_init
mpidrv_worker calls worker_climate_types