hyofS – CABLE
hyofS Subroutine
177 statements
Source File
public pure elemental subroutine hyofS(S, Tsoil, parin, var)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in) :: S
real(kind=r_2), intent(in) :: Tsoil
type(params), intent(inout) :: parin
type(vars), intent(inout) :: var
Calls
Called by
Contents
None
Call graph
hyofs calls tfrz, dthetalmaxdt, slope_esat, igamma
dthetalmaxdt calls tfrz
igamma calls gammln, gcf, gser
gcf calls gammln
gser calls gammln
iflux_loop calls hyofs
sli_main calls hyofs, solve
solve calls hyofs, timestep_loop
timestep_loop calls iflux_loop