init_radiation – CABLE
init_radiation Subroutine
49 statements
Source File
public subroutine init_radiation(ExtCoeff_beam, ExtCoeff_dif, EffExtCoeff_beam, EffExtCoeff_dif, RadFbeam, c1, rhoch, xk, mp, nrb, Clai_thresh, Ccoszen_tols, Cgauss_w, Cpi, Cpi180, cbl_standalone, jls_standalone, jls_radiation, subr_name, veg_mask, sunlit_mask, sunlit_veg_mask, VegXfang, VegTaul, VegRefl, coszen, metDoY, SW_down, reducedLAIdue2snow)
Arguments
Type Intent Optional Attributes Name
real :: ExtCoeff_beam(mp)
real :: ExtCoeff_dif(mp)
real :: EffExtCoeff_beam(mp,nrb)
real :: EffExtCoeff_dif(mp,nrb)
real :: RadFbeam(mp,nrb)
real :: c1(mp,nrb)
real :: rhoch(mp,nrb)
real :: xk(mp,nrb)
integer :: mp
integer :: nrb
real :: Clai_thresh
real :: Ccoszen_tols
real :: Cgauss_w(nrb)
real :: Cpi
real :: Cpi180
logical :: cbl_standalone
logical :: jls_standalone
logical :: jls_radiation
character(len=*) :: subr_name
logical :: veg_mask(mp)
logical :: sunlit_mask(mp)
logical :: sunlit_veg_mask(mp)
real :: VegXfang(mp)
real :: VegTaul(mp,nrb)
real :: VegRefl(mp,nrb)
real :: coszen(mp)
integer :: metDoY(mp)
real :: SW_down(mp,nrb)
real :: reducedLAIdue2snow(mp)
Calls
Called by
Contents
Call graph
init_radiation calls common_initrad_scalings, beamfraction, extinctioncoeff, effectiveextinctcoeffs
common_initrad_scalings calls common_initrad_coeffs, calc_rhoch
beamfraction calls spitter
extinctioncoeff calls extinctioncoeff_dif, extinctioncoeff_beam
effectiveextinctcoeffs calls effectiveextinctcoeff
cbm calls init_radiation
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker