initialize_roughness – CABLE
initialize_roughness Subroutine
31 statements
Source File
public subroutine initialize_roughness(z1_tq, z1_uv, htveg)
Uses
cable_um_tech_mod
cable_def_types_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
real, intent(in), DIMENSION(um1%row_length, um1%rows) :: z1_tq
real, intent(in), DIMENSION(um1%row_length, um1%rows) :: z1_uv
real, intent(inout), DIMENSION(um1%land_pts, um1%ntiles) :: htveg
Calls
Called by
Contents
None
Call graph
initialize_roughness calls um2cable_rr
interface_um_data calls initialize_roughness
cable_explicit_driver calls interface_um_data