init_veg_from_vegin – CABLE
init_veg_from_vegin Subroutine
60 statements
Source File
public subroutine init_veg_from_vegin(ifmp, fmp, veg, soil_zse)
Uses
cable_def_types_mod
cable_params_mod
Arguments
Type Intent Optional Attributes Name
integer :: ifmp
integer :: fmp
type(veg_parameter_type) :: veg
real, dimension(ms) :: soil_zse
Called by
Contents
None
Call graph
init_veg_pars_fr_vegin calls init_veg_from_vegin
initialize_veg calls init_veg_pars_fr_vegin
interface_um_data calls initialize_veg
cable_explicit_driver calls interface_um_data