INTERPOLATE_BIOMASS_1D – CABLE
INTERPOLATE_BIOMASS_1D Subroutine
177 statements
Source File
public subroutine INTERPOLATE_BIOMASS_1D(POP, disturbance_interval, it, g)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: disturbance_interval(:,:)
integer(kind=i4b), intent(in) :: it
integer(kind=i4b), intent(in) :: g
Calls
Called by
Contents
Call graph
interpolate_biomass_1d calls realexponential
getdiagnostics calls interpolate_biomass_1d
popstep calls getdiagnostics
popdriver calls popstep
casaonly_luc calls popdriver
spincasacnp calls popdriver
worker_casaonly_luc calls popdriver
worker_spincasacnp calls popdriver
mpidrv_worker calls popdriver, worker_casaonly_luc, worker_spincasacnp
cable_offline_driver calls popdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker