LAI_eff – CABLE
LAI_eff Subroutine
11 statements
Source File
public subroutine LAI_eff(mp, LAI_PFT, Hgt_PFT, HgtAboveSnow, reducedLAIdue2snow)
Arguments
Type Intent Optional Attributes Name
integer :: mp
real :: LAI_PFT(mp)
real :: Hgt_PFT(mp)
real :: HgtAboveSnow(mp)
real :: reducedLAIdue2snow(mp)
Called by
Contents
None
Call graph
ruff_resist calls lai_eff
cbm calls ruff_resist, define_canopy
define_canopy calls ruff_resist
cable_implicit_driver calls cbm
mpidrv_worker calls cbm
cable_explicit_driver calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker