landuse_mp2land – CABLE
landuse_mp2land Subroutine
167 statements
Source File
subroutine landuse_mp2land(luc, lucmp, mp, cstart, cend)
Uses
landuse_variable
casadimension
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(landuse_mland) :: luc
type(landuse_mp) :: lucmp
integer :: mp
integer, dimension(mland) :: cstart
integer, dimension(mland) :: cend
Called by
Contents
Call graph
landuse_driver calls landuse_mp2land
mpidrv_master calls landuse_driver
cable_offline_driver calls landuse_driver
mpi_driver calls mpidrv_master