landuse_getdata – CABLE
landuse_getdata Subroutine
37 statements
Source File
subroutine landuse_getdata(mlat, mlon, landmask, fxpft, luc_atransit, luc_fharvw)
Uses
netcdf
cable_def_types_mod
landuse_constant
Arguments
Type Intent Optional Attributes Name
integer :: mlat
integer :: mlon
integer, dimension(mlon,mlat) :: landmask
character(len=500) :: fxpft
real(kind=r_2), dimension(mland,mvmax,mvmax) :: luc_atransit
real(kind=r_2), dimension(mland,mharvw) :: luc_fharvw
Calls
Called by
Contents
None
Call graph
landuse_getdata calls nf90_open, nf90_inq_varid, nf90_get_var, nf90_close
landuse_data calls landuse_getdata
mpidrv_master calls landuse_data
cable_offline_driver calls landuse_data
mpi_driver calls mpidrv_master