landuse_land2mpx – CABLE
landuse_land2mpx Subroutine
93 statements
Source File
subroutine landuse_land2mpx(luc, lucmp, mpx)
Uses
landuse_variable
landuse_constant
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(landuse_mland) :: luc
type(landuse_mp) :: lucmp
integer :: mpx
Called by
Contents
None
Call graph
landuse_driver calls landuse_land2mpx
mpidrv_master calls landuse_driver
cable_offline_driver calls landuse_driver
mpi_driver calls mpidrv_master