layer_recruitment – CABLE
layer_recruitment Subroutine
37 statements
Source File
public subroutine layer_recruitment(POP, precip)
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
real(kind=dp), intent(in), optional :: precip(:)
Calls
Called by
Contents
None
Call graph
layer_recruitment calls get_allometry
get_allometry calls getheight, williams_allometry, allometry
patchannualdynamics calls layer_recruitment
popstep calls patchannualdynamics
popdriver calls popstep
casaonly_luc calls popdriver
spincasacnp calls popdriver
mpidrv_worker calls popdriver, worker_spincasacnp, worker_casaonly_luc
worker_spincasacnp calls popdriver
worker_casaonly_luc calls popdriver
cable_offline_driver calls popdriver, casaonly_luc, spincasacnp
mpi_driver calls mpidrv_worker