master_decomp – CABLE
master_decomp Subroutine
45 statements
Source File
private subroutine master_decomp(comm, mland, mp)
Uses
mpi
cable_IO_vars_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
integer, intent(in) :: mland
integer, intent(in) :: mp
Calls
Called by
Contents
Call graph
master_decomp calls mpi_comm_size, mpi_send, mpi_abort
mpidrv_master calls master_decomp
mpi_driver calls mpidrv_master