master_pop_types – CABLE
master_pop_types Subroutine
48 statements
Source File
private subroutine master_pop_types(comm, casamet, pop)
Uses
cable_common_module
POP_Types
casavariable
mpi
pop_mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(casa_met), intent(in) :: casamet
type(POP_TYPE), intent(inout) :: pop
Calls
Called by
Contents
None
Call graph
master_pop_types calls mpi_send, create_pop_gridcell_type
create_pop_gridcell_type calls create_patch, mpi_abort, mpi_get_address, mpi_type_create_struct, mpi_type_commit, mpi_type_create_resized
create_patch calls mpi_abort, mpi_get_address, mpi_type_create_struct, mpi_type_commit, mpi_type_create_resized, create_layer
create_layer calls mpi_abort, mpi_get_address, mpi_type_create_struct, mpi_type_commit, mpi_type_create_resized, create_cohort
create_cohort calls mpi_abort, mpi_get_address, mpi_type_create_struct, mpi_type_commit, mpi_type_create_resized
mpidrv_master calls master_pop_types
mpi_driver calls mpidrv_master