nc_abort – CABLE
nc_abort Subroutine
8 statements
Source File
public subroutine nc_abort(ok, message)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ok
character(len=*), intent(in) :: message
Calls
Called by
Contents
None
Call graph
nc_abort calls nf90_strerror
extrarestart calls nc_abort, readpar
close_output_file calls nc_abort
create_restart calls nc_abort, define_ovar, write_ovar
readpar_rd calls nc_abort
get_default_lai calls nc_abort
create_landuse_cable_restart calls nc_abort, define_ovar, write_ovar
create_new_gridinfo calls nc_abort
write_output_parameter_r2d calls nc_abort
define_output_variable_r1 calls nc_abort
write_output_variable_r1 calls nc_abort
write_output_parameter_r1 calls nc_abort
readpar_r calls nc_abort
readpar_r2 calls nc_abort
write_output_parameter_r2 calls nc_abort
spatialsoil calls nc_abort
get_met_data calls nc_abort
open_output_file calls nc_abort, define_ovar, write_ovar
write_output_parameter_r1d calls nc_abort
read_gridinfo calls nc_abort
load_parameters calls nc_abort, get_restart_data, get_default_params, get_parameters_met
get_restart_data calls nc_abort, extrarestart, readpar
open_met_file calls nc_abort
landuse_data calls nc_abort
define_output_variable_r2 calls nc_abort
write_output calls nc_abort, write_ovar
readpar_i calls nc_abort
close_met_file calls nc_abort
define_output_parameter_r1 calls nc_abort
read_soilcolor calls nc_abort
write_output_variable_r2 calls nc_abort
readpar_r2d calls nc_abort
define_output_parameter_r2 calls nc_abort
mpidrv_master calls close_output_file, create_restart, create_landuse_cable_restart, create_new_gridinfo, get_met_data, open_output_file, load_parameters, open_met_file, landuse_data, write_output, close_met_file
define_ovar calls define_output_variable_r1, define_output_variable_r2, define_output_parameter_r1, define_output_parameter_r2
write_ovar calls write_output_parameter_r2d, write_output_variable_r1, write_output_parameter_r1, write_output_parameter_r2, write_output_parameter_r1d, write_output_variable_r2
readpar calls readpar_rd, readpar_r, readpar_r2, readpar_i, readpar_r2d
cable_offline_driver calls close_output_file, create_restart, create_landuse_cable_restart, create_new_gridinfo, get_met_data, open_output_file, load_parameters, open_met_file, landuse_data, write_output, close_met_file
get_default_params calls spatialsoil, read_gridinfo, read_soilcolor
mpi_driver calls mpidrv_master
get_parameters_met calls readpar