newlitter_thin – CABLE
newlitter_thin Subroutine
76 statements
Source File
public subroutine newlitter_thin(casabiome, frac_x, ifpre_x, frac_y, ifpre_y, cplant_x, nplant_x, pplant_x, cplant_y, nplant_y, pplant_y, clitter_x, nlitter_x, plitter_x, clitter_y, nlitter_y, plitter_y, thinRatio)
Uses
cable_def_types_mod
casadimension
casaparm
casavariable
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(in) :: casabiome
real, intent(in), DIMENSION(mvtype) :: frac_x
logical, intent(in), DIMENSION(mvtype) :: ifpre_x
real, intent(in), DIMENSION(mvtype) :: frac_y
logical, intent(in), DIMENSION(mvtype) :: ifpre_y
real(kind=r_2), intent(in), DIMENSION(mvtype,mplant) :: cplant_x
real(kind=r_2), intent(in), DIMENSION(mvtype,mplant) :: nplant_x
real(kind=r_2), intent(in), DIMENSION(mvtype,mplant) :: pplant_x
real(kind=r_2), intent(inout), DIMENSION(mvtype,mplant) :: cplant_y
real(kind=r_2), intent(inout), DIMENSION(mvtype,mplant) :: nplant_y
real(kind=r_2), intent(inout), DIMENSION(mvtype,mplant) :: pplant_y
real(kind=r_2), intent(in), DIMENSION(mvtype,mlitter) :: clitter_x
real(kind=r_2), intent(in), DIMENSION(mvtype,mlitter) :: nlitter_x
real(kind=r_2), intent(in), DIMENSION(mvtype,mlitter) :: plitter_x
real(kind=r_2), intent(inout), DIMENSION(mvtype,mlitter) :: clitter_y
real(kind=r_2), intent(inout), DIMENSION(mvtype,mlitter) :: nlitter_y
real(kind=r_2), intent(inout), DIMENSION(mvtype,mlitter) :: plitter_y
real, intent(in), DIMENSION(mvtype) :: thinRatio
Called by
Contents
None
Call graph
casa_reinit_pk calls newlitter_thin
casa_init_pk calls casa_reinit_pk
init_casacnp calls casa_init_pk
interface_um_data calls init_casacnp
cable_explicit_driver calls interface_um_data