open_met_file – CABLE
open_met_file Subroutine
738 statements
Source File
public subroutine open_met_file(dels, koffset, kend, spinup, TFRZ)
Uses
casa_ncdf_module
cable_common_module
CABLE_METUTILS_MODULE
=====================VV Determine spatial details VV=================
=================^^ End spatial details ^^========================
=========VV Determine simulation timing details VV================
* gswp input file has bug in timevar *** hacking (BP feb2011)
  kend = 480  ! 2 months for 1986
end hacking * done bug fixing for timevar in gswp input file *
* PALS met file has timevar(1)=0 while timeunits from 00:30:00 * CLN CRITICAL! From my point of view, the information in the file is correct... CLN WHY DO the input files all have bugs??? done bug fixing for timevar in PALS met file ****
* gswp input file has bug in timeunits ** * done bug fixing for timeunits in gwsp file **** vh_js !! ===================^^ End timing details ^^==========================
===================VV Look for met variables VV====================== vh_js !! fixed bug in logic vh_js !! fixed bug in logic $ IF(metunits%LWdown(1:4)/='W/m2'.AND.metunits%LWdown(1:5) & $ /='W/m^2'.AND.metunits%LWdown(1:5)/='Wm^-2' & $ .AND.metunits%LWdown(1:4)/='Wm-2') THEN =================^^ End met variables search^^=======================
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: dels
integer, intent(inout) :: koffset
integer, intent(out) :: kend
logical, intent(in) :: spinup
real, intent(in) :: TFRZ
Calls
Called by
Contents
None
Call graph
open_met_file calls nf90_open, nf90_inquire_variable, nf90_inquire_dimension, nf90_get_var, nf90_inq_dimid, ymdhms2doysod, vegpatch_metfile, nc_abort, handle_err, find_metvarid, nf90_inq_varid, nf90_get_att, is_leapyear, doysod2ymdhms
ymdhms2doysod calls is_leapyear
nc_abort calls nf90_strerror
handle_err calls nf90_strerror
find_metvarid calls nf90_inq_varid
doysod2ymdhms calls is_leapyear
mpidrv_master calls open_met_file
cable_offline_driver calls open_met_file
mpi_driver calls mpidrv_master