open_file_per_node – CABLE
open_file_per_node Subroutine
25 statements
Source File
public subroutine open_file_per_node(iDiag, pDiag, dir, basename, node, fbasename)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
integer :: iDiag
integer :: pDiag
character(len=*) :: dir
character(len=*) :: basename
integer :: node
character(len=*), optional :: fbasename
Calls
Called by
Contents
None
Call graph
open_file_per_node calls open_idiag
fprint_fland calls open_file_per_node
cable_fprintf2 calls open_file_per_node
cable_iprintf1 calls open_file_per_node
cable_fprintf1 calls open_file_per_node
cable_fprintf3 calls open_file_per_node
cable_iprintf2 calls open_file_per_node
cable_lprintf2 calls open_file_per_node
cable_fprintf calls cable_fprintf2, cable_iprintf1, cable_fprintf1, cable_fprintf3, cable_iprintf2, cable_lprintf2