photosynthesis – CABLE
photosynthesis Subroutine
71 statements
Source File
public subroutine photosynthesis(csxz, cx1z, cx2z, gswminz, rdxz, vcmxt3z, vcmxt4z, vx3z, vx4z, gs_coeffz, vlaiz, deltlfz, anxz, fwsoilz)
Uses
cable_def_types_mod
cable_other_constants_mod
cable_photo_constants_mod
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(mp,mf) :: csxz
real, intent(in), DIMENSION(mp,mf) :: cx1z
real, intent(in), DIMENSION(mp,mf) :: cx2z
real, intent(in), DIMENSION(mp,mf) :: gswminz
real, intent(in), DIMENSION(mp,mf) :: rdxz
real, intent(in), DIMENSION(mp,mf) :: vcmxt3z
real, intent(in), DIMENSION(mp,mf) :: vcmxt4z
real, intent(in), DIMENSION(mp,mf) :: vx3z
real, intent(in), DIMENSION(mp,mf) :: vx4z
real, intent(in), DIMENSION(mp,mf) :: gs_coeffz
real, intent(in), DIMENSION(mp,mf) :: vlaiz
real, intent(in), DIMENSION(mp,mf) :: deltlfz
real, intent(inout), DIMENSION(mp,mf) :: anxz
real, DIMENSION(mp) :: fwsoilz
Called by
Contents
None
Call graph
dryleaf calls photosynthesis
define_canopy calls dryleaf
cbm calls define_canopy
cable_implicit_driver calls cbm
mpidrv_worker calls cbm
cable_explicit_driver calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker