POP_init_single – CABLE
POP_init_single Subroutine
22 statements
Source File
public subroutine POP_init_single(POP, disturbance_interval, n, precip)
Uses
TypeDef
POP_Types
Arguments
Type Intent Optional Attributes Name
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: disturbance_interval(:,:)
integer(kind=i4b), intent(in) :: n
real(kind=dp), intent(in), optional :: precip(:)
Calls
Called by
Contents
None
Call graph
pop_init_single calls zeropop, initpop2d_poisson, layer_recruitment_single_patch
initpop2d_poisson calls exponential, cumexponential
layer_recruitment_single_patch calls get_allometry
get_allometry calls getheight, allometry, williams_allometry
lucdriver calls pop_init_single
casaonly_luc calls pop_init_single
popluc_init calls pop_init_single
master_casaonly_luc calls pop_init_single
cable_offline_driver calls lucdriver, casaonly_luc, load_parameters
mpidrv_master calls master_casaonly_luc, lucdriver, load_parameters
load_parameters calls popluc_init
mpi_driver calls mpidrv_master