POPLUC_Init – CABLE
POPLUC_Init Subroutine
65 statements
Source File
public subroutine POPLUC_Init(POPLUC, LUC_EXPT, casapool, casaflux, casabiome, veg, POP, np)
Uses
casaparm
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
type(POPLUC_TYPE), intent(inout) :: POPLUC
type(LUC_EXPT_TYPE), intent(in) :: LUC_EXPT
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(casa_biome), intent(in) :: casabiome
type(veg_parameter_type), intent(in) :: veg
type(POP_TYPE), intent(inout) :: POP
integer(kind=i4b), intent(in) :: np
Calls
Called by
Contents
None
Call graph
popluc_init calls alloc_popluc, zeropopluc, read_luc_restart_nc, popluc_set_params, pop_init_single
read_luc_restart_nc calls nf90_open, handle_err, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_get_var, 1000, nf90_close
pop_init_single calls layer_recruitment_single_patch, zeropop, initpop2d_poisson
layer_recruitment_single_patch calls get_allometry
handle_err calls nf90_strerror
initpop2d_poisson calls cumexponential, exponential
get_allometry calls getheight, allometry, williams_allometry
load_parameters calls popluc_init
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master