psim – CABLE
psim Function
13 statements
Source File
public function psim(zeta, mp, CPI_C) result(r)
Arguments
Type Intent Optional Attributes Name
real, intent(in), DIMENSION(mp) :: zeta
integer, intent(in) :: mp
real, intent(in) :: CPI_C
Return Value real, DIMENSION(mp)
Calls
Called by
Contents
Call graph
psim calls alog
comp_friction_vel calls psim
define_canopy calls psim, comp_friction_vel
cbm calls define_canopy
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker