put_var_ncr1 – CABLE
put_var_ncr1 Subroutine
13 statements
Source File
public subroutine put_var_ncr1(ncid, var_name, var)
Uses
netcdf
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: var_name
real, intent(in), dimension(:) :: var
Calls
Called by
Contents
Call graph
put_var_ncr1 calls nf90_inq_varid, stderr_nc, nf90_put_var
stderr_nc calls nf90_strerror
put_var_nc calls put_var_ncr1