read_soilcolor – CABLE
read_soilcolor Subroutine
48 statements
Source File
private subroutine read_soilcolor(logn)
Uses
cable_common_module
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: logn
Calls
Called by
Contents
Call graph
read_soilcolor calls nf90_open, nc_abort, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_get_var, nf90_close
nc_abort calls nf90_strerror
get_default_params calls read_soilcolor
load_parameters calls get_default_params
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master