ruff_resist – CABLE
ruff_resist Subroutine
92 statements
Source File
public subroutine ruff_resist(veg, rough, ssnow, canopy, LAI_pft, HGT_pft, reducedLAIdue2snow)
Uses
cbl_hruff_mod
cable_other_constants_mod
cable_def_types_mod
cbl_LAI_eff_mod
cable_common_module
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: veg
type(roughness_type), intent(inout) :: rough
type(soil_snow_type), intent(in) :: ssnow
type(canopy_type), intent(inout) :: canopy
real :: LAI_pft(mp)
real :: HGT_pft(mp)
real :: reducedLAIdue2snow(mp)
Calls
Called by
Contents
None
Call graph
ruff_resist calls hgtabovesnow, lai_eff
cbm calls ruff_resist, define_canopy
define_canopy calls ruff_resist
cable_implicit_driver calls cbm
mpidrv_worker calls cbm
cable_explicit_driver calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker