sort – CABLE
sort Subroutine
21 statements
Source File
subroutine sort(mvmax, tmpx, tmpint)
Uses
cable_def_types_mod
Arguments
Type Intent Optional Attributes Name
integer :: mvmax
real(kind=r_2), dimension(mvmax) :: tmpx
integer, dimension(mvmax) :: tmpint
Called by
Contents
None
Call graph
create_new_gridinfo calls sort
mpidrv_master calls create_new_gridinfo
cable_offline_driver calls create_new_gridinfo
mpi_driver calls mpidrv_master