spatialSoil – CABLE
spatialSoil Subroutine
218 statements
Source File
private subroutine spatialSoil(nlon, nlat, logn)
Uses
cable_common_module
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nlon
integer, intent(in) :: nlat
integer, intent(in) :: logn
Calls
Called by
Contents
None
Call graph
spatialsoil calls nf90_open, nc_abort, nf90_inq_varid, nf90_get_var, nf90_close
nc_abort calls nf90_strerror
get_default_params calls spatialsoil
load_parameters calls get_default_params
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master