stderr_nc – CABLE
stderr_nc Subroutine
10 statements
Source File
public subroutine stderr_nc(status, message, var)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: status
character(len=*), intent(in) :: message
character(len=*), intent(in) :: var
Calls
Called by
Contents
None
Call graph
stderr_nc calls nf90_strerror
read_casa_dump calls stderr_nc, get_var_ncr3, get_var_ncr2
get_var_ncr3 calls stderr_nc
get_var_ncr2 calls stderr_nc
write_casa_dump calls stderr_nc, def_dims, def_vars, put_var_ncr1, put_var_ncr2, put_var_ncr3
def_dims calls stderr_nc
def_vars calls stderr_nc
put_var_ncr1 calls stderr_nc
put_var_ncr2 calls stderr_nc
put_var_ncr3 calls stderr_nc
def_var_atts calls stderr_nc
casaonly_luc calls read_casa_dump
master_casaonly_luc calls read_casa_dump
spincasacnp calls read_casa_dump
master_spincasacnp calls read_casa_dump
cable_offline_driver calls read_casa_dump, write_casa_dump, casaonly_luc, spincasacnp
get_var_nc calls get_var_ncr3, get_var_ncr2
mpidrv_master calls write_casa_dump, master_casaonly_luc, master_spincasacnp
put_var_nc calls put_var_ncr1, put_var_ncr2, put_var_ncr3
mpi_driver calls mpidrv_master