surfbv – CABLE
surfbv Subroutine
72 statements
Source File
public subroutine surfbv(dels, met, ssnow, soil, veg, canopy)
Uses
cable_common_module
smoisturev_mod
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dels
type(met_type), intent(inout) :: met
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
type(veg_parameter_type), intent(in) :: veg
type(canopy_type), intent(in) :: canopy
Calls
Called by
Contents
None
Call graph
surfbv calls smoisturev
smoisturev calls trimb
soil_snow calls surfbv
cbm calls soil_snow
cable_implicit_driver calls cbm
cable_explicit_driver calls cbm
cable_offline_driver calls cbm
mpidrv_worker calls cbm
mpi_driver calls mpidrv_worker