total_soil_conductivity – CABLE
total_soil_conductivity Function
44 statements
Source File
public function total_soil_conductivity(ssnow, soil)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: ssnow
type(soil_parameter_type), intent(inout) :: soil
Return Value real(kind=r_2),DIMENSION(mp,ms)
Called by
Contents
None
Call graph
stempv calls total_soil_conductivity
gwstempv calls total_soil_conductivity
soil_snow calls stempv
snow_processes_soil_thermal calls gwstempv
cbm calls soil_snow
soil_snow_gw calls snow_processes_soil_thermal
cable_implicit_driver calls cbm
mpidrv_worker calls cbm
cable_explicit_driver calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker