trimb – CABLE
trimb Subroutine
21 statements
Source File
public subroutine trimb(a, b, c, rhs, kmax)
Arguments
Type Intent Optional Attributes Name
real(kind=r_2), intent(in), DIMENSION(:,:) :: a
real(kind=r_2), intent(in), DIMENSION(:,:) :: b
real(kind=r_2), intent(in), DIMENSION(:,:) :: c
real(kind=r_2), intent(inout), DIMENSION(:,:) :: rhs
integer, intent(in) :: kmax
Called by
Contents
None
Call graph
stempv calls trimb
gwstempv calls trimb
smoisturev calls trimb
soil_snow calls stempv, surfbv
surfbv calls smoisturev
snow_processes_soil_thermal calls gwstempv
cbm calls soil_snow
soil_snow_gw calls snow_processes_soil_thermal
cable_implicit_driver calls cbm
mpidrv_worker calls cbm
cable_explicit_driver calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker