worker_pop_types – CABLE
worker_pop_types Subroutine
49 statements
Source File
private subroutine worker_pop_types(comm, veg, casamet, pop)
Uses
POP_Types
POPModule
cable_def_types_mod
cable_common_module
pop_mpi
mpi
casavariable
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(veg_parameter_type), intent(in) :: veg
type(casa_met), intent(in) :: casamet
type(POP_TYPE), intent(inout) :: pop
Calls
Called by
Contents
None
Call graph
worker_pop_types calls mpi_comm_rank, pop_init, mpi_recv, create_pop_gridcell_type
pop_init calls alloc_pop, initpop2d_poisson, layer_recruitment_single_patch, zeropop
create_pop_gridcell_type calls create_patch, mpi_abort, mpi_type_commit, mpi_type_create_struct, mpi_get_address, mpi_type_create_resized
initpop2d_poisson calls exponential, cumexponential
layer_recruitment_single_patch calls get_allometry
create_patch calls mpi_abort, mpi_type_commit, mpi_type_create_struct, mpi_get_address, mpi_type_create_resized, create_layer
create_layer calls mpi_abort, mpi_type_commit, mpi_type_create_struct, mpi_get_address, mpi_type_create_resized, create_cohort
get_allometry calls getheight, williams_allometry, allometry
create_cohort calls mpi_abort, mpi_type_commit, mpi_type_create_struct, mpi_get_address, mpi_type_create_resized
mpidrv_worker calls worker_pop_types
mpi_driver calls mpidrv_worker