write_output_variable_r2 – CABLE
write_output_variable_r2 Subroutine
326 statements
Source File
private subroutine write_output_variable_r2(ktau, ncid, varID, vname, var_r2, vrange, writepatch, dimswitch, met)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
integer, intent(in) :: ncid
integer, intent(in) :: varID
character(len=*), intent(in) :: vname
real(kind=4), intent(in), DIMENSION(:, :) :: var_r2
real, intent(in), DIMENSION(2) :: vrange
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
type(met_type), intent(in) :: met
Calls
Called by
Contents
None
Call graph
write_output_variable_r2 calls range_abort, nc_abort, nf90_put_var
nc_abort calls nf90_strerror
write_ovar calls write_output_variable_r2
create_landuse_cable_restart calls write_ovar
open_output_file calls write_ovar
write_output calls write_ovar
create_restart calls write_ovar
mpidrv_master calls create_landuse_cable_restart, open_output_file, write_output, create_restart
cable_offline_driver calls create_landuse_cable_restart, open_output_file, write_output, create_restart
mpi_driver calls mpidrv_master