write_output_parameter_r2d – CABLE
write_output_parameter_r2d Subroutine
38 statements
Source File
private subroutine write_output_parameter_r2d(ncid, parID, pname, par_r2d, prange, writepatch, dimswitch, restart)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
integer, intent(in) :: parID
character(len=*), intent(in) :: pname
real(kind=r_2), intent(in), DIMENSION(:, :) :: par_r2d
real, intent(in), DIMENSION(2) :: prange
logical, intent(in) :: writepatch
character(len=*), intent(in) :: dimswitch
logical, intent(in), optional :: restart
Calls
Called by
Contents
None
Call graph
write_output_parameter_r2d calls nf90_put_var, nc_abort
nc_abort calls nf90_strerror
write_ovar calls write_output_parameter_r2d
create_landuse_cable_restart calls write_ovar
create_restart calls write_ovar
write_output calls write_ovar
open_output_file calls write_ovar
mpidrv_master calls create_landuse_cable_restart, create_restart, write_output, open_output_file
cable_offline_driver calls create_landuse_cable_restart, create_restart, write_output, open_output_file
mpi_driver calls mpidrv_master