version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11" # choose arbitrary version of python for now
  jobs:
    pre_build:
      # install dependencies for ford and mkdocs separately to avoid dependency conflicts
      - python -m pip install --exists-action=w --no-cache-dir -r documentation/ford-requirements.txt
      # if we are building a pull request preview, build without search and graph generation
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ];
        then
          ford --no-search documentation/cable_ford.md
          ford --no-search documentation/pop_ford.md
        else
          ford -g documentation/cable_ford.md
          ford -g documentation/pop_ford.md
        fi
      - python -m pip install --exists-action=w --no-cache-dir -r documentation/mkdocs-requirements.txt

mkdocs:
  configuration: documentation/mkdocs.yml
  fail_on_warning: false