name: Build and deploy PR preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: 
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # Necessary to access local action
        uses: actions/checkout@v3

      - name: Build docs
        uses: ./.github/actions/preview

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1.2
        with:
          source-dir: documentation/site
