name: Build and publish docs

on:
  push:
    branches: 
      - main

jobs:
  build_and_deploy_docs:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # Necessary to access local action
        uses: actions/checkout@v3

      - name: Build docs
        uses: ./.github/actions/publish

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # default
          folder: documentation/site
          clean-exclude: pr-preview/ # don't overwrite previews
