name: CI
# Testing --volumes-from with GitHub-hosted runners (properly)
# TODO: See if we can just use the upstream image directly for Github-hosted runners...I guess....
# alternatively, find out what is happening when we mount a volume from upstream/runner to the same place on the host.!
on:
  pull_request:
jobs:
  build-and-test:
    name: Build and Test (GitHub-Hosted)
    uses: access-nri/build-ci/.github/workflows/ci.yml@216-github-hosted-ci
    with:
      spack-manifest-path: .github/build-ci/manifests/spack.yaml.j2
      allow-ssh-into-spack-install: true