name: CI
on:
  pull_request:
jobs:
  build-and-test:
    name: Build and Test (GitHub-Hosted)
    uses: access-nri/build-ci/.github/workflows/ci.yml@build-ci-2.0
    with:
      spack-manifest-path: .github/build-ci/manifests/spack.yaml.j2