name: CI
# Testing --volumes-from with GitHub-hosted runners (properly)
on:
  pull_request:
jobs:
  build-and-test:
    name: Build and Test (GitHub-Hosted)
    uses: access-nri/build-ci/.github/workflows/ci.yml@216-github-hosted-ci
    with:
      spack-manifest-path: .github/build-ci/manifests/spack.yaml.j2
      allow-ssh-into-spack-install: true